### ISSUE TITLE
[BUG] UniGetUI 3.1.0-alpha0 does not understand the path to winget.exe with the Cyrillic name of the user's folder

### ISSUE THREAD

**Issue by Dhowti** [marticliment/UniGetUI#2239]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

See subj.

### Steps to reproduce the issue

Install and view the settings and log. 
And it seems that the problem is not only with winget, but only it is enabled for me.

### WingetUI Log

```text
[22.05.2024 12:32:47] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0-alpha0
[22.05.2024 12:32:47]
[22.05.2024 12:32:47] Version Code:  3,099
[22.05.2024 12:32:47] Loaded language locale: ru
[22.05.2024 12:32:48] Api auth token: 5wh2x661xxc5cqms2oi85fqvnsmvipg1frisyaocxjkmqhsk280ex15ynvtdjz55
[22.05.2024 12:32:48] Api running on http://localhost:7058
[22.05.2024 12:32:49] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[22.05.2024 12:32:49] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:49] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:49] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:50] UniGetUI is up to date
[22.05.2024 12:32:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.2506                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.2506                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:51] Adding chocolatey to path since it was not on path.
[22.05.2024 12:32:51] Could not download updated translations from GitHub
[22.05.2024 12:32:51] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                         at UniGetUI.Core.Language.LanguageEngine.DownloadUpdatedLanguageFile(String LangKey, Boolean UseOldUrl) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 98
[22.05.2024 12:32:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\ЕЕ\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.05.2024 12:32:52] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[22.05.2024 12:32:54] Error finding updates on manager .NET Tool
[22.05.2024 12:32:54] System.InvalidOperationException: Cannot start process because a file name has not been provided.
                         at System.Diagnostics.Process.Start()
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 75
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 168
[22.05.2024 12:32:55] Found 0 installed packages from .NET Tool
[22.05.2024 12:32:55] Found 0 installed packages from PowerShell
[22.05.2024 12:32:55] Downloaded new icons and screenshots successfully!
[22.05.2024 12:32:55] Found 0 available updates from Chocolatey
[22.05.2024 12:32:56] Found 0 installed packages from Chocolatey
[22.05.2024 12:32:56] Found 0 available updates from PowerShell
```

### Package Managers Logs

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:50] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Get-PSRepository : Љ®¬ ­¤  "Get-PSRepository" ­ ©¤Ґ­  ў ¬®¤г«Ґ "PowerShellGet", ­® § Јаг§Ёвм нв®в ¬®¤г«м ­Ґ г¤ «®бм. „«
п Ї®«гзҐ­Ёп ¤®Ї®«­ЁвҐ«м­ле бўҐ¤Ґ­Ё© ўлЇ®«­ЁвҐ Є®¬ ­¤г "Import-Module PowerShellGet".
бва®Є :1 §­ Є:1
+ Get-PSRepository
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PSRepository:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
[22.05.2024 12:32:50] Exit Code: 1
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:52] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\ЕЕ\AppData\Local\UniGetUI\Chocolatey\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
Directory 'C:\Users\��\AppData\Local\UniGetUI\Chocolatey\lib' does not exist.
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[22.05.2024 12:32:52] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:55] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Get-PSRepository : Љ®¬ ­¤  "Get-PSRepository" ­ ©¤Ґ­  ў ¬®¤г«Ґ "PowerShellGet", ­® § Јаг§Ёвм нв®в ¬®¤г«м ­Ґ г¤ «®бм. „«
п Ї®«гзҐ­Ёп ¤®Ї®«­ЁвҐ«м­ле бўҐ¤Ґ­Ё© ўлЇ®«­ЁвҐ Є®¬ ­¤г "Import-Module PowerShellGet".
бва®Є :1 §­ Є:1
+ Get-PSRepository
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PSRepository:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
[22.05.2024 12:32:55] Exit Code: 1
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:55] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.
Download a .NET SDK:
https://aka.ms/dotnet/download
Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[22.05.2024 12:32:55] Exit Code: -2147450735
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:55] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
Get-InstalledModule : Љ®¬ ­¤  "Get-InstalledModule" ­ ©¤Ґ­  ў ¬®¤г«Ґ "PowerShellGet", ­® § Јаг§Ёвм нв®в ¬®¤г«м ­Ґ г¤ «®
бм. „«п Ї®«гзҐ­Ёп ¤®Ї®«­ЁвҐ«м­ле бўҐ¤Ґ­Ё© ўлЇ®«­ЁвҐ Є®¬ ­¤г "Import-Module PowerShellGet".
бва®Є :1 §­ Є:1
+ Get-InstalledModule
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-InstalledModule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
[22.05.2024 12:32:55] Exit Code: 1
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:55] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\ЕЕ\AppData\Local\UniGetUI\Chocolatey\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
Directory 'C:\Users\��\AppData\Local\UniGetUI\Chocolatey\lib' does not exist.
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[22.05.2024 12:32:55] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:55] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\ЕЕ\AppData\Local\UniGetUI\Chocolatey\choco.exe
█  Arguments:  outdated
Chocolatey v2.2.2
Directory 'C:\Users\��\AppData\Local\UniGetUI\Chocolatey\lib' does not exist.
Outdated Packages
 Output is package name | current version | available version | pinned?
Chocolatey has determined 0 package(s) are outdated. 
[22.05.2024 12:32:55] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:56] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\ЕЕ\AppData\Local\UniGetUI\Chocolatey\choco.exe
█  Arguments:  list
Chocolatey v2.2.2
Directory 'C:\Users\��\AppData\Local\UniGetUI\Chocolatey\lib' does not exist.
[22.05.2024 12:32:56] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [22.05.2024 12:32:56] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
█  Arguments: 
Windows PowerShell
(C) ��௮��� �������� (Microsoft Corporation). �� �ࠢ� ���饭�.
��⠭���� ��᫥���� ����� PowerShell ��� ����� �㭪権 � ���襭��! https://aka.ms/PSWindows
PS C:\Program Files\UniGetUI> 
PS C:\Program Files\UniGetUI>                 function Test-GalleryModuleUpdate {
>>                     param (
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Name,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [version] $Version,
>>                         [Parameter(Mandatory,ValueFromPipelineByPropertyName)] [string] $Repository,
>>                         [switch] $NeedUpdateOnly
>>                     )
>>                     process {
>>                         $URLs = @{}
>>                         @(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})
>>                         $page = Invoke-WebRequest -Uri ($URLs[$Repository] + "/package/$Name") -UseBasicParsing -Maximum 0 -ea Ignore
>>                         [version]$latest = Split-Path -Path ($page.Headers.Location -replace "$Name." -replace ".nupkg") -Leaf
>>                         $needsupdate = $Latest -gt $Version
>>                         if ($needsupdate) {
>>                                 Write-Output($Name + "|" + $Version.ToString() + "|" + $Latest.ToString() + "|" + $Repository)
>>                         }
>>                     }
>>                 }
>>                 Get-InstalledModule | Test-GalleryModuleUpdate
PS C:\Program Files\UniGetUI>                 exit
Get-InstalledModule : Љ®¬ ­¤  "Get-InstalledModule" ­ ©¤Ґ­  ў ¬®¤г«Ґ "PowerShellGet", ­® § Јаг§Ёвм нв®в ¬®¤г«м ­Ґ г¤ «®
бм. „«п Ї®«гзҐ­Ёп ¤®Ї®«­ЁвҐ«м­ле бўҐ¤Ґ­Ё© ўлЇ®«­ЁвҐ Є®¬ ­¤г "Import-Module PowerShellGet".
бва®Є :19 §­ Є:17
+                 Get-InstalledModule | Test-GalleryModuleUpdate
+                 ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-InstalledModule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
[22.05.2024 12:32:56] Exit Code: 0
```

### Relevant information

The application sees the path to winget.exe as C:\Users\……\AppData\Local\Microsoft\WindowsApps\winget.exe (actually with dots)

### Screenshots and videos

![Снимок экрана 2024-05-22 124640](https://github.com/marticliment/WingetUI/assets/108597329/397d420e-25eb-4be6-90d4-977480205e4b)

**Comment by Dhowti** [comment]
It was clear installation of UniGetUI.

**Comment by Dhowti** [comment]
In my opinion, not using Latin characters in the profile is a bad practice, but it can’t be fixed for me.
On the second computer it works well with the Latin.

**Comment by Dhowti** [comment]
Same problem with winget:
![image](https://github.com/marticliment/WingetUI/assets/108597329/a8b7d8f6-81ae-40a2-80c2-32437d5f22a4)
Choko is ok:
![image](https://github.com/marticliment/WingetUI/assets/108597329/34d9d696-d59c-4e6c-b54f-ff9b86ab47f6)

**Comment by marticliment** [comment]
please run the command `where winget.exe` on a command prompt and post the results here

**Comment by Dhowti** [comment]
C:\Users\ЕЕ>where winget.exe
C:\Users\ЕЕ\AppData\Local\Microsoft\WindowsApps\winget.exe

**Comment by Dhowti** [comment]
The first beta:
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 

![image](https://github.com/marticliment/WingetUI/assets/108597329/d4cb32ab-cac8-4de2-b1f6-383d09fc11e5)
However:
winget path: "C:\Program Files\UniGetUI\Assets\Utilities\..\..\winget-cli_x64\winget.exe"
Deleting Winget local data sources...
Performing reset...
Resetting bundled WinGet
Removing source: winget...
Done

**Comment by marticliment** [comment]
I have just pushed a commit that may fix this issue. Please wait for the next beta and test it out

**Comment by Dhowti** [comment]
![image](https://github.com/marticliment/WingetUI/assets/108597329/edc82048-6283-4030-a1d8-ac821b98dbf5)
Nop.

**Comment by Dhowti** [comment]
> Please check if Beta 1 fixes the issue

No chance for me? Tried release with the same result.

**Comment by marticliment** [comment]
You should be able to disable autoupdates and roll back

**Comment by Dhowti** [comment]
Only blocking the domain marticliment.com helps, otherwise it is updating anyway. OK, I'm staying with you for now :)

**Comment by marticliment** [comment]
My excuses, you will need to disable autoupdate again once downgraded

**Comment by marticliment** [comment]
Hello,

To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.

UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0
Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

Excuse me for the inconveniences.
