### ISSUE TITLE
[BUG] Installation crashes and odd installation problem

### ISSUE THREAD

**Issue by FrisoDB** [marticliment/UniGetUI#2294]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I tried installing losslesscut, but in normal installation it gets stuck on a warning about a shortcut creation, and as admin installation it runs really fast but seems to install nothing. And then wingetui registers it as installed. 

### Steps to reproduce the issue

Go to package finder, search lossless cut, choose install. Searching windows for lossless cut gives no results. Installation worked correctly on another computer with chocolatey in powershell.

### WingetUI Log

```text
Welcome to WingetUI Version 3.0.2
               Version Code 3,02
C:\Users\friso\AppData\Local\WingetUI\CachedLangFiles\lang_nl.json
C:\Program Files\WingetUI\Assets\Languages\lang_nl.json
Loaded language locale: nl
Api auth token: 6qo6dofdqcw509iaft58un0a83tia9ufqldama16ebjhiqc60n0mvqy7efu0zpfb
Starting update check
Api running on http://localhost:7058
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at ModernWindow.Core.Data.LanguageEngine.UpdateLanguageFile(String LangKey) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\Core\Data\LanguageData.cs:line 104
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
WingetUI is up to date
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\friso\AppData\Local\Microsoft\WindowsApps\python.exe
█ Call arguments:  -m pip
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\friso\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Program Files\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Start backup
Starting check for updates wait interval with waitTime=259200
Finished loading serializable objects. Serializing with format JSON
Finished serializing
Backup saved to C:\Users\friso\Documents\WingetUI\PC_FRISO geïnstalleerde pakketten 2024-06-08 16-57-14.json
Error finding packages on manager Pip with query loss: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query lossless: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in C:\Users\marti\Desktop\wingetui-tempo\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Caching admin rights for process id 1572
Erasing admin rights
```

### Package Managers Logs

```text
Chocolatey v2.2.2
Chocolatey detected you are not running from an elevated command shell
(cmd/powershell).
You may experience errors - many functions/packages
require admin rights. Only advanced users should run choco w/out an
elevated shell. When you open the command shell, you should ensure
that you do so with "Run as Administrator" selected. If you are
attempting to use Chocolatey in a non-administrator setting, you
must select a different location other than the default install
location. See
https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
for details.
For the question below, you have 20 seconds to make a selection.
Do you want to continue?([Y]es/[N]o):
Timeout or your choice of '﻿' is not a valid selection.
Installing the following packages:
lossless-cut
By installing, you accept licenses for the packages.
lossless-cut v3.61.1 [Approved]
lossless-cut package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Extracting C:\Users\friso\AppData\Local\Temp\chocolatey\lossless-cut\3.61.1\LosslessCut-win-x64.7z to C:\Users\friso\AppData\Local\Programs\WingetUI\choco-cli\lib\lossless-cut\tools...
C:\Users\friso\AppData\Local\Programs\WingetUI\choco-cli\lib\lossless-cut\tools
WARNING: Unable to create shortcut. Error captured was Unable to save shortcut "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\LosslessCut.lnk"..
WARNING: Unable to create shortcut. Error captured was Unable to save shortcut "C:\Users\Public\Desktop\LosslessCut.lnk"..
```

**Comment by marticliment** [comment]
Installing from the CLI does work?
`choco install losslesscut`

**Comment by FrisoDB** [comment]
Opening PS as admin I did the following:

PS C:\Users\friso> choco list
Chocolatey v2.2.2
lossless-cut 3.61.1

PS C:\Users\friso> choco uninstall lossless-cut
Chocolatey v2.2.2
Uninstalling the following packages:
lossless-cut

lossless-cut v3.61.1
The package lossless-cut wants to run 'chocolateyuninstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

 Skipping auto uninstaller - No registry snapshot.
 lossless-cut has been successfully uninstalled.

then I did
PS C:\Users\friso> choco install lossless-cut
which was followed by a very long return message, and a succesful installation

so calling chocolatey directly worked
