### ISSUE TITLE
[BUG] API "Nancy self host was unable to start" error in logs

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2378]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 beta 1

### Windows version, edition and architecture

Windows 11 Pro

### Describe your issue

Not sure what this means, but maybe it should be brought to your attention. See the logs.

### Steps to reproduce the issue

\-

### UniGetUI Log

```text
...
[01/07/2024 17:22:29] Randomly-generated background API auth token for the current session: 206m3w9k0dnbfubg38gwfovrf4q28uply2ti6v9p0013tfhd61v6a645wdx3cpdm
[01/07/2024 17:22:29] An error occurred while initializing the API
[01/07/2024 17:22:29] Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException: The Nancy self host was unable to start, as no namespace reservation existed for the provided url(s).
                      
                      Please either enable UrlReservations.CreateAutomatically on the HostConfiguration provided to 
                      the NancyHost, or create the reservations manually with the (elevated) command(s):
                      
                      netsh http add urlacl url="http://+:7058/" user="Everyone"
                      
                         at Nancy.Hosting.Self.NancyHost.StartListener()
                         at Nancy.Hosting.Self.NancyHost.Start()
                         at UniGetUI.Interface.BackgroundApiRunner.Start() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Interface.BackgroundApi\BackgroundApi.cs:line 73
...
```

### Package Managers Logs

```text
\-
```

**Comment by marticliment** [comment]
Are you running 2 or more parallel instances of UniGetUI?

**Comment by marticliment** [comment]
Do you know if you use any program that uses the port 7058?
Can you check if your firewall is blocking localhost:7058

**Comment by marticliment** [comment]
Nancy is used for "Widgets for UniGetUI" and  the "Share Packages" feature, UniGetUI should be able to work without it (in fact, it can be disabled from the settings).

If it is only localhost there should be no need to reserve the port, but perhaps EaseUS software already has this port reserved for itself
