### ISSUE TITLE
[BUG] Keeps complaining about missing dependency ".NET Tools Outdated"

### ISSUE THREAD

**Issue by gtflip** [marticliment/UniGetUI#2408]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition and architecture

Windows 10 Pro Version 22H2 19045.4529 x64

### Describe your issue

When I start UniGetUI, it pops up this dialog:

![Screenshot_10](https://github.com/marticliment/UniGetUI/assets/2807001/27813f91-1d2c-480b-8f32-93076749cd3f)

I have clicked the button to install it, and then restarted the program (as the next popup suggests), but it keeps popping up that message.

When I click the "Install..." button, it opens a PowerShell window which has some text but closes too quickly to read any of it.  When I searched for ".NET Tools Outdated" in the repository, I found the command-line which I tried in a PowerShell window:

```
PS C:\Users\phil> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile -Command "& {dotnet tool install --global dotnet-tools-outdated  --add-source https://api.nuget.org/v3/index.json; if($error.count -ne 0){pause}}"
error NU1202: Package dotnet-tools-outdated 0.7.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package dotnet-tools-outdated 0.7.1 supports:
error NU1202:   - net6.0 (.NETCoreApp,Version=v6.0) / any
error NU1202:   - net8.0 (.NETCoreApp,Version=v8.0) / any
The tool package could not be restored.
Tool 'dotnet-tools-outdated' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
.count : The term '.count' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:109
+ ...   --add-source https://api.nuget.org/v3/index.json; if(.count -ne 0){ ...
+                                                            ~~~~~~
    + CategoryInfo          : ObjectNotFound: (.count:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### UniGetUI Log

```text
[7/3/2024 9:49:02 AM] 
                         __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.0
[7/3/2024 9:49:02 AM]
[7/3/2024 9:49:02 AM] Version Code:  3.1
[7/3/2024 9:49:02 AM] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[7/3/2024 9:49:02 AM] Loaded language locale: en
[7/3/2024 9:49:03 AM] Randomly-generated background API auth token for the current session: tn469y4u1tyrimh7ku75bp2hqauh72bfnajx15mf7ugwmypyo62jb236kw8ovihu
[7/3/2024 9:49:03 AM] Api running on http://localhost:7058
[7/3/2024 9:49:03 AM] Lang files were updated successfully from GitHub
[7/3/2024 9:49:03 AM] UniGetUI is up to date
[7/3/2024 9:49:03 AM] Downloaded new icons and screenshots successfully!
[7/3/2024 9:49:04 AM] Command scoop was not found on the system
[7/3/2024 9:49:04 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:04 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   5.0.408
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:04 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\phil\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Naive WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: 
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:04 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Users\phil\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.0 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip (python 3.11)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:05 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.2.4
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:05 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\phil\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:06 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.4522                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.4522                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[7/3/2024 9:49:07 AM] Resetting administrator rights cache for process id 20868
[7/3/2024 9:49:07 AM] Command dotnet-tools-outdated.exe was not found on the system
[7/3/2024 9:49:08 AM] Found 0 installed packages from .NET Tool
[7/3/2024 9:49:08 AM] Found 0 available updates from Chocolatey
[7/3/2024 9:49:08 AM] Found 0 available updates from Pip
[7/3/2024 9:49:09 AM] Found 0 installed packages from Pip
[7/3/2024 9:49:09 AM] Found 0 installed packages from Chocolatey
[7/3/2024 9:49:09 AM] Dependency WinGet PowerShell Module for manager Winget is present
[7/3/2024 9:49:09 AM] Command dotnet-tools-outdated.exe was not found on the system
[7/3/2024 9:49:09 AM] Dependency .NET Tools Outdated was not found for manager .NET Tool, marking to prompt...
[7/3/2024 9:49:10 AM] Error finding updates on manager .NET Tool
[7/3/2024 9:49:10 AM] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet-tools-outdated.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 103
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 190
[7/3/2024 9:49:11 AM] Found 1 installed packages from PowerShell
[7/3/2024 9:49:12 AM] Found 0 available updates from PowerShell
[7/3/2024 9:49:14 AM] Found 2 installed packages from Npm
[7/3/2024 9:49:14 AM] Found 2 available updates from Npm
[7/3/2024 9:49:17 AM] Found 252 installed packages from Winget
[7/3/2024 9:49:17 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[7/3/2024 9:49:17 AM] Found 26 available updates from Winget
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 7/3/2024 9:49:04 AM
Process end time:   7/3/2024 9:49:04 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\phil\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 7/3/2024 9:49:06 AM
Process end time:   7/3/2024 9:49:07 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 7/3/2024 9:49:06 AM
Process end time:   7/3/2024 9:49:17 AM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 7/3/2024 9:49:07 AM
Process end time:   7/3/2024 9:49:07 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 7/3/2024 9:49:07 AM
Process end time:   7/3/2024 9:49:17 AM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Which windows version are you using?
Do you have .NET SDK 6/7/8/9 installed?
Please try running `dotnet tool install dotnet-tools-outdated`

**Comment by kentkravitz** [comment]
Hi, same problem for me.  Windows 11.
C:\> dotnet tool install dotnet-tools-outdated
`Cannot find a manifest file.
For a list of locations searched, specify the "-d" option before the tool name.
If you intended to install a global tool, add '--global' to the command.
If you would like to create a manifest, use 'dotnet new tool-manifest', usually in the repo root directory.`

**Comment by gtflip** [comment]
> Which windows version are you using? Do you have .NET SDK 6/7/8/9 installed? Please try running `dotnet tool install dotnet-tools-outdated`

As I included in the bug report, Windows 10 Pro Version 22H2 19045.4529 x64  :-)

I have .NET SDK 5.0.404 & 5.0.408 installed, no 6-9

Same output as @kentkravitz

**Comment by christian-haider** [comment]
`C:\>dotnet tool install dotnet-tools-outdated
Cannot find a manifest file.
For a list of locations searched, specify the "-d" option before the tool name.
If you intended to install a global tool, add `--global` to the command.
If you would like to create a manifest, use `dotnet new tool-manifest`, usually in the repo root directory.


C:\>dotnet tool install dotnet-tools-outdated --global
You can invoke the tool using the following command: dotnet-tools-outdated
Tool 'dotnet-tools-outdated' (version '0.7.1') was successfully installed.`

the **"--global"** did the trick for me

**Comment by EckeD** [comment]
hi everybody,
the same issue happened for me - however I realized this happen when UniGet accidentally tried to reinstall the older "beta1" release (it was found as an "update" - now beta2 is found. Both are wrong, 3.1.0 is not in beta anymore).
So what I did to resolve is:

1. ignore the message
2. install 3.1.0 again (on one computer I did a full uninstall + reinstall, on the other however UniGet actually updated itself again to 3.1.0)

3. after that the error was gone.

**Comment by Cloudworks99** [comment]
For me the problem was that I did not have any .NET SDK installed, only .NET runtimes. At first I thought WHY would I install an outdated .NET (dotnet-tools-outdated), is that not insecure? But when I looked it up I found that this dotnet-tools-outdated is a tool to list which NuGet packages are outdated. Dotnet-tools-outdated itsself is a NuGet package. And to be able to install this I needed to install the .NET SDK.

This was not needed for the previous version.

I guess to make this work there are a couple of options:

- Have the installer check for the availability of a .NET SDK;
- Have the installer check for other prerequisites to allow the installation of NuGet packages.
- Not sure where NuGet is used. But maybe the user should be asked if he wants to check and update NuGet packages? If not then do not ask to install dotnet-tools-outdated. If yes, check and install ALL prerequisites.

**Comment by marticliment** [comment]
> This was not needed for the previous version.

It was, but WingetUI did not complain when it was not installed, it silently crashed.

> * Not sure where NuGet is used. But maybe the user should be asked if he wants to check and update NuGet packages? If not then do not ask to install dotnet-tools-outdated. If yes, check and install ALL prerequisites.

You can disable the DotNet Tool package manager from the settings

**Comment by glcraft** [comment]
I have a partial answer as I (just) discovered how to resolve the problem on my PC : 
I don't know why, but when I start my Windows session, explorer.exe (and so its child processes, like the start menu) doesn't have user variable environments loaded. So the PATH env var has just system env vars, no user env var.

To work around this, it's simple : 
* quit unigetUI
* (optional) open at least one explorer window
* go to task explorer
* in the process, right click on explorer.exe and "restart" it (something like that, i'm localized in french)
* Start UnigetUI

Normally, you won't see the message of .NET Tools Outdated and sources updates works correctly.

So, the issue comes from windows, not unigetui

**Comment by IgorKorkin** [comment]
The following steps help me to solve this problem:
1. Download and install `.NET 8.0 SDK` via https://aka.ms/dotnet/download
2. Run `dotnet tool install dotnet-tools-outdated --global`
3. Restart UnigetUI

**Comment by balthanon** [comment]
> The following steps help me to solve this problem:

This resolved the issue for me as well-- it also needed to specifically be the SDK that was installed.  Just the runtime didn't address the issue; so it might be tied to the fact that I had an old version of the SDK installed on my computer.  (Specifically version 5 in my case.)

**Comment by marticliment** [comment]
Yes, .NET SDK 6 or higher must be installed in order for UniGetUI to work

**Comment by marticliment** [comment]
This issue was fixed on a previous commit

**Comment by cayenne17** [comment]
@marticliment : I have the same problem with version 3.1.1 on Windows 10 22h2

**Comment by marticliment** [comment]
What happens if you run the proposed command on a command-prompt window?

**Comment by cayenne17** [comment]
@marticliment 
```
error NU1202: Le package dotnet-tools-outdated 0.7.1 n'est pas compatible avec netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any. Le package dotnet-tools-outdated 0.7.1 prend en charge :
error NU1202:   - net60 (.NETFramework,Version=v6.0) / any
error NU1202:   - net80 (.NETFramework,Version=v8.0) / any
Impossible de restaurer le package de l'outil.
Échec d'installation de l'outil 'dotnet-tools-outdated'. Causes possibles de cet échec :

* Vous essayez d'installer une préversion, mais vous n'avez pas utilisé l'option --version pour spécifier la version.
* Un package portant ce nom a été trouvé, mais il ne s'agit pas d'un outil .NET Core.
* Le flux NuGet exigé n'est pas accessible, peut-être en raison d'un problème de connexion Internet.
* Vous avez mal tapé le nom de l'outil.

```

**Comment by marticliment** [comment]
Oh, you have a very old .NET sdk installed.

Either instal .NET SDK 6.0 or .NET SDK 8.0, or disable .NET from UniGetUI Settingsç

**Comment by cayenne17** [comment]
I have just installed .NET SDK 8.0
 https://dotnet.microsoft.com/fr-fr/download/dotnet/thank-you/sdk-8.0.401-windows-x64-installer
 
I've restarted the order and it's fine

**Comment by ShizCalev** [comment]
For folks who might find this off google in the future, another potential issue that can cause this is having both x86 & x64 dotnet SDK installed. You just have to adjust the order in your system's PATH so the x64 version is detected first. 

https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#no-net-sdk-was-found
