### ISSUE TITLE
[BUG] When selecting "Installed Packages" Winget source is missing.

### ISSUE THREAD

**Issue by 13regent** [marticliment/UniGetUI#2443]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 10 Pro 22H2

### Describe your issue

Just upgraded to version 3.1.0. Was working fine for a short while...but Winget is most often missing from the sources list. This is very intermittent as sometimes all the sources are listed, then other times random ones are missing. 

### Steps to reproduce the issue

Start Uniget....select Installed Packages

### UniGetUI Log

```text
[07/05/2024 11:48:39 PM] 
                            __  __      _ ______     __  __  ______
                           / / / /___  (_) ____/__  / /_/ / / /  _/
                          / / / / __ \/ / / __/ _ \/ __/ / / // /  
                         / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                         \____/_/ /_/_/\____/\___/\__/\____/___/   
                             Welcome to UniGetUI Version 3.1.0
[07/05/2024 11:48:39 PM]
[07/05/2024 11:48:39 PM] Version Code:  3.1
[07/05/2024 11:48:40 PM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[07/05/2024 11:48:41 PM] Loaded language locale: en
[07/05/2024 11:48:42 PM] Randomly-generated background API auth token for the current session: cjz9mfw3fcpw90vb989yge6o2qo7k2culwyfej6rftsxsgobkm5n2aklz1syd5hd
[07/05/2024 11:48:42 PM] Api running on http://localhost:7058
[07/05/2024 11:48:44 PM] Lang files were updated successfully from GitHub
[07/05/2024 11:48:44 PM] UniGetUI is up to date
[07/05/2024 11:48:44 PM] The restored geometry did not have exactly 5 items (found length was 1)
[07/05/2024 11:48:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Pip
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: pip
                         █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\python.exe
                         █ Call arguments:  -m pip
                         █ Version: 
                         █   
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:48:48 PM] Downloaded new icons and screenshots successfully!
[07/05/2024 11:48:51 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: .NET Tool
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: dotnet tool
                         █ Executable path: C:\Program Files\dotnet\dotnet.exe
                         █ Call arguments: tool
                         █ Version: 
                         █   6.0.423
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:48:55 PM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.PEInterface.Initialize() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageEngine\PEInterface.cs:line 44
[07/05/2024 11:48:55 PM] Timeout: Not all package managers have finished initializing.
[07/05/2024 11:49:01 PM] PowerShell sources took too long to load, using known sources as default
[07/05/2024 11:49:01 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: powershell.exe
                         █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -Command
                         █ Version: 
                         █   Name                           Value                                                                                   
                         █   ----                           -----                                                                                   
                         █   PSVersion                      5.1.19041.4522                                                                          
                         █   PSEdition                      Desktop                                                                                 
                         █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                         █   BuildVersion                   10.0.19041.4522                                                                         
                         █   CLRVersion                     4.0.30319.42000                                                                         
                         █   WSManStackVersion              3.0                                                                                     
                         █   PSRemotingProtocolVersion      2.3                                                                                     
                         █   SerializationVersion           1.1.0.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:49:01 PM] Chocolatey sources took too long to load, using known sources as default
[07/05/2024 11:49:01 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Chocolatey
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: choco.exe
                         █ Executable path: C:\Users\Scott\AppData\Local\UniGetUI\Chocolatey\choco.exe
                         █ Call arguments: 
                         █ Version: 
                         █   2.2.2
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:49:02 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Winget
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: winget.exe
                         █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe
                         █ Call arguments: 
                         █ Version: 
                         █   Naive WinGet CLI Version: v1.8.1791
                         █   Microsoft.WinGet.Client PSModule version: 
                         █   Using Native WinGet helper (COM Api)
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:49:02 PM] Scoop sources took too long to load, using known sources as default
[07/05/2024 11:49:02 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Scoop
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: scoop
                         █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                         █ Version: 
                         █   Current Scoop version:
                         █   
                         █   'main' bucket:
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:49:03 PM] Found 0 available updates from Pip
[07/05/2024 11:49:03 PM] Found 0 installed packages from Pip
[07/05/2024 11:49:06 PM] Found 3 installed packages from Scoop
[07/05/2024 11:49:07 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Npm
                         █ Enabled: True
                         █ Found: True
                         █ Fancye exe name: npm
                         █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                         █ Version: 
                         █   10.8.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/05/2024 11:49:15 PM] Dependency Scoop-Search for manager Scoop is present
[07/05/2024 11:49:15 PM] Found 0 available updates from .NET Tool
[07/05/2024 11:49:15 PM] Found 0 available updates from Chocolatey
[07/05/2024 11:49:15 PM] Found 0 installed packages from Chocolatey
[07/05/2024 11:49:15 PM] Found 1 installed packages from .NET Tool
[07/05/2024 11:49:15 PM] Found 1 installed packages from PowerShell
[07/05/2024 11:49:15 PM] Dependency Git for manager Scoop is present
[07/05/2024 11:49:16 PM] Dependency .NET Tools Outdated for manager .NET Tool is present
[07/05/2024 11:49:16 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[07/05/2024 11:49:16 PM] Found 0 available updates from PowerShell
[07/05/2024 11:49:56 PM] Error finding updates on manager Scoop
[07/05/2024 11:49:56 PM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 07/05/2024 11:49:00 PM
Process end time:   07/05/2024 11:49:02 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Relevant information

Tried a "reset Uniget". Tried a "Reset Winget sources" as well as an uninstall and reinstall. 

### Screenshots and videos

![image](https://github.com/marticliment/UniGetUI/assets/28539673/7891b6a6-f260-41ba-846b-3b99ff03c6ca)

**Comment by marticliment** [comment]
Please try this beta release here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0

**Comment by 13regent** [comment]
Updated to the 3.1.1-beta0 and it seems to be working normally.

**Comment by 13regent** [comment]
Just found if I quit Uniget and start it again...when I select Installed Packages" Winget source is missing. If I right click on the Uniget notification icon and select "available packages" ...the Winget and Local sources populate. I had items listed in "Software Updates" that now is totally empty.

**Comment by 13regent** [comment]
Uniget requires quitting at starting several times to work normally.

**Comment by marticliment** [comment]
3.1.1-beta0 also has the quitting requirement?

**Comment by 13regent** [comment]
Yes.

**Comment by 13regent** [comment]
Just installed 3.1.1-beta1. The issue is not resolved. Sources just show Powershell...and no software updates show up...when there were some earlier today.

![image](https://github.com/marticliment/UniGetUI/assets/28539673/1c10bde5-c6d7-48cd-b407-74cc13d9fcf8)

![image](https://github.com/marticliment/UniGetUI/assets/28539673/2b9bdabd-dfeb-4896-9815-e3d90c1d03af)

**Comment by 13regent** [comment]
After a few more tries..listed sources and software updates list are inconsistent.

**Comment by Martin-SF** [comment]
I have a similar problem. currently on 3.1.1-beta1.

Winget is not functioning in UniGet.
not showing it in sources, despite it working before in 3.1.0
Already unsuccesfully tried enabling bundled winget and then reset winget sources


![grafik](https://github.com/marticliment/UniGetUI/assets/32391476/09ba9871-d79b-454d-87fe-17306ca1b70d)
![grafik](https://github.com/marticliment/UniGetUI/assets/32391476/531df142-2454-437f-8793-1f1b183d6a12)
![grafik](https://github.com/marticliment/UniGetUI/assets/32391476/9589759b-003e-4954-9f50-b07194dffbfd)

**Comment by 13regent** [comment]
I have to quit and start usually more than 3 times for things to work correctly.

**Comment by marticliment** [comment]
Please share the package manager logs for version 3.1.1-beta1

**Comment by 13regent** [comment]
Here are the logs:

Manager Winget with version:
Native WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 07/08/2024 11:43:35 AM
Process end time:   07/08/2024 11:43:52 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07/08/2024 11:43:36 AM
Process end time:   07/08/2024 11:43:53 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 07/08/2024 11:43:43 AM
Process end time:   07/08/2024 11:43:53 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07/08/2024 11:43:44 AM
Process end time:   07/08/2024 11:44:17 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07/08/2024 11:43:53 AM
Process end time:   07/08/2024 11:44:26 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07/08/2024 12:52:45 PM
Process end time:   07/08/2024 12:53:06 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07/08/2024 12:53:06 PM
Process end time:   07/08/2024 12:53:22 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07/08/2024 8:22:04 PM
Process end time:   07/08/2024 8:22:46 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

**Comment by Martin-SF** [comment]
@marticliment Correction: It stopped working with the update to 3.1.0 stable from 3.0 stable.

**Comment by 13regent** [comment]
Any update on this? I cant get anything listed in my "software updates". I can sometimes get my full "installed packages" to populate.

**Comment by marticliment** [comment]
Please test the 3.1.1-beta1 release

**Comment by marticliment** [comment]
https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta1/UniGetUI.Installer.exe

**Comment by Martin-SF** [comment]
@marticliment Unfortunately my posts from above are already with 3.1.1-beta1. Same behaviour as since i updated to 3.1.0

**Comment by marticliment** [comment]
Please share logs of 3.1.1-b1

**Comment by 13regent** [comment]
[07/13/2024 5:25:19 PM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /  
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                        \____/_/ /_/_/\____/\___/\__/\____/___/   
                            Welcome to UniGetUI Version 3.1.1-beta1
[07/13/2024 5:25:19 PM]
[07/13/2024 5:25:19 PM] Version Code:  3.1091
[07/13/2024 5:25:19 PM] Encoding Code Page set to 437
[07/13/2024 5:25:23 PM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[07/13/2024 5:25:25 PM] Loaded language locale: en
[07/13/2024 5:25:28 PM] Randomly-generated background API auth token for the current session: 056zzxu9w2mvykswj5t1yuieoxq33lhqj9ydksnvyw2rwu7jojruwm3bs0gaur3s
[07/13/2024 5:25:30 PM] Api running on http://localhost:7058
[07/13/2024 5:25:33 PM] Lang files were updated successfully from GitHub
[07/13/2024 5:25:33 PM] UniGetUI is up to date
[07/13/2024 5:25:33 PM] Command npm was not found on the system
[07/13/2024 5:25:33 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: False
                        █ THE MANAGER IS DISABLED
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:25:36 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: pip
                        █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\python.exe
                        █ Call arguments:  -m pip
                        █ Version: 
                        █   
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:25:36 PM] Downloaded new icons and screenshots successfully!
[07/13/2024 5:25:40 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: dotnet tool
                        █ Executable path: C:\Program Files\dotnet\dotnet.exe
                        █ Call arguments: tool
                        █ Version: 
                        █   6.0.424
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:25:42 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: choco.exe
                        █ Executable path: C:\Users\Scott\AppData\Local\UniGetUI\Chocolatey\choco.exe
                        █ Call arguments: 
                        █ Version: 
                        █   2.2.2
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:25:43 PM] System.TimeoutException: The operation has timed out.
                           at UniGetUI.PackageEngine.PEInterface.Initialize() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageEngine\PEInterface.cs:line 47
[07/13/2024 5:25:43 PM] Timeout: Not all package managers have finished initializing.
[07/13/2024 5:25:59 PM] PowerShell sources took too long to load, using known sources as default
[07/13/2024 5:25:59 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: powershell.exe
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.19041.4648                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.19041.4648                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:26:00 PM] Scoop sources took too long to load, using known sources as default
[07/13/2024 5:26:00 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: scoop
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                        █ Version: 
                        █   Current Scoop version:
                        █   
                        █   'main' bucket:
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:26:02 PM] Winget sources took too long to load, using known sources as default
[07/13/2024 5:26:02 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancye exe name: winget.exe
                        █ Executable path: C:\Users\Scott\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   Native WinGet CLI Version: v1.8.1911
                        █   Microsoft.WinGet.Client PSModule version: 
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07/13/2024 5:26:07 PM] Found 0 available updates from Pip
[07/13/2024 5:26:07 PM] Found 0 installed packages from Pip
[07/13/2024 5:26:07 PM] Dependency WinGet PowerShell Module for manager Winget is present
[07/13/2024 5:26:09 PM] Found 0 available updates from Chocolatey
[07/13/2024 5:26:09 PM] Found 0 installed packages from Chocolatey
[07/13/2024 5:26:09 PM] Found 3 installed packages from Scoop
[07/13/2024 5:26:11 PM] Found 1 installed packages from .NET Tool
[07/13/2024 5:26:11 PM] Dependency Scoop-Search for manager Scoop is present
[07/13/2024 5:26:12 PM] Dependency Git for manager Scoop is present
[07/13/2024 5:26:13 PM] Dependency .NET Tools Outdated for manager .NET Tool is present
[07/13/2024 5:26:13 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[07/13/2024 5:26:23 PM] Found 0 available updates from .NET Tool
[07/13/2024 5:26:23 PM] Found 1 installed packages from PowerShell
[07/13/2024 5:26:23 PM] Found 0 available updates from PowerShell
[07/13/2024 5:26:31 PM] Found 339 installed packages from Winget
[07/13/2024 5:26:33 PM] Found 7 available updates from Winget
[07/13/2024 5:26:44 PM] Error finding updates on manager Scoop
[07/13/2024 5:26:44 PM] System.TimeoutException: The operation has timed out.
                           at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189

**Comment by marticliment** [comment]
Fixed by 0a86316fddc7a90102e77e6dda661b703f2308bc

**Comment by 13regent** [comment]
So just wait for the next update?

**Comment by marticliment** [comment]
yes
