### ISSUE TITLE
[BUG] Chinese garbled names appear in the package list 

### ISSUE THREAD

**Issue by FloatStream** [marticliment/UniGetUI#2450]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 10 Pro 22H2(19045.4598) x64

### Describe your issue

After updating to the latest UnigetUI, it was found that the Chinese characters in the package name were garbled. Currently, it is speculated that the encoding conversion error was caused by using the system Winget. I hope it can be fixed. There are also garbled characters in the log file. After exporting it as a file, I conducted a simple test by transforming the encoding. Whether using GBK (Chinese National Standard Encoding) or UTF-8, they could not be decoded correctly. It is possible that the two encoding methods were used in the wrong order, resulting in a complete encoding error.

The Chinese encoding processing in Windows is a mess. I remember seeing someone analyze the cause of this situation before but I can't find it now; Anyway, it's quite troublesome. May need to change the API to obtain the information provided by the system Winget

![Clip_2024-07-07_16-38-25](https://github.com/marticliment/UniGetUI/assets/69284622/cdbb818e-ecde-4e52-a2ce-f906813f5d93)

### UniGetUI Log

```text
[2024/7/6 15:14:17] 
                       __  __      _ ______     __  __  ______
                      / / / /___  (_) ____/__  / /_/ / / /  _/
                     / / / / __ \/ / / __/ _ \/ __/ / / // /  
                    / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                    \____/_/ /_/_/\____/\___/\__/\____/___/   
                        Welcome to UniGetUI Version 3.1.0
[2024/7/6 15:14:17]
[2024/7/6 15:14:17] Version Code:  3.1
[2024/7/6 15:14:19] Loaded language locale: zh_CN
[2024/7/6 15:14:21] Randomly-generated background API auth token for the current session: 2vwlpmn1pajtup2msr5g0yv9h8x17j6kuz15tbk48ulz576b71e3962vwooxlxow
[2024/7/6 15:14:22] Api running on http://localhost:7058
[2024/7/6 15:14:23] Using System GSudo at C:\Program Files\gsudo\Current\gsudo.exe
[2024/7/6 15:14:23] Lang files were updated successfully from GitHub
[2024/7/6 15:14:23] Downloaded new icons and screenshots successfully!
[2024/7/6 15:14:24] Command npm was not found on the system
[2024/7/6 15:14:24] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Npm
                    █ Enabled: True
                    █ Found: False
                    █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                    █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:24] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: .NET Tool
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:24] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Pip
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: pip
                    █ Executable path: C:\Users\soar\AppData\Local\Microsoft\WindowsApps\python.exe
                    █ Call arguments:  -m pip
                    █ Version: 
                    █   
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:25] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Chocolatey
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:26] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Winget
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: winget.exe
                    █ Executable path: C:\Users\soar\AppData\Local\Microsoft\WindowsApps\winget.exe
                    █ Call arguments: 
                    █ Version: 
                    █   Naive WinGet CLI Version: v1.8.1791
                    █   Microsoft.WinGet.Client PSModule version: 
                    █   Using Native WinGet helper (COM Api)
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:27] Command scoop was not found on the system
[2024/7/6 15:14:27] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Scoop
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:27] UniGetUI is up to date
[2024/7/6 15:14:28] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: PowerShell
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: powershell.exe
                    █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                    █ Call arguments:  -NoProfile -Command
                    █ Version: 
                    █   Name                           Value                                                                                   
                    █   ----                           -----                                                                                   
                    █   PSVersion                      5.1.19041.4597                                                                          
                    █   PSEdition                      Desktop                                                                                 
                    █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                    █   BuildVersion                   10.0.19041.4597                                                                         
                    █   CLRVersion                     4.0.30319.42000                                                                         
                    █   WSManStackVersion              3.0                                                                                     
                    █   PSRemotingProtocolVersion      2.3                                                                                     
                    █   SerializationVersion           1.1.0.1
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/6 15:14:29] Resetting administrator rights cache for process id 9432
[2024/7/6 15:14:29] Found 0 available updates from Pip
[2024/7/6 15:14:29] Found 0 installed packages from Pip
[2024/7/6 15:14:31] Dependency WinGet PowerShell Module for manager Winget is present
[2024/7/6 15:14:31] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024/7/6 15:14:33] Found 1 installed packages from PowerShell
[2024/7/6 15:14:36] Found 0 available updates from PowerShell
[2024/7/6 15:14:48] Found 200 installed packages from Winget
[2024/7/6 15:14:48] Found 12 available updates from Winget
[2024/7/6 15:14:51] Found 0 installed packages from Pip
[2024/7/6 15:14:53] Update
[2024/7/6 15:14:53] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/7/6 15:14:53] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.PowerToys
[2024/7/6 15:14:53] Icon for package Microsoft.PowerToys stored on C:\Users\soar\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.PowerToys.png
[2024/7/6 15:14:53] Found 0 screenshots for package Id=Microsoft.PowerToys
[2024/7/6 15:14:56] Found 1 installed packages from PowerShell
[2024/7/6 15:14:58] Loaded details for package Microsoft.PowerToys on manager Winget
[2024/7/6 15:15:09] Found 200 installed packages from Winget
[2024/7/6 15:16:36] Update
[2024/7/6 15:16:36] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/7/6 15:16:36] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Ubisoft.Connect
[2024/7/6 15:16:36] An error occurred while retrieving the icon for package Ubisoft.Connect
[2024/7/6 15:16:36] System.ArgumentOutOfRangeException: startIndex ('-1') must be a non-negative value. (Parameter 'startIndex')
                    Actual value was -1.
                       at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
                       at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
                       at System.String.Substring(Int32 startIndex, Int32 length)
                       at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 71
                       at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 199
[2024/7/6 15:16:36] Found 0 screenshots for package Id=Ubisoft.Connect
[2024/7/6 15:16:39] Loaded details for package Ubisoft.Connect on manager Winget
[2024/7/6 15:16:45] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/7/6 15:16:45] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.PowerToys
[2024/7/6 15:16:45] Icon for package Microsoft.PowerToys stored on C:\Users\soar\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.PowerToys.png
[2024/7/6 15:16:45] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/7/6 15:16:45] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Ubisoft.Connect
[2024/7/6 15:16:45] An error occurred while retrieving the icon for package Ubisoft.Connect
[2024/7/6 15:16:45] System.ArgumentOutOfRangeException: startIndex ('-1') must be a non-negative value. (Parameter 'startIndex')
                    Actual value was -1.
                       at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
                       at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
                       at System.String.Substring(Int32 startIndex, Int32 length)
                       at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 71
                       at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 199
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/7/6 15:14:25
Process end time:   2024/7/6 15:14:26

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\soar\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024/7/6 15:14:28
Process end time:   2024/7/6 15:14:30

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/6 15:14:28
Process end time:   2024/7/6 15:14:48

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : �޷�����﻿Write-Output����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·��
  ����ȷ��·����ȷ��Ȼ������һ�Ρ�
  ����λ�� ��:1 �ַ�: 1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/7/6 15:14:29
Process end time:   2024/7/6 15:14:29

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/6 15:14:30
Process end time:   2024/7/6 15:14:48

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : �޷�����﻿Write-Output����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·��
  ����ȷ��·����ȷ��Ȼ������һ�Ρ�
  ����λ�� ��:1 �ַ�: 1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/6 15:14:51
Process end time:   2024/7/6 15:15:09

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : �޷�����﻿Write-Output����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·��
  ����ȷ��·����ȷ��Ȼ������һ�Ρ�
  ����λ�� ��:1 �ַ�: 1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 2024/7/6 15:14:53
Process end time:   2024/7/6 15:14:58

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 2024/7/6 15:14:53
Process end time:   2024/7/6 15:14:54

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 2024/7/6 15:16:36
Process end time:   2024/7/6 15:16:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 2024/7/6 15:16:36
Process end time:   2024/7/6 15:16:37

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Hello,

To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.

UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0
Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

Excuse me for the inconveniences.

**Comment by FloatStream** [comment]
Thank you, I will try it out

**Comment by marticliment** [comment]
Let me know if it resolves the issue for you

**Comment by FloatStream** [comment]
It's very effective and looks very good

![Clip_2024-07-07_19-30-09](https://github.com/marticliment/UniGetUI/assets/69284622/2be7518e-bc25-4e0f-b8ca-cb9d04f0df18)
