### ISSUE TITLE
[BUG] When sorting a search result the package source's name occasionally displays the wrong source name

### ISSUE THREAD

**Issue by hboyd2003** [marticliment/UniGetUI#2464]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1-beta1

### Windows version, edition, and architecture

Windows 11 Pro 22H2 x64

### Describe your issue

Occasionally, when sorting a search result the source's name may display wrong (all other information for the respective package remains correct)
This bug is quite confusing and remains persistent between searches so exact causes are hard to pin down.
![image](https://github.com/marticliment/UniGetUI/assets/8950185/07a80630-5625-4656-abd8-7175a4c7c191)

### Steps to reproduce the issue

I could only find one search query that displayed this bug consistently.
1. Search for "Iconsextract"
2. From any search mode that has a greater number of packages than another search mode check a package that will still be displayed in the search mode that displays less packages
3. Switch the to search mode that displays less packages
4. Sort by anything a couple of times

Note: Sorting is not needed to actually display the bug simply switching search modes can sometimes cause it to show.

## Logs
<details>
  <summary>UniGetUI Log</summary>

```text
[2024-07-09 22:48:19]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.1-beta1
[2024-07-09 22:48:19]
[2024-07-09 22:48:19] Version Code:  3.1091
[2024-07-09 22:48:19] Encoding Code Page set to 437
[2024-07-09 22:48:19] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[2024-07-09 22:48:19] Loaded language locale: en
[2024-07-09 22:48:20] Starting update check
[2024-07-09 22:48:20] Randomly-generated background API auth token for the current session: pcb760s3ajvye7tg4a6csipr01snz46kb8ul4bj4k4by55syciqr110uwdl0rh0l
[2024-07-09 22:48:20] Api running on http://localhost:7058
[2024-07-09 22:48:20] Begin "which" search for command winget.exe
[2024-07-09 22:48:20] Moving Bundled Chocolatey from old path to new path...
[2024-07-09 22:48:20] An error occurred while migrating chocolatey
[2024-07-09 22:48:20] System.ArgumentException: The path is empty. (Parameter 'relativeTo')
                         at System.IO.Path.GetRelativePath(String relativeTo, String path, StringComparison comparisonType)
                         at UniGetUI.PackageEngine.Managers.ChocolateyManager.Chocolatey.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Chocolatey\Chocolatey.cs:line 279
[2024-07-09 22:48:20] Begin "which" search for command npm
[2024-07-09 22:48:20] Begin "which" search for command python.exe
[2024-07-09 22:48:20] Begin "which" search for command dotnet.exe
[2024-07-09 22:48:20] Lang files were updated successfully from GitHub
[2024-07-09 22:48:20] UniGetUI is up to date
[2024-07-09 22:48:20] Downloaded new icons and screenshots successfully!
[2024-07-09 22:48:20] Command winget.exe was found on C:\Users\harri\AppData\Local\Microsoft\WindowsApps\winget.exe
[2024-07-09 22:48:20] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[2024-07-09 22:48:20] Command npm was found on C:\Program Files\nodejs\npm
[2024-07-09 22:48:20] Command python.exe was not found on the system
[2024-07-09 22:48:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:20] Saving window geometry -8,-8,2576,1408,1
[2024-07-09 22:48:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:20] Loaded 2 sources for manager Winget
[2024-07-09 22:48:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\harri\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Native WinGet CLI Version: v1.8.1791
                      █   Microsoft.WinGet.Client PSModule version: 
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:21] Begin "which" search for command scoop
[2024-07-09 22:48:21] Command scoop was found on C:\Users\harri\scoop\shims\scoop
[2024-07-09 22:48:22] Loaded 1 sources for manager Chocolatey
[2024-07-09 22:48:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\harri\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   This is try 1/3. Retrying after 400 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.35072.update' is denied.
                      █   This is try 2/3. Retrying after 600 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.35072.update' is denied.
                      █   Maximum tries of 3 reached. Throwing error.
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:22] Loaded 4 sources for manager Scoop
[2024-07-09 22:48:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: scoop
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   716b6db3 chore(release): Bump to version 0.5.0 (#6035)
                      █   
                      █   'main' bucket:
                      █   ce120886d oh-my-posh: Update to version 21.23.1
                      █   
                      █   'extras' bucket:
                      █   afd29e784 x64dbg: Update to version 2024-07-09_23-55
                      █   
                      █   'nirsoft' bucket:
                      █   62f97d6 Update README.md
                      █   
                      █   'java' bucket:
                      █   fdb41b89 temurin17-nightly-jre: Update to version 17.0.12-6.0.ea
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-07-09 22:48:22] Manager Chocolatey has not implemented RefreshPackageIndexes
[2024-07-09 22:48:23] Loaded 2 sources for manager Winget
[2024-07-09 22:48:23] Dependency WinGet PowerShell Module for manager Winget is present
[2024-07-09 22:48:23] Begin "which" search for command scoop-search.exe
[2024-07-09 22:48:23] Command scoop-search.exe was found on C:\Users\harri\scoop\shims\scoop-search.exe
[2024-07-09 22:48:23] Dependency Scoop-Search for manager Scoop is present
[2024-07-09 22:48:23] Begin "which" search for command git.exe
[2024-07-09 22:48:23] Command git.exe was found on C:\Program Files\Git\cmd\git.exe
[2024-07-09 22:48:23] Dependency Git for manager Scoop is present
[2024-07-09 22:48:23] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024-07-09 22:48:23] Found 1 installed packages from Chocolatey
[2024-07-09 22:48:23] Found 41 installed packages from Scoop
[2024-07-09 22:48:23] Loaded 1 sources for manager Chocolatey
[2024-07-09 22:48:24] Found 0 available updates from Chocolatey
[2024-07-09 22:48:24] Loaded 4 sources for manager Scoop
[2024-07-09 22:48:26] Begin "which" search for command scoop-search.exe
[2024-07-09 22:48:26] Command scoop-search.exe was found on C:\Users\harri\scoop\shims\scoop-search.exe
[2024-07-09 22:48:27] Found 0 available packages from Winget with the query Iconsextract
[2024-07-09 22:48:27] Found 1 available packages from Scoop with the query Iconsextract
[2024-07-09 22:48:27] Loaded 1 sources for manager Chocolatey
[2024-07-09 22:48:27] Found 12 available packages from Chocolatey with the query Iconsextract
[2024-07-09 22:48:28] Found 41 installed packages from Scoop
[2024-07-09 22:48:28] Found 43 available updates from Winget
[2024-07-09 22:48:29] Found 478 installed packages from Winget
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=ds4windows
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=gpu-z
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=graalvm21-jdk11
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=graalvm22-jdk17
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=iconsextract
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=meshroom
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=msiafterburner
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=openrgb
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=opus-tools
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=resource-tuner
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=secureuxtheme
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=serviwin
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=simplewmiview
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=wifiinfoview
[2024-07-09 22:48:31] Upgradable scoop package not listed on installed packages - id=winaero-tweaker
[2024-07-09 22:48:31] Found 9 available updates from Scoop
[2024-07-09 22:48:32] Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
```

</details>

<details>
  <summary>WinGet Log</summary>

```text
Manager Winget with version:
Native WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-07-09 22:48:20
Process end time:   2024-07-09 22:48:20

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\harri\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:23

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:29

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:23

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-07-09 22:48:23
Process end time:   2024-07-09 22:48:28

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 2024-07-09 22:48:26
Process end time:   2024-07-09 22:48:27

-- Task information
 ...

The task reported success

——————————————————————————————————————————

</details>

<details>
  <summary>Scoop Log</summary>

Manager Scoop with version:
Current Scoop version:
716b6db3 chore(release): Bump to version 0.5.0 (#6035)

'main' bucket:
ce120886d oh-my-posh: Update to version 21.23.1

'extras' bucket:
afd29e784 x64dbg: Update to version 2024-07-09_23-55

'nirsoft' bucket:
62f97d6 Update README.md

'java' bucket:
fdb41b89 temurin17-nightly-jre: Update to version 17.0.12-6.0.ea

——————————————————————————————————————————


Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 2024-07-09 22:48:21
Process end time:   2024-07-09 22:48:22

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is RefreshIndexes
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop update"
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:27

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:23

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 2024-07-09 22:48:22
Process end time:   2024-07-09 22:48:24

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is FindPackages
Subprocess executable: "C:\Users\harri\scoop\shims\scoop-search.exe"
Command-line arguments: "Iconsextract"
Process start time: 2024-07-09 22:48:26
Process end time:   2024-07-09 22:48:27

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 2024-07-09 22:48:27
Process end time:   2024-07-09 22:48:28

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListUpdates
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop status"
Process start time: 2024-07-09 22:48:28
Process end time:   2024-07-09 22:48:31

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————
```

</details>

### Screenshots and videos

![None233](https://github.com/marticliment/UniGetUI/assets/8950185/56f69f2f-3427-4c0c-8bf3-a5319110f42b)

**Comment by hboyd2003** [comment]
I believe this has been fixed with 3.1.1?
@marticliment
