### ISSUE TITLE
[BUG] Some characters (such as Simplified Chinese) display garbled characters

### ISSUE THREAD

**Issue by MC-Nirvana** [marticliment/UniGetUI#2478]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Professional Workstation Edition 22631.3880

### Describe your issue

Some programs with simplified Chinese names have garbled characters in the interface, and Chinese garbled characters may also appear in the logs during updates

### Steps to reproduce the issue

1. Open the program
2. Check software updates

### UniGetUI Log

```text
[2024/7/12 9:39:05] 
                       __  __      _ ______     __  __  ______
                      / / / /___  (_) ____/__  / /_/ / / /  _/
                     / / / / __ \/ / / __/ _ \/ __/ / / // /  
                    / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                    \____/_/ /_/_/\____/\___/\__/\____/___/   
                        Welcome to UniGetUI Version 3.1.0
[2024/7/12 9:39:05]
[2024/7/12 9:39:05] Version Code:  3.1
[2024/7/12 9:39:06] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[2024/7/12 9:39:06] Loaded language locale: zh_CN
[2024/7/12 9:39:06] Randomly-generated background API auth token for the current session: helg95474hq7u7e0p69bmev51yk941wv8zy4b3khberyhbvphb4bh5ep2nrsr2sb
[2024/7/12 9:39:07] Api running on http://localhost:7058
[2024/7/12 9:39:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Chocolatey
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:07] Lang files were updated successfully from GitHub
[2024/7/12 9:39:07] Downloaded new icons and screenshots successfully!
[2024/7/12 9:39:08] UniGetUI is up to date
[2024/7/12 9:39:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: .NET Tool
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:09] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Pip
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: pip
                    █ Executable path: C:\Program Files\Python312\python.exe
                    █ Call arguments:  -m pip
                    █ Version: 
                    █   pip 24.1.2 from C:\Program Files\Python312\Lib\site-packages\pip (python 3.12)
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Winget
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: winget.exe
                    █ Executable path: C:\Users\nirvana\AppData\Local\Microsoft\WindowsApps\winget.exe
                    █ Call arguments: 
                    █ Version: 
                    █   Naive WinGet CLI Version: v1.8.1911
                    █   Microsoft.WinGet.Client PSModule version: 
                    █   Using Native WinGet helper (COM Api)
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Npm
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: npm
                    █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                    █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                    █ Version: 
                    █   10.7.0
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:12] Starting scoop cleanup...
[2024/7/12 9:39:13] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: PowerShell
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: powershell.exe
                    █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                    █ Call arguments:  -NoProfile -Command
                    █ Version: 
                    █   Name                           Value                                                                                   
                    █   ----                           -----                                                                                   
                    █   PSVersion                      5.1.22621.3880                                                                          
                    █   PSEdition                      Desktop                                                                                 
                    █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                    █   BuildVersion                   10.0.22621.3880                                                                         
                    █   CLRVersion                     4.0.30319.42000                                                                         
                    █   WSManStackVersion              3.0                                                                                     
                    █   PSRemotingProtocolVersion      2.3                                                                                     
                    █   SerializationVersion           1.1.0.1
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:15] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Scoop
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: scoop
                    █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                    █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                    █ Version: 
                    █   Current Scoop version:
                    █   716b6db3 chore(release): Bump to version 0.5.0 (#6035)
                    █   
                    █   'main' bucket:
                    █   56df08a6a terragrunt: Update to version 0.61.0
                    █   
                    █   'extras' bucket:
                    █   038ed34c0 Merge branch 'master' of https://github.com/ScoopInstaller/Extras
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/7/12 9:39:16] Resetting administrator rights cache for process id 21380
[2024/7/12 9:39:17] Scoop cleanup finished!
[2024/7/12 9:39:21] Dependency WinGet PowerShell Module for manager Winget is present
[2024/7/12 9:39:23] Found 0 available updates from Pip
[2024/7/12 9:39:23] Dependency Scoop-Search for manager Scoop is present
[2024/7/12 9:39:23] Found 14 installed packages from Pip
[2024/7/12 9:39:23] Found 1 installed packages from Scoop
[2024/7/12 9:39:23] Found 0 available updates from Npm
[2024/7/12 9:39:23] Dependency Git for manager Scoop is present
[2024/7/12 9:39:23] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024/7/12 9:39:23] Found 1 installed packages from PowerShell
[2024/7/12 9:39:25] Found 0 installed packages from Npm
[2024/7/12 9:39:26] Found 1 available updates from PowerShell
[2024/7/12 9:39:40] Found 1 installed packages from Scoop
[2024/7/12 9:40:06] Found 271 installed packages from Winget
[2024/7/12 9:40:15] Error finding updates on manager Winget
[2024/7/12 9:40:15] System.TimeoutException: The operation has timed out.
                       at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[2024/7/12 9:40:30] Found 0 available updates from Scoop
[2024/7/12 9:40:41] No Icon URL could be parsed on the manifest Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.WinGet.Client',Version='1.8.1791')
[2024/7/12 9:40:41] Icon for package Microsoft.WinGet.Client was not found, returning default icon
[2024/7/12 10:01:24] No Icon URL could be parsed on the manifest Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.WinGet.Client',Version='1.8.1791')
[2024/7/12 10:01:24] Icon for package Microsoft.WinGet.Client was not found, returning default icon
[2024/7/12 10:39:09] UniGetUI is up to date
[2024/7/12 11:39:10] UniGetUI is up to date
[2024/7/12 12:39:11] UniGetUI is up to date
[2024/7/12 13:39:12] UniGetUI is up to date
[2024/7/12 14:07:22] Found 1 installed packages from Scoop
[2024/7/12 14:07:23] Found 14 installed packages from Pip
[2024/7/12 14:07:27] Found 1 installed packages from PowerShell
[2024/7/12 14:07:27] Found 0 installed packages from Npm
[2024/7/12 14:08:20] Error finding installed packages on manager Winget
[2024/7/12 14:08:20] System.TimeoutException: The operation has timed out.
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 217
[2024/7/12 14:10:06] Found 14 installed packages from Pip
[2024/7/12 14:10:07] Found 1 installed packages from Scoop
[2024/7/12 14:10:13] Found 1 installed packages from PowerShell
[2024/7/12 14:10:14] Found 0 installed packages from Npm
[2024/7/12 14:11:02] Error finding installed packages on manager Winget
[2024/7/12 14:11:02] System.TimeoutException: The operation has timed out.
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 217
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/7/12 9:39:09
Process end time:   2024/7/12 9:39:10

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\nirvana\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024/7/12 9:39:15
Process end time:   2024/7/12 9:41:51

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/12 9:39:15
Process end time:   2024/7/12 9:40:06

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : �޷�����﻿Write-Output����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·��
  ����ȷ��·����ȷ��Ȼ������һ�Ρ�
  ����λ�� ��:1 �ַ�: 1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/7/12 9:39:17
Process end time:   2024/7/12 9:39:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/12 14:07:20
Process end time:   2024/7/12 14:08:52

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : �޷�����﻿Write-Output����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·��
  ����ȷ��·����ȷ��Ȼ������һ�Ρ�
  ����λ�� ��:1 �ַ�: 1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 2024/7/12 14:10:02
Process end time:   UNFINISHED

-- Process STDIN
 ...

-- Process STDOUT
 ...

Return code: Process has not finished yet

——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/0be11491-4f7e-4ec3-8ef8-174a59462ab3)

**Comment by sans-125** [comment]
The Chinese characters on the software UI also have this question. The name of the software package is displaying abnormally.
![image](https://github.com/user-attachments/assets/6e464687-11e2-4624-a88e-4a5d5759ac5b)

**Comment by marticliment** [comment]
Please install UniGetUI 3.1.1-beta1 (https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta1/UniGetUI.Installer.exe)
