### ISSUE TITLE
[BUG] Maybe Slow PC showing timeouts and Winget was not found

### ISSUE THREAD

**Issue by Tschak77** [marticliment/UniGetUI#2481]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1 beta 1

### Windows version, edition, and architecture

Windows 11 Pro 10.0.26100.1150

### Describe your issue

I have round about 37 installations of UniGetUI 3.1.0 but also testet with 3.1.1 beta 1
It seems on slow pc I will get timeouts and the Settings at Winget show "Winget was not found" but it seems all is working

### Steps to reproduce the issue

very difficult. It seems faster PC are working and slow PC show this problem

### UniGetUI Log

```text
[12.07.2024 10:35:27]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /  
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                      \____/_/ /_/_/\____/\___/\__/\____/___/   
                          Welcome to UniGetUI Version 3.1.1-beta1
[12.07.2024 10:35:27]
[12.07.2024 10:35:27] Version Code:  3,1091
[12.07.2024 10:35:27] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 27
[12.07.2024 10:35:27] Encoding Code Page set to 0
[12.07.2024 10:35:27] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[12.07.2024 10:35:28] Loaded language locale: en
[12.07.2024 10:35:29] Starting update check
[12.07.2024 10:35:29] Randomly-generated background API auth token for the current session: mo1knaclj38pwh4nkr5fofno3w34g7ogoua25pfdyulztzft6vc8e9qo74947zp1
[12.07.2024 10:35:29] Api running on http://localhost:7058
[12.07.2024 10:35:29] Begin "which" search for command winget.exe
[12.07.2024 10:35:30] Begin "which" search for command npm
[12.07.2024 10:35:30] Begin "which" search for command python.exe
[12.07.2024 10:35:30] Begin "which" search for command dotnet.exe
[12.07.2024 10:35:30] Lang files were updated successfully from GitHub
[12.07.2024 10:35:30] UniGetUI is up to date
[12.07.2024 10:35:30] Command winget.exe was found on C:\Users\admis\AppData\Local\Microsoft\WindowsApps\winget.exe
[12.07.2024 10:35:31] Command npm was not found on the system
[12.07.2024 10:35:31] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:31] Command python.exe was found on C:\Users\admis\AppData\Local\Microsoft\WindowsApps\python.exe
[12.07.2024 10:35:31] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[12.07.2024 10:35:35] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Users\admis\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:35] Downloaded new icons and screenshots successfully!
[12.07.2024 10:35:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.303
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:39] Begin "which" search for command scoop
[12.07.2024 10:35:39] Command scoop was not found on the system
[12.07.2024 10:35:39] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:40] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.PEInterface.Initialize() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageEngine\PEInterface.cs:line 47
[12.07.2024 10:35:40] Timeout: Not all package managers have finished initializing.
[12.07.2024 10:35:40] Manager Chocolatey has not implemented RefreshPackageIndexes
[12.07.2024 10:35:40] Manager Pip has not implemented RefreshPackageIndexes
[12.07.2024 10:35:41] Manager .NET Tool has not implemented RefreshPackageIndexes
[12.07.2024 10:35:41] Begin "which" search for command dotnet-tools-outdated.exe
[12.07.2024 10:35:41] Manager PowerShell has not implemented RefreshPackageIndexes
[12.07.2024 10:35:43] Resetting administrator rights cache for process id 11120
[12.07.2024 10:35:43] Begin "which" search for command dotnet-tools-outdated.exe
[12.07.2024 10:35:44] Command dotnet-tools-outdated.exe was found on C:\Users\admis\.dotnet\tools\dotnet-tools-outdated.exe
[12.07.2024 10:35:48] Chocolatey sources took too long to load, using known sources as default
[12.07.2024 10:35:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: choco.exe
                      █ Executable path: C:\Users\admis\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:51] PowerShell sources took too long to load, using known sources as default
[12.07.2024 10:35:51] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.1150                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.1150                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:54] Command dotnet-tools-outdated.exe was found on C:\Users\admis\.dotnet\tools\dotnet-tools-outdated.exe
[12.07.2024 10:35:54] Dependency .NET Tools Outdated for manager .NET Tool is present
[12.07.2024 10:35:54] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[12.07.2024 10:35:54] Found 0 available updates from Pip
[12.07.2024 10:35:54] Found 0 installed packages from Pip
[12.07.2024 10:35:54] Found 0 available updates from .NET Tool
[12.07.2024 10:35:55] Loaded 1 sources for manager Chocolatey
[12.07.2024 10:35:55] Found 0 available updates from Chocolatey
[12.07.2024 10:35:55] Found 0 installed packages from Chocolatey
[12.07.2024 10:35:55] Loaded 1 sources for manager Chocolatey
[12.07.2024 10:35:56] Loaded 2 sources for manager Winget
[12.07.2024 10:35:56] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\admis\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Native WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: 
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12.07.2024 10:35:58] Found 1 installed packages from .NET Tool
[12.07.2024 10:36:14] Loaded 1 sources for manager PowerShell
[12.07.2024 10:36:16] Loaded 1 sources for manager PowerShell
[12.07.2024 10:36:18] Found 4 installed packages from PowerShell
[12.07.2024 10:36:23] Found 0 available updates from PowerShell
[12.07.2024 10:36:23] Starting check for updates wait interval with waitTime=3600
```

### Package Managers Logs

```text
Manager Winget with version:
Native WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 12.07.2024 10:35:56
Process end time:   12.07.2024 10:35:56

-- Task information
  Found source msstore with argument https://storeedgefd.dsx.mp.microsoft.com/v9.0
  Found source winget with argument https://cdn.winget.microsoft.com/cache

The task reported success

——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/faa50a55-99c4-419e-a476-1b25aa48ab84)

**Comment by marticliment** [comment]
Will investigate
