### ISSUE TITLE
[BUG] 3.1.1 Beta 3 - START OF UNHANDLED ERROR TRACE - Unable to cast object of type 'System.Collections.Generic.List

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/UniGetUI#2535]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1. Beta 3

### Windows version, edition, and architecture

Win10 x64

### Describe your issue

START OF UNHANDLED ERROR TRACE shows up when trying to export log, or open Packagemanager logs.

### Steps to reproduce the issue

Start 3.1.1 Beta 3, wait till finished, go to UniGet log and try to export, or try to open packagemanager logs.

### UniGetUI Log

```text
[23/07/2024 10:41:57]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1-beta3
[23/07/2024 10:41:57]
[23/07/2024 10:41:57] Version Code:  3,1093
[23/07/2024 10:41:58] Encoding Code Page set to 437
[23/07/2024 10:41:58] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[23/07/2024 10:41:59] Loaded language locale: en
[23/07/2024 10:42:00] Starting update check
[23/07/2024 10:42:00] Randomly-generated background API auth token for the current session: mcc41tevnp34zsrenzocebymdm9oa4i4prr7z5r4dmyw6potijukof9eptfkmcn5
[23/07/2024 10:42:00] Api running on http://localhost:7058
[23/07/2024 10:42:00] Begin "which" search for command winget.exe
[23/07/2024 10:42:00] Old chocolatey path does not exist, not migrating Chocolatey
[23/07/2024 10:42:00] Begin "which" search for command choco.exe
[23/07/2024 10:42:00] Begin "which" search for command npm
[23/07/2024 10:42:00] Begin "which" search for command python.exe
[23/07/2024 10:42:00] Begin "which" search for command dotnet.exe
[23/07/2024 10:42:00] Begin "which" search for command pwsh.exe
[23/07/2024 10:42:01] Saving window geometry -8,-8,1936,1176,1
[23/07/2024 10:42:01] Command npm was not found on the system
[23/07/2024 10:42:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:01] Command winget.exe was found on C:\Users\<REMOVED>\AppData\Local\Microsoft\WindowsApps\winget.exe
[23/07/2024 10:42:06] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[23/07/2024 10:42:06] Command python.exe was found on C:\Program Files\Python312\python.exe
[23/07/2024 10:42:06] Command choco.exe was not found on the system
[23/07/2024 10:42:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:06] Command pwsh.exe was not found on the system
[23/07/2024 10:42:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:06] Begin "which" search for command scoop
[23/07/2024 10:42:06] Lang files were updated successfully from GitHub
[23/07/2024 10:42:06] Downloaded new icons and screenshots successfully!
[23/07/2024 10:42:06] Command scoop was found on C:\Users\<REMOVED>\scoop\shims\scoop
[23/07/2024 10:42:07] UniGetUI is up to date
[23/07/2024 10:42:07] Error finding sources for manager .NET Tool
[23/07/2024 10:42:07] System.InvalidOperationException: Manager .NET Tool does not support custom sources but yet GetSources method was called.
                          at System.Environment.get_StackTrace()
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.AssertSourceCompatibility(String MethodName) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 354
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 399
                         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources()
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 91
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
                         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
                         at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
                         at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
                         at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
                         at UniGetUI.PackageEngine.Managers.DotNetManager.DotNet.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Dotnet\DotNet.cs:line 332
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
                         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
                         at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
                         at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr thisPtr)
                         at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(IObjectReference _obj, ApplicationInitializationCallback callback)
                         at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
                         at UniGetUI.EntryPoint.AsyncMain(String[] args) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\EntryPoint.cs:line 71
                         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
                         at UniGetUI.EntryPoint.AsyncMain(String[] args)
                         at UniGetUI.EntryPoint.Main(String[] args) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\EntryPoint.cs:line 32
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.AssertSourceCompatibility(String MethodName) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 354
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 399
[23/07/2024 10:42:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   6.0.424
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:07] Error finding sources for manager Pip
[23/07/2024 10:42:07] System.InvalidOperationException: Manager Pip does not support custom sources but yet GetSources method was called.
                          at System.Environment.get_StackTrace()
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.AssertSourceCompatibility(String MethodName) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 354
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 399
                         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources()
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 91
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
                         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
                         at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
                         at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
                         at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 360
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
                         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
                         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
                         at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
                         at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr thisPtr)
                         at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(IObjectReference _obj, ApplicationInitializationCallback callback)
                         at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
                         at UniGetUI.EntryPoint.AsyncMain(String[] args) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\EntryPoint.cs:line 71
                         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
                         at UniGetUI.EntryPoint.AsyncMain(String[] args)
                         at UniGetUI.EntryPoint.Main(String[] args) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\EntryPoint.cs:line 32
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.AssertSourceCompatibility(String MethodName) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 354
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 399
[23/07/2024 10:42:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: pip
                      █ Executable path: C:\Program Files\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.1.2 from C:\Users\<REMOVED>\AppData\Roaming\Python\Python312\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:08] Loaded 2 sources for manager Winget
[23/07/2024 10:42:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: winget.exe
                      █ Executable path: C:\Users\<REMOVED>\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.1792-preview
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:08] Loaded 1 sources for manager Scoop
[23/07/2024 10:42:08] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   be56faf2 chore(release): Bump to version 0.5.1 (#6057)
                      █   
                      █   'main' bucket:
                      █   98b2e6cd9 symfony-cli: Update to version 5.10.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:09] Loaded 1 sources for manager PowerShell
[23/07/2024 10:42:09] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancye exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.4648                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.4648                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/07/2024 10:42:09] Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
[23/07/2024 10:42:12] Manager Pip has not implemented RefreshPackageIndexes
[23/07/2024 10:42:12] Manager .NET Tool has not implemented RefreshPackageIndexes
[23/07/2024 10:42:12] Begin "which" search for command dotnet-tools-outdated.exe
[23/07/2024 10:42:12] Manager PowerShell has not implemented RefreshPackageIndexes
[23/07/2024 10:42:14] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[23/07/2024 10:42:14] Dependency WinGet PowerShell Module for manager Winget is present
[23/07/2024 10:42:14] Begin "which" search for command scoop-search.exe
[23/07/2024 10:42:14] Command dotnet-tools-outdated.exe was found on C:\Users\<REMOVED>\.dotnet\tools\dotnet-tools-outdated.exe
[23/07/2024 10:42:14] Loaded 2 sources for manager Winget
[23/07/2024 10:42:16] Command scoop-search.exe was found on C:\Users\<REMOVED>\scoop\shims\scoop-search.exe
[23/07/2024 10:42:16] Dependency Scoop-Search for manager Scoop is present
[23/07/2024 10:42:16] Begin "which" search for command git.exe
[23/07/2024 10:42:17] Found 0 available updates from .NET Tool
[23/07/2024 10:42:17] Command git.exe was found on C:\Users\<REMOVED>\scoop\shims\git.exe
[23/07/2024 10:42:17] Dependency Git for manager Scoop is present
[23/07/2024 10:42:17] Begin "which" search for command dotnet-tools-outdated.exe
[23/07/2024 10:42:17] Found 3 installed packages from Scoop
[23/07/2024 10:42:17] Found 14 installed packages from Pip
[23/07/2024 10:42:17] Loaded 1 sources for manager Scoop
[23/07/2024 10:42:18] Found 3 installed packages from .NET Tool
[23/07/2024 10:42:18] Command dotnet-tools-outdated.exe was found on C:\Users\<REMOVED>\.dotnet\tools\dotnet-tools-outdated.exe
[23/07/2024 10:42:18] Dependency .NET Tools Outdated for manager .NET Tool is present
[23/07/2024 10:42:18] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[23/07/2024 10:42:18] Found 2 installed packages from PowerShell
[23/07/2024 10:42:18] Loaded 1 sources for manager PowerShell
[23/07/2024 10:42:19] Found 0 available updates from Pip
[23/07/2024 10:42:21] Found 0 available updates from PowerShell
[23/07/2024 10:42:23] Found 3 installed packages from Scoop
[23/07/2024 10:42:25] Found 5 available updates from Winget
[23/07/2024 10:42:25] Found 232 installed packages from Winget
[23/07/2024 10:42:25] Found 0 available updates from Scoop
[23/07/2024 10:42:25] Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
[23/07/2024 10:43:11]  -
[23/07/2024 10:43:11]  -
[23/07/2024 10:43:11]   ⚠️⚠️⚠️ START OF UNHANDLED ERROR TRACE ⚠️⚠️⚠️
[23/07/2024 10:43:11] Unable to cast object of type 'System.Collections.Generic.List`1[UniGetUI.PackageEngine.ManagerClasses.Classes.TaskLogger]' to type 'System.Collections.Generic.IEnumerable`1[UniGetUI.PackageEngine.ManagerClasses.Classes.ITaskLogger]'.
[23/07/2024 10:43:11] System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[UniGetUI.PackageEngine.ManagerClasses.Classes.TaskLogger]' to type 'System.Collections.Generic.IEnumerable`1[UniGetUI.PackageEngine.ManagerClasses.Classes.ITaskLogger]'.
                         at UniGetUI.PackageEngine.ManagerClasses.Classes.ManagerLogger.get_Operations() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\ManagerLogger.cs:line 15
                         at UniGetUI.Interface.Pages.LogPage.ManagerLogsPage.LoadLog() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Pages\LogPage\ManagerLogsPage.cs:line 33
                         at UniGetUI.Interface.Pages.BaseLogPage.LogLevelCombo_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Pages\LogPage\LogPage.xaml.cs:line 119
                         at WinRT._EventSource_global__Microsoft_UI_Xaml_Controls_SelectionChangedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, SelectionChangedEventArgs e)
                         at ABI.Microsoft.UI.Xaml.Controls.SelectionChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
                      --- End of stack trace from previous location ---
                         at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
                         at ABI.Microsoft.UI.Xaml.Controls.Primitives.ISelectorMethods.set_SelectedIndex(IObjectReference _obj, Int32 value)
                         at Microsoft.UI.Xaml.Controls.Primitives.Selector.set_SelectedIndex(Int32 value)
                         at UniGetUI.Interface.Pages.LogPage.ManagerLogsPage.LoadLogLevels() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Pages\LogPage\ManagerLogsPage.cs:line 68
                         at UniGetUI.Interface.Pages.BaseLogPage..ctor(Boolean log_level_enabled) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Pages\LogPage\LogPage.xaml.cs:line 35
                         at UniGetUI.Interface.Pages.LogPage.ManagerLogsPage..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\Pages\LogPage\ManagerLogsPage.cs:line 12
                         at UniGetUI.Interface.MainView.ManagerLogsMenu_Click(Object sender, RoutedEventArgs e) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\MainView.xaml.cs:line 591
                         at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
                         at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
                      --- End of stack trace from previous location ---
                         at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
                         at ABI.Microsoft.UI.Xaml.Controls.IControlOverridesMethods.OnPointerReleased(IObjectReference _obj, PointerRoutedEventArgs e)
                         at Microsoft.UI.Xaml.Controls.Control.OnPointerReleased(PointerRoutedEventArgs e)
                         at Microsoft.UI.Xaml.Controls.Control.Microsoft.UI.Xaml.Controls.IControlOverrides.OnPointerReleased(PointerRoutedEventArgs e)
                         at ABI.Microsoft.UI.Xaml.Controls.IControlOverrides.Do_Abi_OnPointerReleased_3(IntPtr thisPtr, IntPtr e)
[23/07/2024 10:43:11]   ⚠️⚠️⚠️  END OF UNHANDLED ERROR TRACE  ⚠️⚠️⚠️
[23/07/2024 10:43:11]  -
[23/07/2024 10:43:11]  -
```

### Package Managers Logs

```text
N/A
```

### Relevant information

N/A

### Screenshots and videos

N/A

**Comment by RonnyTNL** [comment]
Please also note;

System.InvalidOperationException: Manager .NET Tool does not support custom sources but yet GetSources method was called.

and
