### ISSUE TITLE
[BUG] no search results from scoop in "discover packages" tab

### ISSUE THREAD

**Issue by Hamido-san** [marticliment/UniGetUI#2550]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 10 Ent 22H2 build: 19045.4651 x64

### Describe your issue

when searching for packages in the "discover packages" tab, no entry from scoop shows up

### Steps to reproduce the issue

- open UniGetUI, go to "settings" tab
- scroll down to "scoop" section, confirm:
  - it is enabled
  - scoop sources list is populated with some "bucket" entries
  - the bottom status message reads "scoop is enabled and ready to go"
- go to "discover packages" tab, enter anything in the "search for packages" search box and hit enter
- wait for search results to be listed
- notice that none of the search results are from the "scoop" source
- notice that the "sources" list to the left has no "scoop" entry

### UniGetUI Log

```text
[7/28/2024 11:29:47 PM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.1
[7/28/2024 11:29:47 PM]
[7/28/2024 11:29:47 PM] Version Code:  3.11
[7/28/2024 11:29:47 PM] Encoding Code Page set to 437
[7/28/2024 11:29:49 PM] Lang files were updated successfully from GitHub
[7/28/2024 11:29:53 PM] Downloaded new icons and screenshots successfully!
[7/28/2024 11:29:56 PM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[7/28/2024 11:56:16 PM] Command parse_pip_search.exe was not found on the system
[7/28/2024 11:56:19 PM] Error finding packages on manager Pip with query 7zip
[7/28/2024 11:56:19 PM] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
                           at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                           at System.Diagnostics.Process.Start()
                           at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 97
                           at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 163
```

### Package Managers Logs

```text
Manager Scoop with version:
Current Scoop version:
be56faf2 chore(release): Bump to version 0.5.1 (#6057)

'main' bucket:
36f5cdba1 mdcat: Update to version 2.3.0

'extras' bucket:
f70291227 x64dbg: Update to version 2024-07-28_17-00

'java' bucket:
7ba2d33f zulufx21-jre: Update to version 21.36.17

'scoop-clojure' bucket:
0a740b5 bb-http-server: Update to version 0.1.13

——————————————————————————————————————————


Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 7/28/2024 11:29:52 PM
Process end time:   7/28/2024 11:29:54 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is RefreshIndexes
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop update"
Process start time: 7/28/2024 11:29:55 PM
Process end time:   7/28/2024 11:30:16 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 7/28/2024 11:29:56 PM
Process end time:   7/28/2024 11:30:11 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 7/28/2024 11:29:56 PM
Process end time:   7/28/2024 11:30:10 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 7/28/2024 11:30:16 PM
Process end time:   7/28/2024 11:30:17 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop status"
Process start time: 7/28/2024 11:30:17 PM
Process end time:   7/28/2024 11:30:27 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is FindPackages
Subprocess executable: "C:\Users\~\scoop\shims\scoop-search.exe"
Command-line arguments: "7zip"
Process start time: 7/28/2024 11:56:16 PM
Process end time:   7/28/2024 11:56:19 PM

Return code: FAILED (-1073741795)

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Hello,

Which CPU are you using?

**Comment by Hamido-san** [comment]
hey

> Which CPU are you using?

intel i5 2500k
why would my CPU matter?

**Comment by marticliment** [comment]
The scoop search executable is crashing with the exit code -1073741795 (or the same 0xC000001D). This error means the executable attempted to run an illegal instruction.

**Comment by marticliment** [comment]
Hello @Hamido-san,

Please run the following command on a powershell window, and then attach here the output

```pwsh
$env:SCOOP_SEARCH_VERBOSE=1 ; scoop-search 7zip
``` 

Btw, I have opened an issue on their repo: https://github.com/shilangyu/scoop-search/issues/65

**Comment by marticliment** [comment]
Please update scoop-search within UniGetUI or by running the command `scoop update scoop-search`. Version 1.5 should have this issue fixed

**Comment by Hamido-san** [comment]
verified: updating `scoop-search` to 1.5 fixed my issue
thank you very much for the follow up
