### ISSUE TITLE
What triggers this message??

### ISSUE THREAD

**Issue by MurraySobol** [marticliment/UniGetUI#2599]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows Profession x64 23H2 (OS Build 22631.3958)

### Describe your issue

I keep getting this message: see attached image.
I checked with the vendor of this software and they state that there is NO update labelled 6.42.18.1 for there product; in fact they state that 6.42.18 is the latest, current release.
So, I was curious; how is this message triggered in your app??

### Steps to reproduce the issue

See above.

### UniGetUI Log

```text
[8/5/2024 9:54:50 AM]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[8/5/2024 9:54:50 AM]
[8/5/2024 9:54:50 AM] Version Code:  3.11
[8/5/2024 9:54:50 AM] Encoding Code Page set to 437
[8/5/2024 9:54:50 AM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[8/5/2024 9:54:51 AM] Loaded language locale: en
[8/5/2024 9:54:51 AM] Randomly-generated background API auth token for the current session: drm1jn7345l0owojme92k6gg8t4sb508zd37dkiljc0l5bupu5ts6i5x1c8rawbw
[8/5/2024 9:54:52 AM] Api running on http://localhost:7058
[8/5/2024 9:54:52 AM] Lang files were updated successfully from GitHub
[8/5/2024 9:54:52 AM] UniGetUI is up to date
[8/5/2024 9:54:52 AM] Downloaded new icons and screenshots successfully!
[8/5/2024 9:54:52 AM] Command npm was not found on the system
[8/5/2024 9:54:52 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:53 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.400-preview.0.24324.5
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:53 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:53 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\murra\AppData\Local\Programs\Python\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Users\murra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.1981-preview
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:55 AM] Command scoop was not found on the system
[8/5/2024 9:54:55 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:56 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3958                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3958                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:56 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.4
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/5/2024 9:54:57 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[8/5/2024 9:54:57 AM] Dependency WinGet PowerShell Module for manager Winget is present
[8/5/2024 9:54:57 AM] Dependency .NET Tools Outdated for manager .NET Tool is present
[8/5/2024 9:54:57 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[8/5/2024 9:54:58 AM] Found 27 installed packages from Pip
[8/5/2024 9:54:58 AM] Found 1 installed packages from .NET Tool
[8/5/2024 9:54:59 AM] Found 0 available updates from .NET Tool
[8/5/2024 9:55:00 AM] Found 0 installed packages from PowerShell7
[8/5/2024 9:55:01 AM] Found 0 available updates from PowerShell7
[8/5/2024 9:55:01 AM] Found 58 installed packages from PowerShell
[8/5/2024 9:55:02 AM] Found 0 available updates from Pip
[8/5/2024 9:55:07 AM] Found 1 available updates from Winget
[8/5/2024 9:55:07 AM] Found 276 installed packages from Winget
[8/5/2024 9:55:56 AM] Error finding updates on manager PowerShell
[8/5/2024 9:55:56 AM] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 10:54:52 AM] UniGetUI is up to date
[8/5/2024 10:55:58 AM] Found 0 available updates from .NET Tool
[8/5/2024 10:56:02 AM] Found 0 available updates from PowerShell7
[8/5/2024 10:56:04 AM] Found 0 available updates from Pip
[8/5/2024 10:56:05 AM] Found 1 available updates from Winget
[8/5/2024 10:56:56 AM] Error finding updates on manager PowerShell
[8/5/2024 10:56:56 AM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 10:58:30 AM] Found 1 installed packages from .NET Tool
[8/5/2024 10:58:30 AM] Found 27 installed packages from Pip
[8/5/2024 10:58:32 AM] Found 0 installed packages from PowerShell7
[8/5/2024 10:58:33 AM] Found 58 installed packages from PowerShell
[8/5/2024 10:58:34 AM] Found 276 installed packages from Winget
[8/5/2024 11:54:53 AM] UniGetUI is up to date
[8/5/2024 11:56:57 AM] Found 0 available updates from .NET Tool
[8/5/2024 11:57:00 AM] Found 0 available updates from PowerShell7
[8/5/2024 11:57:02 AM] Found 0 available updates from Pip
[8/5/2024 11:57:04 AM] Found 1 available updates from Winget
[8/5/2024 11:57:57 AM] Error finding updates on manager PowerShell
[8/5/2024 11:57:57 AM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 12:54:53 PM] UniGetUI is up to date
[8/5/2024 12:57:58 PM] Found 0 available updates from .NET Tool
[8/5/2024 12:58:01 PM] Found 0 available updates from PowerShell7
[8/5/2024 12:58:03 PM] Found 0 available updates from Pip
[8/5/2024 12:58:04 PM] Found 1 available updates from Winget
[8/5/2024 12:58:57 PM] Error finding updates on manager PowerShell
[8/5/2024 12:58:57 PM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 1:33:25 PM] Found 1 installed packages from .NET Tool
[8/5/2024 1:33:25 PM] Found 27 installed packages from Pip
[8/5/2024 1:33:27 PM] Found 0 installed packages from PowerShell7
[8/5/2024 1:33:28 PM] Found 58 installed packages from PowerShell
[8/5/2024 1:33:29 PM] Found 276 installed packages from Winget
[8/5/2024 1:35:38 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[8/5/2024 1:35:38 PM] Icon for package Tonec.InternetDownloadManager was not found, returning default icon
[8/5/2024 1:54:53 PM] UniGetUI is up to date
[8/5/2024 1:58:58 PM] Found 0 available updates from .NET Tool
[8/5/2024 1:59:00 PM] Found 0 available updates from PowerShell7
[8/5/2024 1:59:02 PM] Found 0 available updates from Pip
[8/5/2024 1:59:05 PM] Found 1 available updates from Winget
[8/5/2024 1:59:57 PM] Error finding updates on manager PowerShell
[8/5/2024 1:59:57 PM] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 2:54:54 PM] UniGetUI is up to date
[8/5/2024 2:59:58 PM] Found 0 available updates from .NET Tool
[8/5/2024 3:00:00 PM] Found 0 available updates from PowerShell7
[8/5/2024 3:00:02 PM] Found 0 available updates from Pip
[8/5/2024 3:00:03 PM] Found 1 available updates from Winget
[8/5/2024 3:00:57 PM] Error finding updates on manager PowerShell
[8/5/2024 3:00:57 PM] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/5/2024 3:53:14 PM] Found 1 installed packages from .NET Tool
[8/5/2024 3:53:14 PM] Found 27 installed packages from Pip
[8/5/2024 3:53:16 PM] Found 0 installed packages from PowerShell7
[8/5/2024 3:53:17 PM] Found 58 installed packages from PowerShell
[8/5/2024 3:53:18 PM] Found 276 installed packages from Winget
[8/5/2024 3:54:54 PM] UniGetUI is up to date
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.1981-preview
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 8/5/2024 9:54:54 AM
Process end time:   8/5/2024 9:54:54 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 9:54:56 AM
Process end time:   8/5/2024 9:55:02 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/5/2024 9:54:56 AM
Process end time:   8/5/2024 9:55:07 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 8/5/2024 9:54:57 AM
Process end time:   8/5/2024 9:54:57 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 9:55:02 AM
Process end time:   8/5/2024 9:55:07 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 10:55:56 AM
Process end time:   8/5/2024 10:55:58 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 10:55:58 AM
Process end time:   8/5/2024 10:56:05 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/5/2024 10:58:29 AM
Process end time:   8/5/2024 10:58:34 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 11:56:56 AM
Process end time:   8/5/2024 11:57:00 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 11:57:00 AM
Process end time:   8/5/2024 11:57:04 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 12:57:57 PM
Process end time:   8/5/2024 12:57:58 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 12:57:58 PM
Process end time:   8/5/2024 12:58:04 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/5/2024 1:33:24 PM
Process end time:   8/5/2024 1:33:29 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 1:58:57 PM
Process end time:   8/5/2024 1:59:01 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 1:59:01 PM
Process end time:   8/5/2024 1:59:05 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/5/2024 2:59:57 PM
Process end time:   8/5/2024 2:59:58 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/5/2024 2:59:58 PM
Process end time:   8/5/2024 3:00:03 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/5/2024 3:53:14 PM
Process end time:   8/5/2024 3:53:18 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Screenshots and videos

![UniGetUI](https://github.com/user-attachments/assets/f78d3f05-f89e-48a8-ad3a-c4ca0286b601)

**Comment by marticliment** [comment]
This is an issue that should be reported to microsoft/winget-pkgs, since UniGetUI does not provide the packages itself. Instead, WinGet is used a the backend that loads packages.
