### ISSUE TITLE
[BUG] Not compatible with the latest features of Winget

### ISSUE THREAD

**Issue by alovelydoge** [marticliment/UniGetUI#2621]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Home China 22631.3958 x64

### Describe your issue

Any software package update reports an error, and then I view the command line output, among which Winget reminds me that I need to execute the command “winget settings --enable InstallerHashOverride” with administrator privileges in order to use the parameters

### Steps to reproduce the issue

Using the winget v1.8.1911 to update any software,then report such error.

### UniGetUI Log

```text
[2024/8/11 17:25:21]    __  __      _ ______     __  __  ______
                       / / / /___  (_) ____/__  / /_/ / / /  _/
                      / / / / __ \/ / / __/ _ \/ __/ / / // /
                     / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                     \____/_/ /_/_/\____/\___/\__/\____/___/
                         Welcome to UniGetUI Version 3.1.1
[2024/8/11 17:25:21]
[2024/8/11 17:25:21] Version Code:  3.11
[2024/8/11 17:25:21] Encoding Code Page set to 936
[2024/8/11 17:25:21] Using bundled GSudo at D:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[2024/8/11 17:25:21] Loaded language locale: zh_CN
[2024/8/11 17:25:22] Randomly-generated background API auth token for the current session: b80ib9w5ofn12eu6yazvi14kvxwjvlvkgz8h60su2lyyotkh7zm3sl68jdu4jmby
[2024/8/11 17:25:22] Api running on http://localhost:7058
[2024/8/11 17:25:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Chocolatey
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:22] The restored geometry did not have exactly 5 items (found length was 1)
[2024/8/11 17:25:22] Command npm was not found on the system
[2024/8/11 17:25:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Npm
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: .NET Tool
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Pip
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: pip
                     █ Executable path: C:\Users\alove\AppData\Local\Microsoft\WindowsApps\python.exe
                     █ Call arguments:  -m pip
                     █ Version: 
                     █   
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:23] UniGetUI is up to date
[2024/8/11 17:25:24] Command scoop was not found on the system
[2024/8/11 17:25:24] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Scoop
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:24] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Winget
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: winget.exe
                     █ Executable path: C:\Users\alove\AppData\Local\Microsoft\WindowsApps\winget.exe
                     █ Call arguments: 
                     █ Version: 
                     █   System WinGet CLI Version: v1.8.1911
                     █   Microsoft.WinGet.Client PSModule version: ""
                     █   Using Native WinGet helper (COM Api)
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:26] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell7
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: pwsh.exe
                     █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                     █ Call arguments:  -NoProfile -Command
                     █ Version: 
                     █   PowerShell 7.4.4
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:27] Lang files were updated successfully from GitHub
[2024/8/11 17:25:27] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: powershell.exe
                     █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                     █ Call arguments:  -NoProfile -Command
                     █ Version: 
                     █   Name                           Value                                                                                   
                     █   ----                           -----                                                                                   
                     █   PSVersion                      5.1.22621.3958                                                                          
                     █   PSEdition                      Desktop                                                                                 
                     █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                     █   BuildVersion                   10.0.22621.3958                                                                         
                     █   CLRVersion                     4.0.30319.42000                                                                         
                     █   WSManStackVersion              3.0                                                                                     
                     █   PSRemotingProtocolVersion      2.3                                                                                     
                     █   SerializationVersion           1.1.0.1
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/11 17:25:28] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[2024/8/11 17:25:28] Dependency WinGet PowerShell Module for manager Winget is present
[2024/8/11 17:25:28] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024/8/11 17:25:28] Found 0 available updates from Pip
[2024/8/11 17:25:28] Found 0 installed packages from Pip
[2024/8/11 17:25:32] Found 0 installed packages from PowerShell7
[2024/8/11 17:25:32] Found 0 available updates from PowerShell7
[2024/8/11 17:25:32] Found 0 installed packages from PowerShell
[2024/8/11 17:25:32] Found 0 available updates from PowerShell
[2024/8/11 17:26:18] Found 7 available updates from Winget
[2024/8/11 17:26:18] Found 216 installed packages from Winget
[2024/8/11 17:27:02] Failed to download icons and screenshots
[2024/8/11 17:27:02] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
                      ---> System.TimeoutException: The operation was canceled.
                      ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
                      ---> System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
                      ---> System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
                        --- End of inner exception stack trace ---
                        at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
                        at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
                        at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
                        at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                        at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
                        at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                        at System.Net.Http.HttpConnection.FillAsync(Boolean async)
                        at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
                        at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
                        --- End of inner exception stack trace ---
                        at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
                        at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
                        at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                        --- End of inner exception stack trace ---
                        --- End of inner exception stack trace ---
                        at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
                        at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                        at UniGetUI.Core.IconEngine.IconDatabase.LoadIconAndScreenshotsDatabaseAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconDatabase.cs:line 70
[2024/8/11 17:27:02] Icon Database file not found
[2024/8/11 17:29:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:29:44] Icon for package ByteDance.Doubao was not found, returning default icon
[2024/8/11 17:29:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:29:44] Icon for package Alibaba.DingTalk was not found, returning default icon
[2024/8/11 17:29:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:29:44] Icon for package Microsoft.EdgeWebView2Runtime was not found, returning default icon
[2024/8/11 17:29:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:29:44] Icon for package Python.Python.3.12 was not found, returning default icon
[2024/8/11 17:29:44] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:29:44] Icon for package Tencent.TencentMeeting was not found, returning default icon
[2024/8/11 17:30:01] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:01] Icon for package ByteDance.Doubao was not found, returning default icon
[2024/8/11 17:30:01] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:01] Icon for package Alibaba.DingTalk was not found, returning default icon
[2024/8/11 17:30:01] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:01] Icon for package Microsoft.EdgeWebView2Runtime was not found, returning default icon
[2024/8/11 17:30:01] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:01] Icon for package Python.Python.3.12 was not found, returning default icon
[2024/8/11 17:30:01] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:01] Icon for package Tencent.TencentMeeting was not found, returning default icon
[2024/8/11 17:30:02] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:02] Icon for package ByteDance.Doubao was not found, returning default icon
[2024/8/11 17:30:02] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:02] Icon for package Alibaba.DingTalk was not found, returning default icon
[2024/8/11 17:30:02] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:02] Icon for package Microsoft.EdgeWebView2Runtime was not found, returning default icon
[2024/8/11 17:30:02] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:02] Icon for package Python.Python.3.12 was not found, returning default icon
[2024/8/11 17:30:02] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:30:02] Icon for package Tencent.TencentMeeting was not found, returning default icon
[2024/8/11 17:31:20] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:31:20] Icon for package Alibaba.DingTalk was not found, returning default icon
[2024/8/11 17:31:20] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:31:20] Icon for package Microsoft.EdgeWebView2Runtime was not found, returning default icon
[2024/8/11 17:31:20] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:31:20] Icon for package Python.Python.3.12 was not found, returning default icon
[2024/8/11 17:31:20] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:31:20] Icon for package Tencent.TencentMeeting was not found, returning default icon
[2024/8/11 17:31:43] Found 0 installed packages from Pip
[2024/8/11 17:31:45] Found 0 installed packages from PowerShell7
[2024/8/11 17:31:46] Found 0 installed packages from PowerShell
[2024/8/11 17:31:47] Found 216 installed packages from Winget
[2024/8/11 17:31:50] Resetting administrator rights cache for process id 22684
[2024/8/11 17:32:25] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/11 17:32:25] Icon for package Alibaba.DingTalk was not found, returning default icon
[2024/8/11 17:32:25] Caching admin rights for process id 22684
[2024/8/11 17:32:35] Resetting administrator rights cache for process id 22684
[2024/8/11 17:44:10] Found 0 installed packages from Pip
[2024/8/11 17:44:12] Found 0 installed packages from PowerShell7
[2024/8/11 17:44:13] Found 0 installed packages from PowerShell
[2024/8/11 17:44:15] Found 216 installed packages from Winget
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/8/11 17:25:24
Process end time:   2024/8/11 17:25:24

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\alove\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024/8/11 17:25:27
Process end time:   2024/8/11 17:25:35

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/11 17:25:28
Process end time:   2024/8/11 17:26:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/8/11 17:25:28
Process end time:   2024/8/11 17:25:28

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024/8/11 17:25:35
Process end time:   2024/8/11 17:26:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/11 17:31:43
Process end time:   2024/8/11 17:31:47

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/11 17:44:10
Process end time:   2024/8/11 17:44:15

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Relevant information

**Package Manager Version**
Winget v1.8.1911 

**This issue is translated from Chinese by AI. If there are any less smooth places, please understand.**

### Screenshots and videos

![image](https://github.com/user-attachments/assets/6a4230c8-96f2-4672-800f-ac8b08c60344)

**Comment by marticliment** [comment]
Will investigate
