### ISSUE TITLE
[BUG]  UniGetUI 3.x.x not listing other sources than PowerShell 5.x

### ISSUE THREAD

**Issue by Zafrkant** [marticliment/UniGetUI#2626]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 10 Pro 22H2 19045.4651

### Describe your issue

Hello,

I want to thank developers for great contribution to the community.

I have issue with UniGetUI 3.x.x by not listing other sources than PowerShell 5.x.

Thanks in advance.

### UniGetUI Log

```text
[12-Aug-24 09:33:32] Version Code:  3.11
[12-Aug-24 09:33:32] Encoding Code Page set to 437
[12-Aug-24 09:33:32] Using bundled GSudo at C:\Users\zfk\AppData\Local\Programs\UniGetUI\Assets\Utilities\gsudo.exe
[12-Aug-24 09:33:32] Loaded language locale: en
[12-Aug-24 09:33:33] Randomly-generated background API auth token for the current session: 375dtrerotp6uig53wzv7opnvei883v0anes97mrqfibj1vjjog8bhr581w5959p
[12-Aug-24 09:33:33] Api running on http://localhost:7058
[12-Aug-24 09:33:33] Lang files were updated successfully from GitHub
[12-Aug-24 09:33:33] Downloaded new icons and screenshots successfully!
[12-Aug-24 09:33:33] UniGetUI is up to date
[12-Aug-24 09:33:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: .NET Tool
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Pip
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: pip
                     █ Executable path: C:\Users\zfk\AppData\Local\Microsoft\WindowsApps\python.exe
                     █ Call arguments:  -m pip
                     █ Version: 
                     █   
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:34] Command scoop was not found on the system
[12-Aug-24 09:33:34] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Scoop
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:34] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Winget
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: winget.exe
                     █ Executable path: C:\Users\zfk\AppData\Local\Microsoft\WindowsApps\winget.exe
                     █ Call arguments: 
                     █ Version: 
                     █   System WinGet CLI Version: v1.8.1911
                     █   Microsoft.WinGet.Client PSModule version: ""
                     █   Using Native WinGet helper (COM Api)
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:34] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Npm
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: npm
                     █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                     █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                     █ Version: 
                     █   10.8.1
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Chocolatey
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: choco.exe
                     █ Executable path: C:\Users\zfk\AppData\Local\UniGetUI\Chocolatey\choco.exe
                     █ Call arguments: 
                     █ Version: 
                     █   2.2.2
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: powershell.exe
                     █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                     █ Call arguments:  -NoProfile -Command
                     █ Version: 
                     █   Name                           Value                                                                                   
                     █   ----                           -----                                                                                   
                     █   PSVersion                      5.1.19041.4648                                                                          
                     █   PSEdition                      Desktop                                                                                 
                     █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                     █   BuildVersion                   10.0.19041.4648                                                                         
                     █   CLRVersion                     4.0.30319.42000                                                                         
                     █   WSManStackVersion              3.0                                                                                     
                     █   PSRemotingProtocolVersion      2.3                                                                                     
                     █   SerializationVersion           1.1.0.1
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell7
                     █ Enabled: True
                     █ Found: True
                     █ Fancy exe name: pwsh.exe
                     █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                     █ Call arguments:  -NoProfile -Command
                     █ Version: 
                     █   PowerShell 7.4.4
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12-Aug-24 09:33:37] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[12-Aug-24 09:33:37] Dependency WinGet PowerShell Module for manager Winget is present
[12-Aug-24 09:33:37] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[12-Aug-24 09:33:37] Error finding installed packages on manager Winget
[12-Aug-24 09:33:37] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass5_0.<GetInstalledPackages_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetInstalledPackages_UnSafe>b__28_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[12-Aug-24 09:33:37] Found 0 available updates from Pip
[12-Aug-24 09:33:37] Found 0 installed packages from Pip
[12-Aug-24 09:33:37] Error finding updates on manager Winget
[12-Aug-24 09:33:37] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass4_0.<GetAvailableUpdates_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetAvailableUpdates_UnSafe>b__27_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[12-Aug-24 09:33:39] Found 0 installed packages from Chocolatey
[12-Aug-24 09:33:39] Found 0 available updates from Chocolatey
[12-Aug-24 09:33:40] Found 0 installed packages from PowerShell7
[12-Aug-24 09:33:40] Found 0 installed packages from Npm
[12-Aug-24 09:33:40] Found 0 available updates from Npm
[12-Aug-24 09:33:41] Found 0 available updates from PowerShell7
[12-Aug-24 09:33:42] Found 95 installed packages from PowerShell
[12-Aug-24 09:34:08] Found 0 installed packages from Pip
[12-Aug-24 09:34:08] Error finding installed packages on manager Winget
[12-Aug-24 09:34:08] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass5_0.<GetInstalledPackages_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetInstalledPackages_UnSafe>b__28_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                        at System.Threading.Tasks.Task`1.InnerInvoke()
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                     --- End of stack trace from previous location ---
                        at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                        at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                     --- End of stack trace from previous location ---
                        at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                        at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[12-Aug-24 09:34:09] Found 0 installed packages from Chocolatey
[12-Aug-24 09:34:11] Found 0 installed packages from PowerShell7
[12-Aug-24 09:34:11] Found 0 installed packages from Npm
[12-Aug-24 09:34:13] Found 95 installed packages from PowerShell
```

### Package Managers Logs

```text
Up
```

### Screenshots and videos

![2024-08-12 09_05_17-Window](https://github.com/user-attachments/assets/de01fb5f-9e83-491c-8c4b-0a492ba201f2)

**Comment by marticliment** [comment]
Please go to UniGetUI Settings -> WinGet -> Use Bundled WinGet and disable the COM API

**Comment by Zafrkant** [comment]
> Please go to UniGetUI Settings -> WinGet -> Use Bundled WinGet and disable the COM API

It is working with mentioned settings.

Thank you for help.
