### ISSUE TITLE
[BUG] When importing a package bundle with pinned version it's ignored and the rule is not applied on the importing machine

### ISSUE THREAD

**Issue by only-su** [marticliment/UniGetUI#2630]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 22631.3958

### Describe your issue

When importing a package bundle with pinned version it's ignored and the rule is not applied on the importing machine.

Opening each package information inside the bundle view the "Version to install" and "ignore future updates" of the package will be default, not the info listed on the bundle.json file.

### Steps to reproduce the issue

Import this bundle
```json
{
  "export_version": 2,
  "packages": [
    {
      "Id": "ant",
      "Name": "Ant",
      "Version": "1.9.7",
      "Source": "community",
      "ManagerName": "Chocolatey",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": ""
      },
      "Updates": {
        "UpdatesIgnored": true,
        "IgnoredVersion": "*"
      }
    },
    {
      "Id": "ojdkbuild8",
      "Name": "Ojdkbuild8",
      "Version": "8.0.312",
      "Source": "community",
      "ManagerName": "Chocolatey",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": ""
      },
      "Updates": {
        "UpdatesIgnored": true,
        "IgnoredVersion": "*"
      }
    },
    {
      "Id": "Git.Git",
      "Name": "Git",
      "Version": "2.46.0",
      "Source": "winget",
      "ManagerName": "Winget",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": ""
      },
      "Updates": {
        "UpdatesIgnored": false,
        "IgnoredVersion": ""
      }
    }
  ],
  "incompatible_packages_info": "Incompatible packages cannot be installed from WingetUI, but they have been listed here for logging purposes.",
  "incompatible_packages": []
}
```

the version of `"UpdatesIgnored": true,` packages will be latest and the 'ignore update' behavior is not set equal to the bundle.json file

### UniGetUI Log

```text
[12/08/2024 15:34:19]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[12/08/2024 15:34:19]
[12/08/2024 15:34:19] Version Code:  3,11
[12/08/2024 15:34:19] Encoding Code Page set to 850
[12/08/2024 15:34:20] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[12/08/2024 15:34:20] Loaded language locale: pt_BR
[12/08/2024 15:34:20] Randomly-generated background API auth token for the current session: 3vii94f1ijn97xjbydt7bcn1ovthzxwpvywd7o7tmpsek2furr3r3qry56kbvdc8
[12/08/2024 15:34:20] Api running on http://localhost:7058
[12/08/2024 15:34:20] Lang files were updated successfully from GitHub
[12/08/2024 15:34:21] Downloaded new icons and screenshots successfully!
[12/08/2024 15:34:21] Command pwsh.exe was not found on the system
[12/08/2024 15:34:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:21] UniGetUI is up to date
[12/08/2024 15:34:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:21] Command scoop was not found on the system
[12/08/2024 15:34:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.8.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:22] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\User\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.3.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3958                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3958                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/08/2024 15:34:24] Resetting administrator rights cache for process id 37292
[12/08/2024 15:34:24] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[12/08/2024 15:34:24] Dependency WinGet PowerShell Module for manager Winget is present
[12/08/2024 15:34:24] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[12/08/2024 15:34:26] Found 13 installed packages from Chocolatey
[12/08/2024 15:34:26] Found 0 installed packages from PowerShell
[12/08/2024 15:34:27] Found 0 available updates from Chocolatey
[12/08/2024 15:34:27] Found 0 available updates from PowerShell
[12/08/2024 15:34:27] Found 5 available updates from Winget
[12/08/2024 15:34:27] Found 135 installed packages from Winget
[12/08/2024 15:34:28] Found 0 available updates from Npm
[12/08/2024 15:34:28] Found 0 installed packages from Npm
[12/08/2024 15:34:45] Registering package ant from manager Chocolatey: community
[12/08/2024 15:34:45] Registering package Git.Git from manager Winget: winget
[12/08/2024 15:34:45] Registering package ojdkbuild8 from manager Chocolatey: community
[12/08/2024 15:34:45] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[12/08/2024 15:34:45] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Git.Git
[12/08/2024 15:34:45] Icon for package Git.Git stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\Git.Git.png
[12/08/2024 15:34:45] Error when loading the package icon for the package ojdkbuild8 on manager Chocolatey
[12/08/2024 15:34:45] System.UriFormatException: Invalid URI: The URI is empty.
                         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
                         at System.Uri..ctor(String uriString)
                         at UniGetUI.PackageEngine.Managers.PowerShellManager.BaseNuGetDetailsProvider.GetPackageIcon_Unsafe(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Generic.NuGet\BaseNuGetDetailsProvider.cs:line 140
                         at UniGetUI.PackageEngine.Classes.Manager.BaseProviders.BasePackageDetailsProvider`1.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\BaseProviders\BasePackageDetailsProvider.cs:line 40
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 453
[12/08/2024 15:34:45] Caching admin rights for process id 37292
[12/08/2024 15:34:45] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=ant
[12/08/2024 15:34:45] Icon for package ant stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Chocolatey\ant.svg
[12/08/2024 15:34:56] Install
[12/08/2024 15:34:56] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=ant
[12/08/2024 15:34:56] Icon for package ant stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Chocolatey\ant.svg
[12/08/2024 15:34:56] Found 0 screenshots for package Id=ant
[12/08/2024 15:34:56] Loaded details for package ant on manager Chocolatey
[12/08/2024 15:35:19] Caching admin rights for process id 37292
[12/08/2024 15:35:20] Caching admin rights for process id 37292
[12/08/2024 15:35:24] Resetting administrator rights cache for process id 37292
[12/08/2024 15:35:26] Resetting administrator rights cache for process id 37292
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 12/08/2024 15:34:22
Process end time:   12/08/2024 15:34:22

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 12/08/2024 15:34:23
Process end time:   12/08/2024 15:34:24

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 12/08/2024 15:34:23
Process end time:   12/08/2024 15:34:27

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 12/08/2024 15:34:24
Process end time:   12/08/2024 15:34:24

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 12/08/2024 15:34:24
Process end time:   12/08/2024 15:34:27

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Relevant information

With this feature UniGet could become a powerful team environment synchronization tool

**Comment by only-su** [comment]
no, it's not :(

but also it would be nice to see it on the information of the package on the bundle view so it's possible to audit, understand and edit if needed.

**Comment by only-su** [comment]
tested and custom arguments are also not reflected on the UI and not applied at installation

**Comment by only-su** [comment]
Testing another bundle I saw a conflict on the config that was causing problems:

```json
    {
      "Id": "pnpm.pnpm",
      "Name": "pnpm",
      "Version": "9.7.0",
      "Source": "winget",
      "ManagerName": "Winget",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": "9.1.4"
      },
      "Updates": {
        "UpdatesIgnored": true,
        "IgnoredVersion": "*"
      }
    },
```
there is two versions one on the base object and another inside the `InstallationOptions`. The one that was on my PC when authoring this bundle was the one stated in `InstallationOptions`. But when installing this bundle I would get latest, not even 9.7 (the one on base object). Manually changing base version to 9.1.4 so it looks like this:
```json
    {
      "Id": "pnpm.pnpm",
      "Name": "pnpm",
      "Version": "9.1.4",
      "Source": "winget",
      "ManagerName": "Winget",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": "9.1.4"
      },
      "Updates": {
        "UpdatesIgnored": true,
        "IgnoredVersion": "*"
      }
    },
```

seems to install this version on machine, but still does not apply the update rule

**Comment by marticliment** [comment]
I will investigate the issue then. It looks like a bug

**Comment by marticliment** [comment]
Can you please share your UniGetUI logs after clicking on "install" on a faulting package from a package bundle?

**Comment by only-su** [comment]
I created a bundle from a installed package, correctly pinned: 
```json
{
  "export_version": 2,
  "packages": [
    {
      "Id": "pnpm.pnpm",
      "Name": "pnpm",
      "Version": "9.1.4",
      "Source": "winget",
      "ManagerName": "Winget",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": "9.1.4"
      },
      "Updates": {
        "UpdatesIgnored": true,
        "IgnoredVersion": "*"
      }
    }
  ],
  "incompatible_packages_info": "Incompatible packages cannot be installed from WingetUI, but they have been listed here for logging purposes.",
  "incompatible_packages": []
}
```
```logs
[14/08/2024 11:18:45] Adding native package with id=pnpm.pnpm to bundle as a VALID package...
[14/08/2024 11:18:45] Creating new instance of InstallationOptions for package UniGetUI.PackageEngine.PackageClasses.Package, as no instance was found in cache
[14/08/2024 11:18:45] InstallationOptions loaded successfully from disk for package pnpm.pnpm
[14/08/2024 11:19:00] Finished loading serializable objects. Serializing with format JSON
[14/08/2024 11:19:00] Serialization finished successfully
```

Uninstalled pnpm, deleted entry on manage ignore updates for the package, opened the package and then installed it again via bundle:
```logs
[14/08/2024 12:04:03] Adding native package with id=pnpm.pnpm to bundle as a VALID package... #this alwas happen when opening the bundle
[14/08/2024 12:04:12] Registering package pnpm.pnpm from manager Winget: winget
[14/08/2024 12:04:12] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[14/08/2024 12:04:12] Manager Winget did not find a native icon for pnpm.pnpm
[14/08/2024 12:04:12] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=pnpm.pnpm
[14/08/2024 12:04:12] Icon for package pnpm.pnpm on manager Winget with Uri=https://community.chocolatey.org/content/packageimages/pnpm.7.28.0.png has been determined to be VALID through verification method PackageVersion
[14/08/2024 12:04:12] Icon for package pnpm.pnpm stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\pnpm.pnpm.png
[14/08/2024 12:04:12] Icon for package pnpm.pnpm was loaded from file:///C:/Users/User/AppData/Local/UniGetUI/CachedMedia/Winget/pnpm.pnpm.png
[14/08/2024 12:04:13] Caching admin rights for process id 11336
[14/08/2024 12:04:33] Resetting administrator rights cache for process id 11336
```

closed uniget and openend again:
- There is no entry on manage ignore update for the package
- opening the package detail on the installed package view shows it as  fixed version (9.1.4) and ignore future update true
- software update view still informs as a package that needs to be updated

**Comment by marticliment** [comment]
Thanks, there does not seem to be any exception or crash, so it is likely to be a bug

**Comment by marticliment** [comment]
Please test if this issue gets fixed on the next beta release, coming in the following days

**Comment by marticliment** [comment]
Please try this version: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta0

**Comment by only-su** [comment]
It still shows the wrong version on the bundle visualization
![image](https://github.com/user-attachments/assets/ba2289fb-f77d-4e06-bce2-7118a1baf586)

It now shows correctly on the package info
![image](https://github.com/user-attachments/assets/bf772789-00f7-4c74-a8e1-503b1b57e6b3)

The produced bundle seems right:
```json
{
  "export_version": 2,
  "packages": [
    {
      "Id": "flyway.commandline.withjre",
      "Name": "Flyway.commandline.withjre",
      "Version": "10.9.1",
      "Source": "community",
      "ManagerName": "Chocolatey",
      "InstallationOptions": {
        "SkipHashCheck": false,
        "InteractiveInstallation": false,
        "RunAsAdministrator": false,
        "Architecture": "",
        "InstallationScope": "",
        "CustomParameters": [
          ""
        ],
        "PreRelease": false,
        "CustomInstallLocation": "",
        "Version": "10.0.1"
      },
      "Updates": {
        "UpdatesIgnored": false,
        "IgnoredVersion": ""
      }
    }
  ],
  "incompatible_packages_info": "Incompatible packages cannot be installed from WingetUI, but they have been listed here for logging purposes.",
  "incompatible_packages": []
}
```

The right version was installed:
```
Chocolatey v2.3.0
Installing the following packages:
flyway.commandline.withjre
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
flyway.commandline.withjre v10.0.1 [Approved]
```

The manage ignore updates was created succsessfully!
![image](https://github.com/user-attachments/assets/41f3585f-89f0-44a2-80a1-3720a41e027e)

The right package version was installed with pinned version!
![image](https://github.com/user-attachments/assets/394a5db5-35d9-471f-9206-2da7d951919f)

Thank you!! The problem is solved, and I think we can close the issue :)
Just the version detail on bundle list visualization would be a nice feature would ou like me to open another issue?
Thank you for your time and consideration :))) Cheers to FOSS!

**Comment by marticliment** [comment]
Yes, please open a new issue for it.
