### ISSUE TITLE
[CRASH] UniGetUI crashed

### ISSUE THREAD

**Issue by philring** [marticliment/UniGetUI#2632]
UniGetUI crashed

Error details: 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.19045.0
           OS Architecture: True
          APP Architecture: True
                  Language: en
               APP Version: 3.1.0
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: XAML parsing failed.

Crash Traceback: 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at UniGetUI.Interface.PackageBundlePage.InitializeComponent() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\obj\x64\Release\net8.0-windows10.0.19041.0\win-x64\Interface\SoftwarePages\PackageBundle.g.i.cs:line 111
   at UniGetUI.Interface.PackageBundlePage..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\SoftwarePages\PackageBundle.xaml.cs:line 54
   at UniGetUI.Interface.MainView..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\MainView.xaml.cs:line 51
   at UniGetUI.Interface.MainWindow.SwitchToInterface() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\MainWindow.xaml.cs:line 358
   at UniGetUI.MainApp.LoadComponentsAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 292
```

**Comment by marticliment** [comment]
Please install UniGetUI 3.1.1

**Comment by DrMMu** [comment]
Have the same issue in 3.1.1:

```
                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.1.1
                Executable: C:\Program Files\UniGetUI\UniGetUI.exe

Crash Message: XAML parsing failed.

Crash Traceback:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at UniGetUI.Interface.MainWindow.InitializeComponent() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\obj\x64\Release\net8.0-windows10.0.19041.0\win-x64\Interface\MainWindow.g.i.cs:line 69
   at UniGetUI.Interface.MainWindow..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\MainWindow.xaml.cs:line 85
   at UniGetUI.MainApp.InitializeMainWindow() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 167
   at UniGetUI.MainApp..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 71
```

**Comment by marticliment** [comment]
Is this the first time you installed UniGetUI?

**Comment by DrMMu** [comment]
Yes

**Comment by marticliment** [comment]
Which AV are you running?

**Comment by DrMMu** [comment]
Windows Defender

**Comment by marticliment** [comment]
I will investigate
