### ISSUE TITLE
[BUG] UniGetUI leaving orphaned `gsudo` instances running

### ISSUE THREAD

**Issue by ChristopherHaws** [marticliment/UniGetUI#2641]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro for Workstation v10.0.22631

### Describe your issue

After running updates on my system using UniGetUI, many orphaned instances of `gsudo` get left running and never get cleaned up.

### Steps to reproduce the issue

1. Run updates as administrator using UniGetUI
2. Wait for the updates to complete
3. Open task manager to see many orphaned `gsudo` instances

### UniGetUI Log

```text
[2024-08-16 10:03:40 AM]    __  __      _ ______     __  __  ______
                           / / / /___  (_) ____/__  / /_/ / / /  _/
                          / / / / __ \/ / / __/ _ \/ __/ / / // /
                         / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                         \____/_/ /_/_/\____/\___/\__/\____/___/
                             Welcome to UniGetUI Version 3.1.1
[2024-08-16 10:03:40 AM]
[2024-08-16 10:03:40 AM] Version Code:  3.11
[2024-08-16 10:03:40 AM] Encoding Code Page set to 437
[2024-08-16 10:03:40 AM] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[2024-08-16 10:03:41 AM] Loaded language locale: en
[2024-08-16 10:03:41 AM] Randomly-generated background API auth token for the current session: euaqfhxdkcsgzbygkgwyxwtu5p9bnie3i9fxpp4sk4624sv2dfb8h62mb9f8ohan
[2024-08-16 10:03:42 AM] Api running on http://localhost:7058
[2024-08-16 10:03:42 AM] Old chocolatey path is a symbolic link, not migrating Chocolatey...
[2024-08-16 10:03:42 AM] Lang files were updated successfully from GitHub
[2024-08-16 10:03:42 AM] UniGetUI is up to date
[2024-08-16 10:03:42 AM] Downloaded new icons and screenshots successfully!
[2024-08-16 10:03:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: .NET Tool
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: dotnet tool
                         █ Executable path: C:\Program Files\dotnet\dotnet.exe
                         █ Call arguments: tool
                         █ Version: 
                         █   9.0.100-preview.7.24407.12
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Pip
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Chocolatey
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:44 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Npm
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:44 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Winget
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: winget.exe
                         █ Executable path: C:\Users\chaws\AppData\Local\Microsoft\WindowsApps\winget.exe
                         █ Call arguments: 
                         █ Version: 
                         █   System WinGet CLI Version: v1.9.2151-preview
                         █   Microsoft.WinGet.Client PSModule version: ""
                         █   Using Native WinGet helper (COM Api)
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:45 AM] Command scoop was not found on the system
[2024-08-16 10:03:45 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Scoop
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:47 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: powershell.exe
                         █ Executable path: C:\windows\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -Command
                         █ Version: 
                         █   Name                           Value                                                                                   
                         █   ----                           -----                                                                                   
                         █   PSVersion                      5.1.22621.3958                                                                          
                         █   PSEdition                      Desktop                                                                                 
                         █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                         █   BuildVersion                   10.0.22621.3958                                                                         
                         █   CLRVersion                     4.0.30319.42000                                                                         
                         █   WSManStackVersion              3.0                                                                                     
                         █   PSRemotingProtocolVersion      2.3                                                                                     
                         █   SerializationVersion           1.1.0.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:49 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell7
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: pwsh.exe
                         █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                         █ Call arguments:  -NoProfile -Command
                         █ Version: 
                         █   PowerShell 7.4.4
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-08-16 10:03:50 AM] Resetting administrator rights cache for process id 44984
[2024-08-16 10:03:50 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[2024-08-16 10:03:50 AM] Dependency WinGet PowerShell Module for manager Winget is present
[2024-08-16 10:03:51 AM] Dependency .NET Tools Outdated for manager .NET Tool is present
[2024-08-16 10:03:51 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024-08-16 10:03:51 AM] Found 9 installed packages from .NET Tool
[2024-08-16 10:03:52 AM] Found 2 available updates from .NET Tool
[2024-08-16 10:03:52 AM] Found 7 installed packages from PowerShell7
[2024-08-16 10:03:54 AM] Found 58 installed packages from PowerShell
[2024-08-16 10:04:03 AM] Found 39 available updates from Winget
[2024-08-16 10:04:03 AM] Found 461 installed packages from Winget
[2024-08-16 10:04:50 AM] Error finding updates on manager PowerShell7
[2024-08-16 10:04:50 AM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[2024-08-16 10:04:50 AM] Error finding updates on manager PowerShell
[2024-08-16 10:04:50 AM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[2024-08-16 10:04:57 AM] Restored geometry was outside of desktop bounds
[2024-08-16 10:04:57 AM] Found 9 installed packages from .NET Tool
[2024-08-16 10:04:58 AM] Found 7 installed packages from PowerShell7
[2024-08-16 10:04:59 AM] Found 58 installed packages from PowerShell
[2024-08-16 10:05:00 AM] Found 461 installed packages from Winget
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Adobe.Acrobat.Reader.64-bit was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package ToEverything.AFFiNE was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=AppFlowy.AppFlowy
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package twpayne.chezmoi was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Anysphere.Cursor was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Discord.Discord
[2024-08-16 10:05:38 AM] Icon for package Discord.Discord stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Discord.Discord.png
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=ogdesign.Eagle
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=GoLang.Go
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Graphviz.Graphviz
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Helm.Helm was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Logitech.GHUB
[2024-08-16 10:05:38 AM] Icon for package Logitech.GHUB stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Logitech.GHUB.png
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Microsoft.DotNet.SDK.8 was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.Edge
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.EdgeWebView2Runtime
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Mozilla.Thunderbird
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Notion.Notion
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Ollama.Ollama was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package BitSum.ParkControl was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Postman.Postman
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Icon for package Proton.ProtonMail was not found, returning default icon
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Rainmeter.Rainmeter
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Cockos.REAPER
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Telegram.TelegramDesktop
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=GlavSoft.TightVNC
[2024-08-16 10:05:38 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=VideoLAN.VLC
[2024-08-16 10:05:38 AM] Caching admin rights for process id 44984
[2024-08-16 10:05:38 AM] An error occurred while retrieving the icon for package ogdesign.Eagle
[2024-08-16 10:05:38 AM] System.Net.Http.HttpRequestException: Response status code does not indicate success: 419 (Unknown).
                            at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                            at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 166
                            at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 160
[2024-08-16 10:05:38 AM] Icon for package GoLang.Go stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\GoLang.Go.png
[2024-08-16 10:05:38 AM] Icon for package Microsoft.EdgeWebView2Runtime stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.EdgeWebView2Runtime.png
[2024-08-16 10:05:38 AM] Icon for package Postman.Postman stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Postman.Postman.png
[2024-08-16 10:05:38 AM] Icon for package Notion.Notion stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Notion.Notion.png
[2024-08-16 10:05:38 AM] Icon for package Microsoft.Edge stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.Edge.png
[2024-08-16 10:05:38 AM] Icon for package Graphviz.Graphviz stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Graphviz.Graphviz.png
[2024-08-16 10:05:38 AM] Icon for package VideoLAN.VLC stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\VideoLAN.VLC.png
[2024-08-16 10:05:38 AM] Icon for package Telegram.TelegramDesktop stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Telegram.TelegramDesktop.png
[2024-08-16 10:05:38 AM] Icon for package Mozilla.Thunderbird stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Mozilla.Thunderbird.png
[2024-08-16 10:05:38 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=jetbrains.resharper.globaltools
[2024-08-16 10:05:38 AM] Icon for package Cockos.REAPER stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Cockos.REAPER.png
[2024-08-16 10:05:38 AM] Icon for package GlavSoft.TightVNC stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\GlavSoft.TightVNC.png
[2024-08-16 10:05:38 AM] Icon for package Rainmeter.Rainmeter stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\Rainmeter.Rainmeter.png
[2024-08-16 10:05:38 AM] An error occurred while retrieving the icon for package jetbrains.resharper.globaltools
[2024-08-16 10:05:38 AM] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\.NET Tool\jetbrains.resharper.globaltools.5\icon'.
                            at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                            at System.IO.File.Create(String path)
                            at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 169
                            at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 160
[2024-08-16 10:05:38 AM] Icon for package AppFlowy.AppFlowy stored on C:\Users\chaws\AppData\Local\UniGetUI\CachedMedia\Winget\AppFlowy.AppFlowy.png
[2024-08-16 10:07:12 AM] Caching admin rights for process id 44984
[2024-08-16 10:07:35 AM] Caching admin rights for process id 44984
[2024-08-16 10:07:51 AM] Caching admin rights for process id 44984
[2024-08-16 10:07:57 AM] Caching admin rights for process id 44984
[2024-08-16 10:08:37 AM] Caching admin rights for process id 44984
[2024-08-16 10:08:42 AM] Caching admin rights for process id 44984
[2024-08-16 10:08:52 AM] Caching admin rights for process id 44984
[2024-08-16 10:11:23 AM] Caching admin rights for process id 44984
[2024-08-16 10:11:30 AM] Caching admin rights for process id 44984
[2024-08-16 10:11:49 AM] Caching admin rights for process id 44984
[2024-08-16 10:11:55 AM] Caching admin rights for process id 44984
[2024-08-16 10:12:33 AM] Caching admin rights for process id 44984
[2024-08-16 10:12:35 AM] Caching admin rights for process id 44984
[2024-08-16 10:13:32 AM] Caching admin rights for process id 44984
[2024-08-16 10:13:45 AM] Caching admin rights for process id 44984
[2024-08-16 10:17:48 AM] Caching admin rights for process id 44984
[2024-08-16 10:18:54 AM] Caching admin rights for process id 44984
[2024-08-16 10:18:58 AM] Caching admin rights for process id 44984
[2024-08-16 10:19:07 AM] Caching admin rights for process id 44984
[2024-08-16 10:19:22 AM] Caching admin rights for process id 44984
[2024-08-16 10:19:27 AM] Caching admin rights for process id 44984
[2024-08-16 10:19:36 AM] Caching admin rights for process id 44984
[2024-08-16 10:19:38 AM] Caching admin rights for process id 44984
[2024-08-16 10:20:20 AM] Caching admin rights for process id 44984
[2024-08-16 10:23:46 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:23:46 AM] Icon for package BitSum.ParkControl was not found, returning default icon
[2024-08-16 10:23:46 AM] Caching admin rights for process id 44984
[2024-08-16 10:25:33 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024-08-16 10:25:33 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=ogdesign.Eagle
[2024-08-16 10:25:33 AM] Caching admin rights for process id 44984
[2024-08-16 10:25:33 AM] An error occurred while retrieving the icon for package ogdesign.Eagle
[2024-08-16 10:25:33 AM] System.Net.Http.HttpRequestException: Response status code does not indicate success: 419 (Unknown).
                            at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                            at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 166
                            at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 160
[2024-08-16 10:25:53 AM] Found 1 available updates from .NET Tool
[2024-08-16 10:25:56 AM] Found 20 available updates from Winget
[2024-08-16 10:26:52 AM] Error finding updates on manager PowerShell
[2024-08-16 10:26:52 AM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[2024-08-16 10:26:52 AM] Error finding updates on manager PowerShell7
[2024-08-16 10:26:52 AM] System.TimeoutException: The operation has timed out.
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[2024-08-16 11:03:43 AM] UniGetUI is up to date
[2024-08-16 12:03:43 PM] UniGetUI is up to date
[2024-08-16 01:03:43 PM] UniGetUI is up to date
[2024-08-16 02:03:44 PM] UniGetUI is up to date
[2024-08-16 03:03:44 PM] UniGetUI is up to date
[2024-08-16 04:03:44 PM] UniGetUI is up to date
[2024-08-16 05:03:45 PM] UniGetUI is up to date
[2024-08-16 06:03:45 PM] UniGetUI is up to date
[2024-08-16 07:03:46 PM] UniGetUI is up to date
[2024-08-16 08:03:46 PM] UniGetUI is up to date
[2024-08-16 09:03:46 PM] UniGetUI is up to date
[2024-08-16 10:03:47 PM] UniGetUI is up to date
[2024-08-16 11:03:47 PM] UniGetUI is up to date
[2024-08-17 12:03:47 AM] UniGetUI is up to date
[2024-08-17 01:03:48 AM] UniGetUI is up to date
[2024-08-17 02:03:48 AM] UniGetUI is up to date
[2024-08-17 03:03:48 AM] UniGetUI is up to date
[2024-08-17 04:03:49 AM] UniGetUI is up to date
[2024-08-17 05:03:49 AM] UniGetUI is up to date
[2024-08-17 06:03:49 AM] UniGetUI is up to date
[2024-08-17 07:03:50 AM] UniGetUI is up to date
[2024-08-17 08:03:50 AM] UniGetUI is up to date
[2024-08-17 09:03:50 AM] UniGetUI is up to date
[2024-08-17 10:03:51 AM] UniGetUI is up to date
[2024-08-17 10:09:39 AM] Found 9 installed packages from .NET Tool
[2024-08-17 10:09:43 AM] Found 58 installed packages from PowerShell
[2024-08-17 10:09:44 AM] Found 7 installed packages from PowerShell7
[2024-08-17 10:09:51 AM] Found 459 installed packages from Winget
```
```


### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.2151-preview
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-08-16 10:03:44 AM
Process end time:   2024-08-16 10:03:44 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\chaws\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-08-16 10:03:50 AM
Process end time:   2024-08-16 10:03:52 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-08-16 10:03:50 AM
Process end time:   2024-08-16 10:04:03 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-08-16 10:03:50 AM
Process end time:   2024-08-16 10:03:50 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024-08-16 10:03:52 AM
Process end time:   2024-08-16 10:04:03 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-08-16 10:04:57 AM
Process end time:   2024-08-16 10:05:00 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\chaws\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-08-16 10:25:52 AM
Process end time:   2024-08-16 10:25:52 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024-08-16 10:25:52 AM
Process end time:   2024-08-16 10:25:56 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-08-17 10:09:39 AM
Process end time:   2024-08-17 10:09:51 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/a72b47fe-5dc3-47d0-8970-a10af25b0305)
![image](https://github.com/user-attachments/assets/6cfe95a3-3516-401a-870f-51bc98a773b3)

**Comment by marticliment** [comment]
I am sorry, I am not familiar with the concept of "orphaned process". What do you mean? The process exits, right?

**Comment by ChristopherHaws** [comment]
An orphaned process occurs when a process spawns a child process without properly disposing the native resources. 

Just based on a quick look through the code, I think this is where the issue is happening; I think the created process is never being disposed: https://github.com/marticliment/UniGetUI/blob/45ce9ee26f6c2745e4dfc5d636eaa9749efc335a/src/UniGetUI/PackageEngine/Operations/OperationControl.xaml.cs#L421

[`Process`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-8.0) is `IDisposable` so it will need to be disposed. You can see in my screenshot that the gsudo processes had been started over a day ago.

**Comment by marticliment** [comment]
Oh, I will investigate this issue. Thanks!
