### ISSUE TITLE
[BUG] Scoop updates do not appear in Software Updates list

### ISSUE THREAD

**Issue by RaptDept** [marticliment/UniGetUI#2642]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro / Version 23H2 / OS Build 22631.4037 / Windows Feature Experience Pack 1000.22700.1027.0 / x64

### Describe your issue

Software updates do not list outdated Scoop apps. This happens even disabling then re-enabling Scoop in UniGetUI settings as well as refreshing the updates list.

### UniGetUI Log

```text
[8/18/2024 10:29:38 AM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.1
[8/18/2024 10:29:38 AM]
[8/18/2024 10:29:38 AM] Version Code:  3.11
[8/18/2024 10:29:38 AM] Encoding Code Page set to 437
[8/18/2024 10:29:39 AM] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[8/18/2024 10:29:40 AM] Loaded language locale: en
[8/18/2024 10:29:41 AM] Randomly-generated background API auth token for the current session: chl2t3g0fw6xaz04l9zvt3800k3bipakkldk0987628g3j35d3l30scljft9y76f
[8/18/2024 10:29:41 AM] Api running on http://localhost:7058
[8/18/2024 10:29:42 AM] Lang files were updated successfully from GitHub
[8/18/2024 10:29:42 AM] UniGetUI is up to date
[8/18/2024 10:29:42 AM] Downloaded new icons and screenshots successfully!
[8/18/2024 10:29:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: npm
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                        █ Version: 
                        █   10.7.0
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:43 AM] Starting scoop cleanup...
[8/18/2024 10:29:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pip
                        █ Executable path: C:\Users\MyUsername\scoop\apps\python\current\python.exe
                        █ Call arguments:  -m pip
                        █ Version: 
                        █   pip 24.0 from C:\Users\MyUsername\scoop\apps\python\current\Lib\site-packages\pip (python 3.12)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: winget.exe
                        █ Executable path: C:\Users\MyUsername\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   System WinGet CLI Version: v1.8.1911
                        █   Microsoft.WinGet.Client PSModule version: ""
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: dotnet tool
                        █ Executable path: C:\Program Files\dotnet\dotnet.exe
                        █ Call arguments: tool
                        █ Version: 
                        █   8.0.400
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:44 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: choco.exe
                        █ Executable path: C:\Users\MyUsername\AppData\Local\UniGetUI\Chocolatey\choco.exe
                        █ Call arguments: 
                        █ Version: 
                        █   2.2.2
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:44 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: scoop
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                        █ Version: 
                        █   Current Scoop version:
                        █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                        █   
                        █   'main' bucket:
                        █   3d1c31876 stgit: Update to version 2.4.10
                        █   
                        █   'extras' bucket:
                        █   f5e249038 sidekick-browser: Update to version 122.60.1.39616-1131b84
                        █   
                        █   'nirsoft' bucket:
                        █   b38031d updated manifests
                        █   
                        █   'sysinternals' bucket:
                        █   6b2b695 sysmon: Update to version 15.15
                        █   
                        █   'nonportable' bucket:
                        █   20e94245 10x-np: Update to version 1.0.202
                        █   
                        █   'java' bucket:
                        █   84b7bb31 temurin11-nightly-jre: Update to version 11.0.25-3.0.ea
                        █   
                        █   'games' bucket:
                        █   0456a6584 dolphin-dev: Update to version 2407-223
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:45 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: powershell.exe
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.22621.3958                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.22621.3958                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:45 AM] Scoop cleanup finished!
[8/18/2024 10:29:51 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell7
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pwsh.exe
                        █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   PowerShell 7.4.4
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/18/2024 10:29:52 AM] Resetting administrator rights cache for process id 50420
[8/18/2024 10:29:52 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[8/18/2024 10:29:52 AM] Dependency WinGet PowerShell Module for manager Winget is present
[8/18/2024 10:29:53 AM] Dependency Scoop-Search for manager Scoop is present
[8/18/2024 10:29:53 AM] Dependency Git for manager Scoop is present
[8/18/2024 10:29:53 AM] Found 1 installed packages from Pip
[8/18/2024 10:29:54 AM] Dependency .NET Tools Outdated for manager .NET Tool is present
[8/18/2024 10:29:54 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[8/18/2024 10:29:54 AM] Found 1 installed packages from .NET Tool
[8/18/2024 10:29:54 AM] Found 51 installed packages from Scoop
[8/18/2024 10:29:54 AM] Found 4 installed packages from Chocolatey
[8/18/2024 10:29:55 AM] Found 0 available updates from Chocolatey
[8/18/2024 10:29:55 AM] Found 1 available updates from Pip
[8/18/2024 10:29:55 AM] Found 0 installed packages from Npm
[8/18/2024 10:29:55 AM] Found 2 installed packages from PowerShell
[8/18/2024 10:29:55 AM] Found 0 available updates from Npm
[8/18/2024 10:29:56 AM] Found 0 installed packages from PowerShell7
[8/18/2024 10:29:56 AM] Found 0 available updates from PowerShell7
[8/18/2024 10:29:57 AM] Found 413 installed packages from Winget
[8/18/2024 10:29:57 AM] Found 28 available updates from Winget
[8/18/2024 10:30:02 AM] Found 0 available updates from .NET Tool
[8/18/2024 10:30:05 AM] Found 0 available updates from PowerShell
[8/18/2024 10:30:10 AM] Backup saved to Z:\Backups\WingetUI\installed packages 2024-08-18 10-29-58.json
[8/18/2024 10:30:51 AM] Error finding updates on manager Scoop
[8/18/2024 10:30:51 AM] System.TimeoutException: The operation has timed out.
                           at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 188
[8/18/2024 10:31:52 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[8/18/2024 10:31:52 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=AutoHotkey.AutoHotkey
[8/18/2024 10:31:52 AM] Icon for package AutoHotkey.AutoHotkey stored on C:\Users\MyUsername\AppData\Local\UniGetUI\CachedMedia\Winget\AutoHotkey.AutoHotkey.png
[8/18/2024 10:31:54 AM] Resetting administrator rights cache for process id 50420
[8/18/2024 10:34:22 AM] Scoop buckets have been already refreshed in the last ten minutes, skipping.
[8/18/2024 10:34:23 AM] Found 51 installed packages from Scoop
[8/18/2024 10:34:24 AM] Found 1 available updates from Pip
[8/18/2024 10:34:24 AM] Found 0 available updates from Npm
[8/18/2024 10:34:25 AM] Found 0 available updates from PowerShell7
[8/18/2024 10:34:31 AM] Found 0 available updates from .NET Tool
[8/18/2024 10:34:32 AM] Found 0 available updates from Chocolatey
[8/18/2024 10:34:34 AM] Found 27 available updates from Winget
[8/18/2024 10:34:35 AM] Found 0 available updates from PowerShell
[8/18/2024 10:35:22 AM] Error finding updates on manager Scoop
[8/18/2024 10:35:22 AM] System.TimeoutException: The operation has timed out.
                           at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
[8/18/2024 10:48:17 AM] Found 1 installed packages from .NET Tool
[8/18/2024 10:48:17 AM] Found 1 installed packages from Pip
[8/18/2024 10:48:17 AM] Found 51 installed packages from Scoop
[8/18/2024 10:48:17 AM] Found 4 installed packages from Chocolatey
[8/18/2024 10:48:18 AM] Found 2 installed packages from PowerShell
[8/18/2024 10:48:18 AM] Found 0 installed packages from PowerShell7
[8/18/2024 10:48:19 AM] Found 0 installed packages from Npm
[8/18/2024 10:48:27 AM] Found 413 installed packages from Winget
```

### Package Managers Logs

```text
Manager Scoop with version:
Current Scoop version:
859d1db5 chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
3d1c31876 stgit: Update to version 2.4.10

'extras' bucket:
f5e249038 sidekick-browser: Update to version 122.60.1.39616-1131b84

'nirsoft' bucket:
b38031d updated manifests

'sysinternals' bucket:
6b2b695 sysmon: Update to version 15.15

'nonportable' bucket:
20e94245 10x-np: Update to version 1.0.202

'java' bucket:
84b7bb31 temurin11-nightly-jre: Update to version 11.0.25-3.0.ea

'games' bucket:
0456a6584 dolphin-dev: Update to version 2407-223

——————————————————————————————————————————


Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 8/18/2024 10:29:43 AM
Process end time:   8/18/2024 10:29:44 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is RefreshIndexes
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop update"
Process start time: 8/18/2024 10:29:51 AM
Process end time:   8/18/2024 10:32:04 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 8/18/2024 10:29:51 AM
Process end time:   8/18/2024 10:29:54 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 8/18/2024 10:29:52 AM
Process end time:   8/18/2024 10:29:55 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 8/18/2024 10:34:22 AM
Process end time:   8/18/2024 10:34:23 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop status"
Process start time: 8/18/2024 10:34:23 AM
Process end time:   8/18/2024 10:36:33 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 8/18/2024 10:48:16 AM
Process end time:   8/18/2024 10:48:17 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

I tried `scoop status` in a terminal to get outdated apps from Scoop directly. According to Powershell `Measure-Command { scoop status }`, it took 127 seconds to complete (I've been having network issues recently), so it might be related to #2481. If this is the case, it might be helpful to let the user know that a package manager operation was canceled due to a timeout, as well as let them set the timeout value until there's a better way to handle long-running operations.

**Comment by marticliment** [comment]
I will see what can be done

**Comment by marticliment** [comment]
This issue was fixed on the latest stable version. 

You will need to enable the "Disable 1 minute timeout" from Experimental Settings, as this issue is not caused by UniGetUI, but by scoop taking an exagerated amount of time to load packages (1+ minute)
