### ISSUE TITLE
[BUG] scoop package in not being found

### ISSUE THREAD

**Issue by K0-RR** [marticliment/UniGetUI#2644]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

W11 - build 22631.4037

### Describe your issue

I search for "jami" in UniGetUI - there is no package from scoop.
It should detect that one https://scoop.sh/#/apps?q=jami&id=7d66383f3faf4e93ae63f56f51f6774f549409ab
Extras bucket is installed.

### UniGetUI Log

```text
[19.08.2024 12:47:37]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[19.08.2024 12:47:37]
[19.08.2024 12:47:37] Version Code:  3,11
[19.08.2024 12:47:37] Encoding Code Page set to 437
[19.08.2024 12:47:37] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[19.08.2024 12:47:37] Loaded language locale: en
[19.08.2024 12:47:38] Randomly-generated background API auth token for the current session: 8dr9symsqh2onj1t9rh4ahwwnz5ida0wvbi1gsohbpr62at3vm73jnoslox3rn0d
[19.08.2024 12:47:38] Api running on http://localhost:7058
[19.08.2024 12:47:38] Old chocolatey path is a symbolic link, not migrating Chocolatey...
[19.08.2024 12:47:41] Lang files were updated successfully from GitHub
[19.08.2024 12:47:44] UniGetUI is up to date
[19.08.2024 12:47:44] Downloaded new icons and screenshots successfully!
[19.08.2024 12:47:44] Command pwsh.exe was not found on the system
[19.08.2024 12:47:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.0 from C:\Users\nacia\AppData\Roaming\Python\Python312\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.2.3
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\nacia\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3958                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3958                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   
                      █   'main' bucket:
                      █   
                      █   'extras' bucket:
                      █   
                      █   'nonportable' bucket:
                      █   
                      █   'hero-persson' bucket:
                      █   
                      █   'unmojang' bucket:
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.08.2024 12:47:52] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[19.08.2024 12:47:52] Dependency WinGet PowerShell Module for manager Winget is present
[19.08.2024 12:47:52] Dependency Scoop-Search for manager Scoop is present
[19.08.2024 12:47:52] Found 110 installed packages from Pip
[19.08.2024 12:47:52] Found 7 available updates from Chocolatey
[19.08.2024 12:47:52] Found 23 installed packages from Chocolatey
[19.08.2024 12:47:52] Dependency Git for manager Scoop is present
[19.08.2024 12:47:52] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[19.08.2024 12:47:52] Found 0 available updates from PowerShell
[19.08.2024 12:47:53] Found 11 installed packages from Scoop
[19.08.2024 12:47:53] Found 0 installed packages from PowerShell
[19.08.2024 12:47:54] Found 3 installed packages from Npm
[19.08.2024 12:47:58] Found 60 available updates from Winget
[19.08.2024 12:47:58] Found 296 installed packages from Winget
[19.08.2024 12:47:59] Found 1 available updates from Npm
[19.08.2024 12:48:05] Found 50 available updates from Pip
[19.08.2024 12:50:32] Command parse_pip_search.exe was not found on the system
[19.08.2024 12:50:32] Found 0 available packages from Scoop with the query jami
[19.08.2024 12:50:33] Found 7 available packages from Winget with the query jami
[19.08.2024 12:50:34] Error finding packages on manager Pip with query jami
[19.08.2024 12:50:34] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 97
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 163
[19.08.2024 12:50:34] Found 1 available packages from Chocolatey with the query jami
[19.08.2024 12:50:34] Found 0 available packages from Npm with the query jami
[19.08.2024 12:50:56] Found 6 available packages from PowerShell with the query jami
```

### Package Managers Logs

```text
C:\Users\nacia>scoop install extras/jami
Updating Scoop...
fatal: detected dubious ownership in repository at 'C:/Users/nacia/scoop/apps/scoop/current'
'C:/Users/nacia/scoop/apps/scoop/current' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-25069855-2416687258-871956521-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/nacia/scoop/apps/scoop/current'
'C:/Users/nacia/scoop/apps/scoop/current' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-25069855-2416687258-871956521-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1,param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1,param2>...]
                          synonym for --dirstat=files,param1,param2...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --compact-summary     generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --full-index          show full pre- and post-image object names on the "index" lines
    --color[=<when>]      show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --abbrev[=<n>]        use <n> digits to display object names
    --src-prefix <prefix> show the given source prefix instead of "a/"
    --dst-prefix <prefix> show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --default-prefix      use default prefixes a/ and b/
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --find-copies-harder  use unmodified files as source to find copies
    --no-renames          disable rename detection
    --rename-empty        use empty blobs as rename source
    --follow              continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --indent-heuristic    heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --color-moved[=<mode>]
                          moved lines of code are colored differently
    --color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --relative[=<prefix>] when run from subdir, exclude changes outside and show relative paths
    -a, --text            treat all files as text
    -R                    swap two inputs, reverse the diff
    --exit-code           exit with 1 if there were differences, 0 otherwise
    --quiet               disable all output of the program
    --ext-diff            allow an external diff helper to be executed
    --textconv            run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       output to a specific file

fatal: not in a git directory
fatal: not in a git directory
fatal: detected dubious ownership in repository at 'C:/Users/nacia/scoop/apps/scoop/current'
'C:/Users/nacia/scoop/apps/scoop/current' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-25069855-2416687258-871956521-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/nacia/scoop/apps/scoop/current'
'C:/Users/nacia/scoop/apps/scoop/current' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-25069855-2416687258-871956521-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/nacia/scoop/apps/scoop/current'
'C:/Users/nacia/scoop/apps/scoop/current' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-25069855-2416687258-871956521-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current
Invoke-GitLog : Cannot bind argument to parameter 'CommitHash' because it is an empty string.
At C:\Users\nacia\scoop\apps\scoop\current\libexec\scoop-update.ps1:143 char:57
+ ...           Invoke-GitLog -Path $currentdir -CommitHash $previousCommit
+                                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-GitLog], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Invoke-GitLog

Update failed.
WARN  Purging previous failed installation of jami.
ERROR 'jami' isn't installed correctly.
Removing older version (202407041643).
'jami' was uninstalled.
Installing 'jami' (202407041643) [64bit] from 'extras' bucket
```

**Comment by marticliment** [comment]
You have a misconfiguration in your scoop installation.

Please run `git config --global --add safe.directory C:/Users/nacia/scoop/apps/scoop/current` on a command prompt and try again
