### ISSUE TITLE
No packages were found on my Windows 11 laptop, error messages in the log file

### ISSUE THREAD

**Issue by wernerdietrich** [marticliment/UniGetUI#2659]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro Version	10.0.22631 Build 22631

### Describe your issue

No packages were found by UniGetUI, wierd error messages in the log. I am not sure if this is the expacted behaviour.
[23.08.2024 18:56:37] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26

and 

[23.08.2024 18:56:38] System.ComponentModel.Win32Exception (15700): An error occurred trying to start process 'C:\Users\werne\AppData\Local\Microsoft\WindowsApps\python.exe' with working directory 'C:\Program Files\UniGetUI'. Der Prozess besitzt keine Paketidentität.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 356
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 83
[

### Steps to reproduce the issue

searching for packages 

### UniGetUI Log

```text
[23.08.2024 18:56:37]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[23.08.2024 18:56:37]
[23.08.2024 18:56:37] Version Code:  3,11
[23.08.2024 18:56:37] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[23.08.2024 18:56:37] Encoding Code Page set to 0
[23.08.2024 18:56:37] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[23.08.2024 18:56:37] Loaded language locale: de
[23.08.2024 18:56:38] Randomly-generated background API auth token for the current session: i61b3pu6ku73xrulz3uv3oa1ke95y7p4lz46nsqx8zh1nlqcj8jeu8auylf16q2q
[23.08.2024 18:56:38] Api running on http://localhost:7058
[23.08.2024 18:56:38] Lang files were updated successfully from GitHub
[23.08.2024 18:56:38] Downloaded new icons and screenshots successfully!
[23.08.2024 18:56:38] Command npm was not found on the system
[23.08.2024 18:56:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:38] Could not initialize Package Manager Pip
[23.08.2024 18:56:38] System.ComponentModel.Win32Exception (15700): An error occurred trying to start process 'C:\Users\werne\AppData\Local\Microsoft\WindowsApps\python.exe' with working directory 'C:\Program Files\UniGetUI'. Der Prozess besitzt keine Paketidentität.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 356
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 83
[23.08.2024 18:56:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:38] UniGetUI is up to date
[23.08.2024 18:56:39] Command scoop was not found on the system
[23.08.2024 18:56:39] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:39] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\werne\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:40] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\werne\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:40] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.3.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:42] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3958                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3958                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.08.2024 18:56:43] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[23.08.2024 18:56:43] Dependency WinGet PowerShell Module for manager Winget is present
[23.08.2024 18:56:43] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[23.08.2024 18:56:44] Found 0 installed packages from Chocolatey
[23.08.2024 18:56:44] Found 0 available updates from Chocolatey
[23.08.2024 18:56:45] Found 0 installed packages from PowerShell7
[23.08.2024 18:56:45] Found 0 installed packages from Winget
[23.08.2024 18:56:45] Found 0 available updates from PowerShell7
[23.08.2024 18:56:46] Found 0 available updates from Winget
[23.08.2024 18:56:47] Found 0 installed packages from PowerShell
[23.08.2024 18:56:48] Found 0 available updates from PowerShell
[23.08.2024 19:12:11] Found 0 installed packages from Chocolatey
[23.08.2024 19:12:13] Found 0 installed packages from PowerShell7
[23.08.2024 19:12:14] Found 0 installed packages from PowerShell
[23.08.2024 19:12:16] Found 0 installed packages from Winget
[23.08.2024 19:15:38] Found 0 installed packages from Chocolatey
[23.08.2024 19:15:39] Found 0 installed packages from Winget
[23.08.2024 19:15:39] Found 0 installed packages from PowerShell7
[23.08.2024 19:15:41] Found 0 installed packages from PowerShell
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 23.08.2024 18:56:39
Process end time:   23.08.2024 18:56:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\werne\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 23.08.2024 18:56:42
Process end time:   23.08.2024 18:56:43

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23.08.2024 18:56:42
Process end time:   23.08.2024 18:56:45

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 23.08.2024 18:56:43
Process end time:   23.08.2024 18:56:43

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 23.08.2024 18:56:43
Process end time:   23.08.2024 18:56:46

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23.08.2024 19:12:09
Process end time:   23.08.2024 19:12:16

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23.08.2024 19:15:36
Process end time:   23.08.2024 19:15:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Will fix
