### ISSUE TITLE
[BUG] ignored packages still trying to update

### ISSUE THREAD

**Issue by slrgt** [marticliment/UniGetUI#2678]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11

### Describe your issue

Programs\Packages that ive marked to be ignored continue trying to update so every day at least once i get a bunch of notifications about failed updates. I want UnigetUI to fully ignore them so it never tries to update them or give me notifications about the update and the failed update

### UniGetUI Log

```text
[8/30/2024 11:54:39 AM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.1
[8/30/2024 11:54:39 AM]
[8/30/2024 11:54:39 AM] Version Code:  3.11
[8/30/2024 11:54:39 AM] Encoding Code Page set to 437
[8/30/2024 11:54:40 AM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[8/30/2024 11:54:41 AM] Loaded language locale: en
[8/30/2024 11:54:42 AM] Randomly-generated background API auth token for the current session: vbacd8ejx87xf9mx14ihup7ws54f9pi8b8f3i9vip5n6gijktagoijn5d4ztudq8
[8/30/2024 11:54:42 AM] Api running on http://localhost:7058
[8/30/2024 11:54:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:43 AM] Lang files were updated successfully from GitHub
[8/30/2024 11:54:43 AM] UniGetUI is up to date
[8/30/2024 11:54:43 AM] Downloaded new icons and screenshots successfully!
[8/30/2024 11:54:43 AM] Command npm was not found on the system
[8/30/2024 11:54:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:43 AM] Command scoop was not found on the system
[8/30/2024 11:54:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:43 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pip
                        █ Executable path: C:\Users\dows\AppData\Local\Microsoft\WindowsApps\python.exe
                        █ Call arguments:  -m pip
                        █ Version: 
                        █   
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:44 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: winget.exe
                        █ Executable path: C:\Users\dows\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   System WinGet CLI Version: v1.8.1911
                        █   Microsoft.WinGet.Client PSModule version: ""
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:45 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: powershell.exe
                        █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.22621.3958                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.22621.3958                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:46 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell7
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pwsh.exe
                        █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   PowerShell 7.4.5
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[8/30/2024 11:54:46 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[8/30/2024 11:54:46 AM] Dependency WinGet PowerShell Module for manager Winget is present
[8/30/2024 11:54:46 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[8/30/2024 11:54:46 AM] Found 0 available updates from Pip
[8/30/2024 11:54:46 AM] Found 0 installed packages from Pip
[8/30/2024 11:54:48 AM] Found 0 installed packages from PowerShell7
[8/30/2024 11:54:48 AM] Found 2 installed packages from PowerShell
[8/30/2024 11:54:48 AM] Found 0 available updates from PowerShell7
[8/30/2024 11:54:49 AM] Found 4 available updates from Winget
[8/30/2024 11:54:49 AM] Found 179 installed packages from Winget
[8/30/2024 11:54:50 AM] Found 0 available updates from PowerShell
[8/30/2024 11:54:54 AM] Found 0 installed packages from Pip
[8/30/2024 11:54:56 AM] Found 0 installed packages from PowerShell7
[8/30/2024 11:54:56 AM] Found 2 installed packages from PowerShell
[8/30/2024 11:54:57 AM] Found 179 installed packages from Winget
[8/30/2024 12:00:24 PM] Found 0 installed packages from Pip
[8/30/2024 12:00:26 PM] Found 0 installed packages from PowerShell7
[8/30/2024 12:00:26 PM] Found 179 installed packages from Winget
[8/30/2024 12:00:26 PM] Found 2 installed packages from PowerShell
[8/30/2024 12:02:50 PM] Found 0 installed packages from Pip
[8/30/2024 12:02:52 PM] Found 0 installed packages from PowerShell7
[8/30/2024 12:02:52 PM] Found 179 installed packages from Winget
[8/30/2024 12:02:52 PM] Found 2 installed packages from PowerShell
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 8/30/2024 11:54:44 AM
Process end time:   8/30/2024 11:54:44 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\dows\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 8/30/2024 11:54:46 AM
Process end time:   8/30/2024 11:54:46 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/30/2024 11:54:46 AM
Process end time:   8/30/2024 11:54:49 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 8/30/2024 11:54:46 AM
Process end time:   8/30/2024 11:54:46 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 8/30/2024 11:54:46 AM
Process end time:   8/30/2024 11:54:49 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/30/2024 11:54:54 AM
Process end time:   8/30/2024 11:54:57 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/30/2024 12:00:24 PM
Process end time:   8/30/2024 12:00:26 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 8/30/2024 12:02:50 PM
Process end time:   8/30/2024 12:02:52 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
You are ignoring them by using the "Ignore updates" option or the "Skip this version" option?

**Comment by marticliment** [comment]
Which package is giving you issues?

**Comment by slrgt** [comment]
Discord, spotify, microsoft edge, windows terminal

**Comment by slrgt** [comment]
it randomly fixed for all the packages except for Discord

**Comment by rhockstar** [comment]
I'm getting the following in my log when trying to ingore updates - Currently using 3.1.2-beta1, but this issue has been around for  a number of releses. Just looking for a way i can move this forward and fix it. I've tried reinstalls and running as admin, but beyond that, nothing seems to work.

```
[9/9/2024 1:44:11 PM] Could not add package SublimeHQ.SublimeText.4 to ignored updates
[9/9/2024 1:44:11 PM] System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
                         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
                         at System.Text.Json.Utf8JsonReader.Read()
                         at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
                         at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
                         at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
                         at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
                         at UniGetUI.PackageEngine.PackageClasses.Package.AddToIgnoredUpdatesAsync(String version) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 214
```

**Comment by marticliment** [comment]
> I'm getting the following in my log when trying to ingore updates - Currently using 3.1.2-beta1, but this issue has been around for a number of releses. Just looking for a way i can move this forward and fix it. I've tried reinstalls and running as admin, but beyond that, nothing seems to work.

So this is the issue, I will fix it
