### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by udobehm** [marticliment/UniGetUI#2689]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Win 11 Pro

### Describe your issue

Good day. Each time I start WinGetUi the folder 'WindowsPowerShell' is created inside my user docuements folder. I need to delete this one each time manually. Could you please fix your app so that this folder isn't created all the time WinGetUI starts? The following sub folders are being created but there is no content inside: WindowsPowerShell\Scripts\InstalledScriptInfos

Thanks!
Udo

### Steps to reproduce the issue

Starting WinGetUI

### UniGetUI Log

```text
[31.08.2024 20:13:43]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[31.08.2024 20:13:43]
[31.08.2024 20:13:43] Version Code:  3,11
[31.08.2024 20:13:43] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[31.08.2024 20:13:43] Encoding Code Page set to 0
[31.08.2024 20:13:44] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[31.08.2024 20:13:44] Loaded language locale: de
[31.08.2024 20:13:44] Randomly-generated background API auth token for the current session: p9o15zznrxnazmusvoki593uvrzn56g6mnu8h8e3p70ibichbnnx4yl98rf0cndc
[31.08.2024 20:13:45] Api running on http://localhost:7058
[31.08.2024 20:13:45] Old chocolatey path is a symbolic link, not migrating Chocolatey...
[31.08.2024 20:13:45] Lang files were updated successfully from GitHub
[31.08.2024 20:13:45] UniGetUI is up to date
[31.08.2024 20:13:45] Command npm was not found on the system
[31.08.2024 20:13:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:45] Command pwsh.exe was not found on the system
[31.08.2024 20:13:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:46] Downloaded new icons and screenshots successfully!
[31.08.2024 20:13:47] Command scoop was not found on the system
[31.08.2024 20:13:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\Udo\AppData\Local\Programs\Python\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Users\Udo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:51] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.3958                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.3958                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:51] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Udo\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[31.08.2024 20:13:54] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[31.08.2024 20:13:54] Dependency WinGet PowerShell Module for manager Winget is present
[31.08.2024 20:13:54] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[31.08.2024 20:14:22] Found 5 available updates from Winget
[31.08.2024 20:14:28] Found 866 installed packages from Winget
[31.08.2024 20:14:32] Found 0 installed packages from Chocolatey
[31.08.2024 20:14:32] Found 0 available updates from Chocolatey
[31.08.2024 20:14:32] Found 0 installed packages from PowerShell
[31.08.2024 20:14:32] Found 1 installed packages from Pip
[31.08.2024 20:14:34] Found 0 available updates from PowerShell
[31.08.2024 20:14:37] Backup saved to C:\Users\Udo\Einstellungen\UniGetUI\Sicherung\ENVY installierte Pakete.json
[31.08.2024 20:14:37] Found 0 available updates from Pip
[31.08.2024 20:14:51] Found 1 installed packages from Pip
[31.08.2024 20:14:54] Found 0 installed packages from PowerShell
[31.08.2024 20:14:54] Found 0 installed packages from Chocolatey
[31.08.2024 20:15:04] Found 866 installed packages from Winget
[31.08.2024 20:15:04] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[31.08.2024 20:15:04] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=OpenMedia.4KVideoDownloader
[31.08.2024 20:15:04] Icon for package OpenMedia.4KVideoDownloader stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\OpenMedia.4KVideoDownloader.png
[31.08.2024 20:15:05] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[31.08.2024 20:15:05] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=DeepL.DeepL
[31.08.2024 20:15:05] Icon for package DeepL.DeepL stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\DeepL.DeepL.png
[31.08.2024 20:15:05] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[31.08.2024 20:15:05] Icon for package Microsoft.Teams.Free was not found, returning default icon
[31.08.2024 20:15:05] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[31.08.2024 20:15:05] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Microsoft.WindowsTerminal
[31.08.2024 20:15:05] Icon for package Microsoft.WindowsTerminal stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.WindowsTerminal.png
[31.08.2024 20:15:05] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[31.08.2024 20:15:05] Icon for package Zoom.Zoom.EXE was not found, returning default icon
[31.08.2024 20:18:37] Found 1 installed packages from Pip
[31.08.2024 20:18:37] Found 0 installed packages from Chocolatey
[31.08.2024 20:18:37] Found 0 installed packages from PowerShell
[31.08.2024 20:18:45] Found 866 installed packages from Winget
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 31.08.2024 20:13:48
Process end time:   31.08.2024 20:13:48

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 31.08.2024 20:13:51
Process end time:   31.08.2024 20:13:56

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 31.08.2024 20:13:51
Process end time:   31.08.2024 20:14:28

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 31.08.2024 20:13:54
Process end time:   31.08.2024 20:13:54

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 31.08.2024 20:13:56
Process end time:   31.08.2024 20:14:22

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 31.08.2024 20:14:49
Process end time:   31.08.2024 20:15:04

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 31.08.2024 20:18:31
Process end time:   31.08.2024 20:18:45

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Hello,

The WindowsPowerShell folder is created by PowerShell, a shell built into Windows which UniGetUI uses to  interact with certain package managers. Since it is created by PowerShell, I can't prevent the creation of the folder from UniGetUI
