### ISSUE TITLE
[BUG] Chocolatey installs no longer work.

### ISSUE THREAD

**Issue by FlamingPhoenix40** [marticliment/UniGetUI#2702]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 23H2 22631.4037 x64

### Describe your issue

I can no longer install or update packages using Chocolatey. I am using the system chocolatey because I sometimes like to use the commandline version of chocolatey. Have tried reinstalling UnigetUI to no avail. Installing the failed package using Chocolatey command line goes fine. Tested a Winget package as well, that works fine.

Will paste the "Live output" of the failed install as well, because I don't know if this is in the logs.

### Steps to reproduce the issue

1. Search for a package, in my case "unzip"
2. Select install or install as admin (shouldn't matter because I have chocolatey set to alway require admin)
3. Installation fails.

### UniGetUI Log

```text
[04/09/2024 02:25:51]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[04/09/2024 02:25:51]
[04/09/2024 02:25:51] Version Code:  3,11
[04/09/2024 02:25:51] Encoding Code Page set to 850
[04/09/2024 02:25:51] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[04/09/2024 02:25:52] Loaded language locale: en
[04/09/2024 02:25:52] Randomly-generated background API auth token for the current session: 96xgtxd54i7j8fbvj6bv34sxufolvgdy7tixpotcbpcm7himw7x9fpiu4a2uoz8g
[04/09/2024 02:25:52] Api running on http://localhost:7058
[04/09/2024 02:25:53] Lang files were updated successfully from GitHub
[04/09/2024 02:25:53] UniGetUI is up to date
[04/09/2024 02:25:53] Downloaded new icons and screenshots successfully!
[04/09/2024 02:25:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:54] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:54] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\FlamingPhoenix40\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:55] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:55] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:58] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.3.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[04/09/2024 02:25:58] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[04/09/2024 02:25:58] Dependency WinGet PowerShell Module for manager Winget is present
[04/09/2024 02:25:58] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[04/09/2024 02:26:02] Found 76 installed packages from Chocolatey
[04/09/2024 02:26:03] Found 40 available updates from Chocolatey
[04/09/2024 02:26:07] Found 61 available updates from Winget
[04/09/2024 02:26:08] Found 448 installed packages from Winget
[04/09/2024 02:26:12] Found 18 available packages from Winget with the query unzip
[04/09/2024 02:26:14] Found 12 available packages from Chocolatey with the query unzip
[04/09/2024 02:26:18] Install
[04/09/2024 02:26:18] Found 0 screenshots for package Id=unzip
[04/09/2024 02:26:18] Error when loading the package icon for the package unzip on manager Chocolatey
[04/09/2024 02:26:18] System.UriFormatException: Invalid URI: The URI is empty.
                         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
                         at System.Uri..ctor(String uriString)
                         at UniGetUI.PackageEngine.Managers.PowerShellManager.BaseNuGetDetailsProvider.GetPackageIcon_Unsafe(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Generic.NuGet\BaseNuGetDetailsProvider.cs:line 140
                         at UniGetUI.PackageEngine.Classes.Manager.BaseProviders.BasePackageDetailsProvider`1.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\BaseProviders\BasePackageDetailsProvider.cs:line 40
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 453
[04/09/2024 02:26:18] Loaded details for package unzip on manager Chocolatey
[04/09/2024 02:26:23] Error when loading the package icon for the package unzip on manager Chocolatey
[04/09/2024 02:26:23] System.UriFormatException: Invalid URI: The URI is empty.
                         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
                         at System.Uri..ctor(String uriString)
                         at UniGetUI.PackageEngine.Managers.PowerShellManager.BaseNuGetDetailsProvider.GetPackageIcon_Unsafe(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Generic.NuGet\BaseNuGetDetailsProvider.cs:line 140
                         at UniGetUI.PackageEngine.Classes.Manager.BaseProviders.BasePackageDetailsProvider`1.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\BaseProviders\BasePackageDetailsProvider.cs:line 40
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetPackageIconUrl(IPackage package) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 453
[04/09/2024 02:30:09] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=7zip
[04/09/2024 02:30:10] Icon for package 7zip stored on C:\Users\FlamingPhoenix40\AppData\Local\UniGetUI\CachedMedia\Chocolatey\7zip.svg
[04/09/2024 02:30:25] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[04/09/2024 02:30:25] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=calibre.calibre
[04/09/2024 02:30:25] Icon for package calibre.calibre stored on C:\Users\FlamingPhoenix40\AppData\Local\UniGetUI\CachedMedia\Winget\calibre.calibre.png
```

### Package Managers Logs

```text
Manager Chocolatey with version:
2.3.0

——————————————————————————————————————————


Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 04/09/2024 02:25:55
Process end time:   04/09/2024 02:25:58

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListUpdates
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " outdated"
Process start time: 04/09/2024 02:25:58
Process end time:   04/09/2024 02:26:03

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListInstalledPackages
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " list"
Process start time: 04/09/2024 02:25:58
Process end time:   04/09/2024 02:26:02

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 04/09/2024 02:25:58
Process end time:   04/09/2024 02:26:01

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Chocolatey. Task type is FindPackages
Process start time: 04/09/2024 02:26:12
Process end time:   04/09/2024 02:26:14

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 04/09/2024 02:26:12
Process end time:   04/09/2024 02:26:14

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Chocolatey. Task type is LoadPackageDetails
Process start time: 04/09/2024 02:26:18
Process end time:   04/09/2024 02:26:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is LoadPackageVersions
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " search unzip --exact --all-versions"
Process start time: 04/09/2024 02:26:18
Process end time:   04/09/2024 02:26:21

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

Live output log:
```
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                           
Starting package install operation for package id=unzip with Manager name=Chocolatey
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\ProgramData\chocolatey\bin\choco.exe"  install unzip -y  --no-progress
Working Directory      : C:\Users\FlamingPhoenix40
Process Start Time     : 04/09/2024 02:26:23
ERR | Error: System.ArgumentException: Illegal characters in path.
ERR |    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
ERR |    at System.IO.Path.IsPathRooted(String path)
ERR |    at System.IO.Path.CombineNoChecks(String path1, String path2)
ERR |    at System.IO.StringResultHandler.CreateObject(SearchData searchData, WIN32_FIND_DATA& findData)
ERR |    at System.IO.FileSystemEnumerableIterator`1.MoveNext()
ERR |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
ERR |    at System.IO.Directory.GetFiles(String path)
ERR |    at gsudo.Rpc.NamedPipeUtils.ExistsNamedPipe(String name)
ERR |    at gsudo.Helpers.ServiceHelper.FindServiceByIntegrity(Nullable`1 clientPid, String user)
ERR |    at gsudo.Helpers.ServiceHelper.<FindAnyServiceFast>d__2.MoveNext()
ERR | --- End of stack trace from previous location where exception was thrown ---
ERR |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
ERR |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ERR |    at gsudo.Commands.RunCommand.<RunUsingService>d__8.MoveNext()
ERR | --- End of stack trace from previous location where exception was thrown ---
ERR |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
ERR |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ERR |    at gsudo.Commands.RunCommand.<Execute>d__6.MoveNext()
ERR | --- End of stack trace from previous location where exception was thrown ---
ERR |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
ERR |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
ERR |    at gsudo.Program.<Start>d__1.MoveNext()
Process Exit Code      : 999
Process End Time       : 04/09/2024 02:26:23
```

**Comment by marticliment** [comment]
Please test this beta release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta0
