### ISSUE TITLE
[BUG] Installed programs not being added to PATH or Start menu

### ISSUE THREAD

**Issue by ajalberd** [marticliment/UniGetUI#2723]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 22631.4112

### Describe your issue

I'm not sure if this is the desired behavior, but installing packages that are to be run in the terminal such as ADB etc. cannot be found in the terminal. 

### Steps to reproduce the issue

Install any program through choco, then look for it on Start Menu / run it in the terminal.

### UniGetUI Log

```text
[9/10/2024 10:08:45 AM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.2-beta1
[9/10/2024 10:08:45 AM]
[9/10/2024 10:08:45 AM] Version Code:  3.1191
[9/10/2024 10:08:45 AM] Encoding Code Page set to 437
[9/10/2024 10:08:45 AM] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[9/10/2024 10:08:45 AM] Something went wrong when parsing language file C:\Program Files\WingetUI\Assets\Languages\lang_en.json
[9/10/2024 10:08:45 AM] System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
                           at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
                           at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
                           at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
                           at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
                           at System.Text.Json.Utf8JsonReader.Read()
                           at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
                           at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
                           at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
                           at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
                           at UniGetUI.Core.Language.LanguageEngine.LoadLanguageFile(String LangKey) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.LanguageEngine\LanguageEngine.cs:line 99
[9/10/2024 10:08:45 AM] Loaded language locale: en
[9/10/2024 10:08:45 AM] Randomly-generated background API auth token for the current session: oim96uzmxmi8usl1q32xrm60b8r9if6g4mx2uz69dj4ewuw2um8a76l2ekmcvazf
[9/10/2024 10:08:45 AM] Api running on http://localhost:7058
[9/10/2024 10:08:45 AM] Lang files were updated successfully from GitHub
[9/10/2024 10:08:45 AM] UniGetUI is up to date
[9/10/2024 10:08:45 AM] Downloaded new icons and screenshots successfully!
[9/10/2024 10:08:45 AM] Command npm was not found on the system
[9/10/2024 10:08:45 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:46 AM] Command pwsh.exe was not found on the system
[9/10/2024 10:08:46 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell7
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:46 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:46 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pip
                        █ Executable path: C:\Users\Andrew\AppData\Local\Programs\Python\Python312\python.exe
                        █ Call arguments:  -m pip
                        █ Version: 
                        █   pip 24.2 from C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:47 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: winget.exe
                        █ Executable path: C:\Users\Andrew\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   System WinGet CLI Version: v1.8.1911
                        █   Microsoft.WinGet.Client PSModule version: ""
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: scoop
                        █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                        █ Version: 
                        █   
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:49 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: choco.exe
                        █ Executable path: C:\Users\Andrew\AppData\Local\UniGetUI\Chocolatey\choco.exe
                        █ Call arguments: 
                        █ Version: 
                        █   2.2.2
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:50 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: powershell.exe
                        █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.22621.4111                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.22621.4111                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/10/2024 10:08:50 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[9/10/2024 10:08:50 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[9/10/2024 10:08:50 AM] Dependency WinGet PowerShell Module for manager Winget is present
[9/10/2024 10:08:51 AM] Found 44 installed packages from Pip
[9/10/2024 10:08:51 AM] Dependency Scoop-Search for manager Scoop is present
[9/10/2024 10:08:51 AM] Dependency Git for manager Scoop is present
[9/10/2024 10:08:52 AM] Found 0 installed packages from Scoop
[9/10/2024 10:08:53 AM] Found 0 installed packages from Scoop
[9/10/2024 10:08:53 AM] Found 2 installed packages from Chocolatey
[9/10/2024 10:08:53 AM] Found 1 installed packages from PowerShell
[9/10/2024 10:08:54 AM] Found 0 available updates from Chocolatey
[9/10/2024 10:08:54 AM] Found 4 available updates from Pip
[9/10/2024 10:08:54 AM] Found 0 available updates from Scoop
[9/10/2024 10:08:54 AM] Found 0 available packages from Scoop with the query adb
[9/10/2024 10:08:54 AM] Found 1 available updates from PowerShell
[9/10/2024 10:08:55 AM] Found 42 available updates from Winget
[9/10/2024 10:08:55 AM] Found 4 available packages from Pip with the query adb
[9/10/2024 10:08:56 AM] Found 464 installed packages from Winget
[9/10/2024 10:08:56 AM] Found 3 available packages from Chocolatey with the query adb
[9/10/2024 10:08:57 AM] Found 21 available packages from Winget with the query adb
[9/10/2024 10:09:00 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=adb
[9/10/2024 10:09:00 AM] Icon for package adb stored on C:\Users\Andrew\AppData\Local\UniGetUI\CachedMedia\Chocolatey\adb.jpg
[9/10/2024 10:09:00 AM] Loaded operation parameters for package id=adb on manager Chocolatey and operation Install: install adb -y --no-progress
[9/10/2024 10:09:06 AM] Found 3 available packages from PowerShell with the query adb
[9/10/2024 10:10:13 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=adb
[9/10/2024 10:10:13 AM] Icon for package adb stored on C:\Users\Andrew\AppData\Local\UniGetUI\CachedMedia\Chocolatey\adb.jpg
[9/10/2024 10:10:13 AM] Loaded operation parameters for package id=adb on manager Chocolatey and operation Install: install adb -y --no-progress
```

### Package Managers Logs

```text
Starting package install operation for package id=adb with Manager name=Chocolatey
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\Andrew\AppData\Local\UniGetUI\Chocolatey\choco.exe"  install adb -y --no-progress
Working Directory      : C:\Users\Andrew
Process Start Time     : 9/10/2024 10:10:13 AM
    ║ Chocolatey v2.2.2
    ║ 3 validations performed. 2 success(es), 1 warning(s), and 0 error(s).
    ║ Validation Warnings:
    ║  - System Cache directory is not locked down to administrators.
    ║    Remove the directory 'C:\ProgramData\ChocolateyHttpCache' to have
    ║    Chocolatey CLI create it with the proper permissions.
    ║ adb
    ║ By installing, you accept licenses for the packages.
    ║ adb v35.0.2 [Approved]
    ║ adb package files install completed. Performing other installation steps.
    ║ File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
    ║ Hashes match.
    ║ Hashes match.
    ║ Extracting C:\Users\Andrew\AppData\Local\Temp\chocolatey\adb\35.0.2\platform-tools_r35.0.2-win.zip to C:\ProgramData\chocolatey\lib\adb\tools...
    ║ C:\ProgramData\chocolatey\lib\adb\tools
    ║  ShimGen has successfully created a shim for adb.exe
    ║  ShimGen has successfully created a shim for fastboot.exe
    ║  The install of adb was successful.
    ║   Software installed to 'C:\ProgramData\chocolatey\lib\adb\tools'
    ║ Chocolatey installed 1/1 packages. 
    ║  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Process Exit Code      : 0
Process End Time       : 9/10/2024 10:10:22 AM
```

**Comment by marticliment** [comment]
Huh, they should be. I will investigate this

**Comment by 0ibaba** [comment]
Can confirm, winget installs are fine, but if I install anything through choco it's not added to the path.
