### ISSUE TITLE
[BUG] i deleted unnecessary translations. app doesnt start.

### ISSUE THREAD

**Issue by blackholeearth** [marticliment/UniGetUI#2734]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

win 10 

### Describe your issue

i deleted unnecessary translations.  kept en-* files

app doesnt start.

Expected:
i think, it shound not throw error. for unused translations.

only throw error if the "Currently in use Translation" is missing

### Steps to reproduce the issue

1 open uniget , select ui lang as english. close uniget.
2 go to exe's folder.
3 delete all translations 
4 keep only  en-*  folders

5 run uniget.
6 you will see web browser and this error.

### UniGetUI Log

```text
OS: Win32NT
                   Version: Microsoft Windows NT 10.0.17763.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.1.1
                Executable: C:\Program Files\UniGetUI\UniGetUI.exe

Crash Message: Bu hata koduyla ilişkili metin bulunamadı.

Failed to assign to property 'UniGetUI.Interface.Widgets.TranslatedTextBlock.Text'. [Line: 0 Position: 0]

Crash Traceback:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at UniGetUI.Interface.MainWindow.InitializeComponent() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\obj\x64\Release\net8.0-windows10.0.19041.0\win-x64\Interface\MainWindow.g.i.cs:line 69
   at UniGetUI.Interface.MainWindow..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Interface\MainWindow.xaml.cs:line 85
   at UniGetUI.MainApp.InitializeMainWindow() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 167
   at UniGetUI.MainApp..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 71
```

### Package Managers Logs

```text
cant open uniget
```

**Comment by marticliment** [comment]
Even when they seem _unnecessary_, they are not. Why would you want to delete them?

**Comment by blackholeearth** [comment]
i generally delete those  in my projects.

**Comment by marticliment** [comment]
They just take less than the 1% of the total app disk usage, there is no need to delete them
