### ISSUE TITLE
[BUG] (Enter your description here) I am trying to uninstall Microsoft Store and Xbox, It wont let me uninstall them

### ISSUE THREAD

**Issue by Aloafofbread071** [marticliment/UniGetUI#2746]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 10 Home x64

### Describe your issue

Whenever i try to unistall Windows Store or Xbox I get a Uninstall Failed Message and the Command-Line Output is .
Starting package uninstall operation for package id=MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  uninstall --id "MSIX\Microsoft.GamingApp_2409.1001.5.0_x6…" --exact --accept-source-agreements --version "2409.1001.5.0" --silent --disable-interactivity 
Working Directory      : C:\Users\5monk
Process Start Time     : 9/16/2024 2:24:33 PM
Process Exit Code      : 15612
Process End Time       : 9/16/2024 2:24:33 PM

This line is for Xbox.

### Steps to reproduce the issue

Installed UniGetUI and tried to uninstall Microsoft Store and Xbox

### UniGetUI Log

```text
[9/16/2024 1:38:02 PM]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.1
[9/16/2024 1:38:02 PM]
[9/16/2024 1:38:02 PM] Version Code:  3.11
[9/16/2024 1:38:02 PM] Encoding Code Page set to 437
[9/16/2024 1:38:03 PM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[9/16/2024 1:38:04 PM] Loaded language locale: en
[9/16/2024 1:38:04 PM] Randomly-generated background API auth token for the current session: 0i51a75dppafzpuikkrturmbqee9ko24qpqrreil7e5gvqc8k5cqh39e41njmnwf
[9/16/2024 1:38:05 PM] Api running on http://localhost:7058
[9/16/2024 1:38:05 PM] Lang files were updated successfully from GitHub
[9/16/2024 1:38:05 PM] UniGetUI is up to date
[9/16/2024 1:38:06 PM] Downloaded new icons and screenshots successfully!
[9/16/2024 1:38:06 PM] Command npm was not found on the system
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:06 PM] Command pwsh.exe was not found on the system
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pip
                       █ Executable path: C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:06 PM] Command scoop was not found on the system
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:06 PM] Running elevated, WinGet class registration is likely to fail
[9/16/2024 1:38:06 PM] Cannot create native WinGet instance due to error: Class not registered

[9/16/2024 1:38:06 PM] System.Runtime.InteropServices.COMException (0x80040154): Class not registered
                       
                          at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
                          at WindowsPackageManager.Interop.WindowsPackageManagerStandardFactory.CreateInstance[T](Guid clsid, Guid iid) in C:\SomePrograms\WingetUI-Store\src\WindowsPackageManager.Interop\WindowsPackageManager\WindowsPackageManagerStandardFactory.cs:line 23
                          at WindowsPackageManager.Interop.WindowsPackageManagerFactory.CreateInstance[T]() in C:\SomePrograms\WingetUI-Store\src\WindowsPackageManager.Interop\WindowsPackageManager\WindowsPackageManagerFactory.cs:line 55
                          at WindowsPackageManager.Interop.WindowsPackageManagerFactory.CreatePackageManager() in C:\SomePrograms\WingetUI-Store\src\WindowsPackageManager.Interop\WindowsPackageManager\WindowsPackageManagerFactory.cs:line 32
                          at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 33
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<>c.<LoadManager>b__36_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 393
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                       --- End of stack trace from previous location ---
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 393
[9/16/2024 1:38:06 PM] WinGet will resort to using BundledWinGetHelper()
[9/16/2024 1:38:06 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: 
                       █   Microsoft.WinGet.Client PSModule version: ""
                       █   Using bundled WinGet helper (CLI parsing)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:08 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.19041.4894                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.19041.4894                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:09 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: choco.exe
                       █ Executable path: C:\Users\5monk\AppData\Local\UniGetUI\Chocolatey\choco.exe
                       █ Call arguments: 
                       █ Version: 
                       █   2.2.2
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/16/2024 1:38:10 PM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[9/16/2024 1:38:10 PM] Dependency WinGet PowerShell Module for manager Winget is present
[9/16/2024 1:38:10 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[9/16/2024 1:38:10 PM] Found 0 available updates from Pip
[9/16/2024 1:38:10 PM] Found 0 installed packages from Pip
[9/16/2024 1:38:10 PM] WinGet installed packages returned zero packages, attempting legacy...
[9/16/2024 1:38:11 PM] WinGet updates returned zero packages, attempting legacy...
[9/16/2024 1:38:12 PM] Found 0 installed packages from PowerShell
[9/16/2024 1:38:12 PM] Found 0 available updates from Chocolatey
[9/16/2024 1:38:12 PM] Found 0 available updates from PowerShell
[9/16/2024 1:38:12 PM] Found 0 installed packages from Chocolatey
[9/16/2024 1:38:13 PM] Found 240 installed packages from Winget
[9/16/2024 1:38:13 PM] Found 19 available updates from Winget
[9/16/2024 1:38:14 PM] Found 0 installed packages from Pip
[9/16/2024 1:38:15 PM] WinGet installed packages returned zero packages, attempting legacy...
[9/16/2024 1:38:16 PM] Found 0 installed packages from Chocolatey
[9/16/2024 1:38:16 PM] Found 0 installed packages from PowerShell
[9/16/2024 1:38:17 PM] Found 240 installed packages from Winget
[9/16/2024 1:38:45 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:38:45 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 1:39:22 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:39:22 PM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Discord.Discord
[9/16/2024 1:39:22 PM] Icon for package Discord.Discord stored on C:\Users\5monk\AppData\Local\UniGetUI\CachedMedia\Winget\Discord.Discord.png
[9/16/2024 1:43:26 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:43:26 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 1:47:18 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:47:18 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 1:47:40 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:47:40 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 1:47:40 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 1:47:40 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 2:20:47 PM] Found 0 installed packages from Pip
[9/16/2024 2:20:48 PM] WinGet installed packages returned zero packages, attempting legacy...
[9/16/2024 2:20:49 PM] Found 0 installed packages from Chocolatey
[9/16/2024 2:20:49 PM] Found 0 installed packages from PowerShell
[9/16/2024 2:20:50 PM] Found 240 installed packages from Winget
[9/16/2024 2:23:32 PM] Uninstall
[9/16/2024 2:23:32 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 2:23:32 PM] Icon for package MSIX\Microsoft.WindowsStore_22407.1401.5.… was not found, returning default icon
[9/16/2024 2:23:32 PM] Found 0 screenshots for package Id=MSIX\Microsoft.WindowsStore_22407.1401.5.…
[9/16/2024 2:23:33 PM] Loaded details for package MSIX\Microsoft.WindowsStore_22407.1401.5.… on manager Winget
[9/16/2024 2:24:16 PM] Uninstall
[9/16/2024 2:24:16 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 2:24:16 PM] Icon for package MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… was not found, returning default icon
[9/16/2024 2:24:16 PM] Found 0 screenshots for package Id=MSIX\Microsoft.GamingApp_2409.1001.5.0_x6…
[9/16/2024 2:24:17 PM] Loaded details for package MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… on manager Winget
[9/16/2024 2:24:33 PM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[9/16/2024 2:24:33 PM] Icon for package MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… was not found, returning default icon
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: 
Microsoft.WinGet.Client PSModule version: ""
Using bundled WinGet helper (CLI parsing)

——————————————————————————————————————————


Logged subprocess-based task on manager Winget. Task type is FindPackages
Subprocess executable: "C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source list"
Process start time: 9/16/2024 1:38:06 PM
Process end time:   9/16/2024 1:38:06 PM

Return code: FAILED (15612)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 9/16/2024 1:38:09 PM
Process end time:   9/16/2024 1:38:10 PM

Return code: FAILED (15612)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "cmd.exe"
Command-line arguments: "/C C:\Windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 9/16/2024 1:38:09 PM
Process end time:   9/16/2024 1:38:10 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Import-Module : The specified module 'Microsoft.WinGet.Client' was not loaded because no valid module file was found 
  in any module directory.
  At line:1 char:1
  + Import-Module Microsoft.WinGet.Client
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet.Client:String) [Import-Module], FileNotFoundExcep 
     tion
      + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is FindPackages
Subprocess executable: "C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source list"
Process start time: 9/16/2024 1:38:10 PM
Process end time:   9/16/2024 1:38:10 PM

Return code: FAILED (15612)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "cmd.exe"
Command-line arguments: "/C C:\Windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 9/16/2024 1:38:10 PM
Process end time:   9/16/2024 1:38:11 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Import-Module : The specified module 'Microsoft.WinGet.Client' was not loaded because no valid module file was found 
  in any module directory.
  At line:1 char:1
  + Import-Module Microsoft.WinGet.Client
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet.Client:String) [Import-Module], FileNotFoundExcep 
     tion
      + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " list  --accept-source-agreements"
Process start time: 9/16/2024 1:38:10 PM
Process end time:   9/16/2024 1:38:13 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " update --include-unknown  --accept-source-agreements"
Process start time: 9/16/2024 1:38:11 PM
Process end time:   9/16/2024 1:38:13 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "cmd.exe"
Command-line arguments: "/C C:\Windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 9/16/2024 1:38:14 PM
Process end time:   9/16/2024 1:38:15 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Import-Module : The specified module 'Microsoft.WinGet.Client' was not loaded because no valid module file was found 
  in any module directory.
  At line:1 char:1
  + Import-Module Microsoft.WinGet.Client
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet.Client:String) [Import-Module], FileNotFoundExcep 
     tion
      + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " list  --accept-source-agreements"
Process start time: 9/16/2024 1:38:15 PM
Process end time:   9/16/2024 1:38:17 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is LoadPackageVersions
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " show --id MSIX\Microsoft.WindowsStore_22407.1401.5.… --exact --versions --accept-source-agreements"
Process start time: 9/16/2024 1:47:10 PM
Process end time:   9/16/2024 1:47:11 PM

-- Process STDOUT
 ...

Return code: FAILED (-1978335212)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "cmd.exe"
Command-line arguments: "/C C:\Windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 9/16/2024 2:20:47 PM
Process end time:   9/16/2024 2:20:48 PM

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Import-Module : The specified module 'Microsoft.WinGet.Client' was not loaded because no valid module file was found 
  in any module directory.
  At line:1 char:1
  + Import-Module Microsoft.WinGet.Client
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet.Client:String) [Import-Module], FileNotFoundExcep 
     tion
      + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
   
  Get-WinGetPackage : The term 'Get-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + Get-WinGetPackage | Print-WinGetPackage
  + ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Get-WinGetPackage:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " list  --accept-source-agreements"
Process start time: 9/16/2024 2:20:48 PM
Process end time:   9/16/2024 2:20:50 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is LoadPackageVersions
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " show --id MSIX\Microsoft.WindowsStore_22407.1401.5.… --exact --versions --accept-source-agreements"
Process start time: 9/16/2024 2:23:32 PM
Process end time:   9/16/2024 2:23:33 PM

-- Process STDOUT
 ...

Return code: FAILED (-1978335212)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is LoadPackageVersions
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " show --id MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… --exact --versions --accept-source-agreements"
Process start time: 9/16/2024 2:24:16 PM
Process end time:   9/16/2024 2:24:17 PM

-- Process STDOUT
 ...

Return code: FAILED (-1978335212)

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Are you running UniGetUI elevated?

**Comment by Aloafofbread071** [comment]
Im not sure but i dont think so i just downloaded this to try to fix another problem on my computer so im new to this whole app

**Comment by marticliment** [comment]
Please try to: 
1. Install this beta release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta2
2. Go to `UniGetUI Settings` -> `WinGet` -> enable `Allow using class registered with lower trust`

Your issue will be fixed

**Comment by Aloafofbread071** [comment]
I followed the steps and still am getting the error message
Starting package uninstall operation for package id=MSIX\Microsoft.GamingApp_2409.1001.5.0_x6… with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=True;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\5monk\AppData\Local\Microsoft\WindowsApps\winget.exe"  uninstall --id "MSIX\Microsoft.GamingApp_2409.1001.5.0_x6…" --exact --source winget --accept-source-agreements --disable-interactivity --version 2409.1001.5.0 --interactive 
Working Directory      : C:\Users\5monk
Process Start Time     : 9/17/2024 1:42:51 PM
Process Exit Code      : 15612
Process End Time       : 9/17/2024 1:42:52 PM

**Comment by marticliment** [comment]
You need to restart UniGetUI after enabling that setting

**Comment by Aloafofbread071** [comment]
I have restarted my pc since installing the beta and it still wont let me update or uninstall anything

**Comment by marticliment** [comment]
I will
