### ISSUE TITLE
[BUG] UniGetUI shows only outdated packages in Chocolatey

### ISSUE THREAD

**Issue by SilverGreen93** [marticliment/UniGetUI#2755]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 23H2

### Describe your issue

If I search for a package that I know is present in Chocolatey with WingetUI, I get only an older version in the search results (3.4.1). The version is currently available in chocolatey online and by using the command line choco tool is a lot newer (3.7.7).

Here is what UniGetUI finds when I search for Files in the Chocolatey repository = 3.4.1:
![image](https://github.com/user-attachments/assets/06b6044c-af4e-493f-90e6-18abfb16b180)

Here is the version available on the online page = 3.7.7: https://community.chocolatey.org/packages/files#upgrade

Here is the version I installed manually from Command Line = 3.7.7:
![image](https://github.com/user-attachments/assets/409b3904-161c-4150-8943-322c83ebabc2)

So my question is how come that choco CLI finds the newest version, 3.7.7, but UniGetUI only shows the very outdated version, 3.4.1?

### UniGetUI Log

```text
[19.09.2024 12:07:49]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[19.09.2024 12:07:49]
[19.09.2024 12:07:49] Version Code:  3,11
[19.09.2024 12:07:49] Encoding Code Page set to 866
[19.09.2024 12:07:50] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[19.09.2024 12:07:50] Loaded language locale: ro
[19.09.2024 12:07:51] Randomly-generated background API auth token for the current session: cmcs6op9rslanhbm0bjwnu4480hetbhku0m77xrzjs703f6w9hkif1lurlj7z7jv
[19.09.2024 12:07:51] Api running on http://localhost:7058
[19.09.2024 12:07:51] Lang files were updated successfully from GitHub
[19.09.2024 12:07:51] UniGetUI is up to date
[19.09.2024 12:07:52] Downloaded new icons and screenshots successfully!
[19.09.2024 12:07:52] Command npm was not found on the system
[19.09.2024 12:07:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:52] Command scoop was not found on the system
[19.09.2024 12:07:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.400
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Program Files\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Users\Mihai\AppData\Roaming\Python\Python312\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Mihai\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:54] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Mihai\AppData\Local\UniGetUI\Chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:54] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4111                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4111                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:55] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Users\Mihai\AppData\Local\Microsoft\WindowsApps\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.5
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.09.2024 12:07:57] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[19.09.2024 12:07:57] Dependency WinGet PowerShell Module for manager Winget is present
[19.09.2024 12:07:59] Dependency .NET Tools Outdated for manager .NET Tool is present
[19.09.2024 12:07:59] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[19.09.2024 12:08:02] Found 0 available updates from .NET Tool
[19.09.2024 12:08:03] Found 50 installed packages from Pip
[19.09.2024 12:08:03] Found 0 available updates from Chocolatey
[19.09.2024 12:08:03] Found 1 installed packages from Chocolatey
[19.09.2024 12:08:03] Found 1 installed packages from .NET Tool
[19.09.2024 12:08:03] Found 1 installed packages from PowerShell
[19.09.2024 12:08:03] Found 0 installed packages from PowerShell7
[19.09.2024 12:08:03] Found 0 available updates from PowerShell7
[19.09.2024 12:08:03] Found 0 available updates from PowerShell
[19.09.2024 12:08:03] Found 341 installed packages from Winget
[19.09.2024 12:08:05] Found 0 available updates from Pip
[19.09.2024 12:08:05] Found 3 available updates from Winget
[19.09.2024 12:08:07] Command parse_pip_search.exe was not found on the system
[19.09.2024 12:08:08] Found 46 available packages from Winget with the query files
[19.09.2024 12:08:08] Found 100 available packages from .NET Tool with the query files
[19.09.2024 12:08:08] Found 1 available packages from Chocolatey with the query files
[19.09.2024 12:08:09] Error finding packages on manager Pip with query files
[19.09.2024 12:08:09] System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\WingetUI'. The system cannot find the file specified.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 97
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 163
[19.09.2024 12:08:10] Found 13 available packages from PowerShell with the query files
[19.09.2024 12:08:11] Found 13 available packages from PowerShell7 with the query files
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 19.09.2024 12:07:53
Process end time:   19.09.2024 12:07:53

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Mihai\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 19.09.2024 12:07:55
Process end time:   19.09.2024 12:08:00

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 19.09.2024 12:07:55
Process end time:   19.09.2024 12:08:03

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 19.09.2024 12:07:56
Process end time:   19.09.2024 12:07:57

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 19.09.2024 12:08:02
Process end time:   19.09.2024 12:08:05

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 19.09.2024 12:08:07
Process end time:   19.09.2024 12:08:08

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
What happens when you run `C:\Users\Mihai\AppData\Local\UniGetUI\Chocolatey\bin\choco.exe list`?

Could it be that you have updated the package recently?

**Comment by SilverGreen93** [comment]
I have not updated the package, but just installed it fresh.
I get the same output if I run both choco list and the one with the full path:

```
C:\Windows\System32>C:\Users\Mihai\AppData\Local\UniGetUI\Chocolatey\bin\choco.exe list
Chocolatey v2.2.2
files 3.7.7
1 packages installed.

C:\Windows\System32>choco list
Chocolatey v2.2.2
files 3.7.7
1 packages installed.
```

**Comment by marticliment** [comment]
Huh, this is weird. I will investigate

**Comment by MartinM01** [comment]
Same problem, and when you click on “Install”, the latest version is installed, but it shows that the old version is installed.

**Comment by fuzelet** [comment]
i would like to add that i am also seeing this issue as well.  example for me is the nvidia-display-driver package.  Uniget is showing an older version when chocolatey is already publishing a new version.

![Screenshot 2024-10-02 151639](https://github.com/user-attachments/assets/8f6c06cd-2738-422a-9192-7800cb369c9e)
![Screenshot 2024-10-02 151622](https://github.com/user-attachments/assets/0ef7c0ef-4725-4afe-b21f-0992a6a01373)
![Screenshot 2024-10-02 151612](https://github.com/user-attachments/assets/f76d4751-65b2-4066-bee0-c55ddef36e9e)

**Comment by fuzelet** [comment]
> @fuzelet, I can see the package was published very recently. Have you restarted UniGetUI after the package has been updated?

I did not restart, but this package was published on 10/1 and my computer was turned off overnight(last night) and was turned on this morning, 10/2/24.

**Comment by fuzelet** [comment]
I just had the same issue on another machine. I restarted the machine as well as restarting uniget after seeing the older version still for the Nvidia display driver
![PXL_20241002_210734097 MP](https://github.com/user-attachments/assets/fde3ba54-2db9-41b1-911b-2060304c0aee)

**Comment by emdm00** [comment]
Other example is Ventoy in my case. Because it exists the version 1.0.99 on chocolatey but UnigetUI shows the version 1.0.98. I installed UnigetUI two days ago so it had to be already updated.

**Comment by riedel** [comment]
Stumbled over the same bug for https://marticliment.com/unigetui/share?name=KopiaUI&id=KopiaUI&sourceName=community&managerName=Chocolatey

I was guessing that the sorting is wrong and 0.9.8 (which is shown) is larger than 0.17.0 ( see https://community.chocolatey.org/packages/KopiaUI, current version at time of writing, although I have pushed 0.18.0 just now )

**Comment by 101101100** [comment]
I have the same issue with several SW packages - in my case only with packages which are also available via chocolatey, but did not check other repositories.

Example:
ExifTool (installed via chocolatey) is version 12.98.0 (2024-10-08), Chocolatey GUI suggests to update to 13.3.0 .  Package details point to sourceforge.net .
UniGetUI does not list ExifTool as an installed SW. With the discover function, it suggests 12.87.0 from "chocolatey community, updated:  2024-08-25T04:37:40Z".

Thanks for fixing this one day! UniGetUI is nevertheless already a great helper.

**Comment by riedel** [comment]
Another related problem is that chocolatey package versions are sometimes not parsed. I have `diskgenius 5.6.1.1580` installed via chocolatey. It shows as unknown with a new version `5.6.1` with a winget update. Same with `bluescreenview 1.55.0` .

**Comment by riedel** [comment]
BTW: maybe relying on an external API like repology (suggested in #3015) might help to get things more consistent between multiple package managers.
