### ISSUE TITLE
[BUG] WinGet install commands always sets the version number even when latest is selected

### ISSUE THREAD

**Issue by adrianhalid** [marticliment/UniGetUI#2758]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2-beta2

### Windows version, edition, and architecture

Windows 11 Pro 22631.4169 x64

### Describe your issue

When loading an old bundle, many packages will reference an old application version.
The package installer options will have "Latest" as the version selected for installation.
However, when you run the package installer, it will always include the old version to install, as described in the bundle JSON file.

I would expect it not to include the --version parameter when executing winget.exe.

### Steps to reproduce the issue

1. Use this as the bundle.

[test.ubundle.json](https://github.com/user-attachments/files/17068112/test.ubundle.json)

2. Review the Installation Options
![image](https://github.com/user-attachments/assets/c6b96aa8-686d-4d67-bedd-7ea5d80c63f9)

3. Select the Google Chrome Package and click install selection.

4. Installation Failed as it specified the version defined in the package version header and didn't use the empty string version defined in the "InstallationOptions" section.

You get the following error.

Starting package install operation for package id=Google.Chrome with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\admin\AppData\Local\Microsoft\WindowsApps\winget.exe"  install --id "Google.Chrome" --exact --source winget --accept-source-agreements --disable-interactivity --version 127.0.6533.100 --silent  --accept-package-agreements --force
Working Directory      : C:\Users\admin
Process Start Time     : 20/09/2024 10:17:38 AM
-
No version found matching: 127.0.6533.100
Process Exit Code      : -1978335209
Process End Time       : 20/09/2024 10:17:38 AM

5. I would expect the command to perform the install would not use the --version tag as it should be the latest installed.

### UniGetUI Log

```text
[20/09/2024 10:15:46 AM]    __  __      _ ______     __  __  ______
                           / / / /___  (_) ____/__  / /_/ / / /  _/
                          / / / / __ \/ / / __/ _ \/ __/ / / // /
                         / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                         \____/_/ /_/_/\____/\___/\__/\____/___/
                             Welcome to UniGetUI Version 3.1.2-beta2
[20/09/2024 10:15:46 AM]
[20/09/2024 10:15:46 AM] Version Code:  3.1192
[20/09/2024 10:15:46 AM] Encoding Code Page set to 437
[20/09/2024 10:15:46 AM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[20/09/2024 10:15:46 AM] Loaded language locale: en
[20/09/2024 10:15:47 AM] Randomly-generated background API auth token for the current session: n4uhyk6tfyseksewxhxlja47difli61qebmckjxl77ye56llcx3ipg33anenutmq
[20/09/2024 10:15:47 AM] Api running on http://localhost:7058
[20/09/2024 10:15:47 AM] Lang files were updated successfully from GitHub
[20/09/2024 10:15:48 AM] Command npm was not found on the system
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Npm
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] Downloaded new icons and screenshots successfully!
[20/09/2024 10:15:48 AM] Command dotnet.exe was not found on the system
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: .NET Tool
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] Command cargo was not found on the system
[20/09/2024 10:15:48 AM] Could not initialize Package Manager Cargo
[20/09/2024 10:15:48 AM] System.InvalidOperationException: Cannot start process because a file name has not been provided.
                            at System.Diagnostics.Process.Start()
                            at UniGetUI.PackageEngine.Managers.CargoManager.Cargo.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Cargo\Cargo.cs:line 131
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 88
[20/09/2024 10:15:48 AM] Command pwsh.exe was not found on the system
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell7
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] UniGetUI is up to date
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] Command scoop was not found on the system
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Scoop
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Pip
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:48 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Chocolatey
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:49 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Winget
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: winget.exe
                         █ Executable path: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\winget.exe
                         █ Call arguments: 
                         █ Version: 
                         █   System WinGet CLI Version: v1.8.1911
                         █   Microsoft.WinGet.Client PSModule version: ""
                         █   Using Native WinGet helper (COM Api)
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[20/09/2024 10:15:49 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[20/09/2024 10:15:49 AM] Resetting administrator rights cache for process id 6584
[20/09/2024 10:15:49 AM] Begin attempt to open the package bundle C:\Users\admin\OneDrive\Documents\UniGetUI_Bundles\test.ubundle
[20/09/2024 10:15:50 AM] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[20/09/2024 10:15:50 AM] Dependency WinGet PowerShell Module for manager Winget is present
[20/09/2024 10:15:51 AM] Found 95 installed packages from Winget
[20/09/2024 10:15:51 AM] Found 4 available updates from Winget
[20/09/2024 10:16:00 AM] Registering package Google.Chrome from manager Winget: winget
[20/09/2024 10:16:00 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[20/09/2024 10:16:00 AM] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Google.Chrome
[20/09/2024 10:16:00 AM] Icon for package Google.Chrome stored on C:\Users\admin\AppData\Local\UniGetUI\CachedMedia\Winget\Google.Chrome.png
[20/09/2024 10:16:00 AM] Loaded operation parameters for package id=Google.Chrome on manager Winget and operation Install: install --id "Google.Chrome" --exact --source winget --accept-source-agreements --disable-interactivity --version 127.0.6533.100 --silent  --accept-package-agreements --force
[20/09/2024 10:16:00 AM] Caching admin rights for process id 6584
[20/09/2024 10:16:06 AM] Resetting administrator rights cache for process id 6584
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 20/09/2024 10:15:49 AM
Process end time:   20/09/2024 10:15:49 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\admin\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 20/09/2024 10:15:49 AM
Process end time:   20/09/2024 10:15:50 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 20/09/2024 10:15:49 AM
Process end time:   20/09/2024 10:15:51 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 20/09/2024 10:15:49 AM
Process end time:   20/09/2024 10:15:50 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 20/09/2024 10:15:50 AM
Process end time:   20/09/2024 10:15:51 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by auanasgheps** [comment]
Hi, adding a comment here because I've found an issue that is potentially linked to this one.

Whilst I am facing this exact issue reinstalling a Package Bundle in a test VM, i am also facing the following:

UnigetUI is unable to reinstall any msstore from a Package Bundle because it is attempting to install a specific version, but msstore does not provide ANY version at all.

Example extracted from the output:

This is Power Toys
```
winget.exe
Process Call Arguments :  install --id "XP89DCGQ3K6VLD" --exact --source msstore --accept-source-agreements --version "0.84.1" --silent --disable-interactivity --accept-package-agreements
```

Please let me know if you need a separate issue for this.
