### ISSUE TITLE
[BUG] Upgrade of Calibre failed

### ISSUE THREAD

**Issue by Xembalo** [marticliment/UniGetUI#2771]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 22635.4225

### Describe your issue

Upgrade of Calibre failed every time with Unigetui (installed 7.17.0, available 7.18.0)

Log says:

```
Starting package update operation for package id=calibre.calibre with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=Local;InstallationScope=C:\Program Files\Calibre2;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\socia\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  update --id "calibre.calibre" --exact --source winget --accept-source-agreements --scope user --silent --disable-interactivity  --accept-package-agreements --location "C:\Program Files\Calibre2" --force --include-unknown
Working Directory      : C:\Users\socia
    |    | 
    | Es wurde kein installiertes Paket gefunden, das den Eingabekriterien entspricht.
Process Exit Code      : -1978335212
Process End Time       : 23.09.2024 19:10:25
```

But by using simple cmd everything works fine

```
C:\Users\socia>winget upgrade calibre
Gefunden calibre [calibre.calibre] Version 7.18.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://download.calibre-ebook.com/7.18.0/calibre-64bit-7.18.0.msi
  ██████████████████████████████   202 MB /  202 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert
```

### UniGetUI Log

```text
[23.09.2024 19:10:10]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[23.09.2024 19:10:10]
[23.09.2024 19:10:10] Version Code:  3,11
[23.09.2024 19:10:11] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[23.09.2024 19:10:11] Encoding Code Page set to 0
[23.09.2024 19:10:11] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[23.09.2024 19:10:11] Loaded language locale: de
[23.09.2024 19:10:11] Randomly-generated background API auth token for the current session: 8irr5c636e9bkq10t0bkcxlytjkfigp0ela234i92zi0lbsbxbzfxu85n38y2vgi
[23.09.2024 19:10:12] Api running on http://localhost:7058
[23.09.2024 19:10:12] Lang files were updated successfully from GitHub
[23.09.2024 19:10:12] UniGetUI is up to date
[23.09.2024 19:10:12] Downloaded new icons and screenshots successfully!
[23.09.2024 19:10:12] Command npm was not found on the system
[23.09.2024 19:10:12] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:12] Command pwsh.exe was not found on the system
[23.09.2024 19:10:12] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:12] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\socia\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:15] Command scoop was not found on the system
[23.09.2024 19:10:15] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23.09.2024 19:10:16] Resetting administrator rights cache for process id 17644
[23.09.2024 19:10:16] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[23.09.2024 19:10:16] Dependency WinGet PowerShell Module for manager Winget is present
[23.09.2024 19:10:16] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[23.09.2024 19:10:23] Found 1 available updates from Winget
[23.09.2024 19:10:23] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[23.09.2024 19:10:23] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=calibre.calibre
[23.09.2024 19:10:23] Icon for package calibre.calibre stored on C:\Users\socia\AppData\Local\UniGetUI\CachedMedia\Winget\calibre.calibre.png
[23.09.2024 19:10:23] Found 235 installed packages from Winget
[23.09.2024 19:13:58] Found 235 installed packages from Winget
[23.09.2024 19:14:13] Resetting administrator rights cache for process id 17644
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 23.09.2024 19:10:14
Process end time:   23.09.2024 19:10:14

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\socia\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 23.09.2024 19:10:15
Process end time:   23.09.2024 19:10:19

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23.09.2024 19:10:15
Process end time:   23.09.2024 19:10:23

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 23.09.2024 19:10:16
Process end time:   23.09.2024 19:10:16

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 23.09.2024 19:10:19
Process end time:   23.09.2024 19:10:23

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23.09.2024 19:13:54
Process end time:   23.09.2024 19:13:58

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Running `C:\Users\socia\AppData\Local\Microsoft\WindowsApps\winget.exe update --id "calibre.calibre" --exact --source winget --accept-source-agreements --scope user --silent --disable-interactivity  --accept-package-agreements --location "C:\Program Files\Calibre2" --force --include-unknown` on a command prompt does work?

**Comment by Xembalo** [comment]
it worked after removing `--scope user` from command

in unigetui I do not find the place, where I set User Scope. In Package Details, "Default" is set:
![grafik](https://github.com/user-attachments/assets/4f649585-910b-4123-8144-e6455b3e4615)

In general preferences, I do not find this setting eigther

Shouldn't Unigetui recognize whether a package is installed in the system (%programfiles%) or in the user scope (%appdata%)?

Thanks a lot!

**Comment by marticliment** [comment]
It should, but somehow the package's installation settings say `InstallationScope=Local;`, which is weird. I will investigate this issue

**Comment by Xembalo** [comment]
Any updates on this case?

**Comment by skyerjoe** [comment]
any updates so far ? i get the same one the gnu privacy guard package 

regards
