### ISSUE TITLE
[BUG] PowerShell7 was not found!

### ISSUE THREAD

**Issue by UdaySriHarsha** [marticliment/UniGetUI#2774]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 10.0.22631.4169 x64

### Describe your issue

While trying to manage settings for PowerShell 7.x it says `PowerShell7 was not found! You may need to install PowerShell7 in order to use it with UniGetUI`

While i have PowerShell 7.5.0-preview.4 installed

### Steps to reproduce the issue

Open UniGetUI > Settings > Scroll down to `Package Managers` > Scroll down in that section to `PowerShell 7.x (beta)` > Open the drop down to notice the error at the bottom.

### UniGetUI Log

```text
[24/09/2024 6:47:50 am]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.1
[24/09/2024 6:47:50 am]
[24/09/2024 6:47:50 am] Version Code:  3.11
[24/09/2024 6:47:50 am] Encoding Code Page set to 850
[24/09/2024 6:47:50 am] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[24/09/2024 6:47:51 am] Loaded language locale: en
[24/09/2024 6:47:51 am] Randomly-generated background API auth token for the current session: fjjcei0qwlhnslhco19wn7epw7ri65lb8sbxchyf3evkphj2zh076i2wbgf48nu9
[24/09/2024 6:47:51 am] Api running on http://localhost:7058
[24/09/2024 6:47:51 am] Lang files were updated successfully from GitHub
[24/09/2024 6:47:51 am] Command dotnet.exe was not found on the system
[24/09/2024 6:47:51 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:51 am] Command pwsh.exe was not found on the system
[24/09/2024 6:47:51 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell7
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:51 am] Downloaded new icons and screenshots successfully!
[24/09/2024 6:47:52 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pip
                        █ Executable path: C:\Users\IntNinja\AppData\Local\Programs\Python\Python312\python.exe
                        █ Call arguments:  -m pip
                        █ Version: 
                        █   pip 24.2 from C:\Users\IntNinja\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:52 am] UniGetUI is up to date
[24/09/2024 6:47:54 am] Running elevated, WinGet class registration is likely to fail
[24/09/2024 6:47:54 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: winget.exe
                        █ Executable path: C:\Users\IntNinja\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   System WinGet CLI Version: v1.8.1911
                        █   Microsoft.WinGet.Client PSModule version: ""
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:55 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: npm
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                        █ Version: 
                        █   10.8.3
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:56 am] Command scoop was not found on the system
[24/09/2024 6:47:56 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:57 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: choco.exe
                        █ Executable path: C:\Users\IntNinja\AppData\Local\UniGetUI\Chocolatey\choco.exe
                        █ Call arguments: 
                        █ Version: 
                        █   2.2.2
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:58 am] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: powershell.exe
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.22621.4111                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.22621.4111                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[24/09/2024 6:47:58 am] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[24/09/2024 6:47:58 am] Dependency WinGet PowerShell Module for manager Winget is present
[24/09/2024 6:47:58 am] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[24/09/2024 6:47:59 am] Found 21 installed packages from Pip
[24/09/2024 6:48:01 am] Found 0 available updates from Winget
[24/09/2024 6:48:01 am] Found 96 installed packages from Winget
[24/09/2024 6:48:03 am] Found 0 available updates from Pip
[24/09/2024 6:48:04 am] Found 0 installed packages from Chocolatey
[24/09/2024 6:48:04 am] Found 0 installed packages from PowerShell
[24/09/2024 6:48:04 am] Found 0 available updates from Chocolatey
[24/09/2024 6:48:04 am] Found 0 available updates from PowerShell
[24/09/2024 6:48:05 am] Found 0 installed packages from Npm
[24/09/2024 6:48:05 am] Found 0 available updates from Npm
[24/09/2024 6:48:18 am] Operation crashed:
[24/09/2024 6:48:18 am] System.InvalidOperationException: Cannot start process because a file name has not been provided.
                           at System.Diagnostics.Process.Start()
                           at UniGetUI.PackageEngine.Operations.AbstractOperation.MainThread() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\PackageEngine\Operations\OperationControl.xaml.cs:line 433
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 24/09/2024 6:47:54 am
Process end time:   24/09/2024 6:47:54 am

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\IntNinja\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 24/09/2024 6:47:58 am
Process end time:   24/09/2024 6:47:59 am

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 24/09/2024 6:47:58 am
Process end time:   24/09/2024 6:48:01 am

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 24/09/2024 6:47:58 am
Process end time:   24/09/2024 6:47:59 am

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 24/09/2024 6:47:59 am
Process end time:   24/09/2024 6:48:01 am

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Relevant information

the relevant command to open PowerShell 5.x is proper
but for PowerShell 7.x it's
 `-NoProfile -Command`

### Screenshots and videos

![UniGetUI_xaLP54CIfw](https://github.com/user-attachments/assets/a1ca041d-a20b-4e55-912f-b0d613353434)

**Comment by marticliment** [comment]
what is the result of running `wjere.exe pwsh.exe` on a command prompt?

**Comment by UdaySriHarsha** [comment]
> what is the result of running `wjere.exe pwsh.exe` on a command prompt?

```
Microsoft Windows [Version 10.0.22631.4247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\IntNinja>where.exe
The syntax of this command is:

WHERE [/R dir] [/Q] [/F] [/T] pattern...

Description:
    Displays the location of files that match the search pattern.
    By default, the search is done along the current directory and
    in the paths specified by the PATH environment variable.

Parameter List:
    /R       Recursively searches and displays the files that match the
             given pattern starting from the specified directory.

    /Q       Returns only the exit code, without displaying the list
             of matched files. (Quiet mode)

    /F       Displays the matched filename in double quotes.

    /T       Displays the file size, last modified date and time for all
             matched files.

    pattern  Specifies the search pattern for the files to match.
             Wildcards * and ? can be used in the pattern. The
             "$env:pattern" and "path:pattern" formats can also be
             specified, where "env" is an environment variable and
             the search is done in the specified paths of the "env"
             environment variable. These formats should not be used
             with /R. The search is also done by appending the
             extensions of the PATHEXT variable to the pattern.

     /?      Displays this help message.

  NOTE: The tool returns an error level of 0 if the search is
        successful, of 1 if the search is unsuccessful and
        of 2 for failures or errors.

Examples:
    WHERE /?
    WHERE myfilename1 myfile????.*
    WHERE $windir:*.*
    WHERE /R c:\windows *.exe *.dll *.bat
    WHERE /Q ??.???
    WHERE "c:\windows;c:\windows\system32:*.dll"
    WHERE /F /T *.dll

C:\Users\IntNinja>pwsh.exe
'pwsh.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\IntNinja>
```

might be just that i installed powershell 7 preview msi, instead of using winget

**Comment by UdaySriHarsha** [comment]
Well solved it by reinstalling powershell 7

**Comment by PhoenixxClaw** [comment]
Hey all, am not sure if I should open a new issue as I am having literally the same error as the Creator of this one.
Powershell 7.4.5 is installed in the default path (C:\Program Files\PowerShell\7) and working fine, yet UniGetUI seems to be unable to find it and reports that it's missing as in the above screenshots.
![{67180A84-7312-4DCC-867C-B56BDBFF98AF}](https://github.com/user-attachments/assets/169929f9-1048-45ea-8908-5facd9f48af4)


PATH variable is set correctly and the above requested `where` command, ran in a cmd prompt, returns the correct path.
![{B5A5F53B-2ED1-43A7-BA2A-E1650C9C5C34}](https://github.com/user-attachments/assets/9816a434-bc2b-424b-bffb-bb21aa41e1a5)


Want me to open a new Issue for that instead?
