### ISSUE TITLE
[BUG] Chocolatey sources requiring authentication are ignored

### ISSUE THREAD

**Issue by johchur** [marticliment/UniGetUI#2778]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 1000.22700.1034.0 x64

### Describe your issue

Chocolatey sources requiring authentication are not shown or used in UniGetUI.

The code at ChocolateySourceProvider.cs#L68 checks the existence of the pattern " - " and " | " in the output of the `choco source list` command. But on my system using chocolatey 2.3.0 (bundled one has the same issue) it is of format
```
>choco source list
Chocolatey v2.3.0
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
nexus - https://nexus.<redacted>/repository/chocolatey-hosted (Authenticated)| Priority 1|Bypass Proxy - False|Self-Service - False|Admin Only - False.
```
Note the missing space between the closing bracket and the pipe. Thus, the second source is not added to the internal list of sources.

### Steps to reproduce the issue

Add a chocolatey source repository requiring authentication.

### UniGetUI Log

```text
[25.09.2024 08:02:55]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[25.09.2024 08:02:55]
[25.09.2024 08:02:55] Version Code:  3,11
[25.09.2024 08:02:55] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[25.09.2024 08:02:55] Encoding Code Page set to 0
[25.09.2024 08:02:56] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[25.09.2024 08:02:56] Loaded language locale: de
[25.09.2024 08:02:57] Randomly-generated background API auth token for the current session: 39jvqqd8608mgv6qa25or5uiii77bzqkynk0uy15xui2u0c3o7heokjvkfqrjv4j
[25.09.2024 08:02:58] Api running on http://localhost:7058
[25.09.2024 08:02:58] Lang files were updated successfully from GitHub
[25.09.2024 08:02:58] UniGetUI is up to date
[25.09.2024 08:03:00] Downloaded new icons and screenshots successfully!
[25.09.2024 08:03:00] Command pwsh.exe was not found on the system
[25.09.2024 08:03:00] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:04] Starting scoop cleanup...
[25.09.2024 08:03:04] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Johannes\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:04] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.8.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                      █   
                      █   'main' bucket:
                      █   54e3992fc winget-ps: Update to version 1.9.2505
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:07] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.3.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:09] Scoop cleanup finished!
[25.09.2024 08:03:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4111                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4111                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.09.2024 08:03:12] Resetting administrator rights cache for process id 16560
[25.09.2024 08:03:12] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[25.09.2024 08:03:12] Dependency WinGet PowerShell Module for manager Winget is present
[25.09.2024 08:03:14] Dependency Scoop-Search for manager Scoop is present
[25.09.2024 08:03:14] Dependency Git for manager Scoop is present
[25.09.2024 08:03:14] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[25.09.2024 08:03:17] Found 3 installed packages from Chocolatey
[25.09.2024 08:03:18] Found 9 installed packages from Scoop
[25.09.2024 08:03:20] Found 0 available updates from Chocolatey
[25.09.2024 08:03:20] Found 1 installed packages from Npm
[25.09.2024 08:03:20] Found 0 available updates from Npm
[25.09.2024 08:03:21] Found 129 installed packages from Winget
[25.09.2024 08:03:22] Found 5 installed packages from PowerShell
[25.09.2024 08:03:22] Found 1 available updates from Winget
[25.09.2024 08:03:22] Backup saved to <redacted>
[25.09.2024 08:03:23] Found 9 installed packages from Scoop
[25.09.2024 08:03:27] Found 0 available updates from PowerShell
[25.09.2024 08:03:27] Found 1 available updates from Scoop
```

### Package Managers Logs

```text
Not relevant
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/30d310b9-88ec-4008-b6a9-c372b522ec51)

**Comment by marticliment** [comment]
Please share your "Chocolatey" Manager logs

**Comment by johchur** [comment]
Here is the log

```
Manager Chocolatey with version:
2.3.0

——————————————————————————————————————————


Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 08:03:04
Process end time:   25.09.2024 08:03:07

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListUpdates
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " outdated"
Process start time: 25.09.2024 08:03:10
Process end time:   25.09.2024 08:03:20

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListInstalledPackages
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " list"
Process start time: 25.09.2024 08:03:10
Process end time:   25.09.2024 08:03:17

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 08:03:12
Process end time:   25.09.2024 08:03:20

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListInstalledPackages
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " list"
Process start time: 25.09.2024 09:21:49
Process end time:   25.09.2024 09:21:54

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Chocolatey. Task type is FindPackages
Process start time: 25.09.2024 09:22:17
Process end time:   25.09.2024 09:22:27

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 09:22:17
Process end time:   25.09.2024 09:22:27

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Chocolatey. Task type is FindPackages
Process start time: 25.09.2024 09:24:43
Process end time:   25.09.2024 09:24:50

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 09:24:43
Process end time:   25.09.2024 09:24:49

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListUpdates
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " outdated"
Process start time: 25.09.2024 10:03:27
Process end time:   25.09.2024 10:03:30

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 10:09:56
Process end time:   25.09.2024 10:09:58

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListUpdates
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " outdated"
Process start time: 25.09.2024 12:03:36
Process end time:   25.09.2024 12:03:39

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListUpdates
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " outdated"
Process start time: 25.09.2024 14:03:45
Process end time:   25.09.2024 14:03:48

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Chocolatey. Task type is ListInstalledPackages
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " list"
Process start time: 25.09.2024 14:33:00
Process end time:   25.09.2024 14:33:03

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————
```

**Comment by johchur** [comment]
Okay, after updating to 3.1.2-beta the verbose logs are working again. Here is the interesting part of the log:
```text
Logged subprocess-based task on manager Chocolatey. Task type is ListSources
Subprocess executable: "C:\ProgramData\chocolatey\bin\choco.exe"
Command-line arguments: " source list"
Process start time: 25.09.2024 14:44:07
Process end time:   25.09.2024 14:44:11

-- Process STDOUT
  Chocolatey v2.3.0
  chocolatey - https://community.chocolatey.org/api/v2/ | Priority 1|Bypass Proxy - False|Self-Service - False|Admin Only - False.
  nexus - https://nexus.<redacted>/repository/chocolatey-hosted (Authenticated)| Priority 2|Bypass Proxy - False|Self-Service - False|Admin Only - False.

Return code: SUCCESS (0)

——————————————————————————————————————————
```
