### ISSUE TITLE
[BUG] UniGetui not finding installed software or updates after the first launch

### ISSUE THREAD

**Issue by Tommytom2002** [marticliment/UniGetUI#2795]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 23H2 22631.4169 X64

### Describe your issue

When I ran uniGetui the first time after installation it found a lot of installed Software and also a lot of updates via WinGet, Choco and PS5.
When I started it a second time, only WinGet via PS5 was found as installed Applications, and no updates.
I resetted all Packagemanagers already , tried the latest Beta - but ther was no change.
I installed it on a different computer (same Windows Version as above) there everything is working like a charm.

### UniGetUI Log

```text
[30.09.2024 08:44:59]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[30.09.2024 08:44:59]
[30.09.2024 08:44:59] Version Code:  3,11
[30.09.2024 08:44:59] System.FormatException: The input string '850.' was not in a correct format.
                         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
                         at System.Int32.Parse(String s)
                         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
[30.09.2024 08:44:59] Encoding Code Page set to 0
[30.09.2024 08:44:59] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[30.09.2024 08:45:00] Loaded language locale: de
[30.09.2024 08:45:00] Randomly-generated background API auth token for the current session: abqazzxqp0wyaljsoxbp6jb4pdemif50gth0yupa232hu57d84ewrzn5leltotu9
[30.09.2024 08:45:00] Api running on http://localhost:7058
[30.09.2024 08:45:01] Lang files were updated successfully from GitHub
[30.09.2024 08:45:01] UniGetUI is up to date
[30.09.2024 08:45:01] Downloaded new icons and screenshots successfully!
[30.09.2024 08:45:01] Command npm was not found on the system
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] Command choco.exe was not found on the system
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] Command pwsh.exe was not found on the system
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] Command scoop was not found on the system
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:01] Cannot create native WinGet instance due to error: Bundled WinGet was forced by the user!
[30.09.2024 08:45:01] System.InvalidOperationException: Bundled WinGet was forced by the user!
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 390
[30.09.2024 08:45:01] WinGet will resort to using BundledWinGetHelper()
[30.09.2024 08:45:01] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Program Files\UniGetUI\winget-cli_x64\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   Bundled WinGet CLI Version: 
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using bundled WinGet helper (CLI parsing)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:02] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4111                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4111                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 08:45:03] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[30.09.2024 08:45:03] Dependency WinGet PowerShell Module for manager Winget is present
[30.09.2024 08:45:03] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[30.09.2024 08:45:03] Found 0 installed packages from Winget
[30.09.2024 08:45:03] Found 0 available updates from Winget
[30.09.2024 08:45:04] Found 1 installed packages from PowerShell
[30.09.2024 08:45:05] Found 0 available updates from PowerShell
[30.09.2024 08:46:16] Found 0 available packages from Winget with the query chrome
[30.09.2024 08:46:47] Found 21 available packages from PowerShell with the query chrome
```

### Package Managers Logs

```text
Manager WinGet with version:
Bundled WinGet CLI Version: 
Microsoft.WinGet.Client PSModule version: ""
Using bundled WinGet helper (CLI parsing)

——————————————————————————————————————————


Logged subprocess-based task on manager Winget. Task type is FindPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " source list"
Process start time: 30.09.2024 08:45:01
Process end time:   30.09.2024 08:45:01

Return code: FAILED (-1978335231)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 30.09.2024 08:45:02
Process end time:   30.09.2024 08:45:03

Return code: FAILED (-1978335231)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListInstalledPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " list  --accept-source-agreements"
Process start time: 30.09.2024 08:45:02
Process end time:   30.09.2024 08:45:02

Return code: FAILED (-1978335231)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is FindPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " source list"
Process start time: 30.09.2024 08:45:03
Process end time:   30.09.2024 08:45:03

Return code: FAILED (-1978335231)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " update --include-unknown  --accept-source-agreements"
Process start time: 30.09.2024 08:45:03
Process end time:   30.09.2024 08:45:03

Return code: FAILED (-1978335231)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is FindPackages
Subprocess executable: "C:\Program Files\UniGetUI\winget-cli_x64\winget.exe"
Command-line arguments: " search "chrome"  --accept-source-agreements"
Process start time: 30.09.2024 08:46:16
Process end time:   30.09.2024 08:46:16

Return code: FAILED (-1978335231)

——————————————————————————————————————————
```

**Comment by StanleyPain** [comment]
I have a similar issue. It only finds PIP updates but nothing more.

**Comment by marticliment** [comment]
I am afraid you have a faulty WinGet installation. Please toggle the option "UniGetUI Settings -> WinGet -> Use bundled WinGet instead of the COM API"

**Comment by Tommytom2002** [comment]
I already tried that, but there is the same behaviour.

**Comment by marticliment** [comment]
I am working on a troubleshooter. Please wait for the next release

**Comment by marticliment** [comment]
Hello, 

Please try UniGetUI 3.1.2-beta4. It has a built-in troubleshooter for WinGet that is supposed to fix this issue.

Download it here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta4
