### ISSUE TITLE
[BUG] [ENV ERROR]: Cannot update any package

### ISSUE THREAD

**Issue by rmueller83** [marticliment/UniGetUI#2798]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2-beta3

### Windows version, edition, and architecture

Windows 11 Pro 23H2 (Build 22631.4169) x64

### Describe your issue

After #2728 was fixed with beta3, the outdated packages are listed now for me. But I cannot update any package, neither with winget, nor with pip:
```
[30.09.2024 22:23:58] System.ComponentModel.Win32Exception (87): An error occurred trying to start process 'C:\Users\myuser\AppData\Local\Microsoft\WindowsApps\winget.exe' with working directory 'C:\Users\myuser'. Falscher Parameter.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Operations.AbstractOperation.MainThread() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Controls\OperationWidgets\OperationControl.xaml.cs:line 441
```
On the command line, winget works.

### UniGetUI Log

```text
[30.09.2024 22:23:18]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.2-beta3
[30.09.2024 22:23:18]
[30.09.2024 22:23:18] Version Code:  3,1193
[30.09.2024 22:23:18] Encoding Code Page set to 850
[30.09.2024 22:23:18] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[30.09.2024 22:23:19] Loaded language locale: de
[30.09.2024 22:23:19] Starting update check
[30.09.2024 22:23:20] Randomly-generated background API auth token for the current session: 4fkebqav9qrg2o0q81ha4jr2vse4x3f24d3ny69vz4z22b4emnfak2n15k8iyv5l
[30.09.2024 22:23:20] Api running on http://localhost:7058
[30.09.2024 22:23:20] Lang files were updated successfully from GitHub
[30.09.2024 22:23:20] UniGetUI is up to date
[30.09.2024 22:23:20] Old chocolatey path does not exist, not migrating Chocolatey
[30.09.2024 22:23:20] Begin "which" search for command npm
[30.09.2024 22:23:20] Begin "which" search for command pwsh.exe
[30.09.2024 22:23:20] Begin "which" search for command python.exe
[30.09.2024 22:23:20] Begin "which" search for command cargo
[30.09.2024 22:23:20] Begin "which" search for command winget.exe
[30.09.2024 22:23:20] Begin "which" search for command dotnet.exe
[30.09.2024 22:23:20] Downloaded new icons and screenshots successfully!
[30.09.2024 22:23:20] Saving window geometry 168,266,2200,1059,0
[30.09.2024 22:23:21] Begin "which" search for command python.exe
[30.09.2024 22:23:21] Begin "which" search for command npm
[30.09.2024 22:23:21] Begin "which" search for command winget.exe
[30.09.2024 22:23:21] Begin "which" search for command dotnet.exe
[30.09.2024 22:23:21] Begin "which" search for command pwsh.exe
[30.09.2024 22:23:21] Begin "which" search for command cargo
[30.09.2024 22:23:21] Command npm was not found on the system
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] Command python.exe was found on C:\Users\myuser\AppData\Local\Programs\Python\Python310\python.exe
[30.09.2024 22:23:21] Command winget.exe was found on C:\Users\myuser\AppData\Local\Microsoft\WindowsApps\winget.exe
[30.09.2024 22:23:21] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[30.09.2024 22:23:21] Command pwsh.exe was not found on the system
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] Command cargo was not found on the system
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] Loaded 2 sources for manager Winget
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\myuser\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\myuser\AppData\Local\Programs\Python\Python310\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:21] Begin "which" search for command scoop
[30.09.2024 22:23:21] Begin "which" search for command scoop
[30.09.2024 22:23:21] Command scoop was not found on the system
[30.09.2024 22:23:21] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:23] Loaded 1 sources for manager Chocolatey
[30.09.2024 22:23:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\myuser\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:23] Loaded 1 sources for manager PowerShell
[30.09.2024 22:23:23] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4111                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4111                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[30.09.2024 22:23:23] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[30.09.2024 22:23:23] Manager Pip has not implemented RefreshPackageIndexes
[30.09.2024 22:23:23] Manager PowerShell has not implemented RefreshPackageIndexes
[30.09.2024 22:23:24] Loaded 2 sources for manager Winget
[30.09.2024 22:23:25] Found 0 installed packages from Chocolatey
[30.09.2024 22:23:25] Found 0 available updates from Chocolatey
[30.09.2024 22:23:25] Loaded 1 sources for manager Chocolatey
[30.09.2024 22:23:25] Found 89 installed packages from Pip
[30.09.2024 22:23:25] Ignored updates database was never loaded, so it is going to be loaded now
[30.09.2024 22:23:26] Found 1 installed packages from PowerShell
[30.09.2024 22:23:26] Loaded 1 sources for manager PowerShell
[30.09.2024 22:23:27] Found 0 available updates from PowerShell
[30.09.2024 22:23:31] Found 3 available updates from Winget
[30.09.2024 22:23:31] Found 314 installed packages from Winget
[30.09.2024 22:23:32] Found 21 available updates from Pip
[30.09.2024 22:23:32] Invalid value for UpdatesCheckInterval, using default value of 3600 seconds
[30.09.2024 22:23:58] Creating new instance of InstallationOptions for package UniGetUI.PackageEngine.PackageClasses.Package, as no instance was found in cache
[30.09.2024 22:23:58] Manager Pip does not support native icons
[30.09.2024 22:23:58] Icon id for package=pydot is pydot
[30.09.2024 22:23:58] Icon for package pydot was not found, returning default icon
[30.09.2024 22:23:58] Creating new instance of InstallationOptions for package UniGetUI.PackageEngine.PackageClasses.Package, as no instance was found in cache
[30.09.2024 22:23:58] Icon for package pydot was loaded from ms-appx:///Assets/Images/package_color.png
[30.09.2024 22:23:58] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[30.09.2024 22:23:58] Manager Winget did not find a native icon for Ubisoft.Connect
[30.09.2024 22:23:58] Icon id for package=Ubisoft.Connect is connect
[30.09.2024 22:23:58] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Ubisoft.Connect
[30.09.2024 22:23:58] An error occurred while retrieving the icon for package Ubisoft.Connect
[30.09.2024 22:23:58] System.ArgumentOutOfRangeException: startIndex ('-1') must be a non-negative value. (Parameter 'startIndex')
                      Actual value was -1.
                         at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
                         at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
                         at System.String.Substring(Int32 startIndex, Int32 length)
                         at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 71
                         at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 181
[30.09.2024 22:23:58] Loaded operation parameters for package id=pydot on manager Pip and operation Update: install --upgrade pydot --no-input --no-color --no-python-version-warning --no-cache
[30.09.2024 22:23:58] Operation crashed:
[30.09.2024 22:23:58] System.ComponentModel.Win32Exception (87): An error occurred trying to start process 'C:\Users\myuser\AppData\Local\Programs\Python\Python310\python.exe' with working directory 'C:\Users\myuser'. Falscher Parameter.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Operations.AbstractOperation.MainThread() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Controls\OperationWidgets\OperationControl.xaml.cs:line 441
[30.09.2024 22:23:58] Loaded operation parameters for package id=Ubisoft.Connect on manager Winget and operation Update: update --id "Ubisoft.Connect" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[30.09.2024 22:23:58] Operation crashed:
[30.09.2024 22:23:58] System.ComponentModel.Win32Exception (87): An error occurred trying to start process 'C:\Users\myuser\AppData\Local\Microsoft\WindowsApps\winget.exe' with working directory 'C:\Users\myuser'. Falscher Parameter.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Operations.AbstractOperation.MainThread() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Controls\OperationWidgets\OperationControl.xaml.cs:line 441
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 30.09.2024 22:23:21
Process end time:   30.09.2024 22:23:21

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\myuser\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 30.09.2024 22:23:23
Process end time:   30.09.2024 22:23:26

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 30.09.2024 22:23:23
Process end time:   30.09.2024 22:23:31

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 30.09.2024 22:23:24
Process end time:   30.09.2024 22:23:24

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 30.09.2024 22:23:26
Process end time:   30.09.2024 22:23:31

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
I will fix this issue
