### ISSUE TITLE
[BUG] No installed winget packages showing after updating all packages

### ISSUE THREAD

**Issue by wrightsg** [marticliment/UniGetUI#2801]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Enterprise 10.0.22631 Build 22631 x64

### Describe your issue

I recently updated WingetUI to UniGetUI and followed that by updating all my installed packages.

After running the updates, I'm only seeing packages from the "Pip" source in the "Installed Packages" list even though I have installed several packages from the "Winget" source.

I've tried deleteing UniGetUI related folders as described in https://github.com/marticliment/UniGetUI/issues/1721 but this did not help.

### Steps to reproduce the issue

N/A

### UniGetUI Log

```text
[01.10.2024 09:02:09]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.1
[01.10.2024 09:02:09]
[01.10.2024 09:02:09] Version Code:  3.11
[01.10.2024 09:02:09] Encoding Code Page set to 850
[01.10.2024 09:02:09] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[01.10.2024 09:02:09] Loaded language locale: en
[01.10.2024 09:02:10] Randomly-generated background API auth token for the current session: jcjn9myl08m5vr612b8qu3bh8r95lrn00ed4728iz64e0szy2mho2dlrgrap2g6x
[01.10.2024 09:02:10] Api running on http://localhost:7058
[01.10.2024 09:02:10] Lang files were updated successfully from GitHub
[01.10.2024 09:02:10] Downloaded new icons and screenshots successfully!
[01.10.2024 09:02:10] Command npm was not found on the system
[01.10.2024 09:02:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:10] UniGetUI is up to date
[01.10.2024 09:02:10] Command pwsh.exe was not found on the system
[01.10.2024 09:02:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:10] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Program Files\WingetUI\choco-cli\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:10] Found 0 installed packages from Chocolatey
[01.10.2024 09:02:11] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\swright\AppData\Local\Programs\Python\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.2 from C:\Users\swright\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:11] Command scoop was not found on the system
[01.10.2024 09:02:11] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:11] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\swright\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Microsoft.WinGet.Client PSModule version: ""
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:13] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4111                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4111                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[01.10.2024 09:02:13] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[01.10.2024 09:02:13] Dependency WinGet PowerShell Module for manager Winget is present
[01.10.2024 09:02:13] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[01.10.2024 09:02:13] Found 0 available updates from Chocolatey
[01.10.2024 09:02:13] Found 0 installed packages from Chocolatey
[01.10.2024 09:02:13] Found 14 installed packages from Pip
[01.10.2024 09:02:15] Found 0 installed packages from PowerShell
[01.10.2024 09:02:15] Found 0 available updates from PowerShell
[01.10.2024 09:02:15] Found 0 available updates from Pip
[01.10.2024 09:02:19] Error finding installed packages on manager Winget
[01.10.2024 09:02:19] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass5_0.<GetInstalledPackages_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 157
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetInstalledPackages_UnSafe>b__28_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 138
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[01.10.2024 09:02:23] Error finding updates on manager Winget
[01.10.2024 09:02:23] System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 192
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.<>c__DisplayClass4_0.<GetAvailableUpdates_UnSafe>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 137
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.<GetAvailableUpdates_UnSafe>b__27_0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                      --- End of stack trace from previous location ---
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 133
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 189
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 01.10.2024 09:02:11
Process end time:   01.10.2024 09:02:11

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\swright\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 01.10.2024 09:02:13
Process end time:   01.10.2024 09:02:17

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 01.10.2024 09:02:13
Process end time:   01.10.2024 09:02:19

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 01.10.2024 09:02:13
Process end time:   01.10.2024 09:02:13

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 01.10.2024 09:02:17
Process end time:   01.10.2024 09:02:23

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Please go to UniGetUI Settings -> WinGet -> Use System WinGet instead of COM APIs

**Comment by wrightsg** [comment]
> Please go to UniGetUI Settings -> WinGet -> Use System WinGet instead of COM APIs

Thanks, this worked!

Specifically, the option is called "Settings > WinGet > **Use the WinGet PowerShell Module instead of the WinGet COM API**"

**Comment by Tommytom2002** [comment]
For me it was not working!

**Comment by Kuki77** [comment]
> For me it was not working!

Here it worked, but it took a moment to refresh the list.

**Comment by marticliment** [comment]
Hello, 

Please try UniGetUI 3.1.2-beta4. It has a built-in troubleshooter for WinGet that is supposed to fix this issue.

Download it here: https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta4

**Comment by nhwCoder** [comment]
### Installed UniGetUI 3.1.2-beta4.
* WinGet Troubleshooter did detect a problem and installed a new NuGet package via a script window popup
* After that => problems as described above still exists

### INFO: Running Win11 (with latest updates)
* **Login as NormalUser** => **problems** as described above still exists
* Login as NormalUser, but starting UniGetUI with admin rights => problems as described above still exists
* **Login with AdminUser** und using UniGetUI = **WORKING fine, without any problems**

#### PS
And yes I tried Settings > WinGet
a) Run WinGet with admin rights
b) Use the WinGet PowerShell Module instead of the WinGet COM API"
=> problems as described above still exists

**Comment by Kuki77** [comment]
Installed UniGetUI 3.1.2-beta4.

1. WinGet Troubleshooter did detect a problem and installed a new NuGet package via a script window popup
2. After that => Restart => again troubleshooter found winget issue loop (not solved)
3. Winget packages not solved

**Comment by nhwCoder** [comment]
#### UPDATE for UniGetUI 3.1.2 (Final version) => same problem
* Exact same problems and results as described in my post above

**Comment by nhwCoder** [comment]
UPDATE for UniGetUI 3.1.2 (Final version) 
* After updating Win11 to 24H2 = solved
* UniGetUI 3.1.2 => No problem win winget anymore, working fine (after update to Win11 24H2)
