### ISSUE TITLE
unigetui is failing to detect software updates for python and git

### ISSUE THREAD

**Issue by MurraySobol** [marticliment/UniGetUI#2820]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0-beta3

### Windows version, edition, and architecture

Windows Profession x64 23H2 (OS Build 22631.3958)

### Describe your issue

2 software products have new updates but unigetui is failing to detect them.
They are: python, current version is 3.12, 3.13 has been available for more than 24 hours
Git 24.6.2 is current, 24.7 is available
Second question: how do I remove a software update, python 3.13.0rc2 shows as being installed but I am unable to remove it.

### Steps to reproduce the issue

run unigetui searching for software updates.

### UniGetUI Log

```text
[10/8/2024 8:43:01 AM]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.2-beta3
[10/8/2024 8:43:02 AM]
[10/8/2024 8:43:02 AM] Version Code:  3.1193
[10/8/2024 8:43:02 AM] Encoding Code Page set to 437
[10/8/2024 8:43:03 AM] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[10/8/2024 8:43:04 AM] Loaded language locale: en
[10/8/2024 8:43:05 AM] Randomly-generated background API auth token for the current session: 5cmk0148z7usy1aet0svdi8d8gheuo1ru90rlh3atd3kc6hsrkjoxp6kmead2d1v
[10/8/2024 8:43:05 AM] Api running on http://localhost:7058
[10/8/2024 8:43:05 AM] Lang files were updated successfully from GitHub
[10/8/2024 8:43:05 AM] UniGetUI is up to date
[10/8/2024 8:43:05 AM] Downloaded new icons and screenshots successfully!
[10/8/2024 8:43:06 AM] Command npm was not found on the system
[10/8/2024 8:43:06 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:07 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Cargo
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: cargo.exe
                       █ Executable path: C:\Users\murra\.cargo\bin\cargo.exe
                       █ Call arguments: 
                       █ Version: 
                       █   cargo 1.81.0
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:07 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pip
                       █ Executable path: C:\Users\murra\AppData\Local\Microsoft\WindowsApps\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:08 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: v1.9.1981-preview
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:09 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:10 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: dotnet tool
                       █ Executable path: C:\Program Files\dotnet\dotnet.exe
                       █ Call arguments: tool
                       █ Version: 
                       █   9.0.100-rc.1.24452.12
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:14 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.26100.1882                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.26100.1882                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:15 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pwsh.exe
                       █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   PowerShell 7.4.5
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:15 AM] Command scoop was not found on the system
[10/8/2024 8:43:15 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[10/8/2024 8:43:15 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[10/8/2024 8:43:16 AM] Found 0 available updates from Pip
[10/8/2024 8:43:16 AM] Found 0 installed packages from Pip
[10/8/2024 8:43:18 AM] Found 7 installed packages from Cargo
[10/8/2024 8:43:18 AM] Found 0 available updates from Cargo
[10/8/2024 8:43:18 AM] Dependency cargo-update for manager Cargo is present
[10/8/2024 8:43:18 AM] Ignored updates database was never loaded, so it is going to be loaded now
[10/8/2024 8:43:19 AM] Dependency .NET Tools Outdated for manager .NET Tool is present
[10/8/2024 8:43:19 AM] Found 1 installed packages from .NET Tool
[10/8/2024 8:43:22 AM] Found 0 available updates from .NET Tool
[10/8/2024 8:43:24 AM] Found 0 installed packages from PowerShell7
[10/8/2024 8:43:25 AM] Found 0 available updates from PowerShell7
[10/8/2024 8:43:25 AM] Found 58 installed packages from PowerShell
[10/8/2024 8:43:32 AM] Found 0 available updates from Winget
[10/8/2024 8:43:32 AM] Found 288 installed packages from Winget
[10/8/2024 8:44:16 AM] Error finding updates on manager PowerShell
[10/8/2024 8:44:16 AM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[10/8/2024 8:50:10 AM] Found 0 installed packages from Pip
[10/8/2024 8:50:10 AM] Found 1 installed packages from .NET Tool
[10/8/2024 8:50:11 AM] Found 7 installed packages from Cargo
[10/8/2024 8:50:13 AM] Found 0 installed packages from PowerShell7
[10/8/2024 8:50:14 AM] Found 58 installed packages from PowerShell
[10/8/2024 8:50:15 AM] Found 288 installed packages from Winget
[10/8/2024 8:50:15 AM] Adding missing package MSIX\5319275A.51895FA4EA97F_2.2440.8.0_x64__cv1g1gvanyjgm to installed packages list
[10/8/2024 8:50:15 AM] Adding missing package MSIX\7EE7776C.LinkedInforWindows_3.0.38.0_x64__w1wdnht996qgy to installed packages list
[10/8/2024 8:50:15 AM] Adding missing package MSIX\Microsoft.GamingApp_2410.1001.55.0_x64__8wekyb3d8bbwe to installed packages list
[10/8/2024 8:50:35 AM] Found 288 installed packages from Winget
[10/8/2024 8:50:35 AM] Found 0 installed packages from Pip
[10/8/2024 8:50:36 AM] Found 7 installed packages from Cargo
[10/8/2024 8:50:36 AM] Found 1 installed packages from .NET Tool
[10/8/2024 8:50:39 AM] Found 0 installed packages from PowerShell7
[10/8/2024 8:50:40 AM] Found 58 installed packages from PowerShell
[10/8/2024 8:51:14 AM] Command parse_pip_search.exe was not found on the system
[10/8/2024 8:51:15 AM] Error finding packages on manager Pip with query python
[10/8/2024 8:51:15 AM] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\WINDOWS\system32'. The system cannot find the file specified.)
                        ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\WINDOWS\system32'. The system cannot find the file specified.
                          at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                          at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 95
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass52_0.<FindPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          --- End of inner exception stack trace ---
                          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                          at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
[10/8/2024 8:51:15 AM] Found 100 available packages from .NET Tool with the query python
[10/8/2024 8:51:24 AM] Found 1 available packages from Cargo with the query python
[10/8/2024 8:51:34 AM] Found 89 available packages from Winget with the query python
[10/8/2024 8:51:41 AM] Found 18 available packages from PowerShell7 with the query python
[10/8/2024 8:51:42 AM] Found 18 available packages from PowerShell with the query python
[10/8/2024 8:57:05 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[10/8/2024 8:57:05 AM] Icon for package Python.Python.3.13 was not found, returning default icon
[10/8/2024 8:57:05 AM] Loaded operation parameters for package id=Python.Python.3.13 on manager Winget and operation Install: install --id "Python.Python.3.13" --exact --source winget --accept-source-agreements --disable-interactivity --silent --accept-package-agreements --force
[10/8/2024 8:58:15 AM] Did not know how to handle the parameter unigetui:%20how%20to%20remove%20a%20software%20update
[10/8/2024 8:58:16 AM] Found 0 installed packages from Pip
[10/8/2024 8:58:17 AM] Found 1 installed packages from .NET Tool
[10/8/2024 8:58:17 AM] Found 7 installed packages from Cargo
[10/8/2024 8:58:19 AM] Found 0 installed packages from PowerShell7
[10/8/2024 8:58:20 AM] Found 58 installed packages from PowerShell
[10/8/2024 8:58:22 AM] Found 288 installed packages from Winget
[10/8/2024 9:03:33 AM] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[10/8/2024 9:03:33 AM] Icon for package Python.Python.3.13 was not found, returning default icon
[10/8/2024 9:03:33 AM] Loaded operation parameters for package id=Python.Python.3.13 on manager Winget and operation Uninstall: uninstall --id "Python.Python.3.13" --exact --source winget --accept-source-agreements --disable-interactivity --version 3.13.0rc2 --silent
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.1981-preview
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 10/8/2024 8:43:08 AM
Process end time:   10/8/2024 8:43:08 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\murra\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 10/8/2024 8:43:15 AM
Process end time:   10/8/2024 8:43:22 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 10/8/2024 8:43:15 AM
Process end time:   10/8/2024 8:43:32 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 10/8/2024 8:43:16 AM
Process end time:   10/8/2024 8:43:16 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 10/8/2024 8:43:22 AM
Process end time:   10/8/2024 8:43:32 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 10/8/2024 8:50:09 AM
Process end time:   10/8/2024 8:50:15 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 10/8/2024 8:50:30 AM
Process end time:   10/8/2024 8:50:35 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 10/8/2024 8:51:14 AM
Process end time:   10/8/2024 8:51:34 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 10/8/2024 8:58:15 AM
Process end time:   10/8/2024 8:58:22 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Hello Murray,

Why are you running UniGetUI 3.1.0-beta3?
Please upgrade to 3.1.1: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1

**Comment by MurraySobol** [comment]
Marti:

      A typo on my part, I am running UniGetUI 3.1.2-beta3

Murray

________________________________

**Comment by marticliment** [comment]
Ah, Ok.

How long have this updates been missing?
Are they available through CLI?

**Comment by MurraySobol** [comment]
Marti:

      For Git, I installed the previous version 2.46 thru CLI, this was before I started using UniGetUi.

      For Python, I was installing older versions using the CLI, but I believe that I installed the prior version 3.12 thru UniGetUi.
      I also examined the Windows registry entries for it, I found  many references to 3.10 and 3.11, I manually removed them from the registry.
      I MAY have complicated things further since I downloaded and installed Python 3.13.0rc2; it is this version that I would like to remove but I have not found a way to do it.

      When I run "Installed Packages" thru UniGetUI it shows me an entry for Python 3.12; I wonder if the presence of Python 3.13.0rc2 is complicating things.
      In the future, I will avoid installing Release Candidates of software, unless there is a pressing need for me to use it, since it seems to provide "more pain than gsain".

Murray

________________________________

**Comment by marticliment** [comment]
Either way, I will investigate this issue
