### ISSUE TITLE
[BUG] (Private Nuget chocolatey repository not searched)

### ISSUE THREAD

**Issue by GandiKB** [marticliment/UniGetUI#2821]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2 beta 3

### Windows version, edition, and architecture

Windows 10 Pro 22H2 19045.4894

### Describe your issue

Private Nuget choco repository that requires authentication is not searchable.

### UniGetUI Log

```text
[2024-10-09 16:25:28]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.2-beta3
[2024-10-09 16:25:28]
[2024-10-09 16:25:28] Version Code:  3,1193
[2024-10-09 16:25:28] Encoding Code Page set to 852
[2024-10-09 16:25:28] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[2024-10-09 16:25:29] Loaded language locale: pl
[2024-10-09 16:25:29] Randomly-generated background API auth token for the current session: h2ki6o9ybl2yy83ukelwr3tu6fg7sb9kshov6ot8bhv31905ud0aok5ww0672nqr
[2024-10-09 16:25:29] Api running on http://localhost:7058
[2024-10-09 16:25:29] Lang files were updated successfully from GitHub
[2024-10-09 16:25:30] UniGetUI is up to date
[2024-10-09 16:25:30] Command cargo was not found on the system
[2024-10-09 16:25:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Program Files (x86)\Python311-32\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 23.0.1 from C:\Program Files (x86)\Python311-32\Lib\site-packages\pip (python 3.11)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\kbalicki\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:31] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:31] Downloaded new icons and screenshots successfully!
[2024-10-09 16:25:31] Command scoop was not found on the system
[2024-10-09 16:25:31] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.7.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.3.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.5
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.19041.4894                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.19041.4894                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-09 16:25:36] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024-10-09 16:25:39] Found 43 installed packages from Chocolatey
[2024-10-09 16:25:40] Found 34 available updates from Pip
[2024-10-09 16:25:40] Ignored updates database was never loaded, so it is going to be loaded now
[2024-10-09 16:25:42] Found 0 available updates from Npm
[2024-10-09 16:25:42] Found 44 available updates from Winget
[2024-10-09 16:25:43] Found 0 available updates from PowerShell
[2024-10-09 16:25:44] Found 53 installed packages from Pip
[2024-10-09 16:25:46] Found 16 available updates from Chocolatey
[2024-10-09 16:25:46] Found 1 installed packages from PowerShell7
[2024-10-09 16:25:47] Found 0 installed packages from Npm
[2024-10-09 16:25:49] Found 2 installed packages from PowerShell
[2024-10-09 16:25:49] Found 0 available updates from PowerShell7
[2024-10-09 16:25:51] Found 428 installed packages from Winget
[2024-10-09 16:26:41] Found 0 available packages from Chocolatey with the query *
[2024-10-09 16:26:49] Found 0 available packages from Chocolatey with the query ac
[2024-10-09 16:26:53] Found 0 available packages from Chocolatey with the query acfk
[2024-10-09 16:31:18] Found 0 available packages from Chocolatey with the query acfk 1.2.9
[2024-10-09 16:31:29] Found 0 available packages from Chocolatey with the query acfk 1.2.0
[2024-10-09 16:42:29] Command parse_pip_search.exe was not found on the system
[2024-10-09 16:42:31] Error finding packages on manager Pip with query acfk 1.2.0]
[2024-10-09 16:42:31] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Nie można odnaleźć określonego pliku.)
                       ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Nie można odnaleźć określonego pliku.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 95
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass52_0.<FindPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
[2024-10-09 16:42:31] Found 0 available packages from Chocolatey with the query acfk 1.2.0]
[2024-10-09 16:42:31] Found 0 available packages from PowerShell7 with the query acfk 1.2.0]
[2024-10-09 16:42:31] Found 0 available packages from Winget with the query acfk 1.2.0]
[2024-10-09 16:42:32] Found 0 available packages from Npm with the query acfk 1.2.0]
[2024-10-09 16:43:03] Found 0 available packages from PowerShell with the query acfk 1.2.0]
[2024-10-09 16:47:30] Found 43 installed packages from Chocolatey
[2024-10-09 16:47:31] Found 1 installed packages from PowerShell7
[2024-10-09 16:47:31] Found 53 installed packages from Pip
[2024-10-09 16:47:31] Found 2 installed packages from PowerShell
[2024-10-09 16:47:32] Found 0 installed packages from Npm
[2024-10-09 16:47:32] Found 428 installed packages from Winget
[2024-10-09 16:47:34] Command parse_pip_search.exe was not found on the system
[2024-10-09 16:47:36] Error finding packages on manager Pip with query acfk
[2024-10-09 16:47:36] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Nie można odnaleźć określonego pliku.)
                       ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Nie można odnaleźć określonego pliku.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 95
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass52_0.<FindPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
[2024-10-09 16:47:37] Found 1 available packages from Npm with the query acfk
[2024-10-09 16:47:37] Found 0 available packages from PowerShell7 with the query acfk
[2024-10-09 16:47:37] Found 0 available packages from Chocolatey with the query acfk
[2024-10-09 16:47:37] Found 0 available packages from Winget with the query acfk
[2024-10-09 16:48:03] Found 0 available packages from PowerShell with the query acfk
```

### Package Managers Logs

```text
Logged native task on manager Chocolatey. Task type is FindPackages
Process start time: 2024-10-09 16:47:34
Process end time:   2024-10-09 16:47:37

-- Task information
  Begin package search with url=https://nexus.****.com/repository/choco-group//Search()?searchTerm=%27acfk%27&targetFramework=%27%27&includePrerelease=false on manager Chocolatey

-- Task errors
  Failed to fetch api at Url=https://nexus.****.com/repository/choco-group//Search()?searchTerm=%27acfk%27&targetFramework=%27%27&includePrerelease=false with status code Unauthorized

The task reported success
```

### Relevant information

I can search a packet by choco builtin 'find' feature without any login prompt
C:\WINDOWS\system32>choco find acfk
Chocolatey v2.3.0
acfk 1.2.0
1 packages found.

Searching by https api requires login and password.

**Comment by marticliment** [comment]
I will investigate
