### ISSUE TITLE
[BUG] Cannot uninstall scoop programs when program installation link is very long

### ISSUE THREAD

**Issue by Daviteusz** [marticliment/UniGetUI#2853]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1, 3.1.2-beta4

### Windows version, edition, and architecture

Windows 11 Pro 26100.1742 x64

### Describe your issue

UniGetUI does not properly handle long links from scoop package manager

### Steps to reproduce the issue

1. Install e.g msi afterburner via scoop, but in terminal:
```cmd
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e410228a5db3441997dfa92ca3bcc9d6430/bucket/msiafterburner.json 
```
2. Try uninstalling msiafterburner using UniGetUI

### UniGetUI Log

```text
[19.10.2024 20:01:45]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.2-beta4
[19.10.2024 20:01:45]
[19.10.2024 20:01:45] Version Code:  3,1194
[19.10.2024 20:01:45] Encoding Code Page set to 852
[19.10.2024 20:01:46] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[19.10.2024 20:01:46] Loaded language locale: pl
[19.10.2024 20:01:46] Randomly-generated background API auth token for the current session: rgbhgqknfcsm9j2fkbflgtkmsa5u0usi1t7g0y3sgezt2uvxbnvxvncde6y3j9j3
[19.10.2024 20:01:46] Api running on http://localhost:7058
[19.10.2024 20:01:46] Lang files were updated successfully from GitHub
[19.10.2024 20:01:46] Command pwsh.exe was not found on the system
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:46] Command cargo was not found on the system
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:46] Command npm was not found on the system
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:46] Downloaded new icons and screenshots successfully!
[19.10.2024 20:01:46] UniGetUI is up to date
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:46] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Mateusz\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:47] Starting scoop cleanup...
[19.10.2024 20:01:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Mateusz\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                      █   
                      █   'main' bucket:
                      █   f3a1b7b29f terraform-provider-ibm: Update to version 1.70.1
                      █   
                      █   'extras' bucket:
                      █   d07013c2a xpipe: Update to version 12.3.4
                      █   
                      █   'versions' bucket:
                      █   b362b31cb swift-nightly: Update to version 20241019.2
                      █   
                      █   'java' bucket:
                      █   13abecbb openjdk-ea: Update to version 24-20-ea
                      █   
                      █   'bissli' bucket:
                      █   c01b5ca added irontcl
                      █   
                      █   'gaming' bucket:
                      █   be07fc1 nvidia-display-driver: Update to version 565.90
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[19.10.2024 20:01:48] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[19.10.2024 20:01:49] Dependency Scoop-Search for manager Scoop is present
[19.10.2024 20:01:49] Dependency Git for manager Scoop is present
[19.10.2024 20:01:49] Scoop cleanup finished!
[19.10.2024 20:01:49] Found 45 installed packages from Scoop
[19.10.2024 20:01:50] Found 1 installed packages from Chocolatey
[19.10.2024 20:01:50] Ignored updates database was never loaded, so it is going to be loaded now
[19.10.2024 20:01:50] Found 0 available updates from Chocolatey
[19.10.2024 20:01:50] An error occurred while retrieving the icon for package ddu
[19.10.2024 20:01:50] An error occurred while retrieving the icon for package ddu
[19.10.2024 20:01:50] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:50] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:50] Found 101 installed packages from Winget
[19.10.2024 20:01:51] An error occurred while retrieving the icon for package ds4windows
[19.10.2024 20:01:51] An error occurred while retrieving the icon for package ds4windows
[19.10.2024 20:01:51] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:51] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:51] Found 5 available updates from Winget
[19.10.2024 20:01:51] Icon for package obs-studio stored on C:\Users\Mateusz\AppData\Local\UniGetUI\CachedMedia\Scoop\obs-studio.png
[19.10.2024 20:01:51] NEWLY DOWNLOADED Icon for Package=obs-studio Manager=Scoop Uri=https://community.chocolatey.org/content/packageimages/obs-studio.install.29.0.2.png is VALID (verification method is PackageVersion)
[19.10.2024 20:01:51] Icon for package obs-studio stored on C:\Users\Mateusz\AppData\Local\UniGetUI\CachedMedia\Scoop\obs-studio.png
[19.10.2024 20:01:51] NEWLY DOWNLOADED Icon for Package=obs-studio Manager=Scoop Uri=https://community.chocolatey.org/content/packageimages/obs-studio.install.29.0.2.png is VALID (verification method is PackageVersion)
[19.10.2024 20:01:52] An error occurred while retrieving the icon for package twinkle-tray
[19.10.2024 20:01:52] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:52] An error occurred while retrieving the icon for package twinkle-tray
[19.10.2024 20:01:52] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:52] An error occurred while retrieving the icon for package ungoogled-chromium
[19.10.2024 20:01:52] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:53] An error occurred while retrieving the icon for package ungoogled-chromium
[19.10.2024 20:01:53] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:01:54] Found 45 installed packages from Scoop
[19.10.2024 20:01:55] An error occurred while retrieving the icon for package namazso.OpenHashTab
[19.10.2024 20:01:55] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[19.10.2024 20:02:00] Found 0 available updates from Scoop
[19.10.2024 20:02:20] Loaded operation parameters for package id=msiafterburner on manager Scoop and operation Uninstall: uninstall https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e4102.../msiafterburner
```

### Package Managers Logs

```text
Manager Scoop with version:
Current Scoop version:
859d1db5 chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
f3a1b7b29f terraform-provider-ibm: Update to version 1.70.1

'extras' bucket:
d07013c2a xpipe: Update to version 12.3.4

'versions' bucket:
b362b31cb swift-nightly: Update to version 20241019.2

'java' bucket:
13abecbb openjdk-ea: Update to version 24-20-ea

'bissli' bucket:
c01b5ca added irontcl

'gaming' bucket:
be07fc1 nvidia-display-driver: Update to version 565.90

——————————————————————————————————————————


Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 19.10.2024 20:01:47
Process end time:   19.10.2024 20:01:48

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is RefreshIndexes
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop update"
Process start time: 19.10.2024 20:01:48
Process end time:   19.10.2024 20:01:54

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 19.10.2024 20:01:48
Process end time:   19.10.2024 20:01:49

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListSources
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list"
Process start time: 19.10.2024 20:01:49
Process end time:   19.10.2024 20:01:50

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop list"
Process start time: 19.10.2024 20:01:54
Process end time:   19.10.2024 20:01:54

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Scoop. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command scoop status"
Process start time: 19.10.2024 20:01:54
Process end time:   19.10.2024 20:02:00

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

```
Starting package uninstall operation for package id=msiafterburner with Manager name=Scoop
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -ExecutionPolicy Bypass -Command scoop uninstall https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e4102.../msiafterburner 
Working Directory      : C:\Users\Mateusz
Process Start Time     : 19.10.2024 20:02:20
ERROR 'https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e4102.../msiafterburner' isn't installed.
Process Exit Code      : 0
Process End Time       : 19.10.2024 20:02:20

```

**Comment by marticliment** [comment]
please attach the output of the `scoop list` command here

**Comment by Daviteusz** [comment]
```
$ scoop list
Installed apps:

Name                           Version            Source                                                                                                                      Updated             Info
----                           -------            ------                                                                                                                      -------             ----
64gram                         1.1.43             extras                                                                                                                      2024-10-16 15:06:19
7zip                           24.08              main                                                                                                                        2024-08-19 00:42:52
adb                            35.0.0             main                                                                                                                        2024-08-06 19:19:03
anydesk                        8.1.0              extras                                                                                                                      2024-10-15 00:00:09
blender                        4.2.3              extras                                                                                                                      2024-10-15 18:19:22
borderless-gaming              9.5.6              gaming                                                                                                                      2024-08-25 16:46:10
crystaldiskinfo                9.4.4              extras                                                                                                                      2024-09-26 00:38:04
cura                           5.8.1              extras                                                                                                                      2024-08-30 13:49:30
ddu                            18.0.8.2           extras                                                                                                                      2024-10-14 16:20:46
ds4windows                     3.9.2              https://raw.githubusercontent.com/Daviteusz/ScoopExtras/refs/heads/patch-2/bucket/ds4windows.json                           2024-10-18 16:48:56
easy-context-menu              1.6                extras                                                                                                                      2024-08-11 15:34:35
flameshot                      12.1.0             extras                                                                                                                      2024-08-11 14:16:31
geekuninstaller                1.5.2.165          extras                                                                                                                      2024-08-08 21:08:37
gimp                           2.10.38-1          extras                                                                                                                      2024-10-19 15:52:57
git                            2.47.0             main                                                                                                                        2024-10-14 16:20:59
github                         3.4.6              extras                                                                                                                      2024-10-14 16:21:20
gpu-z                          2.60.0             extras                                                                                                                      2024-08-19 00:48:26
imageglass                     9.1.8.723          extras                                                                                                                      2024-09-23 09:48:52
innounp                        1.73               C:\Users\Mateusz\Downloads\innounp.json                                                                                     2024-10-19 16:24:16
jdownloader                    nightly-20240812   versions                                                                                                                    2024-08-12 22:48:47
kodi                           21.1               extras                                                                                                                      2024-10-15 23:30:02
link-shell-extension           3.9.3.5            bissli                                                                                                                      2024-08-11 15:06:06
msiafterburner                 4.6.5              https://raw.githubusercontent.com/ScoopInstaller/Extras/bfd10e410228a5db3441997dfa92ca3bcc9d6430/bucket/msiafterburner.json 2024-10-19 14:38:22
nssm                           2.24-103           main                                                                                                                        2024-08-03 18:09:26
nvcleanstall                   1.16.0             extras                                                                                                                      2024-10-19 14:55:01
obs-studio                     30.2.3             extras                                                                                                                      2024-08-19 00:48:41
openrgb                        0.9                extras                                                                                                                      2024-08-03 17:53:08
qbittorrent                    5.0.0              extras                                                                                                                      2024-10-02 11:45:27
raspberry-pi-imager            1.9.0              extras                                                                                                                      2024-09-26 00:39:46
rnote                          0.11.0             extras                                                                                                                      2024-10-19 16:01:53
rtss                           7.3.6              extras                                                                                                                      2024-08-03 16:44:55
rufus                          4.5                extras                                                                                                                      2024-08-27 12:56:36
scoop-search                   1.5.0              main                                                                                                                        2024-08-03 15:24:24
snappy-driver-installer-origin 1.13.4.771         extras                                                                                                                      2024-09-26 00:40:12
steam-library-manager          1.7.1.0            extras                                                                                                                      2024-08-11 13:58:27
temurin8-jre                   8.0.422-5          java                                                                                                                        2024-08-12 22:49:56
throttlestop                   9.6                extras                                                                                                                      2024-08-07 23:43:55
twinkle-tray                   1.16.2             extras                                                                                                                      2024-10-14 16:22:22
ungoogled-chromium             129.0.6668.100-1.1 extras                                                                                                                      2024-10-14 16:22:53
vcredist-aio                   0.84.0             extras                                                                                                                      2024-10-14 16:24:03
ventoy                         1.0.99             extras                                                                                                                      2024-08-27 14:39:11
vscodium                       1.94.2.24286       extras                                                                                                                      2024-10-14 16:28:06
winrar                         7.01               extras                                                                                                                      2024-08-13 00:14:14
winscp                         6.3.5              extras                                                                                                                      2024-09-26 00:40:50
yubikey-manager-qt             1.2.6              extras                                                                                                                      2024-08-08 12:58:59
```
