### ISSUE TITLE
[BUG] Unable to install UnigetUI with scoop

### ISSUE THREAD

**Issue by csc530** [marticliment/UniGetUI#2873]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2

### Windows version, edition, and architecture

Microsoft Windows 11 Home, 10.0.22631, x64

### Describe your issue

When trying to install UnigetUI from the extras bucket on Scoop, the installer fails because innounp is unable to extract the files.
[innounp.log](https://github.com/user-attachments/files/17468434/innounp.log)

(I had also tried to extract v3.1.2 installer with innounp v0.50 and it failed with the following error message `The setup files are corrupted or made by incompatible version. Maybe it's not an Inno Setup installation at all.
(00492DAA)`)

I had looked through the [build_release.bat](https://github.com/marticliment/UniGetUI/blob/4b05e4d04456576089e3c5da41d4640b2948462f/build_release.bat#L57) and I'm not sure which version of innounp UnigetUI is built with if that could be the issue.

### Steps to reproduce the issue

```powershell
scoop bucket add extras
scoop install extras/wingetui
```

### UniGetUI Log

```text
[2024-10-21 16:35:43]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.2
[2024-10-21 16:35:43]
[2024-10-21 16:35:43] Version Code:  3.12
[2024-10-21 16:35:43] Encoding Code Page set to 65001
[2024-10-21 16:35:44] Using bundled GSudo at C:\Users\legor\AppData\Local\Programs\UniGetUI\Assets\Utilities\gsudo.exe
[2024-10-21 16:35:46] Loaded language locale: en
[2024-10-21 16:35:48] Randomly-generated background API auth token for the current session: s0jbmstjye1jpqqs2n6yvc74wee34p5w1bucixtwob46mihgmt27uw99766x3cid
[2024-10-21 16:35:48] Api running on http://localhost:7058
[2024-10-21 16:35:48] Lang files were updated successfully from GitHub
[2024-10-21 16:35:50] UniGetUI is up to date
[2024-10-21 16:35:50] Downloaded new icons and screenshots successfully!
[2024-10-21 16:35:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\legor\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: cargo.exe
                      █ Executable path: C:\Users\legor\scoop\apps\rustup-gnu\current\.cargo\bin\cargo.exe
                      █ Call arguments: 
                      █ Version: 
                      █   cargo 1.78.0 (54d8815d0 2024-03-26)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.9.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.403
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:53] Starting scoop cleanup...
[2024-10-21 16:35:53] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:55] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4249                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4249                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:56] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                      █   
                      █   'main' bucket:
                      █   c5d09c1bf temporal-cli: Update to version 1.1.1
                      █   
                      █   'extras' bucket:
                      █   df775a156 youtrack: Update to version 2024.3.47707
                      █   
                      █   'sysinternals' bucket:
                      █   6b2b695 sysmon: Update to version 15.15
                      █   
                      █   'nerd-fonts' bucket:
                      █   c6d9e8d2 SarasaGothic: Update to version 1.0.22
                      █   
                      █   'java' bucket:
                      █   5620947d microsoft21-jdk: Update to version 21.0.5
                      █   
                      █   'games' bucket:
                      █   f1ac08a37 pcsx2-dev: Update to version 2.1.217
                      █   
                      █   'charmbracelet' bucket:
                      █   0d11064 Scoop update for mods version v1.6.0
                      █   
                      █   'pillager' bucket:
                      █   99b8b33 Scoop update for pillager version v0.8.1
                      █   
                      █   'rsteube' bucket:
                      █   0fbd71d Scoop update for carapace-bin version v1.0.7
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:56] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Users\legor\scoop\shims\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.5
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-10-21 16:35:56] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024-10-21 16:35:58] Scoop cleanup finished!
[2024-10-21 16:35:59] Found 11 installed packages from Cargo
[2024-10-21 16:35:59] Found 0 available updates from .NET Tool
[2024-10-21 16:36:00] Found 5 installed packages from .NET Tool
[2024-10-21 16:36:00] Dependency Scoop-Search for manager Scoop is present
[2024-10-21 16:36:02] Found 4 available updates from Cargo
[2024-10-21 16:36:03] Ignored updates database was never loaded, so it is going to be loaded now
[2024-10-21 16:36:03] Found 0 available updates from PowerShell
[2024-10-21 16:36:03] Dependency Git for manager Scoop is present
[2024-10-21 16:36:03] Found 0 installed packages from PowerShell
[2024-10-21 16:36:04] Dependency cargo-update for manager Cargo is present
[2024-10-21 16:36:04] Found 207 installed packages from Winget
[2024-10-21 16:36:04] Dependency .NET Tools Outdated for manager .NET Tool is present
[2024-10-21 16:36:07] Found 4 installed packages from PowerShell7
[2024-10-21 16:36:09] Found 1 available updates from Npm
[2024-10-21 16:36:10] Found 199 installed packages from Scoop
[2024-10-21 16:36:11] Found 2 available updates from Winget
[2024-10-21 16:36:12] Found 15 installed packages from Npm
[2024-10-21 16:36:12] Backup saved to C:\Users\legor\.config\packages\EHDGE installed packages.ubundle
[2024-10-21 16:36:14] Found 199 installed packages from Scoop
[2024-10-21 16:36:19] Found 0 available updates from PowerShell7
[2024-10-21 16:36:26] Upgradable scoop package not listed on installed packages - id=tableplus
[2024-10-21 16:36:26] Upgradable scoop package not listed on installed packages - id=wingetui
[2024-10-21 16:36:26] Found 5 available updates from Scoop
[2024-10-21 16:36:26] Loaded operation parameters for package id=codeql on manager Scoop and operation Update: update main/codeql
[2024-10-21 16:36:26] Loaded operation parameters for package id=typstyle on manager Cargo and operation Update: install-update typstyle
[2024-10-21 16:36:27] Loaded operation parameters for package id=choose on manager Cargo and operation Update: install-update choose
[2024-10-21 16:36:27] Loaded operation parameters for package id=gimp on manager Scoop and operation Update: update extras/gimp
[2024-10-21 16:36:27] Loaded operation parameters for package id=zeitfetch on manager Cargo and operation Update: install-update zeitfetch
[2024-10-21 16:36:27] Loaded operation parameters for package id=vivid on manager Cargo and operation Update: install-update vivid
[2024-10-21 16:36:27] Loaded operation parameters for package id=Discord.Discord on manager Winget and operation Update: update --id "Discord.Discord" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[2024-10-21 16:36:27] Loaded operation parameters for package id=python on manager Scoop and operation Update: update main/python
[2024-10-21 16:36:27] Loaded operation parameters for package id=glzr-io.glazewm on manager Winget and operation Update: update --id "glzr-io.glazewm" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[2024-10-21 16:36:27] Loaded operation parameters for package id=sqlite on manager Scoop and operation Update: update main/sqlite
[2024-10-21 16:36:27] Loaded operation parameters for package id=telegram on manager Scoop and operation Update: update extras/telegram
[2024-10-21 16:36:28] Loaded operation parameters for package id=jsdoc on manager Npm and operation Update: install jsdoc@4.0.4 jsdoc --global
[2024-10-21 16:36:30] An error occurred while retrieving the icon for package codeql
[2024-10-21 16:36:30] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[2024-10-21 16:36:37] An error occurred while retrieving the icon for package telegram
[2024-10-21 16:36:37] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[2024-10-21 19:54:55] Found 0 screenshots for package Id=python
[2024-10-21 19:54:57] Loaded details for package python on manager Scoop
[2024-10-21 19:54:57] Loaded operation parameters for package id=python on manager Scoop and operation Update: update main/python
[2024-10-21 19:54:59] Loaded operation parameters for package id=python on manager Scoop and operation Update: update main/python
[2024-10-21 20:36:03] UniGetUI is up to date
[2024-10-21 20:44:26] Found 0 screenshots for package Id=MartiCliment.UniGetUI.Pre-Release
[2024-10-21 20:44:35] Loaded details for package MartiCliment.UniGetUI.Pre-Release on manager Winget
[2024-10-21 20:44:35] Loaded operation parameters for package id=MartiCliment.UniGetUI.Pre-Release on manager Winget and operation Uninstall: uninstall --id "MartiCliment.UniGetUI.Pre-Release" --exact --source winget --accept-source-agreements --disable-interactivity --version "3.1.2" --silent
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-10-21 16:35:52
Process end time:   2024-10-21 16:35:52

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\legor\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-10-21 16:35:56
Process end time:   2024-10-21 16:35:58

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-10-21 16:35:56
Process end time:   2024-10-21 16:36:04

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-10-21 16:35:58
Process end time:   2024-10-21 16:35:58

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024-10-21 16:36:04
Process end time:   2024-10-21 16:36:11

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 2024-10-21 20:44:26
Process end time:   2024-10-21 20:44:35

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 2024-10-21 20:44:26
Process end time:   2024-10-21 20:44:31

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
The scoop unigetui package is broken, but is not updated by me, so I can't really fix it.
However, I will try to contact the maintainers to see if I can get it fixed

**Comment by maboloshi** [comment]
The main reason is that `UnigetUI` uses Inno (6.3.0) for packaging, and there is no third-party tool to support unpacking. Also the `UnigetUI` installer does not support unpacking in the `/Dir=$dir /portable` way.
I would like to release the `.7z` package directly as an attachment.

**Comment by marticliment** [comment]
This issue will be fixed once https://github.com/ScoopInstaller/Nonportable/pull/362 is merged
