### ISSUE TITLE
[BUG] Subtitles and Checkboxes almost unreadable in dark mode [hot theme change only]

### ISSUE THREAD

**Issue by ghost** [marticliment/UniGetUI#2883]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2

### Windows version, edition, and architecture

Windows 11 Pro 23H2 x64

### Describe your issue

Subtitles and checkboxes are almost unreadable in darkmode

### UniGetUI Log

```text
[23/10/2024 20:53:15]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.2
[23/10/2024 20:53:15]
[23/10/2024 20:53:15] Version Code:  3,12
[23/10/2024 20:53:15] Encoding Code Page set to 850
[23/10/2024 20:53:17] Using bundled GSudo at C:\Users\rober\AppData\Local\Programs\UniGetUI\Assets\Utilities\gsudo.exe
[23/10/2024 20:53:20] Tried to access a non-existing cached language file! file=C:\Users\rober\AppData\Local\UniGetUI\CachedLanguageFiles\lang_it.json
[23/10/2024 20:53:20] Loaded language locale: it
[23/10/2024 20:53:23] Randomly-generated background API auth token for the current session: vrijbqyqnmwb0jv5ql5s2uekdik49anrx8jqod0du04ck8epvopa449uqt5umvsp
[23/10/2024 20:53:23] Api running on http://localhost:7058
[23/10/2024 20:53:23] Lang files were updated successfully from GitHub
[23/10/2024 20:53:23] UniGetUI is up to date
[23/10/2024 20:53:24] The restored geometry did not have exactly 5 items (found length was 1)
[23/10/2024 20:53:29] Downloaded new icons and screenshots successfully!
[23/10/2024 20:53:29] Command cargo was not found on the system
[23/10/2024 20:53:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:29] Command npm was not found on the system
[23/10/2024 20:53:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\rober\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\rober\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.8.1911
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:30] Adding chocolatey to path since it was not on path.
[23/10/2024 20:53:32] Command scoop was not found on the system
[23/10/2024 20:53:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\rober\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4249                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4249                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Users\rober\AppData\Local\Microsoft\WindowsApps\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.5
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[23/10/2024 20:53:38] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[23/10/2024 20:53:39] Found 0 installed packages from Pip
[23/10/2024 20:53:39] Found 0 available updates from Pip
[23/10/2024 20:53:40] Found 0 installed packages from Chocolatey
[23/10/2024 20:53:40] Found 0 available updates from Chocolatey
[23/10/2024 20:53:41] Found 0 installed packages from PowerShell
[23/10/2024 20:53:41] Found 0 installed packages from PowerShell7
[23/10/2024 20:53:41] Found 0 available updates from PowerShell
[23/10/2024 20:53:42] Found 0 available updates from PowerShell7
[23/10/2024 20:53:43] Found 231 installed packages from Winget
[23/10/2024 20:53:43] Ignored updates database was never loaded, so it is going to be loaded now
[23/10/2024 20:53:43] Found 11 available updates from Winget
[23/10/2024 20:53:50] Command parse_pip_search.exe was not found on the system
[23/10/2024 20:53:50] Error finding packages on manager Pip with query paint.net
[23/10/2024 20:53:50] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Users\rober\AppData\Local\Programs\UniGetUI'. Impossibile trovare il file specificato.)
                       ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Users\rober\AppData\Local\Programs\UniGetUI'. Impossibile trovare il file specificato.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 95
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass52_0.<FindPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
[23/10/2024 20:53:51] Found 2 available packages from Winget with the query paint.net
[23/10/2024 20:53:52] Found 1 available packages from Chocolatey with the query paint.net
[23/10/2024 20:53:58] Loaded operation parameters for package id=dotPDN.PaintDotNet on manager Winget and operation Install: install --id "dotPDN.PaintDotNet" --exact --source winget --accept-source-agreements --disable-interactivity --silent --accept-package-agreements --force
[23/10/2024 20:53:59] Icon for package dotPDN.PaintDotNet stored on C:\Users\rober\AppData\Local\UniGetUI\CachedMedia\Winget\dotPDN.PaintDotNet.png
[23/10/2024 20:53:59] NEWLY DOWNLOADED Icon for Package=dotPDN.PaintDotNet Manager=Winget Uri=https://s5.postimg.cc/v55fm921z/pdnlogorevisited2.png is VALID (verification method is PackageVersion)
[23/10/2024 20:54:17] Found 1 available packages from PowerShell with the query paint.net
[23/10/2024 20:54:22] Found 1 available packages from PowerShell7 with the query paint.net
[23/10/2024 21:23:45] Found 0 installed packages from Pip
[23/10/2024 21:23:46] Found 0 installed packages from Chocolatey
[23/10/2024 21:23:47] Found 0 installed packages from PowerShell
[23/10/2024 21:23:47] Found 0 installed packages from PowerShell7
[23/10/2024 21:23:49] Found 232 installed packages from Winget
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 23/10/2024 20:53:30
Process end time:   23/10/2024 20:53:30

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\rober\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 23/10/2024 20:53:39
Process end time:   23/10/2024 20:53:39

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23/10/2024 20:53:39
Process end time:   23/10/2024 20:53:43

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 23/10/2024 20:53:39
Process end time:   23/10/2024 20:53:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 23/10/2024 20:53:40
Process end time:   23/10/2024 20:53:43

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 23/10/2024 20:53:50
Process end time:   23/10/2024 20:53:51

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 23/10/2024 21:23:44
Process end time:   23/10/2024 21:23:49

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/2d4ed4f7-a7af-4187-9605-c451efa47173)

**Comment by marticliment** [comment]
Have you tried restarting UniGetUI after switching theme to dark?

**Comment by dearpowa** [comment]
Just restarted it, and it actually fixed it, but now changing it back to light mode result in the same elements not being visible, I guess it's a problem of "hot swapping" the theme without a restart

**Comment by marticliment** [comment]
Ok, I will investigate this issue then

**Comment by mrixner** [comment]
This looks like it's fixed on the main branch, is that correct? Otherwise I was going to add a Restart Required banner to `ThemeSelector_ValueChanged()` to make it clearer that a restart is needed, but it doesn't look like that's necessary.

**Comment by marticliment** [comment]
Is it? I haven't changed anything, perhaps the bug was caused by WinUI and they fixed it

**Comment by mrixner** [comment]
Ahh, never mind. It's just fickle; sorry.
