### ISSUE TITLE
[BUG] Repeatedly need to repair Winget

### ISSUE THREAD

**Issue by cmdshft** [marticliment/UniGetUI#2917]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Win 11 Pro 22631.4391

### Describe your issue

When starting UniGetUI, it reports that Winget is broken and needs repair. Repair runs successfully, but then randomly when running UniGetUI, it's reported as broken again for an unknown reason.

### Steps to reproduce the issue

Start UniGetUI and it randomly breaks Winget

### UniGetUI Log

```text
[11/1/2024 1:41:52 AM]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.3
[11/1/2024 1:41:52 AM]
[11/1/2024 1:41:52 AM] Version Code:  3.13001
[11/1/2024 1:41:52 AM] Encoding Code Page set to 437
[11/1/2024 1:41:52 AM] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[11/1/2024 1:41:52 AM] Loaded language locale: en
[11/1/2024 1:41:53 AM] Randomly-generated background API auth token for the current session: awju3xufrv6bbom0v6fxv7beifslnjg7s50m590to6vdo59n9b4xqtcfbnc8t3kp
[11/1/2024 1:41:53 AM] Api running on http://localhost:7058
[11/1/2024 1:41:53 AM] Lang files were updated successfully from GitHub
[11/1/2024 1:41:53 AM] UniGetUI is up to date
[11/1/2024 1:41:54 AM] Downloaded new icons and screenshots successfully!
[11/1/2024 1:41:54 AM] Command npm was not found on the system
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:54 AM] Command cargo was not found on the system
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Cargo
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pip
                       █ Executable path: C:\Users\cmdshft\AppData\Local\Microsoft\WindowsApps\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\cmdshft\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: v1.8.1911
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:54 AM] Command scoop was not found on the system
[11/1/2024 1:41:54 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:55 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: choco.exe
                       █ Executable path: C:\Users\cmdshft\AppData\Local\UniGetUI\Chocolatey\choco.exe
                       █ Call arguments: 
                       █ Version: 
                       █   2.2.2
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:56 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pwsh.exe
                       █ Executable path: C:\Users\cmdshft\AppData\Local\Microsoft\WindowsApps\pwsh.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   PowerShell 7.4.6
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:56 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.22621.4391                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.22621.4391                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[11/1/2024 1:41:56 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[11/1/2024 1:41:56 AM] Found 0 installed packages from Pip
[11/1/2024 1:41:56 AM] Found 0 available updates from Pip
[11/1/2024 1:41:57 AM] Found 1 installed packages from Chocolatey
[11/1/2024 1:41:57 AM] Ignored updates database was never loaded, so it is going to be loaded now
[11/1/2024 1:41:57 AM] Found 0 available updates from Chocolatey
[11/1/2024 1:41:57 AM] Found 1 installed packages from PowerShell
[11/1/2024 1:41:57 AM] Found 2 installed packages from PowerShell7
[11/1/2024 1:41:59 AM] Found 0 available updates from PowerShell
[11/1/2024 1:41:59 AM] Found 12 available updates from Winget
[11/1/2024 1:41:59 AM] Found 237 installed packages from Winget
[11/1/2024 1:41:59 AM] Found 0 available updates from PowerShell7
[11/1/2024 1:42:03 AM] Found 0 installed packages from Pip
[11/1/2024 1:42:04 AM] Found 1 installed packages from Chocolatey
[11/1/2024 1:42:04 AM] Found 237 installed packages from Winget
[11/1/2024 1:42:04 AM] Found 2 installed packages from PowerShell7
[11/1/2024 1:42:04 AM] Found 1 installed packages from PowerShell
[11/1/2024 1:42:05 AM] Loaded operation parameters for package id=Audacity.Audacity on manager Winget and operation Update: update --id "Audacity.Audacity" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[11/1/2024 1:42:05 AM] Icon for package Mozilla.Firefox stored on C:\Users\cmdshft\AppData\Local\UniGetUI\CachedMedia\Winget\Mozilla.Firefox.ico
[11/1/2024 1:42:05 AM] Icon for package Audacity.Audacity stored on C:\Users\cmdshft\AppData\Local\UniGetUI\CachedMedia\Winget\Audacity.Audacity.ico
[11/1/2024 1:42:05 AM] NEWLY DOWNLOADED Icon for Package=Audacity.Audacity Manager=Winget Uri=https://cdn.winget.microsoft.com/icons/9adaf3397de72c8ef34c341311a489d94ca149803af846e8b4616dac323aba8b.ico is VALID (verification method is SHA256)
[11/1/2024 1:42:05 AM] NEWLY DOWNLOADED Icon for Package=Mozilla.Firefox Manager=Winget Uri=https://cdn.winget.microsoft.com/icons/fc73cd8d65c449fefaa5fe5f18b4e800e3ef73e63908a375686bd2db2c0adab4.ico is VALID (verification method is SHA256)
[11/1/2024 1:42:11 AM] Loaded operation parameters for package id=Mozilla.Firefox on manager Winget and operation Update: update --id "Mozilla.Firefox" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 11/1/2024 1:41:54 AM
Process end time:   11/1/2024 1:41:54 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\cmdshft\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 11/1/2024 1:41:56 AM
Process end time:   11/1/2024 1:41:56 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 11/1/2024 1:41:56 AM
Process end time:   11/1/2024 1:41:59 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 11/1/2024 1:41:56 AM
Process end time:   11/1/2024 1:41:56 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 11/1/2024 1:41:56 AM
Process end time:   11/1/2024 1:41:59 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 11/1/2024 1:42:03 AM
Process end time:   11/1/2024 1:42:04 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/107431b6-efb8-41c0-8bd5-16d1a5da1112)

**Comment by marticliment** [comment]
When saying randomly, you mean always or 1 out of X times?

**Comment by cmdshft** [comment]
> When saying randomly, you mean always or 1 out of X times?

I cannot reproduce it manually, it just happens. It could happen 0 of 5 times, or 3 of 5 times.

**Comment by marticliment** [comment]
When UniGetUI reports WinGet needs to be repaired, if you refresh the "Installed Packages" page do your WinGet packages appear there?

**Comment by cmdshft** [comment]
> When UniGetUI reports WinGet needs to be repaired, if you refresh the "Installed Packages" page do your WinGet packages appear there?

I don't know to be honest, when this happened I was always in the Software Updates tab. I didn't think to check the first tab (this is because I run UniGetUI in the background and only ever open it in that tab).

**Comment by marticliment** [comment]
When this issue happens again, attempt to reload all software pages without repairing winget, and let me know if you see less packages

**Comment by ezande** [comment]
Same issue here. W10 system. Used repair for winget when asked for but after restart of wingetui again "WinGet malfunction detected" appears. The only installed package left is Microsoft.WinGet,Client (1.9.25190), nothing else.
Every time I restart the repair option is shown.

**Comment by marticliment** [comment]
What is the output of running `winget list` on a command prompt?

**Comment by ezande** [comment]
That gives me the full list
Log file shows

`[02/11/2024 15:53:24] Error finding installed packages on manager Winget
[02/11/2024 15:53:24] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                       ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 211                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 176
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 102
                         at System.Threading.Tasks.Task 1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 228
`

**Comment by ezande** [comment]
Maybe this causes an issue when running winget from within UniGetUI:
```
C:\>winget list
The msstore source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No:
```
I have to acknowledge that each time winget is being run.

**Comment by marticliment** [comment]
Every single time you run `winget list` you are requested  to accept the msstore agreements? Or only after attempting to repair WinGet from UniGetUI?

**Comment by cmdshft** [comment]
I haven't had that issue, but when I too tried to update Microsoft.WinGet,Client (1.9.25190) via UniGetUI, it would fail and then I would try the command manually in CLI and I had to agree, but then that also failed too (something about -Scope not working). But that's a different issue than the bug(?) I reported.

**Comment by marticliment** [comment]
This is a different bug, and is being tracked here: https://github.com/marticliment/UniGetUI/issues/2814

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/db9e5863-7927-458e-a018-4c12c51e1071)

Think it's related:
This message appears all the time, and the fix doesn't fix it!

**Comment by wplj** [comment]
I have the same issue.
My `winget` works fine from the CLI (`v1.9.25180`) (both from PowerShell Core and Windows PowerShell), nothing seems to be broken.

**Comment by wplj** [comment]
Ok, I just ran `winget list` from the CLI to confirm it works and show the output here, and I noticed that recently updated winget shows this prompt:
```
"The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US"). Do you agree to all the source agreements terms?
[Y] Yes  [N] No: "
```
and waits for input. After I agreed to the terms, and ran UniGetUI scan for updates again - it worked.
So probably UniGetUI should handle such "interactive scenarios" and use corresponding switches or API parameters when invoking external utilities.

**Comment by baumheld** [comment]
Having the same issue. I think got this notice around 5-8 times already.
I tried also uninstalled Winget (not WingetUI/UniGet) and then installed it again, but some days later the notice popped up again

The reinstallation through the UniGetUI itself seems to work, it just doesn't resolve the underlying issue for a long time

**Comment by larsen0815** [comment]
Same here. Installed today. UniGetUI showed available updates. I uninstalled some programs, ignored other ones, updated one or two. Then after a while (no idea what might have caused this) got an error on updating a program (didn't save the error message, something about "access denied" and "store reset"), so first reaction is to restart. I was then greeted by the repair message, tried that, restarted, but the repair message shows up again and again.

```
PS C:\WINDOWS\system32> winget list
Die Quelle "msstore" erfordert, dass Sie die folgenden Vereinbarungen vor der Verwendung anzeigen.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Die Quelle erfordert, dass die geografische Region des aktuellen Computers aus 2 Buchstaben an den Back-End-Dienst gesendet wird, damit er ordnungsgemäß funktioniert (z. B. „US“).

Stimmen Sie allen Nutzungsbedingungen der Quelle zu?
[Y] Ja  [N] Nein: y
Fehler beim Durchsuchen der Quelle. Ergebnisse werden nicht einbezogen: winget
Name                                                           ID                                                                     Version
--------------------------------------------------------------------------------------------------------------------------------------------------------
yEd Graph Editor 3.23.2                                        ARP\Machine\X64\3309-7404-0599-8908                                    3.23.2
Reolink 8.15.7                                                 ARP\Machine\X64\3e633401-0468-5835-935c-33d2b4b2a764                   8.15.7
...
```


Second run:

```
PS C:\WINDOWS\system32> winget list
Fehler beim Durchsuchen der Quelle. Ergebnisse werden nicht einbezogen: winget
Name                                                           ID                                                                     Version
--------------------------------------------------------------------------------------------------------------------------------------------------------
...
```


Translates to "Error on scanning the source. Results are ignored: winget"

**Comment by larsen0815** [comment]
Tried the solution from https://forums.tomshardware.com/threads/first-unigetui-breaks-so-i-try-winget-command-line-tool-instead-but-that-breaks-as-well.3853568. Didn't work.

**Comment by Gerome100** [comment]
For me, it seems to happen every reboot of my machine.

**Comment by ROBYER1** [comment]
Same issue here, UnigetUI installed via windows store on Win 11, this issue seems to happen because I am on a non admin user for a work pc so I have to use admin password on popups for install actions. What happens is eventually a package doesn't install because winget doesn't have admin access to overwrite the hash of an installer and there is an admin command prompt line I have to put through to let Winget overwrite the installer hash or something like this `winget settings --enable InstallerHashOverride`. Once I have done that, after a few system restarts or days this repair Winget popup shows for me. It doesn't happen again if I clean uninstall UnigetUI until I do the same process as above where I do the installerhashoverride setting.

**Comment by Gerome100** [comment]
Just that you know, it is still happening when it starts before an internet connection could be established.
