### ISSUE TITLE
[BUG] UniGetUI wants to upgrade .Net 4.8 to .Net 4.8.1 but this is not supported on Windows 1809

### ISSUE THREAD

**Issue by tps800** [marticliment/UniGetUI#2949]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 10 1809 x64

### Describe your issue

UniGetUI wants to upgrade software not designed for Windows 10 1809 and fails in tune

### Steps to reproduce the issue

1. Have Windows 10 1809 installed
2. Then install .Net 4.8
3. Start UniGetUI.
4. It will offer to upgrade .Net 4.8 to .Net 4.8.1
5. This will fail, because .Net 4.8.1 only installs on Windows 10 20H2 and up.

### UniGetUI Log

```text
[Fr, 08.Nov..2024 13:48:03]    __  __      _ ______     __  __  ______
                              / / / /___  (_) ____/__  / /_/ / / /  _/
                             / / / / __ \/ / / __/ _ \/ __/ / / // /
                            / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                            \____/_/ /_/_/\____/\___/\__/\____/___/
                                Welcome to UniGetUI Version 3.1.3
[Fr, 08.Nov..2024 13:48:03]
[Fr, 08.Nov..2024 13:48:03] Version Code:  3,13001
[Fr, 08.Nov..2024 13:48:04] Encoding Code Page set to 850
[Fr, 08.Nov..2024 13:48:10] Using bundled GSudo at C:\PRGS\UniGetUI\Assets\Utilities\gsudo.exe
[Fr, 08.Nov..2024 13:48:13] Loaded language locale: de
[Fr, 08.Nov..2024 13:48:16] Lang files were updated successfully from GitHub
[Fr, 08.Nov..2024 13:48:16] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Chocolatey
                            ¦ Enabled: True
                            ¦ Found: False
                            ¦ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                            ¦ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:48:21] Command winget.exe was not found on the system
[Fr, 08.Nov..2024 13:48:21] User does not have WinGet installed, forcing bundled WinGet...
[Fr, 08.Nov..2024 13:48:21] Command npm was not found on the system
[Fr, 08.Nov..2024 13:48:21] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Npm
                            ¦ Enabled: True
                            ¦ Found: False
                            ¦ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                            ¦ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:48:28] Command cargo was not found on the system
[Fr, 08.Nov..2024 13:48:28] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Cargo
                            ¦ Enabled: True
                            ¦ Found: False
                            ¦ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                            ¦ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:48:37] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: .NET Tool
                            ¦ Enabled: True
                            ¦ Found: False
                            ¦ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                            ¦ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:48:39] System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://localhost:3128/' failed with status code '504'."
                               at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
                               at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                               at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                               at UniGetUI.MainApp.UpdateUniGetUIIfPossible(Int32 round) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 411
[Fr, 08.Nov..2024 13:48:39] Downloaded new icons and screenshots successfully!
[Fr, 08.Nov..2024 13:48:46] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Winget
                            ¦ Enabled: True
                            ¦ Found: True
                            ¦ Fancy exe name: winget.exe
                            ¦ Executable path: C:\PRGS\UniGetUI\winget-cli_x64\winget.exe
                            ¦ Call arguments: 
                            ¦ Version: 
                            ¦   Bundled WinGet CLI Version: v1.8.1911
                            ¦   Using bundled WinGet helper (CLI parsing)
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:48:51] Command scoop was not found on the system
[Fr, 08.Nov..2024 13:48:51] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Scoop
                            ¦ Enabled: True
                            ¦ Found: False
                            ¦ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                            ¦ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:49:06] PowerShell sources took too long to load, using known sources as default
[Fr, 08.Nov..2024 13:49:06] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: PowerShell
                            ¦ Enabled: True
                            ¦ Found: True
                            ¦ Fancy exe name: powershell.exe
                            ¦ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                            ¦ Call arguments:  -NoProfile -Command
                            ¦ Version: 
                            ¦   Name                           Value                                                                                                                                                          
                            ¦   ----                           -----                                                                                                                                                          
                            ¦   PSVersion                      5.1.17763.6414                                                                                                                                                 
                            ¦   PSEdition                      Desktop                                                                                                                                                        
                            ¦   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
                            ¦   BuildVersion                   10.0.17763.6414                                                                                                                                                
                            ¦   CLRVersion                     4.0.30319.42000                                                                                                                                                
                            ¦   WSManStackVersion              3.0                                                                                                                                                            
                            ¦   PSRemotingProtocolVersion      2.3                                                                                                                                                            
                            ¦   SerializationVersion           1.1.0.1
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:49:11] PowerShell7 sources took too long to load, using known sources as default
[Fr, 08.Nov..2024 13:49:11] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: PowerShell7
                            ¦ Enabled: True
                            ¦ Found: True
                            ¦ Fancy exe name: pwsh.exe
                            ¦ Executable path: C:\PRGS\pwsh\7\pwsh.exe
                            ¦ Call arguments:  -NoProfile -Command
                            ¦ Version: 
                            ¦   PowerShell 7.4.6
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:49:15] Timeout: Not all package managers have finished initializing.
[Fr, 08.Nov..2024 13:49:15] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[Fr, 08.Nov..2024 13:49:22] Resetting administrator rights cache for process id 16092
[Fr, 08.Nov..2024 13:49:24] Resetting administrator rights cache for process id 16092
[Fr, 08.Nov..2024 13:49:36] _____________________________________________
                            ¦¯¯¯¯¯¯¯¯¯¯¯¯¯ MANAGER LOADED ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
                            ¦ Name: Pip
                            ¦ Enabled: True
                            ¦ Found: True
                            ¦ Fancy exe name: pip
                            ¦ Executable path: C:\PRGS\Python\312\python.exe
                            ¦ Call arguments:  -m pip
                            ¦ Version: 
                            ¦   pip 24.3.1 from C:\PRGS\Python\312\Lib\site-packages\pip (python 3.12)
                            ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
[Fr, 08.Nov..2024 13:50:15] Error finding installed packages on manager PowerShell7
[Fr, 08.Nov..2024 13:50:15] System.TimeoutException: The operation has timed out.
                               at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 230
[Fr, 08.Nov..2024 13:50:18] Found 148 installed packages from Winget
[Fr, 08.Nov..2024 13:50:23] Error finding updates on manager PowerShell
[Fr, 08.Nov..2024 13:50:23] System.TimeoutException: The operation has timed out.
                               at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[Fr, 08.Nov..2024 13:50:23] Ignored updates database was never loaded, so it is going to be loaded now
[Fr, 08.Nov..2024 13:50:32] Found 14 available updates from Winget
[Fr, 08.Nov..2024 13:50:38] Could not load announcements
[Fr, 08.Nov..2024 13:50:38] System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://localhost:3128/' failed with status code '504'."
                               at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
                               at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
                               at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                               at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                               at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                               at UniGetUI.Interface.Widgets.Announcer.LoadAnnouncements(Boolean retry) in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Controls\Announcer.xaml.cs:line 57
[Fr, 08.Nov..2024 13:50:46] Found 0 installed packages from PowerShell
[Fr, 08.Nov..2024 13:50:48] Backup saved to C:\Users\<user>\Documents\UniGetUI\<Hostname> installierte Pakete 2024-11-08 13-50-48.ubundle
[Fr, 08.Nov..2024 13:51:00] Found 0 available updates from PowerShell7
[Fr, 08.Nov..2024 13:58:41] UniGetUI is up to date
[Fr, 08.Nov..2024 14:03:51] Loaded operation parameters for package id=Microsoft.Edge on manager Winget and operation Update: update --id "Microsoft.Edge" --exact --source winget --accept-source-agreements --disable-interactivity --interactive --include-unknown --accept-package-agreements --force
[Fr, 08.Nov..2024 14:03:53] Icon for package Microsoft.Edge stored on C:\Users\<user>\AppData\Local\UniGetUI\CachedMedia\Winget\Microsoft.Edge.png
[Fr, 08.Nov..2024 14:03:53] NEWLY DOWNLOADED Icon for Package=Microsoft.Edge Manager=Winget Uri=https://i.postimg.cc/pd256kHk/logo.png is VALID (verification method is PackageVersion)
[Fr, 08.Nov..2024 14:14:21] Resetting administrator rights cache for process id 16092
[Fr, 08.Nov..2024 14:24:59] Error finding updates on manager Pip
[Fr, 08.Nov..2024 14:24:59] System.TimeoutException: The operation has timed out.
                               at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[Fr, 08.Nov..2024 14:24:59] Error finding updates on manager PowerShell
[Fr, 08.Nov..2024 14:24:59] System.TimeoutException: The operation has timed out.
                               at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[Fr, 08.Nov..2024 14:24:59] Error finding updates on manager PowerShell7
[Fr, 08.Nov..2024 14:24:59] System.TimeoutException: The operation has timed out.
                               at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[Fr, 08.Nov..2024 14:25:13] Found 12 available updates from Winget
[Fr, 08.Nov..2024 14:30:44] Found 14 installed packages from Pip
[Fr, 08.Nov..2024 14:30:49] Found 0 installed packages from PowerShell
[Fr, 08.Nov..2024 14:30:49] Found 148 installed packages from Winget
[Fr, 08.Nov..2024 14:30:57] Found 0 installed packages from PowerShell7
[Fr, 08.Nov..2024 14:35:22] Loaded operation parameters for package id=gnome.Dia on manager Winget and operation Update: update --id "gnome.Dia" --exact --source winget --accept-source-agreements --disable-interactivity --interactive  --include-unknown --accept-package-agreements --force --location "C:\PRGS\Dia"
[Fr, 08.Nov..2024 14:40:14] Resetting administrator rights cache for process id 16092
[Fr, 08.Nov..2024 14:40:24] Loaded operation parameters for package id=Microsoft.DotNet.Framework.DeveloperPack_4 on manager Winget and operation Update: update --id "Microsoft.DotNet.Framework.DeveloperPack_4" --exact --source winget --accept-source-agreements --disable-interactivity --interactive --include-unknown --accept-package-agreements --force
[Fr, 08.Nov..2024 14:58:45] UniGetUI is up to date
[Fr, 08.Nov..2024 15:47:21] Found 14 installed packages from Pip
[Fr, 08.Nov..2024 15:47:24] Found 0 installed packages from PowerShell
[Fr, 08.Nov..2024 15:47:27] Resetting administrator rights cache for process id 16092
[Fr, 08.Nov..2024 15:47:28] Found 148 installed packages from Winget
[Fr, 08.Nov..2024 15:47:28] Adding missing package ARP\Machine\X86\Vivaldi to installed packages list
[Fr, 08.Nov..2024 15:47:31] Found 0 installed packages from PowerShell7
[Fr, 08.Nov..2024 15:58:47] UniGetUI is up to date
```

### Package Managers Logs

```text
> Powershell.exe -ExecutionPolicy Bypass .\Deploy-DotNet481.ps1 -DeploymentType "Install" -DeployMode "Interactive"
[11-08-2024 15:41:06.944] [Get-LoggedOnUser] :: Getting session information for all logged on users.
[11-08-2024 15:41:07.245] [Get-RegistryKey] :: Registry key [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MUI\Settings] does not exist. Return $null.
[11-08-2024 15:41:07.314] [Get-RegistryKey] :: Getting registry key [Registry::HKEY_USERS\S-1-5-21-2371448200-2626132239-2341880065-2205\Software\Policies\Microsoft\Windows\Control Panel\Desktop] value [PreferredUILanguages].
[11-08-2024 15:41:07.331] [Get-RegistryKey] :: Registry key value [Registry::HKEY_USERS\S-1-5-21-2371448200-2626132239-2341880065-2205\Software\Policies\Microsoft\Windows\Control Panel\Desktop] [PreferredUILanguages] does not exist. Return $null.
[11-08-2024 15:41:07.348] [Get-RegistryKey] :: Getting registry key [Registry::HKEY_USERS\S-1-5-21-2371448200-2626132239-2341880065-2205\Control Panel\Desktop] value [PreferredUILanguages].
[11-08-2024 15:41:07.865] [Initialization] [PSAppDeployToolkit] :: *******************************************************************************
[11-08-2024 15:41:07.865] [Initialization] [PSAppDeployToolkit] :: *******************************************************************************
[11-08-2024 15:41:07.915] [Initialization] [PSAppDeployToolkit] :: [Microsoft_.NETFramework_4.8.1] setup started.
[11-08-2024 15:41:08.701] [Initialization] [PSAppDeployToolkit] :: Script [C:\Users\<user>\Downloads\DotNet481\AppDeployToolkit\AppDeployToolkitMain.ps1] dot-source invoked by [C:\Users\<user>\Downloads\DotNet481\Deploy-DotNet481.ps1]
[11-08-2024 15:41:08.800] [Initialization] [PSAppDeployToolkitExt] :: Script [C:\Users\<user>\Downloads\DotNet481\AppDeployToolkit\AppDeployToolkitExtensions.ps1] dot-source invoked by [C:\Users\<user>\Downloads\DotNet481\AppDeployToolkit\AppDeployToolkitMain.ps1]
[11-08-2024 15:41:08.863] [Initialization] [PSAppDeployToolkit] :: [Microsoft_.NETFramework_4.8.1] script version is [1.0.0]
[11-08-2024 15:41:08.875] [Initialization] [PSAppDeployToolkit] :: [Microsoft_.NETFramework_4.8.1] script date is [XX/XX/20XX]
[11-08-2024 15:41:08.886] [Initialization] [PSAppDeployToolkit] :: [Microsoft_.NETFramework_4.8.1] script author is [Jason Bergner]
[11-08-2024 15:41:08.897] [Initialization] [PSAppDeployToolkit] :: [Deploy Application] script version is [3.8.4]
[11-08-2024 15:41:08.909] [Initialization] [PSAppDeployToolkit] :: The following non-default parameters were passed to [Deploy Application]: [-DeploymentType:'Install' -DeployMode:'Interactive']
[11-08-2024 15:41:08.924] [Initialization] [PSAppDeployToolkit] :: [App Deploy Toolkit Main] script version is [3.10.2]
[11-08-2024 15:41:08.936] [Initialization] [PSAppDeployToolkit] :: [App Deploy Toolkit Extensions] version is [3.10.1]
[11-08-2024 15:41:08.948] [Initialization] [PSAppDeployToolkit] :: Computer Name is [BCL2353-MUC.<dom>.intern]
[11-08-2024 15:41:08.962] [Initialization] [PSAppDeployToolkit] :: Current User is [<dom>\<user>]
[11-08-2024 15:41:08.976] [Initialization] [PSAppDeployToolkit] :: OS Version is [Microsoft Windows 10 Enterprise LTSC 64-bit 10.0.17763.6414]
[11-08-2024 15:41:08.990] [Initialization] [PSAppDeployToolkit] :: OS Type is [Workstation]
[11-08-2024 15:41:09.006] [Initialization] [PSAppDeployToolkit] :: Current Culture is [de-DE], language is [DE] and UI language is [DE]
[11-08-2024 15:41:09.026] [Initialization] [Get-HardwarePlatform] :: Retrieving hardware platform information.
[11-08-2024 15:41:09.063] [Initialization] [PSAppDeployToolkit] :: Hardware Platform is [Physical]
[11-08-2024 15:41:09.082] [Initialization] [PSAppDeployToolkit] :: PowerShell Host is [ConsoleHost] with version [5.1.17763.6414]
[11-08-2024 15:41:09.095] [Initialization] [PSAppDeployToolkit] :: PowerShell Version is [5.1.17763.6414 x64]
[11-08-2024 15:41:09.110] [Initialization] [PSAppDeployToolkit] :: PowerShell CLR (.NET) version is [4.0.30319.42000]
[11-08-2024 15:41:09.126] [Initialization] [PSAppDeployToolkit] :: *******************************************************************************
[11-08-2024 15:41:09.154] [Initialization] [PSAppDeployToolkit] :: Display session information for all logged on users:


NTAccount           : <dom>\<user>
SID                 : S-1-5-21-2371448200-2626132239-2341880065-2205
UserName            : <user>
DomainName          : <dom>
SessionId           : 1
SessionName         : Console
ConnectState        : Active
IsCurrentSession    : True
IsConsoleSession    : True
IsActiveUserSession : True
IsUserSession       : True
IsRdpSession        : False
IsLocalAdmin        : False
LogonTime           : 08.11.2024 09:21:23
IdleTime            : 00:00:00
DisconnectTime      :
ClientName          :
ClientProtocolType  :
ClientDirectory     :
ClientBuildNumber   : 0




[11-08-2024 15:41:09.172] [Initialization] [PSAppDeployToolkit] :: The following users are logged on to the system: [<dom>\<user>].
[11-08-2024 15:41:09.186] [Initialization] [PSAppDeployToolkit] :: Current process is running with user account [<dom>\<user>] under logged in user session for [<dom>\<user>].
[11-08-2024 15:41:09.462] [Initialization] [PSAppDeployToolkit] :: The following user is the console user [<dom>\<user>] (user with control of physical monitor, keyboard, and mouse).
[11-08-2024 15:41:09.476] [Initialization] [PSAppDeployToolkit] :: The active logged on user is [<dom>\<user>].
[11-08-2024 15:41:09.491] [Initialization] [PSAppDeployToolkit] :: The active logged on user [<dom>\<user>] has a primary UI language of [DE].
[11-08-2024 15:41:09.505] [Initialization] [PSAppDeployToolkit] :: The following UI messages were imported from the config XML file: [UI_Messages_DE].
[11-08-2024 15:41:09.520] [Initialization] [PSAppDeployToolkit] :: The active logged on user [<dom>\<user>] has a DPI scale factor of [100] with DPI pixels [96].
[11-08-2024 15:41:09.557] [Initialization] [PSAppDeployToolkit] :: Unable to load COM Object [Microsoft.SMS.TSEnvironment]. Therefore, script is not currently running from a SCCM Task Sequence.
[11-08-2024 15:41:09.576] [Initialization] [PSAppDeployToolkit] :: Skipping attempt to check for and make the task scheduler services healthy, because the App Deployment Toolkit is not running under the [NT-AUTORITÄT\SYSTEM] account.
[11-08-2024 15:41:09.590] [Initialization] [PSAppDeployToolkit] :: Session 0 not detected.
[11-08-2024 15:41:09.608] [Initialization] [PSAppDeployToolkit] :: Installation is running in [Interactive] mode.
[11-08-2024 15:41:09.629] [Initialization] [PSAppDeployToolkit] :: Deployment type is [Installation].
[11-08-2024 15:41:09.719] [Installation] [Deploy-DotNet481] :: Microsoft .NET Framework 4.8.1 only applies to Windows 10 Version 20H2 and later.
[11-08-2024 15:41:09.761] [Post-Installation] [Close-InstallationProgress] :: The installation progress dialog does not exist. Waiting up to 5 seconds...
[11-08-2024 15:41:14.784] [Post-Installation] [Close-InstallationProgress] :: The installation progress dialog was not created within 5 seconds.
[11-08-2024 15:41:14.818] [Post-Installation] [Exit-Script] :: Microsoft_.NETFramework_4.8.1 Installation completed with exit code [0].
[11-08-2024 15:41:14.896] [Post-Installation] [Test-PowerPoint] :: Checking if PowerPoint is in either fullscreen slideshow mode or presentation mode...
[11-08-2024 15:41:14.928] [Post-Installation] [Test-PowerPoint] :: PowerPoint application is not running.
[11-08-2024 15:41:14.941] [Post-Installation] [Test-PowerPoint] :: PowerPoint is running in fullscreen mode [False].
[11-08-2024 15:41:14.960] [Post-Installation] [Show-BalloonTip] :: Displaying balloon tip notification asynchronously with message [Installation abgeschlossen.].
[11-08-2024 15:41:15.011] [Post-Installation] [Execute-Process] :: [C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe] is a valid fully qualified path, continue.
[11-08-2024 15:41:15.044] [Post-Installation] [Execute-Process] :: UseShellExecute is set to true, standard output and error will not be available.
[11-08-2024 15:41:15.063] [Post-Installation] [Execute-Process] :: Working Directory is [C:\Windows\System32\WindowsPowerShell\v1.0].
[11-08-2024 15:41:15.080] [Post-Installation] [Execute-Process] :: Executing [C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [PowerShell ScriptBlock]]...
[11-08-2024 15:41:15.221] [Post-Installation] [Execute-Process] :: NoWait parameter specified. Continuing without waiting for exit code...
[11-08-2024 15:41:15.253] [Post-Installation] [Exit-Script] :: -------------------------------------------------------------------------------
```

### Relevant information

Software installs only on newer Windows versions, not the one trying the upgrade.

**Comment by marticliment** [comment]
this is an issue that should be reported to microsoft/winget-pkgs
