### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by Cosmosatogiri** [marticliment/UniGetUI#3002]
### Please confirm these before moving forward.

- [X] I have tried deleting a folder named `UniGetUI` under `%UserProfile%\AppData\Local\UniGetUI`.
- [X] I have tried reinstalling UniGetUI.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

BOOTING UP THE PC 

### Logs (if possible)

```text
OS: Win32NT
                   Version: Microsoft Windows NT 10.0.19045.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.1.2
                Executable: C:\Users\NEW PC\AppData\Local\Programs\UniGetUI\UniGetUI.exe

Crash Message: The text associated with this error code could not be found.

Failed to assign to property 'UniGetUI.Interface.Widgets.TranslatedTextBlock.Text'. [Line: 0 Position: 0]

Crash Traceback:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at UniGetUI.Interface.MainWindow.InitializeComponent() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\obj\x64\Release\net8.0-windows10.0.22621.0\win-x64\MainWindow.g.i.cs:line 71
   at UniGetUI.Interface.MainWindow..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\MainWindow.xaml.cs:line 57
   at UniGetUI.MainApp.InitializeMainWindow() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App.xaml.cs:line 169
   at UniGetUI.MainApp..ctor() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\App
```

### More details

NOPE

**Comment by marticliment** [comment]
Please upgrade to version 3.1.3
