### ISSUE TITLE
 [BUG] WinGet funktioniert nicht richtig in UniGetUI Version 3.1.3

### ISSUE THREAD

**Issue by gseilheimer** [marticliment/UniGetUI#3008]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 Pro 26100.2161

### Describe your issue

WinGet wird in UniGetUI als fehlerhaft angezeigt. Die Meldung "WinGet scheint nicht richtig zu funktionieren. Möchten Sie versuchen WinGet zu reparieren?" wird eingeblendet, obwohl WinGet installiert ist. Die Reparatur scheitert und der Fehler erscheint erneut.

### Steps to reproduce the issue

Starten Sie UniGetUI Version 3.1.3.
Gehen Sie zu den Software-Updates oder anderen Bereichen, die WinGet verwenden.
Die Fehlermeldung wird im oberen Bereich der Anwendung angezeigt.

### UniGetUI Log

```text
[22.11.2024 21:04:14]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.3
[22.11.2024 21:04:14]
[22.11.2024 21:04:14] Version Code:  3,13001
[22.11.2024 21:04:14] Encoding Code Page set to 850
[22.11.2024 21:04:14] Copying C:\Users\GS\.wingetui\AlreadyWarnedAboutNameChange
[22.11.2024 21:04:14] Copying C:\Users\GS\.wingetui\ChocolateyAddedToPath
[22.11.2024 21:04:14] Deleting old Chocolatey directory C:\Users\GS\.wingetui
[22.11.2024 21:04:15] Command gsudo.exe was not found on the system
[22.11.2024 21:04:15] Loaded language locale: de
[22.11.2024 21:04:16] Deleting old Chocolatey directory C:\Users\GS\AppData\Local\WingetUI\CachedData
[22.11.2024 21:04:16] Randomly-generated background API auth token for the current session: pf3q89kbgcv9mbnogs8i45l6otorm1wtciuhl5vj38a11a9bfka6nmnx7x648u4n
[22.11.2024 21:04:16] Api running on http://localhost:7058
[22.11.2024 21:04:16] System GSudo enabled but not found!
[22.11.2024 21:04:16] Lang files were updated successfully from GitHub
[22.11.2024 21:04:16] UniGetUI is up to date
[22.11.2024 21:04:17] Downloaded new icons and screenshots successfully!
[22.11.2024 21:04:17] Command npm was not found on the system
[22.11.2024 21:04:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:17] Command cargo was not found on the system
[22.11.2024 21:04:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\GS\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:17] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Program Files\WingetUI\choco-cli\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:18] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\GS\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.25200
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:19] Command scoop was not found on the system
[22.11.2024 21:04:19] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.2161                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.2161                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Users\GS\AppData\Local\Microsoft\WindowsApps\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[22.11.2024 21:04:20] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[22.11.2024 21:04:20] Found 0 installed packages from Chocolatey
[22.11.2024 21:04:20] Found 0 installed packages from Pip
[22.11.2024 21:04:20] Found 0 available updates from Chocolatey
[22.11.2024 21:04:20] Found 0 available updates from Pip
[22.11.2024 21:04:20] Resetting administrator rights cache for process id 26720
[22.11.2024 21:04:20] Could not create new directory. You may perhaps need to disable Controlled Folder Access from Windows Settings or make an exception for UniGetUI.
[22.11.2024 21:04:20] System.IO.FileNotFoundException: Could not find file 'C:\Users\GS\Documents\UniGetUI'.
                      File name: 'C:\Users\GS\Documents\UniGetUI'
                         at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
                         at System.IO.Directory.CreateDirectory(String path)
                         at UniGetUI.Core.Data.CoreData.GetNewDataDirectoryOrMoveOld(String old_path, String new_path) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 306
[22.11.2024 21:04:23] Error finding installed packages on manager Winget
[22.11.2024 21:04:23] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                       ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 211
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 176
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 102
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 228
[22.11.2024 21:04:23] Found 1 installed packages from PowerShell
[22.11.2024 21:04:23] Found 0 installed packages from PowerShell7
[22.11.2024 21:04:23] Ignored updates database was never loaded, so it is going to be loaded now
[22.11.2024 21:04:23] Could not create new directory. You may perhaps need to disable Controlled Folder Access from Windows Settings or make an exception for UniGetUI.
[22.11.2024 21:04:23] System.IO.FileNotFoundException: Could not find file 'C:\Users\GS\Documents\UniGetUI'.
                      File name: 'C:\Users\GS\Documents\UniGetUI'
                         at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
                         at System.IO.Directory.CreateDirectory(String path)
                         at UniGetUI.Core.Data.CoreData.GetNewDataDirectoryOrMoveOld(String old_path, String new_path) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 306
[22.11.2024 21:04:23] An error occurred while performing a backup
[22.11.2024 21:04:23] System.IO.FileNotFoundException: Could not find file 'C:\Users\GS\Documents\UniGetUI'.
                      File name: 'C:\Users\GS\Documents\UniGetUI'
                         at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
                         at System.IO.Directory.CreateDirectory(String path)
                         at UniGetUI.Interface.SoftwarePages.InstalledPackagesPage.BackupPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Pages\SoftwarePages\InstalledPackagesPage.cs:line 377
[22.11.2024 21:04:23] Found 0 available updates from PowerShell7
[22.11.2024 21:04:24] Found 0 available updates from PowerShell
[22.11.2024 21:04:35] Error finding updates on manager Winget
[22.11.2024 21:04:35] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                       ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 211
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 156
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 95
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 197
[22.11.2024 21:09:31] Found 0 installed packages from Chocolatey
[22.11.2024 21:09:32] Found 0 installed packages from Pip
[22.11.2024 21:09:34] Found 0 installed packages from PowerShell7
[22.11.2024 21:09:34] Found 1 installed packages from PowerShell
[22.11.2024 21:09:39] Error finding installed packages on manager Winget
[22.11.2024 21:09:39] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                       ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages(INativeTaskLogger logger) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 211
                         at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetInstalledPackages_UnSafe(WinGet Manager) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGetHelpers\NativeWinGetHelper.cs:line 176
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 102
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 228
[22.11.2024 21:09:39] Could not create new directory. You may perhaps need to disable Controlled Folder Access from Windows Settings or make an exception for UniGetUI.
[22.11.2024 21:09:39] System.IO.FileNotFoundException: Could not find file 'C:\Users\GS\Documents\UniGetUI'.
                      File name: 'C:\Users\GS\Documents\UniGetUI'
                         at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
                         at System.IO.Directory.CreateDirectory(String path)
                         at UniGetUI.Core.Data.CoreData.GetNewDataDirectoryOrMoveOld(String old_path, String new_path) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 306
[22.11.2024 21:09:39] An error occurred while performing a backup
[22.11.2024 21:09:39] System.IO.FileNotFoundException: Could not find file 'C:\Users\GS\Documents\UniGetUI'.
                      File name: 'C:\Users\GS\Documents\UniGetUI'
                         at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
                         at System.IO.Directory.CreateDirectory(String path)
                         at UniGetUI.Interface.SoftwarePages.InstalledPackagesPage.BackupPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI\Pages\SoftwarePages\InstalledPackagesPage.cs:line 377
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 22.11.2024 21:04:18
Process end time:   22.11.2024 21:04:18

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\GS\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 22.11.2024 21:04:20
Process end time:   22.11.2024 21:04:28

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 22.11.2024 21:04:20
Process end time:   22.11.2024 21:04:23

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 22.11.2024 21:04:20
Process end time:   22.11.2024 21:04:20

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 22.11.2024 21:04:28
Process end time:   22.11.2024 21:04:35

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 22.11.2024 21:09:31
Process end time:   22.11.2024 21:09:39

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 22.11.2024 21:15:55
Process end time:   22.11.2024 21:15:58

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————
```

### Screenshots and videos

![Screenshot 2024-11-22 211755](https://github.com/user-attachments/assets/20e49a71-f277-471f-b510-24d874383488)

**Comment by marticliment** [comment]
Please run the command `winget list` on a command prompt and share here what you see

**Comment by shisva** [comment]
Hi, had the same issue, run cmd as admin and copy past this : winget source reset --force

**Comment by ludwigkreuzpointner** [comment]
Hello. I have the same problem now as  gseilheimer wrote. The way shisva wrote does not solve it for me. I get then a list and accept the tos, but UniGetUI does still not work with winget. 

winget list as user gives:

C:\Windows\System32>winget list
Fehler beim Versuch, die Quelle zu aktualisieren: winget
Fehler beim Öffnen der vordefinierten Quelle. Bitte melden Sie dieses Problem an die Entwickler von winget.
Unerwarteter Fehler beim Ausführen des Befehls:
0x80070005 : Zugriff verweigert

Any idea? 

On my second computer it works fine. Thank you for this software!

**Comment by borque** [comment]
Hi!
I have the same issue. Running UniGetUI from an account which is member of the Administrators group does not cause any problems. Running it from a normal user account results in the issue described above.
Unfortunatly @shisva method requires admin rights and does not repair  it for normal users.
Here is the (german) output of "winget list":

Fehler beim Versuch, die Quelle zu aktualisieren: winget
Fehler beim Öffnen der vordefinierten Quelle. Bitte melden Sie dieses Problem an die Entwickler von winget.
Unerwarteter Fehler beim Ausführen des Befehls:
0x80070005 : Zugriff verweigert

It is interesting, that this problem occured suddenly. UniGetUI was working, but after I had closed it completely and restarted it a bit later, the error occured.

**Comment by borque** [comment]
I think, I have found the solution:
This is not a problem with UniGetUI but with wrong access rights for wingets temp folder that -for whatever reason- seems to miss accessrights for the user encountering that error.

Solution:
Go to %localappdata%/temp , locate and delete the WinGet directory there. It might trigger an UAC-request due to the missing rights, which are the reason for that problem.
Once deleted run winget list in a Terminal and everything should be fine.

**Comment by borque** [comment]
Doing some further investigation, gsudo might be the culprid:

https://github.com/microsoft/winget-cli/issues/4704#issuecomment-2411879890

**Comment by marticliment** [comment]
I am aware of this, but I can't happen to find why gsudo will cause this issue when regular UAC won't

**Comment by gseilheimer** [comment]
> I think, I have found the solution: This is not a problem with UniGetUI but with wrong access rights for wingets temp folder that -for whatever reason- seems to miss accessrights for the user encountering that error.
> 
> Solution: Go to %localappdata%/temp , locate and delete the WinGet directory there. It might trigger an UAC-request due to the missing rights, which are the reason for that problem. Once deleted run winget list in a Terminal and everything should be fine.
> 
> **Edit:** This seems to be only a temporary solution: after following the procedure mentioned above the first run of WinGetUI is fine. But when starting it again after installing software with Admin priviliges the error is back again. So doing installations with elevated rights seem to mess up the access rights to WinGets temp folders. Whether this is UniGetUIs or WinGets fault I can not say right now.

Thank you for the detailed explanation and workaround!

This solution worked for me as well, and I agree it should be added to the FAQs since it seems to address a recurring issue.

The fact that the error reappears after installations with elevated privileges suggests that the access rights of the temp folder are being reset during that process. This seems more like a permissions issue with WinGet itself, which is being exposed through UniGetUI. A potential permanent fix could involve either automating a cleanup process or providing a warning/notice within the tool.

Thanks again for the analysis and workaround—it’s greatly appreciated! 👏

**Comment by marticliment** [comment]
> > I think, I have found the solution: This is not a problem with UniGetUI but with wrong access rights for wingets temp folder that -for whatever reason- seems to miss accessrights for the user encountering that error.
> > Solution: Go to %localappdata%/temp , locate and delete the WinGet directory there. It might trigger an UAC-request due to the missing rights, which are the reason for that problem. Once deleted run winget list in a Terminal and everything should be fine.
> > **Edit:** This seems to be only a temporary solution: after following the procedure mentioned above the first run of WinGetUI is fine. But when starting it again after installing software with Admin priviliges the error is back again. So doing installations with elevated rights seem to mess up the access rights to WinGets temp folders. Whether this is UniGetUIs or WinGets fault I can not say right now.
> 
> Thank you for the detailed explanation and workaround!
> 
> This solution worked for me as well, and I agree it should be added to the FAQs since it seems to address a recurring issue.
> 
> The fact that the error reappears after installations with elevated privileges suggests that the access rights of the temp folder are being reset during that process. This seems more like a permissions issue with WinGet itself, which is being exposed through UniGetUI. A potential permanent fix could involve either automating a cleanup process or providing a warning/notice within the tool.
> 
> Thanks again for the analysis and workaround—it’s greatly appreciated! 👏

**Comment by b1naryzer0** [comment]
This helped me:
- close UniGetUI
- close Winget, if active
- enter Windows settings
- choose apps
- choose installed apps
- search for 'package'
- choose 'windows package manager source (winget) v2'
- click on the '...' field on the right 
- 'advanced options'
- 'repair'
- restart UniGetUI
- update your app/s
