### ISSUE TITLE
[BUG] Un/Install as Administrator Results in Error

### ISSUE THREAD

**Issue by ChedRed** [marticliment/UniGetUI#3044]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 Enterprise LTSC IoT 26100.2454

### Describe your issue

When I use the `un/install as administrator` option, I always get the same error. For example, Onecommander log:

```Starting package uninstall operation for package id=MilosParipovic.OneCommander with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\winget.exe"  uninstall --id "MilosParipovic.OneCommander" --exact --source winget --accept-source-agreements --disable-interactivity --version "3.93.0" --silent
Working Directory      : C:\Users\ChedRed
Process Start Time     : 12/2/2024 7:03:29 PM
/v:on : The term '/v:on' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ /v:on /s /c C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\wing ...
+ ~~~~~
+ CategoryInfo          : ObjectNotFound: (/v:on:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException```

### Steps to reproduce the issue

_No response_

### UniGetUI Log

```text
[12/2/2024 7:01:46 PM]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.3
[12/2/2024 7:01:46 PM]
[12/2/2024 7:01:46 PM] Version Code:  3.13001
[12/2/2024 7:01:46 PM] Encoding Code Page set to 437
[12/2/2024 7:01:47 PM] Loaded language locale: en
[12/2/2024 7:01:47 PM] Command gsudo.exe was not found on the system
[12/2/2024 7:01:47 PM] Randomly-generated background API auth token for the current session: p91dlfi6zi3l6ycvfdsfaxd85dgb5wqvej0b712isyfttfclckia11xzmcpq7th6
[12/2/2024 7:01:47 PM] Api running on http://localhost:7058
[12/2/2024 7:01:47 PM] System GSudo enabled but not found!
[12/2/2024 7:01:47 PM] Lang files were updated successfully from GitHub
[12/2/2024 7:01:47 PM] UniGetUI is up to date
[12/2/2024 7:01:47 PM] Downloaded new icons and screenshots successfully!
[12/2/2024 7:01:48 PM] Command pwsh.exe was not found on the system
[12/2/2024 7:01:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pip
                       █ Executable path: C:\msys64\mingw64\bin\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Cargo
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: cargo.exe
                       █ Executable path: C:\Users\ChedRed\.cargo\bin\cargo.exe
                       █ Call arguments: 
                       █ Version: 
                       █   cargo 1.81.0 (2dbb1af80 2024-08-20)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:48 PM] Command scoop was not found on the system
[12/2/2024 7:01:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:48 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: v1.9.25200
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:49 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: dotnet tool
                       █ Executable path: C:\Program Files\dotnet\dotnet.exe
                       █ Call arguments: tool
                       █ Version: 
                       █   9.0.100-rc.2.24474.11
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:52 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.26100.2161                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.26100.2161                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:01:52 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: choco.exe
                       █ Executable path: C:\Users\ChedRed\AppData\Local\UniGetUI\Chocolatey\choco.exe
                       █ Call arguments: 
                       █ Version: 
                       █   This is try 1/3. Retrying after 400 milliseconds.
                       █    Error converted to warning:
                       █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.119244.update' is denied.
                       █   This is try 2/3. Retrying after 600 milliseconds.
                       █    Error converted to warning:
                       █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.119244.update' is denied.
                       █   Maximum tries of 3 reached. Throwing error.
                       █   2.2.2
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:02:47 PM] Timeout: Not all package managers have finished initializing.
[12/2/2024 7:02:47 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[12/2/2024 7:02:47 PM] Found 0 available updates from Pip
[12/2/2024 7:02:48 PM] Found 0 installed packages from Pip
[12/2/2024 7:02:48 PM] Resetting administrator rights cache for process id 76860
[12/2/2024 7:02:48 PM] Found 0 available updates from Cargo
[12/2/2024 7:02:48 PM] Found 0 installed packages from Cargo
[12/2/2024 7:02:48 PM] Command cargo-install-update.exe was not found on the system
[12/2/2024 7:02:48 PM] Dependency cargo-update was not found for manager Cargo, marking to prompt...
[12/2/2024 7:02:49 PM] Dependency .NET Tools Outdated for manager .NET Tool is present
[12/2/2024 7:02:49 PM] Found 1 installed packages from .NET Tool
[12/2/2024 7:02:49 PM] Ignored updates database was never loaded, so it is going to be loaded now
[12/2/2024 7:02:49 PM] Found 0 available updates from Chocolatey
[12/2/2024 7:02:50 PM] Found 0 available updates from .NET Tool
[12/2/2024 7:02:50 PM] Found 0 installed packages from Chocolatey
[12/2/2024 7:02:51 PM] Found 14 available updates from Winget
[12/2/2024 7:02:51 PM] Found 150 installed packages from Winget
[12/2/2024 7:02:52 PM] Found 0 installed packages from PowerShell
[12/2/2024 7:02:52 PM] Found 0 available updates from PowerShell
[12/2/2024 7:03:27 PM] Loaded operation parameters for package id=MilosParipovic.OneCommander on manager Winget and operation Uninstall: uninstall --id "MilosParipovic.OneCommander" --exact --source winget --accept-source-agreements --disable-interactivity --version "3.93.0" --silent
[12/2/2024 7:03:27 PM] Caching admin rights for process id 76860
[12/2/2024 7:03:33 PM] Resetting administrator rights cache for process id 76860
[12/2/2024 7:05:40 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: npm
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/2/2024 7:05:46 PM] Command parse_pip_search.exe was not found on the system
[12/2/2024 7:05:46 PM] Found 100 available packages from .NET Tool with the query powershell
[12/2/2024 7:05:46 PM] Error finding packages on manager Pip with query powershell
[12/2/2024 7:05:46 PM] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. The system cannot find the file specified.)
                        ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. The system cannot find the file specified.
                          at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                          at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 95
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass52_0.<FindPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          --- End of inner exception stack trace ---
                          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                          at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 165
[12/2/2024 7:05:47 PM] Found 15 available packages from Winget with the query powershell
[12/2/2024 7:05:48 PM] Found 8 available packages from Chocolatey with the query powershell
[12/2/2024 7:05:50 PM] Found 15 available packages from PowerShell with the query powershell
[12/2/2024 7:05:55 PM] Found 6 available packages from Cargo with the query powershell
[12/2/2024 7:06:21 PM] Loaded operation parameters for package id=PowerShell on manager .NET Tool and operation Install: install PowerShell
[12/2/2024 7:06:22 PM] An error occurred while retrieving the icon for package PowerShell
[12/2/2024 7:06:22 PM] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ChedRed\AppData\Local\UniGetUI\CachedMedia\.NET Tool\PowerShell.6\icon'.
                          at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
                          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                          at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                          at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
                          at System.IO.File.Create(String path)
                          at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 146
                          at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[12/2/2024 7:06:25 PM] Resetting administrator rights cache for process id 76860
[12/2/2024 7:06:26 PM] Loaded operation parameters for package id=PowerShell on manager .NET Tool and operation Install: install PowerShell
[12/2/2024 7:06:26 PM] Caching admin rights for process id 76860
[12/2/2024 7:06:40 PM] Resetting administrator rights cache for process id 76860
[12/2/2024 7:06:46 PM] Error finding packages on manager Npm with query powershell
[12/2/2024 7:06:46 PM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.FindPackages(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 167
[12/2/2024 7:13:06 PM] Found 0 installed packages from Pip
[12/2/2024 7:13:06 PM] Found 0 installed packages from Cargo
[12/2/2024 7:13:07 PM] Found 1 installed packages from .NET Tool
[12/2/2024 7:13:07 PM] Found 0 installed packages from Chocolatey
[12/2/2024 7:13:08 PM] Found 150 installed packages from Winget
[12/2/2024 7:13:09 PM] Found 0 installed packages from PowerShell
[12/2/2024 7:14:05 PM] Error finding installed packages on manager Npm
[12/2/2024 7:14:05 PM] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 230
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 12/2/2024 7:01:48 PM
Process end time:   12/2/2024 7:01:48 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 12/2/2024 7:02:47 PM
Process end time:   12/2/2024 7:02:48 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 12/2/2024 7:02:47 PM
Process end time:   12/2/2024 7:02:51 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 12/2/2024 7:02:48 PM
Process end time:   12/2/2024 7:02:48 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 12/2/2024 7:02:48 PM
Process end time:   12/2/2024 7:02:51 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 12/2/2024 7:05:46 PM
Process end time:   12/2/2024 7:05:47 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 12/2/2024 7:13:05 PM
Process end time:   12/2/2024 7:13:08 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Can you please test the latest beta? It had changes in how UAC is handled
https://github.com/marticliment/UniGetUI/releases/tag/3.1.4-beta1

**Comment by ChedRed** [comment]
![{95C63C63-32C2-47F2-AA41-A1BD6FCE33A6}](https://github.com/user-attachments/assets/93997b71-1e6b-4299-ae81-efe7f3abff1f)
it still seems to have trouble :/

**Comment by marticliment** [comment]
What happens if you run the following commands on a command prompt?

```
"C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe" "C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\winget.exe"  uninstall --id "MilosParipovic.OneCommander" --exact --source winget --accept-source-agreements --disable-interactivity --version "3.93.0" --silent
```

```
"C:\Users\ChedRed\AppData\Local\Microsoft\WindowsApps\winget.exe"  uninstall --id "MilosParipovic.OneCommander" --exact --source winget --accept-source-agreements --disable-interactivity --version "3.93.0" --silent
```

**Comment by ChedRed** [comment]
![{89D63F4F-AFE2-4101-80DF-68B286456DAF}](https://github.com/user-attachments/assets/679ac8a3-f9b8-435f-b369-4a9a13a18a84)

**Comment by ChedRed** [comment]
The second command has a different problem ¯\_(ツ)_/¯
![{BFA0D80E-318D-48C3-8465-FBD1B8E84CCF}](https://github.com/user-attachments/assets/8c09427d-f4ef-4218-afb6-45b97e722235)
