### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by udobehm** [marticliment/UniGetUI#3048]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Win 11 Pro

### Describe your issue

Good day. When the 'Ask for admin privileges once for each batch of operations' option is selected I still get UAC notifications for the update of my apps that I need to confirm in order UniGetUI is installing them. How can I really configure UniGetUI to only show me once these UAC notifications for the updates of my apps? Thanks!
Udo

### UniGetUI Log

```text
[07.12.2024 18:58:03]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.3
[07.12.2024 18:58:03]
[07.12.2024 18:58:03] Version Code:  3,13001
[07.12.2024 18:58:04] Encoding Code Page set to 850
[07.12.2024 18:58:09] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[07.12.2024 18:58:15] Loaded language locale: de
[07.12.2024 18:58:18] Randomly-generated background API auth token for the current session: e6h0wfpzllpq5hll7m06fx9p7yv90ezmk3z7jx0vmo2vwkx09b4zwqlqchgf8cqc
[07.12.2024 18:58:18] Api running on http://localhost:7058
[07.12.2024 18:58:19] Lang files were updated successfully from GitHub
[07.12.2024 18:58:19] UniGetUI is up to date
[07.12.2024 18:58:19] Downloaded new icons and screenshots successfully!
[07.12.2024 18:58:22] Old chocolatey path is a symbolic link, not migrating Chocolatey...
[07.12.2024 18:58:25] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.25200
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:26] Command npm was not found on the system
[07.12.2024 18:58:26] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\Udo\AppData\Local\Programs\Python\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.3.1 from C:\Users\Udo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:29] Command cargo was not found on the system
[07.12.2024 18:58:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:30] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:33] Command pwsh.exe was not found on the system
[07.12.2024 18:58:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:47] Chocolatey sources took too long to load, using known sources as default
[07.12.2024 18:58:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Udo\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:47] PowerShell sources took too long to load, using known sources as default
[07.12.2024 18:58:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.2161                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.2161                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:47] Command scoop was not found on the system
[07.12.2024 18:58:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[07.12.2024 18:58:47] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[07.12.2024 18:59:28] Found 15 available updates from Winget
[07.12.2024 18:59:43] Ignored updates database was never loaded, so it is going to be loaded now
[07.12.2024 18:59:45] Found 0 available updates from Chocolatey
[07.12.2024 18:59:48] Error finding installed packages on manager PowerShell
[07.12.2024 18:59:51] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 230
[07.12.2024 18:59:53] Error finding updates on manager Pip
[07.12.2024 18:59:53] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[07.12.2024 18:59:57] Error finding updates on manager PowerShell
[07.12.2024 18:59:57] System.TimeoutException: The operation has timed out.
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetAvailableUpdates() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 199
[07.12.2024 19:00:24] Found 883 installed packages from Winget
[07.12.2024 19:00:24] Found 1 installed packages from Pip
[07.12.2024 19:00:26] Found 0 installed packages from Chocolatey
[07.12.2024 19:00:28] Backup saved to C:\Users\Udo\Einstellungen\UniGetUI\Sicherung\ENVY installierte Pakete.ubundle
[07.12.2024 19:58:20] UniGetUI is up to date
[07.12.2024 20:00:03] Found 0 available updates from Chocolatey
[07.12.2024 20:00:04] Found 0 available updates from PowerShell
[07.12.2024 20:00:05] Found 0 available updates from Pip
[07.12.2024 20:00:15] Found 15 available updates from Winget
[07.12.2024 20:10:58] Icon for Package=TeamViewer.TeamViewer Manager=Winget Uri=https://i.imgur.com/2UWkAjM.png is NOT VALID (verification method is PackageVersion)
[07.12.2024 20:10:58] Icon for Package=dotPDN.PaintDotNet Manager=Winget Uri=https://s5.postimg.cc/v55fm921z/pdnlogorevisited2.png is NOT VALID (verification method is PackageVersion)
[07.12.2024 20:10:58] Loaded operation parameters for package id=dotPDN.PaintDotNet on manager Winget and operation Update: update --id "dotPDN.PaintDotNet" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 20:11:00] Icon for Package=geeksoftwareGmbH.PDF24Creator Manager=Winget Uri=https://i.postimg.cc/DfP15pB1/icon.png is NOT VALID (verification method is PackageVersion)
[07.12.2024 20:11:13] Icon for package TeamViewer.TeamViewer stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\TeamViewer.TeamViewer.png
[07.12.2024 20:11:13] NEWLY DOWNLOADED Icon for Package=TeamViewer.TeamViewer Manager=Winget Uri=https://i.imgur.com/2UWkAjM.png is VALID (verification method is PackageVersion)
[07.12.2024 20:11:13] Icon for package dotPDN.PaintDotNet stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\dotPDN.PaintDotNet.png
[07.12.2024 20:11:13] NEWLY DOWNLOADED Icon for Package=dotPDN.PaintDotNet Manager=Winget Uri=https://s5.postimg.cc/v55fm921z/pdnlogorevisited2.png is VALID (verification method is PackageVersion)
[07.12.2024 20:11:13] Icon for package geeksoftwareGmbH.PDF24Creator stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\geeksoftwareGmbH.PDF24Creator.png
[07.12.2024 20:11:13] NEWLY DOWNLOADED Icon for Package=geeksoftwareGmbH.PDF24Creator Manager=Winget Uri=https://i.postimg.cc/DfP15pB1/icon.png is VALID (verification method is PackageVersion)
[07.12.2024 20:11:14] Icon for package OBSProject.OBSStudio stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\OBSProject.OBSStudio.ico
[07.12.2024 20:11:14] Icon for package Python.Python.3.13 stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\Python.Python.3.13.ico
[07.12.2024 20:11:14] NEWLY DOWNLOADED Icon for Package=Python.Python.3.13 Manager=Winget Uri=https://cdn.winget.microsoft.com/icons/ebbc52305cda5a9fb7c108a2cc9466e7e72a33841d2c7935f6a48b1653fc1373.ico is VALID (verification method is SHA256)
[07.12.2024 20:11:14] NEWLY DOWNLOADED Icon for Package=OBSProject.OBSStudio Manager=Winget Uri=https://cdn.winget.microsoft.com/icons/eb4cffccc2793bb60ba947cf85f427e91d5d31b990f974ec4f1ca993f2cc9b94.ico is VALID (verification method is SHA256)
[07.12.2024 20:11:14] An error occurred while retrieving the icon for package Microsoft.Office
[07.12.2024 20:11:14] Icon for package Anki.Anki stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\Anki.Anki.png
[07.12.2024 20:11:14] NEWLY DOWNLOADED Icon for Package=Anki.Anki Manager=Winget Uri=https://i.redd.it/cruevyf68dt31.png is VALID (verification method is PackageVersion)
[07.12.2024 20:11:14] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[07.12.2024 20:11:14] Icon for package EaseUS.PartitionMaster stored on C:\Users\Udo\AppData\Local\UniGetUI\CachedMedia\Winget\EaseUS.PartitionMaster.ico
[07.12.2024 20:11:15] NEWLY DOWNLOADED Icon for Package=EaseUS.PartitionMaster Manager=Winget Uri=https://cdn.winget.microsoft.com/icons/4d0dc76cfb96a628feaf9dcb9267658732d7f5f95d3bd05a5f73d60279f1b354.ico is VALID (verification method is SHA256)
[07.12.2024 20:21:49] Loaded operation parameters for package id=Microsoft.PowerAutomateDesktop on manager Winget and operation Update: update --id "Microsoft.PowerAutomateDesktop" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 20:58:21] UniGetUI is up to date
[07.12.2024 21:00:28] Found 14 available updates from Winget
[07.12.2024 21:00:33] Found 0 available updates from PowerShell
[07.12.2024 21:00:38] Found 0 available updates from Chocolatey
[07.12.2024 21:00:40] Found 0 available updates from Pip
[07.12.2024 21:39:50] Found 1 installed packages from Pip
[07.12.2024 21:39:56] Found 883 installed packages from Winget
[07.12.2024 21:40:01] Found 0 installed packages from Chocolatey
[07.12.2024 21:40:01] Adding missing package dotPDN.PaintDotNet to installed packages list
[07.12.2024 21:40:04] Found 0 installed packages from PowerShell
[07.12.2024 21:42:56] Loaded operation parameters for package id=Microsoft.Teams.Classic on manager Winget and operation Update: update --id "Microsoft.Teams.Classic" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:45:38] Loaded operation parameters for package id=TeamViewer.TeamViewer on manager Winget and operation Update: update --id "TeamViewer.TeamViewer" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:47:22] Loaded operation parameters for package id=HulubuluSoftware.AdvancedRenamer on manager Winget and operation Update: update --id "HulubuluSoftware.AdvancedRenamer" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:47:56] Loaded operation parameters for package id=Python.Python.3.12 on manager Winget and operation Update: update --id "Python.Python.3.12" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:48:13] Resetting administrator rights cache for process id 16008
[07.12.2024 21:52:18] Loaded operation parameters for package id=OpenMedia.4KVideoDownloader on manager Winget and operation Update: update --id "OpenMedia.4KVideoDownloader" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:52:26] Loaded operation parameters for package id=geeksoftwareGmbH.PDF24Creator on manager Winget and operation Update: update --id "geeksoftwareGmbH.PDF24Creator" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:55:27] Loaded operation parameters for package id=OBSProject.OBSStudio on manager Winget and operation Update: update --id "OBSProject.OBSStudio" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[07.12.2024 21:57:22] Loaded operation parameters for package id=DeepL.DeepL on manager Winget and operation Update: update --id "DeepL.DeepL" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 07.12.2024 18:58:25
Process end time:   07.12.2024 18:58:25

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07.12.2024 18:58:48
Process end time:   07.12.2024 18:58:57

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 07.12.2024 18:58:57
Process end time:   07.12.2024 18:59:28

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 07.12.2024 18:59:06
Process end time:   07.12.2024 18:59:06

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07.12.2024 18:59:45
Process end time:   07.12.2024 19:00:24

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07.12.2024 19:59:58
Process end time:   07.12.2024 19:59:59

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 07.12.2024 20:00:03
Process end time:   07.12.2024 20:00:15

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Udo\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 07.12.2024 21:00:16
Process end time:   07.12.2024 21:00:17

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 07.12.2024 21:00:17
Process end time:   07.12.2024 21:00:28

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 07.12.2024 21:39:20
Process end time:   07.12.2024 21:39:56

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Some packages do not properly specify when they require administrator rights to be installed. Therefore, UniGetUI can't properly handle automatic elevation.

Please note that while this issue can't be fixed, since it is caused by incorrect package manifests on certain package managers, the next UniGetUI version will have improvements in this matter.
