### ISSUE TITLE
[BUG] WinGet functionality inside UniGetUI seems to be corrupted or broken since installing UniGetUI v3.1.4 beta 1

### ISSUE THREAD

**Issue by ZPNRG** [marticliment/UniGetUI#3055]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4 beta 2

### Windows version, edition, and architecture

Windows 10 22H2 19045.5198

### Describe your issue

Since I installed UniGetUI 3.1.4 beta 1, I have been having problems with WinGet within UniGetUI and I am not offered any updates.  Furthermore, I am constantly warned "WinGet malfunction detected", but repairing never works.  UniGetUI says it has successfully repaired WinGet, but then I get the same warning.

![UniGetUI 1](https://github.com/user-attachments/assets/fb8abd7a-1468-4f1d-bf56-64191e778011)

If I click on "Repair WinGet", then a PowerShell window launches, but then while running I see the following (I had to grab a video of it to get a screenshot):

![UniGetUI 2](https://github.com/user-attachments/assets/39b36492-904b-4f09-9a2e-719808dafc69)

But despite that error while the cmdlet/script file is running, UnIGetUI always comes back and says that WinGet was repaired successfully as follows:

![UniGetUI 3](https://github.com/user-attachments/assets/4c6203e9-8562-4531-bc92-f7c2dd937ec8)

I have not changed anything. I have uninstalled UniGetUI and reinstalled it, but nothing changed.  I have also tried enabling the "Use bundled WinGet" option, but that didn't help.  The following are the settings I have been using for months other than temporarily trying the "Use bundled WinGet" option:

![UniGetUI 4](https://github.com/user-attachments/assets/ff7e608b-afdf-485e-8835-35434adf5f23)

Please note that I can manually open PowerShell in an admin window and find and install updates via WinGet.  I just don't know what to do to get WinGet past whatever problem it is having (or thinks it has) with WinGet. ???

I did update to 3.1.4 beta 2 today, but that didn't change anything.  In fact, I tested again today and then produced the screenshots submitted in this submission.

### Steps to reproduce the issue

All I have to do is launch UniGetUI and/or try manually looking for updates (since UniGetUI doesn't seem to be able to) and the warning about "WinGet malfunction detected" pops up.  If I try repairing, then the whole loop starts.

### UniGetUI Log

```text
[12/9/2024 1:51:29 PM]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.4-beta2
[12/9/2024 1:51:29 PM]
[12/9/2024 1:51:29 PM] Build 72
[12/9/2024 1:51:29 PM] Encoding Code Page set to 437
[12/9/2024 1:51:29 PM] Using built-in UniGetUI Elevator
[12/9/2024 1:51:29 PM] Loaded language locale: en
[12/9/2024 1:51:30 PM] Randomly-generated background API auth token for the current session: okedfnqcco7yvvra7wilf8ya79je2gilg67mgtxn8fj7x6qfmffgr9ugc2pukku1
[12/9/2024 1:51:30 PM] Api running on http://localhost:7058
[12/9/2024 1:51:30 PM] Lang files were updated successfully from GitHub
[12/9/2024 1:51:30 PM] Downloaded new icons and screenshots successfully!
[12/9/2024 1:51:30 PM] Command npm was not found on the system
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] Command cargo was not found on the system
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Cargo
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] Command vcpkg was not found on the system
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: vcpkg
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] Command scoop was not found on the system
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\ZeroE\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: v1.10.40-preview
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:30 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: False
                       █ THE MANAGER IS DISABLED
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:32 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.19041.5198                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.19041.5198                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:32 PM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pwsh.exe
                       █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   PowerShell 7.4.6
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[12/9/2024 1:51:32 PM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[12/9/2024 1:51:32 PM] Found 1 installed packages from PowerShell7
[12/9/2024 1:51:32 PM] Failed to download the PowerShell7 manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='AIShell',Version='1.0.1') with status code NotFound
[12/9/2024 1:51:32 PM] No manifest content could be loaded for package AIShell on manager PowerShell7
[12/9/2024 1:51:34 PM] Found 1 installed packages from PowerShell
[12/9/2024 1:51:35 PM] Found 0 available updates from PowerShell
[12/9/2024 1:51:41 PM] Manager WinGet failed to list available updates with exception InvalidOperationException: WinGet: Failed to connect to composite catalog.
[12/9/2024 1:51:41 PM] Since this was the first attempt, Winget.AttemptFastRepair() will be called and the procedure will be restarted
[12/9/2024 1:51:41 PM] Manager WinGet failed to list installed packages with exception InvalidOperationException: WinGet: Failed to connect to composite catalog.
[12/9/2024 1:51:41 PM] Since this was the first attempt, Winget.AttemptFastRepair() will be called and the procedure will be restarted
[12/9/2024 1:51:41 PM] Attempting to reconnec to WinGet COM Server...
[12/9/2024 1:51:41 PM] Attempting to reconnec to WinGet COM Server...
[12/9/2024 1:51:50 PM] Error finding updates on manager Winget
[12/9/2024 1:51:50 PM] Error finding installed packages on manager Winget
[12/9/2024 1:51:50 PM] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                        ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                          at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\ClientHelpers\NativeWinGetHelper.cs:line 240
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 103
                       --- End of stack trace from previous location ---
                          at UniGetUI.Core.Classes.TaskRecycler`1.RunOrAttach(Func`1 method, Int32 cacheTimeSecs) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Classes\TaskRecycler.cs:line 66
                          at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\ClientHelpers\NativeWinGetHelper.cs:line 157
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 96
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          --- End of inner exception stack trace ---
                          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                          at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 239
[12/9/2024 1:51:50 PM] System.AggregateException: One or more errors occurred. (WinGet: Failed to connect to composite catalog.)
                        ---> System.InvalidOperationException: WinGet: Failed to connect to composite catalog.
                          at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetLocalWinGetPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\ClientHelpers\NativeWinGetHelper.cs:line 240
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetInstalledPackages_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 103
                       --- End of stack trace from previous location ---
                          at UniGetUI.Core.Classes.TaskRecycler`1.RunOrAttach(Func`1 method, Int32 cacheTimeSecs) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Classes\TaskRecycler.cs:line 66
                          at UniGetUI.PackageEngine.Managers.WingetManager.NativeWinGetHelper.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\ClientHelpers\NativeWinGetHelper.cs:line 157
                          at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 96
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          at System.Threading.Tasks.Task`1.InnerInvoke()
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                       --- End of stack trace from previous location ---
                          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                          --- End of inner exception stack trace ---
                          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                          at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                          at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 194
[12/9/2024 1:51:50 PM] Backup saved to D:\__Zero\MEGAsync\Documents\UniGetUI\L-TP-P15-GEN-2 installed packages 2024-12-09 13-51-50.ubundle
[12/9/2024 1:52:32 PM] Manager PowerShell 7.x failed to list available updates with exception TimeoutException: The operation has timed out.
[12/9/2024 1:52:32 PM] Since this was the first attempt, PowerShell7.AttemptFastRepair() will be called and the procedure will be restarted
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.10.40-preview
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 12/9/2024 1:51:30 PM
Process end time:   12/9/2024 1:51:30 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\ZeroE\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 12/9/2024 1:51:32 PM
Process end time:   12/9/2024 1:51:41 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 12/9/2024 1:51:32 PM
Process end time:   UNFINISHED

The task has not finished yet

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 12/9/2024 1:51:32 PM
Process end time:   12/9/2024 1:51:41 PM

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 12/9/2024 1:51:41 PM
Process end time:   UNFINISHED

The task has not finished yet

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\ZeroE\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 12/9/2024 1:51:41 PM
Process end time:   12/9/2024 1:51:48 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 12/9/2024 1:51:41 PM
Process end time:   UNFINISHED

The task has not finished yet

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 12/9/2024 1:51:41 PM
Process end time:   12/9/2024 1:51:50 PM

-- Task information
 ...

-- Task errors
  Failed to connect to installedSearchCatalogRef. Aborting.

The task reported a failure (1)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 12/9/2024 1:51:48 PM
Process end time:   UNFINISHED

The task has not finished yet

——————————————————————————————————————————
```

**Comment by ZPNRG** [comment]
I first started to run the "Install-Module Microsoft.WinGet.Client" in a non-eleveated Powershell window, but it said it needed admin privileges. So, I opened an admin-level Powershell window and ran both lines in succession.  Nothing appeared to happen.  This is what I saw:

![UniGetUI 1](https://github.com/user-attachments/assets/96e51b44-7df4-4784-a705-f10b258f716a)

However, apparently, the Microsoft Store version of WinGet was installed.  I see this in the sources: 

![UniGetUI 2](https://github.com/user-attachments/assets/4ff3f0a2-973d-4e41-8829-ff702b48b2ea)

This didn't fix anything.  I wasn't getting the "WinGet malfunction detected" message, but UniGetUI was also still not finding any updates.  However, once I re-enabled the "Enable the automatic WinGet troubleshooter", the "WinGet malfunction detected" message returned and UniGetUI still isn't finding any available updates (that I know there are).

**Comment by marticliment** [comment]
`winget --list` on a command prompt does work?

**Comment by ZPNRG** [comment]
--list doesn't appear to be a valid switch/option.  From an admin Powershell window, "winget list" works fine and comes back with a list of maybe 70-80 apps installed on the system.  Here is a small sample of the first five listed:

Name                                       Id                                         Version          Available Source
-----------------------------------------------------------------------------------------------------------------------
7-Zip 24.09 (x64)                          7zip.7zip                                  24.09                      winget
Battery Mode 64-bit                        TarasovArtyom.BatteryMode                  4.3.2.204                  winget
Everything 1.5.0.1386a (x64)               voidtools.Everything.Alpha                 1.5.0.1386a                winget
FinePrint                                  FineprintSoftware.FinePrint                12.10                      winget
HashCheck Shell Extension                  gurnec.HashCheckShellExtension             2.5.0.1                    winget

**Comment by marticliment** [comment]
Now, after running this command, test UniGetUI again

**Comment by ZPNRG** [comment]
Okay.  Nothing has changed. Upon lauching UniGetUI and checking for updates, I immediately got the "WinGet malfunction detected" message and no updates were found. Here is what I wonder... 

For probably 15 years or so, I have run my primary Windows account as a Standard (non-admin) account. I still do and I just deal with UAC and perform the necessary admin authentication as needed for various tasks.  So, when I open a (non-admin) Windows Powershell window and run "winget list", I get this:

![image](https://github.com/user-attachments/assets/5e541529-e28f-4e3c-91d0-fcab0da9c6f3)

As I said above earlier, if I open an admin (elevated) Powershell window, then "winget list" works fine and comes back with a long list of installed apps.

However, since I started using WinGetUI (now UniGetUI) in June 2023, I've always been running it 100% of the time from my Standard (non-admin) Windows account. I do install UniGetUI to work for all users, but I never use it from the Windows admin account. So, if Winget is having a problem from a regular (non-admin) Powershell command line launched from my Standard Windows account, then I wouldn't think UniGetUI would be able to work when it is running in my Standard Windows account unless UniGetUI is somehow getting around that behind the scenes.

I wonder if I need to delete both sources and then just re-install the original source I was using (https://cdn.winget.microsoft.com/cache).  Granted, maybe you have seen better results with UniGetUI using the MSStore version.

**Comment by DrStrange** [comment]
@ZPNRG,
I would think since winget works in your Admin account but not in your standard user account and the error is 0x80070005, the fix might be to go to C:\Users\ZeroE\AppData\Local\Temp and check your permissions for the WinGet folder. If ZeroE is missing from the security tab, add ZeroE and give yourself full permissions. Check if `winget list` now works and if UnigetUI's offer to fix Winget has disappeared. 
Unfortunately this is a long standing well known bug with and an issue has been raised for it here, in winget-cli and in GSudo's  repositories. See here:
https://github.com/marticliment/UniGetUI/issues/3008
It might be caused by GSudo. Marti is aware of it "but doesn't know why gsudo causes the error when regular UAC doesn't". 
The maintainer for GSudo is also aware of it:
https://github.com/gerardog/gsudo/issues/376

**Comment by ZPNRG** [comment]
@DrStrange  Okay. I'll look into it.  What is strange is that something must have changed with me installing UniGetUI 3.1.4 beta 1 that introduced this or the dormant bug was brought to the surface.  Nothing has changed on my PC as far as permissions, etc.  Geez, I haven't reinstalled Windows in a couple of years.  Now, that said, maybe Windows is getting "creeky" and a Windows update or something else screwy happened about the same time as I installed UniGetUI.

**Comment by tps800** [comment]
Looks like the underlying error is: No applicable license found.

`Winget.exe` seems needing a license file to run, but this file is missing. And without it you may get some error messages not giving real causes trying to run `winget.exe`: "Fehler beim Ausführen des Programms "winget.exe": Eine angegebene Anmeldesitzung ist nicht vorhanden. Sie wurde gegebenenfalls bereits beendet."

`C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\winget.exe`: "Das angegebene Programm kann nicht ausgeführt werden." -- not really helpful, since acl and policy say it can.

`winget.exe` has more than one location installed. Some run. some not. It depends.
- `C:\PRGS\UniGetUI\winget-cli_x64\winget.exe` -- works (v1.8.1911)
- `C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\winget.exe` -- does not (v1.24.25200.0)
- `C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\winget.exe` -- does not  (v1.24.25200.0)
- `C:\Users\<anotheruser>\AppData\Local\Microsoft\WindowsApps\winget.exe` -- does not  (v1.24.25200.0)
- `C:\Users\<anotheruser>\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\winget.exe` -- does not  (v1.24.25200.0)

Could we have an installable package including the necessary license file installed at a place `winget.exe` can find this license? Or: could someone remove this license-stuff from `winget.exe` to make it work again as it did with older versions?

**Comment by ROBYER1** [comment]
Think I found the cause here https://github.com/marticliment/UniGetUI/issues/3153#issuecomment-2627038340

**Comment by tps800** [comment]
Seems this is the cause. `winget` is just not allowed to read the installed license, because only an administrator (or in case of CCM installed UniGetUI/Winget: system) has access to it. After changing ACLs so all users have access, it works.

**Comment by marticliment** [comment]
Once you have set the proper ACLs, does the issue reappear after a while?

**Comment by tps800** [comment]
Did not test until now. Will try next week.
