### ISSUE TITLE
[BUG] (The program issue me to update several times the same software)

### ISSUE THREAD

**Issue by verdetto** [marticliment/UniGetUI#3077]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 24H2

### Describe your issue

The program asked me to update the same software several times, even several times a day, but each time the update was correctly installed.

### UniGetUI Log

```text
[17/12/2024 08:08:47]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.3
[17/12/2024 08:08:47]
[17/12/2024 08:08:47] Version Code:  3,13001
[17/12/2024 08:08:47] Encoding Code Page set to 850
[17/12/2024 08:08:48] Using bundled GSudo at C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
[17/12/2024 08:08:48] Loaded language locale: it
[17/12/2024 08:08:49] Randomly-generated background API auth token for the current session: 97aykc2rq37mvqr7datxl9nuz7ke22lw6u8xahfm3asp6ba5wk5s8226eiq7rge9
[17/12/2024 08:08:49] Api running on http://localhost:7058
[17/12/2024 08:08:49] Lang files were updated successfully from GitHub
[17/12/2024 08:08:49] UniGetUI is up to date
[17/12/2024 08:08:49] Downloaded new icons and screenshots successfully!
[17/12/2024 08:08:50] Command npm was not found on the system
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:50] Command cargo was not found on the system
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:50] Command pwsh.exe was not found on the system
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:50] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.25200
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\massimo1\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:52] Command scoop was not found on the system
[17/12/2024 08:08:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:52] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.2161                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.2161                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[17/12/2024 08:08:52] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[17/12/2024 08:08:53] Found 0 installed packages from Pip
[17/12/2024 08:08:53] Found 0 available updates from Pip
[17/12/2024 08:08:54] Found 0 installed packages from Chocolatey
[17/12/2024 08:08:54] Found 0 available updates from Chocolatey
[17/12/2024 08:08:55] Found 1 installed packages from PowerShell
[17/12/2024 08:08:55] Ignored updates database was never loaded, so it is going to be loaded now
[17/12/2024 08:08:56] Found 1 available updates from PowerShell
[17/12/2024 08:09:00] Found 6 available updates from Winget
[17/12/2024 08:09:00] Found 295 installed packages from Winget
[17/12/2024 09:08:50] UniGetUI is up to date
[17/12/2024 09:09:00] Found 0 available updates from Pip
[17/12/2024 09:09:02] Found 0 available updates from Chocolatey
[17/12/2024 09:09:05] Found 1 available updates from PowerShell
[17/12/2024 09:09:05] Found 6 available updates from Winget
[17/12/2024 10:08:50] UniGetUI is up to date
[17/12/2024 10:09:06] Found 0 available updates from Pip
[17/12/2024 10:09:07] Found 0 available updates from Chocolatey
[17/12/2024 10:09:10] Found 1 available updates from PowerShell
[17/12/2024 10:09:11] Found 6 available updates from Winget
[17/12/2024 11:08:51] UniGetUI is up to date
[17/12/2024 11:09:11] Found 0 available updates from Pip
[17/12/2024 11:09:13] Found 0 available updates from Chocolatey
[17/12/2024 11:09:15] Found 6 available updates from Winget
[17/12/2024 11:09:15] Found 1 available updates from PowerShell
[17/12/2024 12:08:51] UniGetUI is up to date
[17/12/2024 12:09:16] Found 0 available updates from Pip
[17/12/2024 12:09:18] Found 0 available updates from Chocolatey
[17/12/2024 12:09:21] Found 6 available updates from Winget
[17/12/2024 12:09:22] Found 1 available updates from PowerShell
[17/12/2024 12:09:26] Found 0 installed packages from Pip
[17/12/2024 12:09:27] Found 0 installed packages from Chocolatey
[17/12/2024 12:09:29] Found 1 installed packages from PowerShell
[17/12/2024 12:09:29] Found 295 installed packages from Winget
[17/12/2024 12:09:29] Adding missing package MSIX\Microsoft.Windows.Photos_2024.11120.5010.0_x64__8wekyb3d8bbwe to installed packages list
[17/12/2024 12:09:29] Adding missing package MSIX\Microsoft.Winget.Source_2024.1217.929.27_neutral__8wekyb3d8bbwe to installed packages list
[17/12/2024 12:09:40] Loaded operation parameters for package id=Microsoft.ReportBuilder on manager Winget and operation Update: update --id "Microsoft.ReportBuilder" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 12:09:40] An error occurred while retrieving the icon for package Microsoft.WinGet.Client
[17/12/2024 12:09:40] System.ArgumentOutOfRangeException: startIndex ('-1') must be a non-negative value. (Parameter 'startIndex')
                      Actual value was -1.
                         at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
                         at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
                         at System.String.Substring(Int32 startIndex, Int32 length)
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 89
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[17/12/2024 12:09:41] An error occurred while retrieving the icon for package Wacom.WacomTabletDriver
[17/12/2024 12:09:41] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.GetCacheOrDownloadIcon(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 143
                         at UniGetUI.PackageEngine.PackageClasses.Package.LoadIconUrlIfAny() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 200
[17/12/2024 12:09:42] Loaded operation parameters for package id=Microsoft.Teams.Classic on manager Winget and operation Update: update --id "Microsoft.Teams.Classic" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 12:09:47] Loaded operation parameters for package id=Microsoft.WinGet.Client on manager PowerShell and operation Update: Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
[17/12/2024 12:09:48] Loaded operation parameters for package id=Mozilla.Firefox on manager Winget and operation Update: update --id "Mozilla.Firefox" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 12:09:51] Loaded operation parameters for package id=PuTTY.PuTTY on manager Winget and operation Update: update --id "PuTTY.PuTTY" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 12:09:54] Loaded operation parameters for package id=Wacom.WacomTabletDriver on manager Winget and operation Update: update --id "Wacom.WacomTabletDriver" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 12:09:56] Loaded operation parameters for package id=Zoom.Zoom.EXE on manager Winget and operation Update: update --id "Zoom.Zoom.EXE" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 13:08:52] UniGetUI is up to date
[17/12/2024 13:09:22] Found 0 available updates from Pip
[17/12/2024 13:09:24] Found 0 available updates from Chocolatey
[17/12/2024 13:09:26] Found 5 available updates from Winget
[17/12/2024 13:09:28] Found 1 available updates from PowerShell
[17/12/2024 14:08:52] UniGetUI is up to date
[17/12/2024 14:09:28] Found 0 available updates from Pip
[17/12/2024 14:09:30] Found 0 available updates from Chocolatey
[17/12/2024 14:09:33] Found 5 available updates from Winget
[17/12/2024 14:09:34] Found 1 available updates from PowerShell
[17/12/2024 14:40:14] Loaded operation parameters for package id=Microsoft.ReportBuilder on manager Winget and operation Update: update --id "Microsoft.ReportBuilder" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 14:40:16] Loaded operation parameters for package id=Microsoft.Teams.Classic on manager Winget and operation Update: update --id "Microsoft.Teams.Classic" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 14:40:21] Loaded operation parameters for package id=Microsoft.WinGet.Client on manager PowerShell and operation Update: Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
[17/12/2024 14:40:23] Loaded operation parameters for package id=Mozilla.Firefox on manager Winget and operation Update: update --id "Mozilla.Firefox" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 14:40:27] Loaded operation parameters for package id=PuTTY.PuTTY on manager Winget and operation Update: update --id "PuTTY.PuTTY" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 14:40:31] Loaded operation parameters for package id=Wacom.WacomTabletDriver on manager Winget and operation Update: update --id "Wacom.WacomTabletDriver" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[17/12/2024 15:08:52] UniGetUI is up to date
[17/12/2024 15:09:35] Found 0 available updates from Pip
[17/12/2024 15:09:36] Found 0 available updates from Chocolatey
[17/12/2024 15:09:40] Found 1 available updates from PowerShell
[17/12/2024 15:09:41] Found 5 available updates from Winget
[17/12/2024 16:08:53] UniGetUI is up to date
[17/12/2024 16:09:41] Found 0 available updates from Pip
[17/12/2024 16:09:44] Found 0 available updates from Chocolatey
[17/12/2024 16:09:46] Found 5 available updates from Winget
[17/12/2024 16:09:47] Found 1 available updates from PowerShell
[17/12/2024 17:08:53] UniGetUI is up to date
[17/12/2024 17:09:48] Found 0 available updates from Pip
[17/12/2024 17:09:50] Found 0 available updates from Chocolatey
[17/12/2024 17:09:53] Found 5 available updates from Winget
[17/12/2024 17:09:54] Found 1 available updates from PowerShell
[17/12/2024 17:10:00] Found 0 installed packages from Pip
[17/12/2024 17:10:02] Found 0 installed packages from Chocolatey
[17/12/2024 17:10:04] Found 1 installed packages from PowerShell
[17/12/2024 17:10:04] Found 295 installed packages from Winget
[17/12/2024 17:10:04] Adding missing package Zoom.Zoom.EXE to installed packages list
[17/12/2024 17:10:08] Found 0 installed packages from Pip
[17/12/2024 17:10:10] Found 0 installed packages from Chocolatey
[17/12/2024 17:10:12] Found 1 installed packages from PowerShell
[17/12/2024 17:10:12] Found 295 installed packages from Winget
[17/12/2024 17:15:06] Found 0 installed packages from Pip
[17/12/2024 17:15:08] Found 0 installed packages from Chocolatey
[17/12/2024 17:15:09] Found 1 installed packages from PowerShell
[17/12/2024 17:15:10] Found 295 installed packages from Winget
[17/12/2024 17:17:22] Found 0 installed packages from Pip
[17/12/2024 17:17:24] Found 0 installed packages from Chocolatey
[17/12/2024 17:17:25] Found 1 installed packages from PowerShell
[17/12/2024 17:17:25] Found 295 installed packages from Winget
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 17/12/2024 08:08:50
Process end time:   17/12/2024 08:08:50

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 08:08:52
Process end time:   17/12/2024 08:09:00

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 08:08:52
Process end time:   17/12/2024 08:08:56

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 17/12/2024 08:08:53
Process end time:   17/12/2024 08:08:53

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 08:08:56
Process end time:   17/12/2024 08:09:00

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 09:09:00
Process end time:   17/12/2024 09:09:02

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 09:09:02
Process end time:   17/12/2024 09:09:05

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 10:09:05
Process end time:   17/12/2024 10:09:08

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 10:09:08
Process end time:   17/12/2024 10:09:11

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 11:09:11
Process end time:   17/12/2024 11:09:12

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 11:09:12
Process end time:   17/12/2024 11:09:15

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 12:09:16
Process end time:   17/12/2024 12:09:17

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 12:09:17
Process end time:   17/12/2024 12:09:21

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 12:09:25
Process end time:   17/12/2024 12:09:29

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 13:09:22
Process end time:   17/12/2024 13:09:23

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 13:09:23
Process end time:   17/12/2024 13:09:26

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 14:09:28
Process end time:   17/12/2024 14:09:29

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 14:09:29
Process end time:   17/12/2024 14:09:33

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 15:09:34
Process end time:   17/12/2024 15:09:37

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 15:09:37
Process end time:   17/12/2024 15:09:41

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 16:09:41
Process end time:   17/12/2024 16:09:42

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 16:09:42
Process end time:   17/12/2024 16:09:46

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\massimo1\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 17/12/2024 17:09:48
Process end time:   17/12/2024 17:09:49

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 17/12/2024 17:09:49
Process end time:   17/12/2024 17:09:53

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 17:09:59
Process end time:   17/12/2024 17:10:04

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 17:10:08
Process end time:   17/12/2024 17:10:12

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 17:15:05
Process end time:   17/12/2024 17:15:10

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 17/12/2024 17:17:21
Process end time:   17/12/2024 17:17:25

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
This issue will be fixed in the next version
