### ISSUE TITLE
[BUG] Minor Text Bug

### ISSUE THREAD

**Issue by CardcaptorRLH85** [marticliment/UniGetUI#3081]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4

### Windows version, edition, and architecture

Windows 11 Pro 22631.4602 x64

### Describe your issue

This is a **very** minor text bug. In the popup that asks for you to install parse-pip-search, it says that a black window might pop up. However, since it starts a Powershell 5 instance, the window that appears is blue. 

### Steps to reproduce the issue

Run UnigetUI without parse-pip-search installed and you'll see the popup. 

### UniGetUI Log

```text
[2024-12-18 00:34:40]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.4
[2024-12-18 00:34:41]
[2024-12-18 00:34:41] Build 73
[2024-12-18 00:34:44] Encoding Code Page set to 437
[2024-12-18 00:34:47] Using built-in UniGetUI Elevator
[2024-12-18 00:34:52] Loaded language locale: en
[2024-12-18 00:35:00] Randomly-generated background API auth token for the current session: wjzdkdn4hqb0cu944uefmliwuopfmd6kbeoz6f1h4s7duhvjkxucumoqsczocir0
[2024-12-18 00:35:00] Api running on http://localhost:7058
[2024-12-18 00:35:00] Lang files were updated successfully from GitHub
[2024-12-18 00:35:01] Old chocolatey path is a symbolic link, not migrating Chocolatey...
[2024-12-18 00:35:05] Command cargo was not found on the system
[2024-12-18 00:35:05] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:06] Command vcpkg was not found on the system
[2024-12-18 00:35:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: vcpkg
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:16] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\CCRLH85\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.10.40-preview
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:17] Downloaded new icons and screenshots successfully!
[2024-12-18 00:35:28] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   5.0.416
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:30] Starting scoop cleanup...
[2024-12-18 00:35:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.9.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:34] PowerShell sources took too long to load, using known sources as default
[2024-12-18 00:35:34] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.22621.4391                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.22621.4391                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.3.1 from C:\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:41] Chocolatey sources took too long to load, using known sources as default
[2024-12-18 00:35:41] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   2.4.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:43] PowerShell7 sources took too long to load, using known sources as default
[2024-12-18 00:35:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:45] Scoop sources took too long to load, using known sources as default
[2024-12-18 00:35:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                      █   
                      █   'main' bucket:
                      █   162462b10 watchman: Update to version 2024.12.16.00
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024-12-18 00:35:45] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024-12-18 00:35:58] Dependency Scoop-Search for manager Scoop is present
[2024-12-18 00:36:04] Dependency Git for manager Scoop is present
[2024-12-18 00:36:07] Command parse_pip_search.exe was not found on the system
[2024-12-18 00:36:07] Dependency parse-pip-search was not found for manager Pip, marking to prompt...
[2024-12-18 00:36:15] Found 0 available updates from .NET Tool
[2024-12-18 00:36:17] Dependency .NET Tools Outdated for manager .NET Tool is present
[2024-12-18 00:36:37] Scoop cleanup finished!
[2024-12-18 00:36:45] Manager PowerShell 7.x failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:36:45] Since this was the first attempt, PowerShell7.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:36:47] Manager Chocolatey failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager Chocolatey did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:36:47] Since this was the first attempt, Chocolatey.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:04] Manager Pip failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager Pip did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:04] Since this was the first attempt, Pip.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:04] Manager PowerShell 5.x failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:04] Since this was the first attempt, PowerShell.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:04] Manager WinGet failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager Winget did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:04] Since this was the first attempt, Winget.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:04] Attempting to reconnec to WinGet COM Server...
[2024-12-18 00:37:04] Manager PowerShell 7.x failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:04] Since this was the first attempt, PowerShell7.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:04] Manager Npm failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager Npm did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:04] Since this was the first attempt, Npm.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:07] Manager Scoop failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager Scoop did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:07] Since this was the first attempt, Scoop.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:20] Manager Chocolatey failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager Chocolatey did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:20] Since this was the first attempt, Chocolatey.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:37] Manager Npm failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager Npm did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:37] Since this was the first attempt, Npm.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:45] Manager WinGet failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager Winget did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:45] Since this was the first attempt, Winget.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:45] Attempting to reconnec to WinGet COM Server...
[2024-12-18 00:37:45] Manager Scoop failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager Scoop did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:37:45] Since this was the first attempt, Scoop.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:37:45] Error finding installed packages on manager PowerShell7
[2024-12-18 00:37:46] System.TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 255
[2024-12-18 00:37:49] Found 16 installed packages from Pip
[2024-12-18 00:37:57] Found 1 installed packages from .NET Tool
[2024-12-18 00:37:57] Scoop buckets have been already refreshed in the last ten minutes, skipping.
[2024-12-18 00:38:03] Found 4 installed packages from Scoop
[2024-12-18 00:38:03] Found 4 installed packages from Scoop
[2024-12-18 00:38:03] Found 4 installed packages from Scoop
[2024-12-18 00:38:04] Error finding installed packages on manager Winget
[2024-12-18 00:38:04] System.TimeoutException: Task _getInstalledPackages for manager Winget did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 255
[2024-12-18 00:38:05] Error finding updates on manager PowerShell
[2024-12-18 00:38:05] System.TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:38:15] Error finding updates on manager Pip
[2024-12-18 00:38:15] System.TimeoutException: Task _getInstalledPackages for manager Pip did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:38:15] Error finding updates on manager PowerShell7
[2024-12-18 00:38:15] Error finding updates on manager Chocolatey
[2024-12-18 00:38:15] Error finding updates on manager Npm
[2024-12-18 00:38:15] Manager PowerShell 5.x failed to list installed packages with exception TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[2024-12-18 00:38:15] Since this was the first attempt, PowerShell.AttemptFastRepair() will be called and the procedure will be restarted
[2024-12-18 00:38:15] System.TimeoutException: Task _getInstalledPackages for manager PowerShell7 did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:38:15] System.TimeoutException: Task _getInstalledPackages for manager Npm did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:38:20] Error finding installed packages on manager Chocolatey
[2024-12-18 00:38:20] System.TimeoutException: Task _getInstalledPackages for manager Chocolatey did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 255
[2024-12-18 00:38:37] Error finding installed packages on manager Npm
[2024-12-18 00:38:37] System.TimeoutException: Task _getInstalledPackages for manager Npm did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 255
[2024-12-18 00:38:57] Error finding updates on manager Scoop
[2024-12-18 00:38:57] System.TimeoutException: Task _getInstalledPackages for manager Scoop did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:39:15] Error finding installed packages on manager PowerShell
[2024-12-18 00:39:15] System.TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getInstalledPackages(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 255
[2024-12-18 00:39:18] Error finding updates on manager Winget
[2024-12-18 00:39:18] System.TimeoutException: Task _getInstalledPackages for manager Winget did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[2024-12-18 00:39:45] Backup saved to C:\Users\CCRLH85\Documents\UniGetUI\SATSUKI-SAN installed packages 2024-12-18 00-39-45.ubundle
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.10.40-preview
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024-12-18 00:35:15
Process end time:   2024-12-18 00:35:16

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-12-18 00:36:15
Process end time:   2024-12-18 00:39:05

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024-12-18 00:37:15
Process end time:   2024-12-18 00:39:06

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 2024-12-18 00:37:15
Process end time:   2024-12-18 00:37:57

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 2024-12-18 00:37:15
Process end time:   2024-12-18 00:37:59

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\CCRLH85\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-12-18 00:37:46
Process end time:   2024-12-18 00:38:04

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024-12-18 00:37:49
Process end time:   2024-12-18 00:39:13

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 2024-12-18 00:37:49
Process end time:   2024-12-18 00:38:22

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\CCRLH85\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024-12-18 00:37:57
Process end time:   2024-12-18 00:38:18

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024-12-18 00:39:15
Process end time:   2024-12-18 00:40:07

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 2024-12-18 00:39:15
Process end time:   2024-12-18 00:39:52

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
I have updated the relevant translation. Changes should be effective in 24/48h
