### ISSUE TITLE
[BUG] Chocolatey not autoelevating vscode update when required

### ISSUE THREAD

**Issue by GeoSimos** [marticliment/UniGetUI#3107]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4

### Windows version, edition, and architecture

Windows 10 Enterprise 22H2 (10.0.19045 Build 19045)

### Describe your issue

The new UniGetUI-Branded UAC Elevator doesn't work when running the application as a standard user (non-elevated). 

### Steps to reproduce the issue

Enable the new UniGetUl-Branded UAC Elevator from the Experimental Settings and restart the application as a standard user.
Let the application update itself a detected package, it will fail with access denied error on the installation path.

### UniGetUI Log

```text
[21/12/2024 12:34:13 πμ]    __  __      _ ______     __  __  ______
                           / / / /___  (_) ____/__  / /_/ / / /  _/
                          / / / / __ \/ / / __/ _ \/ __/ / / // /
                         / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                         \____/_/ /_/_/\____/\___/\__/\____/___/
                             Welcome to UniGetUI Version 3.1.4
[21/12/2024 12:34:13 πμ]
[21/12/2024 12:34:13 πμ] Build 73
[21/12/2024 12:34:13 πμ] Encoding Code Page set to 737
[21/12/2024 12:34:14 πμ] Using built-in UniGetUI Elevator
[21/12/2024 12:34:14 πμ] Loaded language locale: en
[21/12/2024 12:34:14 πμ] Checking for internet connectivity. Pinging google.com, microsoft.com, couldflare.com and marticliment.com
[21/12/2024 12:34:14 πμ] google.com responded successfully to ping, internet connection was validated.
[21/12/2024 12:34:14 πμ] Begin check for updates on endpoint https://www.marticliment.com/versions/unigetui/stable.ver
[21/12/2024 12:34:14 πμ] Lang files were updated successfully from GitHub
[21/12/2024 12:34:14 πμ] Begin "which" search for command npm
[21/12/2024 12:34:14 πμ] Begin "which" search for command winget.exe
[21/12/2024 12:34:14 πμ] Old chocolatey path does not exist, not migrating Chocolatey
[21/12/2024 12:34:14 πμ] Begin "which" search for command choco.exe
[21/12/2024 12:34:15 πμ] Command choco.exe was found on C:\ProgramData\chocolatey\bin\choco.exe
[21/12/2024 12:34:15 πμ] Command npm was not found on the system
[21/12/2024 12:34:15 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Npm
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:15 πμ] Begin "which" search for command python.exe
[21/12/2024 12:34:15 πμ] Command winget.exe was found on C:\Users\SouthPark\AppData\Local\Microsoft\WindowsApps\winget.exe
[21/12/2024 12:34:15 πμ] Saving window geometry 2553,380,1922,1025,0
[21/12/2024 12:34:15 πμ] Command python.exe was found on C:\Users\SouthPark\AppData\Local\Programs\Python\Python312\python.exe
[21/12/2024 12:34:15 πμ] Downloaded new icons and screenshots successfully!
[21/12/2024 12:34:15 πμ] Loaded 2 sources for manager Winget
[21/12/2024 12:34:15 πμ] Begin "which" search for command cargo
[21/12/2024 12:34:15 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Winget
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: winget.exe
                         █ Executable path: C:\Users\SouthPark\AppData\Local\Microsoft\WindowsApps\winget.exe
                         █ Call arguments: 
                         █ Version: 
                         █   System WinGet CLI Version: v1.9.25200
                         █   Using Native WinGet helper (COM Api)
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:15 πμ] Begin "which" search for command vcpkg
[21/12/2024 12:34:16 πμ] Command cargo was not found on the system
[21/12/2024 12:34:16 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Cargo
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:16 πμ] Command vcpkg was not found on the system
[21/12/2024 12:34:16 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: vcpkg
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:16 πμ] Begin "which" search for command dotnet.exe
[21/12/2024 12:34:16 πμ] Command dotnet.exe was found on C:\Program Files\dotnet\dotnet.exe
[21/12/2024 12:34:16 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: .NET Tool
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:16 πμ] Got response from endpoint: (73, 3.1.4, 88491C8F11D981F4259833448C1CE631B4F6D8279B69C8DF3AAB5DC3F6B6776E)
[21/12/2024 12:34:16 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Pip
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:16 πμ] Begin "which" search for command pwsh.exe
[21/12/2024 12:34:16 πμ] Command pwsh.exe was not found on the system
[21/12/2024 12:34:16 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell7
                         █ Enabled: True
                         █ Found: False
                         █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                         █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:16 πμ] Begin "which" search for command scoop
[21/12/2024 12:34:17 πμ] Command scoop was not found on the system
[21/12/2024 12:34:17 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Scoop
                         █ Enabled: False
                         █ THE MANAGER IS DISABLED
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:18 πμ] Loaded 1 sources for manager Chocolatey
[21/12/2024 12:34:18 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: Chocolatey
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: choco.exe
                         █ Executable path: C:\ProgramData\chocolatey\bin\choco.exe
                         █ Call arguments: 
                         █ Version: 
                         █   2.4.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:21 πμ] Loaded 1 sources for manager PowerShell
[21/12/2024 12:34:21 πμ] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                         █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                         █ Name: PowerShell
                         █ Enabled: True
                         █ Found: True
                         █ Fancy exe name: powershell.exe
                         █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                         █ Call arguments:  -NoProfile -Command
                         █ Version: 
                         █   Name                           Value                                                                                   
                         █   ----                           -----                                                                                   
                         █   PSVersion                      5.1.19041.5247                                                                          
                         █   PSEdition                      Desktop                                                                                 
                         █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                         █   BuildVersion                   10.0.19041.5247                                                                         
                         █   CLRVersion                     4.0.30319.42000                                                                         
                         █   WSManStackVersion              3.0                                                                                     
                         █   PSRemotingProtocolVersion      2.3                                                                                     
                         █   SerializationVersion           1.1.0.1
                         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/12/2024 12:34:21 πμ] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[21/12/2024 12:34:21 πμ] Manager Chocolatey has not implemented RefreshPackageIndexes
[21/12/2024 12:34:22 πμ] Manager PowerShell has not implemented RefreshPackageIndexes
[21/12/2024 12:34:23 πμ] Found 64 installed packages from Chocolatey
[21/12/2024 12:34:29 πμ] Resetting administrator rights cache for process id 16264
[21/12/2024 12:34:31 πμ] Found 2 available updates from Chocolatey
[21/12/2024 12:34:31 πμ] Found 97 installed packages from PowerShell
[21/12/2024 12:34:32 πμ] Found 0 available updates from Winget
[21/12/2024 12:34:32 πμ] Found 0 installed packages from Winget
[21/12/2024 12:34:33 πμ] Starting package backup
[21/12/2024 12:34:33 πμ] Finished loading serializable objects. Serializing with format JSON
[21/12/2024 12:34:33 πμ] Serialization finished successfully
[21/12/2024 12:34:33 πμ] Backup saved to D:\Data\Users\SouthPark\OneDrive\Documents\UniGetUI\AltsantiriNewz installed packages 2024-12-21 00-34-33.ubundle
[21/12/2024 12:35:22 πμ] Manager PowerShell 5.x failed to list available updates with exception TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
[21/12/2024 12:35:22 πμ] Since this was the first attempt, PowerShell.AttemptFastRepair() will be called and the procedure will be restarted
[21/12/2024 12:35:22 πμ] Manager PowerShell has not implemented RefreshPackageIndexes
[21/12/2024 12:36:03 πμ] Cached icon for id=BurntToast is valid and won't be downloaded again (PackageVersion)
[21/12/2024 12:36:04 πμ] Cached icon for id=Microsoft.WinGet.Client is valid and won't be downloaded again (PackageVersion)
[21/12/2024 12:36:05 πμ] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Particular.ServiceControl.Manage...',Version='5.3.0') with status code NotFound
[21/12/2024 12:36:05 πμ] No manifest content could be loaded for package Particular.ServiceControl.Manage... on manager PowerShell
[21/12/2024 12:36:06 πμ] Cached icon for id=VcRedist is valid and won't be downloaded again (PackageVersion)
[21/12/2024 12:36:22 πμ] Error finding updates on manager PowerShell
[21/12/2024 12:36:22 πμ] System.TimeoutException: Task _getInstalledPackages for manager PowerShell did not finish after 60 seconds, aborting.  You may disable timeouts from UniGetUI Advanced Settings
                            at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 204
[21/12/2024 12:36:22 πμ] Starting check for updates wait interval with waitTime=604800
```

### Package Managers Logs

```text
None at the moment.
```

### Relevant information

None.

**Comment by marticliment** [comment]
> Enable the new UniGetUl-Branded UAC Elevator from the Experimental Settings and restart the application as a standard user. Let the application update itself a detected package, it will fail with access denied error on the installation path.

Can you provide further details or a screenshot/recording of the error?

**Comment by GeoSimos** [comment]
Hi @marticliment,

I got the version 3.1.5 today and also had some updates to apply, here is the command line output from the chocolatey VSCode update:
```
Chocolatey v2.4.1
Chocolatey detected you are not running from an elevated command shell
(cmd/powershell).
You may experience errors - many functions/packages
require admin rights. Only advanced users should run choco w/out an
elevated shell. When you open the command shell, you should ensure
that you do so with "Run as Administrator" selected. If you are
attempting to use Chocolatey in a non-administrator setting, you
must select a different location other than the default install
location. See
https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
for details.
For the question below, you have 20 seconds to make a selection.
Do you want to continue?([Y]es/[N]o):
Timeout or your choice of '﻿' is not a valid selection.
Upgrading the following packages:
vscode
By upgrading, you accept licenses for the packages.
You have vscode v1.96.1 installed. Version 1.96.2 is available based on your source(s).
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib-bkp\vscode.install' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib-bkp\vscode.install' is denied.
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\lib-bkp\vscode.install". Error was:
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib-bkp\vscode.install' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
at chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass63_0.<CreateDirectory>b__1()
at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1_0.<Retry>b__0()
at chocolatey.infrastructure.tolerance.FaultTolerance.Retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
at chocolatey.infrastructure.tolerance.FaultTolerance.Retry(Int32 numberOfTries, Action action, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
at chocolatey.infrastructure.filesystem.DotNetFileSystem.CreateDirectory(String directoryPath, Boolean isSilent)
at chocolatey.infrastructure.filesystem.DotNetFileSystem.EnsureDirectoryExists(String directoryPath, Boolean ignoreError, Boolean isSilent)
Failed to run backup or beforeModify steps for package 'vscode.install': Access to the path 'C:\ProgramData\chocolatey\lib-bkp\vscode.install' is denied.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\vscode.install.nupkg' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\vscode.install.nupkg' is denied.
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\vscode.install.nuspec' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\vscode.install.nuspec' is denied.
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\tools\ChocolateyInstall.ps1' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\tools\ChocolateyInstall.ps1' is denied.
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\tools\helpers.ps1' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\tools\helpers.ps1' is denied.
Maximum tries of 3 reached. Throwing error.
Unable to remove existing package prior to upgrade:
One or more errors occurred.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
Maximum tries of 3 reached. Throwing error.
vscode not upgraded. An error occurred during installation:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
This is try 1/3. Retrying after 300 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
This is try 2/3. Retrying after 400 milliseconds.
Error converted to warning:
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
Maximum tries of 3 reached. Throwing error.
Chocolatey upgraded 0/0 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Access to the path 'C:\ProgramData\chocolatey\lib\vscode.install\.chocolateyPending' is denied.
```
It seems like the new UAC Elevation is not kicking in....
Attached a new log file with debug level output. 
[UniGetUI Log.txt](https://github.com/user-attachments/files/18218874/UniGetUI.Log.txt)

**Comment by marticliment** [comment]
If you manually run it as administrator from UniGetUI does it work?

**Comment by GeoSimos** [comment]
Yes, I get the UAC prompt and can elevate the process, also if it helps, I have the option this option selected -which was working fine with gsudo previously-.
![image](https://github.com/user-attachments/assets/67a80968-f6c6-4e8e-810b-a254da23829d)

**Comment by marticliment** [comment]
Then this issue is a regression in how UniGetUI detects missing elevation with chocolatey installs, but it is not related with the new Elevator

**Comment by GeoSimos** [comment]
Haven't had a winget update to check yet, if you can check it, would be great to know if the regression is of a wider scope than chocolatey only. Thanks for your time and the great product!

**Comment by marticliment** [comment]
It should be, as I have tested some WinGet updates recently and they seem to autoelevate

**Comment by GeoSimos** [comment]
Ok, I'll update this issue thread as well for any outcome when this happens.

**Comment by Beet4** [comment]
Can confirm this as well. It does not elevate for Chocolatey package upgrades, it fails with access denied to all folders and files. Been like this for a week or so. Manually running `choco upgrade all` in an elevate PowerShell prompt in Windows Terminal works fine.

UniGetUI still works fine on winget packages.

**Comment by andreas-profitlich** [comment]
This error is still present in themost recent version 3.1.6

**Comment by marticliment** [comment]
for the packages I have been able to test, part of the issue was fixed. Could you please share your upgrade logs for vscode?

**Comment by andreas-profitlich** [comment]
I will share future error logs. Currently I just upgraded every Softwarepackage manually.

**Comment by marticliment** [comment]
@andreas-profitlich, I was able to find and fix another issue that could be causing your issues.
