### ISSUE TITLE
[BUG] Chocolatey versions is not matching

### ISSUE THREAD

**Issue by ekozcifci** [marticliment/UniGetUI#3129]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.5

### Windows version, edition, and architecture

Windows 11 Pro, x64, 24H2, 26100.2033

### Describe your issue

As you can see, versions are not same with chocolatey but it is installing latest one (as chocolatey website), i guess it is a bug? i am newbie so im confused. I am really sorry if i created this topic to wrong section.
Also, a little question that i found weird, why some (maybe all) chocolatey packages do not have icon? just blank icons they have.

![image](https://github.com/user-attachments/assets/e3f5d2c9-8d98-46fc-aadf-427ee167450d)
![image](https://github.com/user-attachments/assets/550d5cf0-10db-4314-bae3-b6a0a5f7015b)

### UniGetUI Log

```text
[25.12.2024 21:04:34]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.5
[25.12.2024 21:04:34]
[25.12.2024 21:04:34] Build 74
[25.12.2024 21:04:34] Encoding Code Page set to 857
[25.12.2024 21:04:34] Using built-in UniGetUI Elevator
[25.12.2024 21:04:34] Loaded language locale: en
[25.12.2024 21:04:35] Randomly-generated background API auth token for the current session: l2c9vr22uwvq9qq65jlvh7gec1qkpts2a8ot8yqtp8cr2q2cpxtanmmzcgxxfk8n
[25.12.2024 21:04:35] Api running on http://localhost:7058
[25.12.2024 21:04:35] Lang files were updated successfully from GitHub
[25.12.2024 21:04:35] Downloaded new icons and screenshots successfully!
[25.12.2024 21:04:35] Command vcpkg was not found on the system
[25.12.2024 21:04:35] Command cargo was not found on the system
[25.12.2024 21:04:35] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:35] Command vcpkg was not found on the system
[25.12.2024 21:04:35] Command vcpkg was not found on the system
[25.12.2024 21:04:35] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: vcpkg
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: C:\Program Files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.403
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: winget.exe
                      █ Executable path: C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\winget.exe
                      █ Call arguments: 
                      █ Version: 
                      █   System WinGet CLI Version: v1.9.25200
                      █   Using Native WinGet helper (COM Api)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pip
                      █ Executable path: C:\Python312\python.exe
                      █ Call arguments:  -m pip
                      █ Version: 
                      █   pip 24.3.1 from C:\Python312\Lib\site-packages\pip (python 3.12)
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:36] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: npm
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command npm
                      █ Version: 
                      █   10.9.0
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:37] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: scoop
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
                      █ Version: 
                      █   Current Scoop version:
                      █   859d1db5 chore(release): Bump to version 0.5.2 (#6080)
                      █   
                      █   'main' bucket:
                      █   f1c92d933 usql: Update to version 0.19.15
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:37] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.1882                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.1882                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:38] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: choco.exe
                      █ Executable path: C:\Users\Administrator\AppData\Local\UniGetUI\Chocolatey\choco.exe
                      █ Call arguments: 
                      █ Version: 
                      █   This is try 1/3. Retrying after 400 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.21952.update' is denied.
                      █   This is try 2/3. Retrying after 600 milliseconds.
                      █    Error converted to warning:
                      █    Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config.21952.update' is denied.
                      █   Maximum tries of 3 reached. Throwing error.
                      █   2.2.2
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[25.12.2024 21:04:38] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[25.12.2024 21:04:39] Found 14 installed packages from Pip
[25.12.2024 21:04:39] Found 2 installed packages from PowerShell7
[25.12.2024 21:04:39] Found 1 installed packages from .NET Tool
[25.12.2024 21:04:39] Dependency Scoop-Search for manager Scoop is present
[25.12.2024 21:04:40] Found 1 installed packages from Scoop
[25.12.2024 21:04:40] Dependency Git for manager Scoop is present
[25.12.2024 21:04:40] Command parse_pip_search.exe was not found on the system
[25.12.2024 21:04:40] Dependency parse-pip-search was not found, and the user set it to not be reminded of the missing dependency
[25.12.2024 21:04:40] Found 0 available updates from .NET Tool
[25.12.2024 21:04:40] Dependency .NET Tools Outdated for manager .NET Tool is present
[25.12.2024 21:04:40] Found 0 installed packages from Chocolatey
[25.12.2024 21:04:41] Found 0 available updates from Chocolatey
[25.12.2024 21:04:42] Found 0 installed packages from PowerShell
[25.12.2024 21:04:43] Found 0 available updates from PowerShell
[25.12.2024 21:04:43] Found 0 installed packages from Npm
[25.12.2024 21:04:43] Found 1 installed packages from Scoop
[25.12.2024 21:04:43] Found 0 available updates from Pip
[25.12.2024 21:04:44] Found 0 available updates from Npm
[25.12.2024 21:04:45] Found 0 available updates from Scoop
[25.12.2024 21:04:47] Command parse_pip_search.exe was not found on the system
[25.12.2024 21:04:47] Found 0 available packages from Scoop with the query audacity
[25.12.2024 21:04:47] Found 1 available packages from Chocolatey with the query audacity
[25.12.2024 21:04:48] Found 0 available packages from .NET Tool with the query audacity
[25.12.2024 21:04:48] Found 5 available packages from Winget with the query audacity
[25.12.2024 21:04:48] Found 20 available packages from Npm with the query audacity
[25.12.2024 21:04:49] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:49] Manager Pip failed to find packages with exception Win32Exception: An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Sistem belirtilen dosyayı bulamıyor.
[25.12.2024 21:04:49] Since this was the first attempt, Pip.AttemptFastRepair() will be called and the procedure will be restarted
[25.12.2024 21:04:49] Command parse_pip_search.exe was not found on the system
[25.12.2024 21:04:49] Found 0 available updates from PowerShell7
[25.12.2024 21:04:50] Found 33 available updates from Winget
[25.12.2024 21:04:50] Found 241 installed packages from Winget
[25.12.2024 21:04:50] Unknown mimetype image/jpeg for icon https://cdn.neowin.com/news/images/uploaded/2017/09/1506235786_camtasia_studio_story.jpg, aborting download
[25.12.2024 21:04:50] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:50] Error finding packages on manager Pip with query audacity
[25.12.2024 21:04:50] System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Sistem belirtilen dosyayı bulamıyor.)
                       ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'parse_pip_search.exe' with working directory 'C:\Program Files\UniGetUI'. Sistem belirtilen dosyayı bulamıyor.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.PipManager.Pip.FindPackages_UnSafe(String query) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Pip\Pip.cs:line 120
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.<>c__DisplayClass50_0.<_findPackages>b__0() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 147
                         at System.Threading.Tasks.Task`1.InnerInvoke()
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                      --- End of stack trace from previous location ---
                         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                         --- End of inner exception stack trace ---
                         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
                         at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._findPackages(String query, Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 148
[25.12.2024 21:04:51] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:51] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:52] Icon download attempt at https://community.chocolatey.org/content/packageimages/plex.1.64.2.3546.png failed with code NotFound
[25.12.2024 21:04:52] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:53] Could not parse Images array from Microsoft Store response
[25.12.2024 21:04:56] Found 3 screenshots for package Id=audacity
[25.12.2024 21:04:56] Loaded details for package audacity on manager Chocolatey
[25.12.2024 21:04:56] Loaded operation parameters for package id=audacity on manager Chocolatey and operation Install: install audacity -y --no-progress
[25.12.2024 21:05:00] Loaded operation parameters for package id=audacity on manager Chocolatey and operation Install: install audacity -y  --no-progress
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 25.12.2024 21:04:36
Process end time:   25.12.2024 21:04:36

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 25.12.2024 21:04:38
Process end time:   25.12.2024 21:04:42

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 25.12.2024 21:04:38
Process end time:   25.12.2024 21:04:50

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 25.12.2024 21:04:39
Process end time:   25.12.2024 21:04:47

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 25.12.2024 21:04:42
Process end time:   25.12.2024 21:04:50

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is FindPackages
Process start time: 25.12.2024 21:04:47
Process end time:   25.12.2024 21:04:48

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
Is the last update recent? Chocolatey sometimes can take a while when updating indexes

**Comment by hgschehl** [comment]
I can confirm this, UniGetUI showing Version 1.4.9 for Cryptsync, Chocolatey Version 1.4.11; New version was entered at 7 Dec 2024 at chocolatey.
It seems, that it doesn't take a "general" link, but a more direct one (see Manifest): 

![Image](https://github.com/user-attachments/assets/2b6680e4-19f4-4085-bbb6-89505ce35687)

I then clicked on "install" and it got even more weird (as I had already installed before I started to use UniGetUI) - 
"Installed Packages" shows now 3 entries:
![Image](https://github.com/user-attachments/assets/7c7e40d9-281d-4771-81cc-f6f8175ad7ba)

Running software itself shows version 1.4.11.515 ...

**Comment by HariSeldon85** [comment]
yes it applies to every chocolatey packages. For instance firefox show the 125.0 but then it correctly install the 135.0 (latest)

**Comment by marticliment** [comment]
I think I may know what is happening. the internal NuGet helper is not parsing the latest version, but the _first_ one. I will fix that

**Comment by albino1** [comment]
@marticliment this is still not parsing correctly in 3.1.7, see my comment here:

https://github.com/marticliment/UniGetUI/discussions/3128#discussioncomment-12357723

**Comment by marticliment** [comment]
Hello, please test if the latest PreRelease version 3.1.8-beta1 fixes the issue: https://github.com/marticliment/UniGetUI/releases/download/3.1.8-beta1/UniGetUI.Installer.exe

**Comment by albino1** [comment]
> Hello, please test if the latest PreRelease version 3.1.8-beta1 fixes the issue: https://github.com/marticliment/UniGetUI/releases/download/3.1.8-beta1/UniGetUI.Installer.exe

I tested a couple quick ones that were an issue before and it seems good now.  Thanks!
